### ISSUE TITLE
Works perfectly on Catalina GM

### ISSUE THREAD

**Issue by atk88** [ExistentialAudio/BlackHole#1]
First try out, works perfectly on Catalina GM, thanks for your work, please keep it up : )

**Comment by devinroth** [comment]
Thanks. I'll add a note to the README.

**Comment by vitishko** [comment]
Does not work on Catalina for me :(
Followed instructions, however no luck :(

**Comment by devinroth** [comment]
@vitishko could you be more specific? What's not working? How do you have it setup? I need more information.

**Comment by vitishko** [comment]
I've installed it following installation instruction. 
Rebooted laptop. 
Tried to record audio from Safari (playing music on YouTube) in Audacity: I've set recording device as BlackHole in Audacity and hit Record button. Audio from Safari does not record.

Am I missing something?

Thank you.

**Comment by devinroth** [comment]
Did you set the output device to BlackHole?

**Comment by synnys** [comment]
just a heads up, I couldn't get it to work when using OBS, which after some research wasn't because of blackhole, but because of OBS not being compatible yet with Catalina. There is a workaround though, you have to start OBS from the terminal. and make sure you give terminal access rights to your microphone.

thanks for the blackhole development though, it's a genuinely useful tool.

**Comment by devinroth** [comment]
@synnys great point. Make sure the app that you want to have access has microphone permission in System Preferences -> Security & Privacy -> Privacy -> Microphone.

**Comment by vitishko** [comment]
> Did you set the system output device to BlackHole?
> […](#)

Yes, I did.

**Comment by vitishko** [comment]
I've also tried to setup Multi-Output device (System Audio + BlackHole) and used it as output device:
<img width="624" alt="image" src="https://user-images.githubusercontent.com/2146674/67124080-9d73fc00-f1a6-11e9-9d13-2e9549be27e0.png">

**Comment by devinroth** [comment]
There seems to be a bug in the Multi-Output which requires you to set your MacBook Speakers as the first device. Like in my picture. Try unselecting BlackHole and reselecting it. Let me know if that works.
![image](https://user-images.githubusercontent.com/13010961/67124207-efb51d00-f1a6-11e9-884e-6f1c18cdc84f.png)

**Comment by vitishko** [comment]
Multi-output device works, with your suggestion. Thanks!
<img width="643" alt="image" src="https://user-images.githubusercontent.com/2146674/67124470-6ce09200-f1a7-11e9-8ed6-2048bd363074.png">

However, recording does not work in Audacity:

<img width="932" alt="image" src="https://user-images.githubusercontent.com/2146674/67124518-871a7000-f1a7-11e9-85f3-9ee3b3a2c8fb.png">

**Comment by devinroth** [comment]
Is Audacity listed in System Preferences -> Security & Privacy -> Privacy -> Microphone?

**Comment by vitishko** [comment]
<img width="670" alt="image" src="https://user-images.githubusercontent.com/2146674/67124607-b7faa500-f1a7-11e9-8beb-7612be23a512.png">

**Comment by vitishko** [comment]
Also tried QuickTime voice recorder, does not work either.

**Comment by devinroth** [comment]
Have you been able to record with your build-in mic with Audacity and QuickTime?

**Comment by vitishko** [comment]
> Have you been able to record with your build-in mic with Audacity and QuickTime?

Ohhhh..... 

Audacity does not work with build-in mic, QuickTime works with both build-in mic and with BlackHole!!!

This is Audacity issue!

Thank you very much for your help with troubleshooting!

**Comment by vitishko** [comment]
Workaround:

https://www.audacityteam.org/macos-10-15-catalina-is-not-yet-supported-by-audacity/

**Comment by emotpix** [comment]
In order to get it working in Catalina, I definitely had to set up a multi-output device. It's working great now! Thank you

**Comment by emotpix** [comment]
Hi, just noticed that I now cannot make or receive calls on my mac via FaceTime with black hole installed. In the sound settings I have it set to microphone for input and internal speakers for output. Any thoughts on why sound is disabled when using FaceTime to make or receive audio calls?
