### ISSUE TITLE
Facetime no longer working 

### ISSUE THREAD

**Issue by emotpix** [ExistentialAudio/BlackHole#10]
Hi, I'm on mac catalina, and the plug-in works perfectly for screen recording audio, but now I'm seeing an issue with it when I make or receive calls on my mac via FaceTime. I have the sound settings back to microphone and internal speakers, but I cannot hear calls and the caller can't hear me. Any thoughts?

**Comment by devinroth** [comment]
I just tested it and everything seems normal. My guess is you have the input/output setup incorrectly. Send me a screenshot of the audio window in Audio Midi Setup.

**Comment by emotpix** [comment]
I restarted and it now works. Didn't change any settings. Hmm 
![Screen Shot 2019-10-26 at 11 17 09 AM](https://user-images.githubusercontent.com/56932136/67621916-7939a000-f7e2-11e9-9a5c-29330e63a919.png)

**Comment by devinroth** [comment]
Cool. Glad it works now.
