### ISSUE TITLE
BlackHole and SoundSource

### ISSUE THREAD

**Issue by Shrapnel21** [ExistentialAudio/BlackHole#103]
Hi all! =)
Total noob here, so I need some info.
What I'd like to know is: will Rogue Amoeba's SoundSource 'see' BlackHole as a destination for audio from a certain app, just as it does with speakers, headphones and so on?
I've just started streaming retrogames on Twitch and I need to redirect sound output from emulators to OBS.
Thanks in advance and keep up the good work!

**Comment by devinroth** [comment]
It should. All audio applications see the BlackHole driver.

**Comment by Shrapnel21** [comment]
I can confirm it perfectly works. Thank you! =)
