### ISSUE TITLE
Midi instrument

### ISSUE THREAD

**Issue by tjglenn** [ExistentialAudio/BlackHole#108]
I can’t hear my midi instrument when I use black hole out out out

**Comment by devinroth** [comment]
https://github.com/ExistentialAudio/BlackHole#how-can-i-listen-to-the-audio-and-use-blackhole-at-the-same-time

**Comment by tjglenn** [comment]
So it won’t work in the midi only for audio?

**Comment by devinroth** [comment]
BlackHole is an audio driver. It doesn't work with MIDI.
