### ISSUE TITLE
Not working for audacity 

### ISSUE THREAD

**Issue by artempenn** [ExistentialAudio/BlackHole#11]
After installing BlackHole (followed instructions including restart), I set all my input/output to blackhole, and tried recording from audacity, but it's a flatline. I changed the audio settings to BlackHole in both the system settings and audacity. I am seeing that it is successfully routing through because macOS is registering an input through BlackHole, but it doesn't seem to extend to audacity. 
I have tried the following:

1.  Restart audacity 
2. Turn Transport Options > Software Playthrough on/off. 

Any thoughts? I'm assuming this should work with any DAW. I'm going to try reinstalling Audacity. Otherwise I might have to wait for Soundflower to add Catalina support.

**Comment by devinroth** [comment]
Audacity is not compatible with Catalina. 

https://github.com/ExistentialAudio/BlackHole/issues/1#issuecomment-543926835
