### ISSUE TITLE
Typo in Aggregate Device WIKI

### ISSUE THREAD

**Issue by m-r-m-s** [ExistentialAudio/BlackHole#111]
Nothing huge - just a minor typo in the documentation that fixing would assist readability:
https://github.com/ExistentialAudio/BlackHole/wiki/Aggregate-Device#4-select-devices

where it says: **IMPORTANT: Due to issues with macOS the Build-in Output must be enabled and listed as the top device in the Aggregate**

**Build-in** should be **Built-in**

Thanks for your consideration and hard work!

**Comment by devinroth** [comment]
Thanks for pointing that out. Fixed.
