### ISSUE TITLE
Interface ch 1 and 2 to skype

### ISSUE THREAD

**Issue by Shags1225** [ExistentialAudio/BlackHole#113]
Hi!
I am a newb and I can't figure out how to get a mic and a line in to Skype using blackhole. I have created an aggregate device and a multi output device, routed my interface into blackhole, and selected it as the mic in Skype but it still only picks up input 1 of my interface. Am I doing something wrong?

**Comment by devinroth** [comment]
Send me some photos of your setup and I'll try to help you out.

**Comment by Shags1225** [comment]
Thanks, I have to send em one at a time

**Comment by Shags1225** [comment]
![20200423_153426](https://user-images.githubusercontent.com/64201863/80145114-abec0780-857d-11ea-83e8-6a31d5f5d3db.jpg)
