### ISSUE TITLE
Notarize Installer

### ISSUE THREAD

**Issue by Jake3231** [ExistentialAudio/BlackHole#114]
BlackHole is a great product that I have been using on Catalina, though recently I encountered the warning that, "macOS cannot verify that this app is free from malware" when running the installer.
<img width="488" alt="Screen Shot 2020-04-23 at 9 10 02 AM" src="https://user-images.githubusercontent.com/13911970/80108718-3878d480-8542-11ea-87e0-9410844e5f51.png">

It would be ideal to [notarize the installer](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution) going forward.

**Comment by devinroth** [comment]
Thanks fo the reminder. It’s on my todo list. 

Devin

**Comment by devinroth** [comment]
Finally figured it out!
