### ISSUE TITLE
Possible to run two instances?

### ISSUE THREAD

**Issue by fastfourier666** [ExistentialAudio/BlackHole#116]
Hey. First of all, thanks for this. It's much more reliable than Soundflower. It just works fantastically.

I use a number of applications (Skype, Zoom, OBS etc) which will only use channel 1+2 of a particular audio device. My usual workaround for this is to create an aggregate device and designate the speakers as 3+4, 5+6 etc in Audio Midi Setup, but the first two of those apps don't seem to respect that setting and just use 1+2 anyway. 

My only thought is perhaps I could compile a couple of different copies of blackhole for use in these situations? I'm not too up on mac programming, just wondering your thoughts ..

thanks!

**Comment by devinroth** [comment]
Yes that is definitely possible. There are instructions in the wiki if you are feeling up for it.

If not I have a sponsorship tier where I will do custom builds. https://github.com/sponsors/ExistentialAudio

**Comment by fastfourier666** [comment]
Whoops. Should have poked around a bit more. I'm kind of new to github! I'll give it a shot, thanks!
