### ISSUE TITLE
No screenshots? No binary?

### ISSUE THREAD

**Issue by microfx** [ExistentialAudio/BlackHole#12]
Hey! 

If you want to become n°1 replacement for Soundflower then please add some screenshots... and maybe have a website with a binary? That would make the decision easier if I want to use/try/love it or not.

Cheers

**Comment by devinroth** [comment]
Yeah great ideas. But for screenshots what do you recommend? It's not like there is a UI at the moment. I could give a screenshot of the Audio Devices window.

**Comment by microfx** [comment]
would help a lot!

**Comment by devinroth** [comment]
Yeah it's in the plans. A simple UI for changing the number of channels, driver latency, and clock syncing. 

I do have a downloadable binary on the releases page. But yeah a good landing page would be helpful. I'll work on it when I get a chance.
