### ISSUE TITLE
On phone call pickup, other side can not hear me

### ISSUE THREAD

**Issue by coolp123** [ExistentialAudio/BlackHole#120]
Whenever I connect to any of the following voice calls on my computer (FaceTime & FT audio, a cellular call over Mac, and screen sharing), the other side does not hear me. This happens regardless if I initiate the call or if the other side calls me. I have found a temporary fix... during the call (after I determined that the other party can not hear me), I have to switch my _output_ to be something other than my speakers; when switching back to my speakers, they can hear me. This is obviously quite odd as I'm switching the output, not the input.

A restart of my computer makes this problem go away, but after a day the bug comes back and consistently affects every call. Uninstalling BlackHole has resolved this issue, which makes me think it was BlackHole. I know this is quite an abstract issue...

**Comment by devinroth** [comment]
You're right that is abstract.

Are you using BlackHole for anything when that was happening? Aggregates? Multi-outputs? Or any of those apps?

**Comment by coolp123** [comment]
I wasn't using BlackHole at the moment of a phone call, nor was I using it recently. I do have a multi-output set up... I deleted it, but the issue persisted the following day.

**Comment by coolp123** [comment]
I did notice that QuickTime automatically selected BlackHole over my Mic when I was recording my screen. Perhaps FaceTime is doing the same; I haven't payed attention to that.

**Comment by devinroth** [comment]
Was BlackHole selected as your default input/output in Audio Midi Setup?

**Comment by coolp123** [comment]
Not that I was aware. I will reinstall and pay attention to this. I'll update if I have more issues! I guess you can close this for now, thank you!!
