### ISSUE TITLE
Media won't play on High Sierra when BlackHole set as input

### ISSUE THREAD

**Issue by momomie** [ExistentialAudio/BlackHole#121]
Hi,
I attempt to install BlackHole on a MacBook Pro HighSierra 10.13.6 in order to record FaceTime audio 
But, on the DAW when i set BlackHole as input, media won't play

For example on iTunes when i start the song play, it show the pause button but the music don't play and stay stuck on timecode 

See here : https://victorlabro.fr/cloud/index.php/s/zbQLARepcgkeTTr 
Other video here : https://victorlabro.fr/cloud/index.php/s/ytfBKBwGxfRGQw6 
I've installed BlackHole on my own MBP under Catalina and all works fine, what's wrong ? 

Thx for replies

**Comment by devinroth** [comment]
BlackHole can't be the top in the multi-output. That should solve your problem.

https://github.com/ExistentialAudio/BlackHole/wiki/Multi-Output-Device#4-select-output-devices
