### ISSUE TITLE
Proble setting up Multi-Output Device

### ISSUE THREAD

**Issue by MikeyB456** [ExistentialAudio/BlackHole#123]
Hi, I've installed BlackHole 0.2.6 on my 2016 MacbookPro, Mac OS 10.14.6
I'm trying to set it up so I can play my app sound together with a microphone (ie me!) to my students when using Zoom for virtual classes. By default, they can only hear my app sound through whatever the mic picks up from the computer's speaker output.

So I think I need a "Multi-Output Device" - correct? 

I've worked through the setup, made the Multi-Output Device in Audio Midi Setup, but I do the last bit. When I right-click on the Multi-Output device, "Use this device for sound output" is greyed out. What could I be doing wrong?

**Comment by devinroth** [comment]
Send a screenshot of your multi-output in Audio Midi setup.

**Comment by MikeyB456** [comment]
Hi Devin,
Thanks for the reply. I've discovered the problem lies with the Zoom audio device that Zoom has created for itself. If it is removed from the Multi-Output Device list then all is well.
Cheers
Mike

**Comment by devinroth** [comment]
Glad it was an easy fix.
