### ISSUE TITLE
Two apple cinema displays

### ISSUE THREAD

**Issue by marcoaramburo** [ExistentialAudio/BlackHole#124]
Hello.
I am trying to configure blackhole to deliver the computer audio to my two apple cinema displays. I follow the instructions but is not working. The two displays are connected with thunderbolt/mini display. If i change manually between display the sound is perfect. But I am unable to use both displays audio at the same time. Any solution here ?

**Comment by devinroth** [comment]
Please submit an issue on GitHub.

**Comment by marcoaramburo** [comment]
mmmm I am new on this, how ? And I want to correct the issue, the sound actually is delivered to both screens, the issue now is the volume is not working.

**Comment by devinroth** [comment]
https://github.com/ExistentialAudio/BlackHole/issues <https://github.com/ExistentialAudio/BlackHole/issues>

Please include a detailed description of the problem, how you have it setup and what you’ve tried.
