### ISSUE TITLE
Volume control is not working

### ISSUE THREAD

**Issue by marcoaramburo** [ExistentialAudio/BlackHole#125]
I successfully install BlackHole and now my two apple cinema displays are with full audio. 
Now my issue is the volume control, now is not working. 
Someone know how to activate this function ? 
If I select the display audio (image 5) the settings and output volume are fully working with audio in only one display.
If I select the Multi-output device (image 6) the same setting are disabled (the selected device has not output controls) and I cannot control the sound volume, but I have audio in my two displays.
 I am attaching pictures of the complete configuration (images 1,2,3 and 4)
![6](https://user-images.githubusercontent.com/64651022/80839579-28579980-8bc1-11ea-8068-a03e3b289a8a.png)
![5](https://user-images.githubusercontent.com/64651022/80839585-2a215d00-8bc1-11ea-9243-ae398258b752.png)
![4](https://user-images.githubusercontent.com/64651022/80839589-2ab9f380-8bc1-11ea-9a8b-eac450d89f6d.png)
![3](https://user-images.githubusercontent.com/64651022/80839590-2b528a00-8bc1-11ea-955c-122ed4aa2dc6.png)
![2](https://user-images.githubusercontent.com/64651022/80839592-2beb2080-8bc1-11ea-979b-7e2900cd2193.png)
![1](https://user-images.githubusercontent.com/64651022/80839594-2beb2080-8bc1-11ea-88c4-2c6779ae4094.png)

**Comment by devinroth** [comment]
Unfortunately Multi-outputs don’t have volume control.

**Comment by QuantumInformation** [comment]
just set it on the individual item
