### ISSUE TITLE
Route Apple Books app output to BH. Can it be done without routing all apps?

### ISSUE THREAD

**Issue by sidney** [ExistentialAudio/BlackHole#128]
This could be labeled as Setup if there is a positive answer or Enhancement request if there isn't.
Loopback provides the ability to connect the output of a specific application. I was successful at capturing the output of Books by setting the system default output to BH, but that ties up the sound output for the whole machine. I guess Loopback substitutes their UI for what BH relies on Audio Midi Setup for. As far as I can tell the virtual devices created by Audio Midi Setup can only be used in Sound Preferences, where they apply to all applications, or in applications that are written to present options to select the audio devices that they use.

Is there a way to configure Books to output to BH or a Multi-Output Device other than making that the system device, or would that need an enhancement?

**Comment by devinroth** [comment]
Can't be done. Sorry.
