### ISSUE TITLE
Aggregate devices with Rode and BH often have to be reset

### ISSUE THREAD

**Issue by quantuminformation** [ExistentialAudio/BlackHole#129]
I often have to keep setting this up whenever I disconnect devices, because my rode mic is greyed out. Not sure if this is related in any way to black hole. Once I reselect the active rode device and after bh it works for until I disconnect stuff.

![image](https://user-images.githubusercontent.com/216566/80911342-fd428680-8d35-11ea-8317-14fcea743389.png)

**Comment by devinroth** [comment]
I created a tag for this specific situation.

**Comment by devinroth** [comment]
Basically there's a bug where the primary audio device (aka on the top) needs to have 2 channels. Any device with more causes problems. 

Blame apple.

**Comment by QuantumInformation** [comment]
ah ok, makes sense

Apple I blame you
