### ISSUE TITLE
Swap channels of input

### ISSUE THREAD

**Issue by jakub-zawislak** [ExistentialAudio/BlackHole#13]
I didn't found such functionality in readme, but maybe I just don't know how to use this program. 

My use case:
I have a Scarlett Solo with instrument input at channel 2. I want to use it in the Rocksmith 2014, which listens only to channel 1. So I need to swap channels of input.

I can do it in the Loopback, but for the price of license, I could buy a more expensive Scarlett 2i2 which also solves this problem.

**Comment by devinroth** [comment]
It’s definitely possible but not implemented. I can add it to the feature requests. If you want to dig into the code you could modify it to fit your needs. 

Devin

**Comment by chaimpeck** [comment]
I have a similar use-case.

I have a Steinberg UR22 and I want to use it with a direct-in bass in the right channel and combine it with some music that I want to play along with (from Spotify or a web browser, etc.) and to record that with QuickTime Player.

I can do that currently with SoundFlower (and presumably Blackhole too), but the bass is only in the right channel.

With Loopback, I am able to send the right channel to the left/right output channels. Looks like this:
<img width="610" alt="Screen Shot 2019-11-13 at 1 14 44 AM" src="https://user-images.githubusercontent.com/4606444/68737979-09cdf980-05b3-11ea-83d0-4a9f23d115aa.png">

But, I concur with with @jakub-zawislak that it is not worth the $99 to only use that one feature.

I could conceivably do this in a DAW, but I am trying to rely entirely on the system audio options and record direct to QuickTime, without having to mix things after the fact.

I think that the ability to pipe in audio from any channel of any device would be a great feature.

**Comment by PatTheMav** [comment]
A +1 from me for what @chaimpeck wrote - I currently need to route two channels of an external audio device to two seperate loopback devices as the target software doesn't allow channel selection (and downmixes everything to stereo per device).

I could compile blackhole twice with different UUIDs to get those two loopbacks (something that _might_ be a great built-in feature: blackhole "clones"), but I'd still need some way to route a single channel from device A to a seperate blackhole device.

**Comment by thomasberglund** [comment]
@devinroth Awesome work with BlackHole, and thanks for sharing it in the open with the rest of the world. Amazing.

Skype has the same issue as other apps mentioned here. It only listens to channel 1/2, with multi-channel audio interfaces – hence no audio from other inputs via BlackHole in Skype.

**Comment by krono86** [comment]
+1 I need this functionality for Serato DJ Pro.

**Comment by williammuff** [comment]
I second the Serato DJ comment!

**Comment by Teufeuleu** [comment]
+1 !

**Comment by reneotten** [comment]
+1

**Comment by jts3k** [comment]
+1

**Comment by rmonge** [comment]
+1

**Comment by nathanpthousand** [comment]
+1 the Zoom R24 has no phantom power to channels 1 and 2 and is useless as an interface for almost all streaming applications.

**Comment by dexterslabor** [comment]
+1 Traktor DJ

**Comment by andregriffin** [comment]
Channel matrix routing like this would be amazing. And I'd think the latency here would be less than Loopback doing the same thing.

For example, I'm using an RME UFX with 30in/30out. The UFX has it's own set of routing and loopback features, however I need to pick up inputs 17/18 from the UFX and route them to Blackhole 1/2, for use in applications that don't support multichannel audio cards. 

There's seemingly no reliable way to do this without using a $99 app like Loopback or something like LadioCast (which is unreliable for some reason).

This would be a huge feature, especially for those needing to submix audio for streaming to OBS with the least amount of latency.

**Comment by julientaq** [comment]
Hi!

Got a zoom r16 with 8 channel, and the 48v for my mic is on channel 5/6. I would love to be able to send the audio through the web browser for Big blue button / jisti / ~~zoom~~ / etc. sessions.

Thanks for the great work!

Ju

**Comment by zfogg** [comment]
+1
