### ISSUE TITLE
Transcribe audio using OSX dictation

### ISSUE THREAD

**Issue by vnckppl** [ExistentialAudio/BlackHole#134]
I have an audio file that I would like to transcribe to text. I set up 'BlackHole 16ch' as the output device and selected 'BlackHole 16ch' as the input device under `System Preferences > Keyboard > Dictation`.  On this panel, there is an icon of a microphone that shows volume levels in real-time and indicates that it is picking up the audio. However, as soon as I start the dictation the microphone volume indicator goes flat and no audio is being captured. 

What would be the correct way of routing standard output to the microphone input?

**Comment by devinroth** [comment]
I've tried a couple time to figure this out and I just don't have any explanation why dictation does this.

**Comment by vnckppl** [comment]
Thanks for looking into this. I appreciate the effort.

**Comment by devinroth** [comment]
I’ll keep it on the list. Hopefully figure it out eventually.

**Comment by devinroth** [comment]
Hey I figured it out.

By default macOS mute the audio output when dictation is running. Of course BlackHole will not work if muted. To change the setting Apple->System Preferences->Accessibility->Dictation and uncheck "Mute audio output while dictating" and voilà it should work.

So not a bug after all just a setting in macOS that makes perfect sense under a normal situation.

**Comment by vnckppl** [comment]
Thanks so much!

**Comment by cradesto** [comment]
What about Catalina? There is no option Apple->System Preferences->Accessibility->Dictation

**Comment by devinroth** [comment]
Great question. It looks like that option has disappeared in Catalina. I tried to see if there is a way around but it doesn't look like it. It will probably work if you use something other than the default output for audio. For example try using GarageBand to play the audio and set the default to something other than BlackHole. It's kind of annoying that Apple removed this option.
