### ISSUE TITLE
System Audio + USB Interface Audio

### ISSUE THREAD

**Issue by arothmanmusic** [ExistentialAudio/BlackHole#135]
I've read the docs and watched several YouTube videos, but clearly I'm still doing something wrong. :)

I have a Focusrite USB audio interface that I use to drive my speakers and as the input for my mic. I want to combine the mic audio with the sound coming from iTunes/Spotify/etc. on the system and use that as an aggregated device for live streaming and/or recording.

I've checked off both my USB interface and Blackhole in the multi-output device and in the aggregate device, but when I go into Audacity and set the Aggregate device as my input, I'm only getting the mic and no system audio.

Can someone clarify how this should be routed?

**Comment by devinroth** [comment]
Do you happen to be on Catalina? If so, Audacity doesn’t work.

**Comment by arothmanmusic** [comment]
Nah, I'm on High Sierra... newest thing this old beast will handle (and barely at that). But that's a good direction to follow... maybe it's Audacity that's not working and not my Blackhole setup. I'll have to see if I can use it in a different app!

**Comment by arothmanmusic** [comment]
Nope. Same thing. I must have something set up incorrectly. I can get the mic or the system audio but I can't get them both.

- I have an aggregate device and a multi output. 
- Blackhole is first and my USB audio I/O is second on both of them. 
- In the System 'Sound' panel I have the aggregate device set up as the input and the multu-out device set up as the output.

Now, if I go to RingCentral Meetings for example, and I set up the multi-output as my out and the aggregate device as my in, I get nothing. Am I doing this all wrong? :)

**Comment by devinroth** [comment]
Try changing it so BH isn't first on the list.

**Comment by devinroth** [comment]
Send a photo.

**Comment by arothmanmusic** [comment]
Hey Devin - thanks for giving it a shot. I think I've figured out how to get things working via a different combination of software (Soundflower and OBS), so I'm going to close this post up, but I appreciate the responsiveness! I'm going to keep trying to figure this out regardless.
