### ISSUE TITLE
Build from source?

### ISSUE THREAD

**Issue by innerop** [ExistentialAudio/BlackHole#136]
Hi,

I've been using SoundFlower and have managed to get it to build from source with the latest XCode on Mojave, after jumping through some hoops.

Is it possible to add a How-To for building from source? I'm not a MacOS developer, but I've done some work in the past with Objective-C on iOS, so I'm familiar with the environment. The reason I'd like to build this from source is for my own learning and for getting your latest changes, and hopefully contributing bug fixes, if I find any issues I can solve. 

It took a lot to find this project. I've been searching for a SoundFlower replacement for a month.

Thanks a lot.

**Comment by devinroth** [comment]
Please look in the wiki. Instructions are there.

**Comment by innerop** [comment]
Oh. Awesome. Thank you so much Devin.
