### ISSUE TITLE
Severe dropouts with SuperCollider -> BlackHole 32ch -> Ableton w/ Aggregate Device

### ISSUE THREAD

**Issue by colinsullivan** [ExistentialAudio/BlackHole#137]
Greetings,

Thanks for your work!

Sharing my experience here as a data point and to receive any suggestions.

For many years I have been using the JackPilot application on mac to route audio bi-directionally between SuperCollider and Ableton Live.

Today I tried using BlackHole as a possible alternative.

I built BlackHole with 34 channels and `LATENCY_FRAME_SIZE` of 1024.  After playing for 30 seconds to a minute, Ableton sound engine slows completely, it sounds as if everything is time stretched and crackling, and Ableton CPU usage shoots up.

My audio interface is a MOTU UltraLite mk3.  I have an Aggregate device with the Ultralite and BlackHole, clock on ultralite and drift correction enabled for BlackHole.  The interface is set to 48k and Ableton at 256 sample buffer size.  I tried sending SuperCollider to just BlackHole, and to the aggregate device as well.

I realize this is likely a corner case, still any suggestions?  Should I wait for the clock sync feature and try again?

I have validated that it achieving this performance is possible in theory because Jack does it well.

**Comment by devinroth** [comment]
Aggregates are definitely not the best. But with a buffer size of 256 is probably a major contributor. Try increasing that and see if it improves.

**Comment by colinsullivan** [comment]
I did try that too, seemed to extend the duration but eventually went off the rails again.

For my use, I need the 256 size for low latency from external instruments, but I can compromise latency within the BlackHole signal path.

Just wondering if there is something else going on, because it's not just some crackle / dropouts like you'd hear typically if your machine is too slow and buffer size too low, it really becomes unstable and I need to restart everything.

Happy to try anything and report back.  Appreciate the attention + quick response!

**Comment by devinroth** [comment]
Could you do me a favor and test to see if you have the same issues with just using BH without the aggregate?

**Comment by colinsullivan** [comment]
OK!

I ended up getting similar instability when I started up Jack right after I posted this issue. Restarted and things are back to usual.  So there was definitely something crusty on my end, probably the last time I restarted this machine was weeks ago.

Now BlackHole with the settings mentioned above gives *inconsistent but tolerable* dropouts.  I wouldn't use it for a performance but it is no longer freaking out, just occasional drop outs.

I tried what you mentioned, which was using BH only.  So I set up SuperCollider -> Ableton -> Adobe Audition, so I could capture the output of Ableton and listen back.  It sounds fine to my ears!

So I went back in and increased this already beefy buffer `LATENCY_FRAME_SIZE` to `2048` and it sounds okay now, Ableton's CPU is hovering around 37% where before it was hovering around 50%.

Still more to test but I have a bit more intuition.

Think the clock sync feature will help with the Aggregate devices?

**Comment by colinsullivan** [comment]
I guess I was expecting only stuff going through BH would have a latency that feels like 2048, but in fact playing instruments in Ableton does too!

Glad I did this test though, looking forward to staying the loop 👀

**Comment by colinsullivan** [comment]
And just for kicks I reduced the BH buffer size back down to 256.  It is performing well so far.  Will keep playing around and report back.

**Comment by colinsullivan** [comment]
OK yup, bringing in live sounds from the audio interface (just moving up the fader in Ableton) made it go off the rails again :-o !

**Comment by colinsullivan** [comment]
Final update for now - you might be relieved at what is my dismay.

As I mentioned, yesterday I decided to look into BH as an alternative to a Jack-based setup which I have been using for years.

Coincidentally, yesterday my 2018 6-core MacBook Pro began heat throttling the CPU down to 30% of it's capacity.  This is why I was seeing such extreme performance issues.  Of course since I was switching my audio system, I thought that was the reason.  It's totally reasonable for a machine 30% as fast as mine to not be able to handle 32 channels of internal audio at 256 buffer size :P

I'll report back when I have some non-broken hardware.
