### ISSUE TITLE
Output & Input device IDs are equals.

### ISSUE THREAD

**Issue by slorenzo** [ExistentialAudio/BlackHole#138]
Hi there.

I've this issue enumerating the devices using Web Audio API.
Running the following code should be enough to reproduce it.
```
const devices = await navigator.mediaDevices.enumerateDevices();
console.log(devices);
```

If you take a look to the devices, BlackHole shares the same ID in inputs/output devices while on other devices they are different.

Thanks for this amazing project!

**Comment by slorenzo** [comment]
A screenshot with the results of the above code.

<img width="1592" alt="Screen Shot 2020-05-07 at 21 15 57" src="https://user-images.githubusercontent.com/15804684/81356761-5862d900-90a8-11ea-8f50-0f18d5a5751b.png">

**Comment by devinroth** [comment]
Interesting. Why is it causing you problems? In core audio the BlackHole Audio Device has one ID. The input and output stream may have the same ID that definitely something I can look into. But I'm curious why this is a problem.

**Comment by slorenzo** [comment]
@devinroth thanks for your reply.

It's been causing troubles because I want to capture the audio from the Black Hole device's output stream for processing and send it to a selected speaker. But I couldn't because input/output devices have the same ID. I've already done this for input devices, but I'm not sure why the ID is working for the input stream and not for the outputs.

Would really appreciate if you can tackle it.

**Comment by slorenzo** [comment]
@devinroth  thanks for your reply.

It's been causing troubles because I want to capture the audio from the Black Hole device's output stream for processing and send it to a selected speaker. But I couldn't because input/output devices have the same ID. I've already done this for the input device but it's not working for the  output device. Seems that the Web Audio API attaches the ID to the input device. I guess a possible solution for this issue is to have different IDs for input/output devices.

Any thoughts?

**Comment by Bradysm** [comment]
Very interesting. It could be solved by adding an 'O' and an 'I' for output and input to create two unique identifiers to differentiate between them which would then allow you to do your desired task.

**Comment by jonas-db** [comment]
I have the same problem in javascript on catalina, any fix possible?

**Comment by jbuecker** [comment]
Looking for clarification..I Believe I am too experiencing the problem... In LOGIC PRO ... I am Using an Aggregate Setup (Zoom TAC-2 2x2 interface and Blackhole 16) for example..... 

If I route Audio to Blackhole channel output 3 and 4..... and have another channel listening to Blackhole Input 3 and 4, I get a feedback loop.  Is this because the input and output IDs are equal?... this is a big issue as then essentially the inputs and outputs are mirrored....

~JB

**Comment by devinroth** [comment]
It shouldn't be a problem. And those device IDs aren't ones that are assigned by BlackHole they must be part of the web audio API. That being said a potential fix might be to change them internally as suggested by @Bradysm for the input / output.   What you'll need to do is return a different string for kAudioPlugInPropertyTranslateUIDToDevice and kAudioDevicePropertyDeviceUID depending wether the scope ie kAudioObjectPropertyScopeInput or kAudioObjectPropertyScopeOutput. This may create other issues but if you're willing to get your hands dirty it's worth trying.

**Comment by devinroth** [comment]
Is this still an issue? If so, reopen.
