### ISSUE TITLE
audio finicky after interjection for podcast recording

### ISSUE THREAD

**Issue by larissaaalam** [ExistentialAudio/BlackHole#139]
hello! im so glad i found blackhole to replace soundflower for catalina. thanks so much!

i want to point out a minor issue im facing while recording with blackhole in garageband for my podcast. so i have my blueyeti as channel 1-2 and blackhole as 3-4 for the recording input. blackhole is recording my guest who is calling in via google hangout. i realize whenever i interject, the guest audio gets finicky and distorted for .5-1 second after my interjection. has anyone run into this problem or know how to fix it? thanks :)

**Comment by devinroth** [comment]
That seams strange. BH is running the entire time. I wonder if it has to do with Hangout's audio compression.

**Comment by larissaaalam** [comment]
i also just found out there are 5mins of audio that is super staticie. there was no static while i was recording. i wonder what happened

**Comment by devinroth** [comment]
Test again on the latest release 0.2.8. I fixed a number of bugs and it may completely solve this. Reopen if you still have problems.
