### ISSUE TITLE
Audio Issue on Catalina oS

### ISSUE THREAD

**Issue by ineedhelplease** [ExistentialAudio/BlackHole#145]
I'm trying to use this in order to use audio from the source when I screen record instead of via my mic, however the audio sounds filtered and off and I can't seem to figure out why this is happening, can anyone offer any advice?

**Comment by jonas-db** [comment]
I have similar problems on catalina:
I have the following scenario:
route audio from a system (eg youtube video) to multi-output device #1
multi-output device #1 routes to: display audio speakers #2 and soundflower channel #3

then I assume that connecting to the audio output of #3 would give me the clear sound, but it seems like it is recorded through the microphone/filtered? What am i doing wrong here?
