### ISSUE TITLE
Installed - Uninstalled - now can't use MacBook Pro microphone for some apps

### ISSUE THREAD

**Issue by cliffordinho** [ExistentialAudio/BlackHole#147]
I recently installed Blackhole and when I opened up Audio MIDI setup the option to select blackhole disappeared, reappeared, disappeared...on and on. So, I uninstalled as per guidelines and now the same issue is happening with the MacBook pro microphone. It disappears, reappears...over and over. 

Issues that have happened since the uninstall:

- Zoom and similar apps are unable to detect the MacBook mic.

- I'm having issues crop up within final cut pro and logic pro x such as random crashes and playback errors.

The above issues never happened before I installed Blackhole.

I'm hoping some of you can shed some light on what has happened and what I need to do next to resolve this problem.

Thanks.

**Comment by cliffordinho** [comment]
<img width="1572" alt="Screenshot 2020-05-13 at 22 07 58" src="https://user-images.githubusercontent.com/65312808/81865928-657b3e80-9566-11ea-80a0-1fb1ed858426.png">

**Comment by cliffordinho** [comment]
<img width="1572" alt="Screenshot 2020-05-13 at 22 08 10" src="https://user-images.githubusercontent.com/65312808/81866024-80e64980-9566-11ea-80c4-da4cf87470f7.png">

**Comment by cliffordinho** [comment]
<img width="1572" alt="Screenshot 2020-05-13 at 22 08 29" src="https://user-images.githubusercontent.com/65312808/81866078-95c2dd00-9566-11ea-805c-925c10465c82.png">

**Comment by cliffordinho** [comment]
<img width="1572" alt="Screenshot 2020-05-13 at 22 08 46" src="https://user-images.githubusercontent.com/65312808/81866114-a5422600-9566-11ea-824e-327ad2a086e0.png">

**Comment by devinroth** [comment]
Have you restarted your computer? I need to ask.

**Comment by cliffordinho** [comment]
Hi Devin,

Yes, several times I’ve restarted and same issue. Uninstalled and reinstalled zoom and same issue present.

**Comment by devinroth** [comment]
I've had a couple reports of this happening. In both cases it just went away. 

Honestly I don't have a clue what the issue is. 

Send me all audio related reports from Console. 
Under devices select your computer and search for coreaudiod.
system.log search for audio. Basically try to find any reference to the coreaudio crash.

**Comment by cliffordinho** [comment]
**System.log - searched for audio**

May 14 00:43:51 Steves-MacBook-Pro coreaudiod[1325]: BGM_Device::AddClient: Adding client 319 (com.apple.systempreferences)
May 14 00:43:51 Steves-MacBook-Pro coreaudiod[1325]: BGM_ClientMap::AddClient: Found previous volume 1.000000 for client 319
May 14 00:43:51 Steves-MacBook-Pro coreaudiod[1325]: BGM_TaskQueue::QueueSync: Queueing task synchronously to be processed on the realtime thread. inTaskID=2 inTaskArg1=4463538736 inTaskArg2=0
May 14 00:43:51 Steves-MacBook-Pro coreaudiod[1325]: BGM_TaskQueue::ProcessRealTimeThreadTask: Swapping the shadow maps in BGM_ClientMap
May 14 00:43:52 Steves-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.audio.coreaudiod[1325]): Service exited due to SIGSEGV | sent by exc handler[1325]
May 14 00:43:52 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::RealTimeThreadProc: The realtime worker thread has started
May 14 00:43:52 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::NonRealTimeThreadProc: The non-realtime worker thread has started
May 14 00:43:52 Steves-MacBook-Pro coreaudiod[1490]: BGM_Device::AddClient: Adding client 58 (com.apple.audio.coreaudiod)
May 14 00:43:52 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::QueueSync: Queueing task synchronously to be processed on the realtime thread. inTaskID=2 inTaskArg1=4429566512 inTaskArg2=0
May 14 00:43:52 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::ProcessRealTimeThreadTask: Swapping the shadow maps in BGM_ClientMap
May 14 00:43:52 Steves-MacBook-Pro coreaudiod[1490]: BGM_Device::AddClient: Adding client 59 (no bundle ID)
May 14 00:43:52 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::QueueSync: Queueing task synchronously to be processed on the realtime thread. inTaskID=2 inTaskArg1=4429566512 inTaskArg2=0
May 14 00:43:52 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::ProcessRealTimeThreadTask: Swapping the shadow maps in BGM_ClientMap
May 14 00:43:52 Steves-MacBook-Pro coreaudiod[1490]: BGM_Device::AddClient: Adding client 60 (com.apple.controlstrip)
May 14 00:43:52 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::QueueSync: Queueing task synchronously to be processed on the realtime thread. inTaskID=2 inTaskArg1=4429566512 inTaskArg2=0
May 14 00:43:52 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::ProcessRealTimeThreadTask: Swapping the shadow maps in BGM_ClientMap
May 14 00:43:52 Steves-MacBook-Pro coreaudiod[1490]: BGM_Device::AddClient: Adding client 61 (com.apple.systempreferences)
May 14 00:43:52 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::QueueSync: Queueing task synchronously to be processed on the realtime thread. inTaskID=2 inTaskArg1=4429566512 inTaskArg2=0
May 14 00:43:52 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::ProcessRealTimeThreadTask: Swapping the shadow maps in BGM_ClientMap
May 14 00:43:52 Steves-MacBook-Pro coreaudiod[1490]: BGM_Device::AddClient: Adding client 62 (com.apple.PowerChime)
May 14 00:43:52 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::QueueSync: Queueing task synchronously to be processed on the realtime thread. inTaskID=2 inTaskArg1=4429566512 inTaskArg2=0
May 14 00:43:52 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::ProcessRealTimeThreadTask: Swapping the shadow maps in BGM_ClientMap
May 14 00:43:52 Steves-MacBook-Pro coreaudiod[1490]: BGM_Device::AddClient: Adding client 63 (com.google.Chrome.helper)
May 14 00:43:52 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::QueueSync: Queueing task synchronously to be processed on the realtime thread. inTaskID=2 inTaskArg1=4429566512 inTaskArg2=0
May 14 00:43:52 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::ProcessRealTimeThreadTask: Swapping the shadow maps in BGM_ClientMap
May 14 00:43:52 Steves-MacBook-Pro coreaudiod[1490]: BGM_Device::AddClient: Adding client 64 (com.apple.quicklook.QuickLookUIService)
May 14 00:43:52 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::QueueSync: Queueing task synchronously to be processed on the realtime thread. inTaskID=2 inTaskArg1=4429566512 inTaskArg2=0
May 14 00:43:52 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::ProcessRealTimeThreadTask: Swapping the shadow maps in BGM_ClientMap
May 14 00:43:52 Steves-MacBook-Pro coreaudiod[1490]: BGM_Device::AddClient: Adding client 65 (com.apple.mediaremoted)
May 14 00:43:52 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::QueueSync: Queueing task synchronously to be processed on the realtime thread. inTaskID=2 inTaskArg1=4429566512 inTaskArg2=0
May 14 00:43:52 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::ProcessRealTimeThreadTask: Swapping the shadow maps in BGM_ClientMap
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_Device::AddClient: Adding client 116 (com.apple.universalaccessd)
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::QueueSync: Queueing task synchronously to be processed on the realtime thread. inTaskID=2 inTaskArg1=4429566512 inTaskArg2=0
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::ProcessRealTimeThreadTask: Swapping the shadow maps in BGM_ClientMap
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_Device::AddClient: Adding client 117 (com.apple.audio.AudioMIDISetup)
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::QueueSync: Queueing task synchronously to be processed on the realtime thread. inTaskID=2 inTaskArg1=4429566512 inTaskArg2=0
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::ProcessRealTimeThreadTask: Swapping the shadow maps in BGM_ClientMap
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_Device::AddClient: Adding client 118 (no bundle ID)
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::QueueSync: Queueing task synchronously to be processed on the realtime thread. inTaskID=2 inTaskArg1=4429566512 inTaskArg2=0
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::ProcessRealTimeThreadTask: Swapping the shadow maps in BGM_ClientMap
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_Device::AddClient: Adding client 119 (com.focusrite.FocusriteControl.Server)
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::QueueSync: Queueing task synchronously to be processed on the realtime thread. inTaskID=2 inTaskArg1=4429566512 inTaskArg2=0
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::ProcessRealTimeThreadTask: Swapping the shadow maps in BGM_ClientMap
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_Device::AddClient: Adding client 120 (com.apple.CoreSpeech)
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::QueueSync: Queueing task synchronously to be processed on the realtime thread. inTaskID=2 inTaskArg1=4429566512 inTaskArg2=0
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::ProcessRealTimeThreadTask: Swapping the shadow maps in BGM_ClientMap
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_Device::AddClient: Adding client 121 (com.google.Chrome)
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::QueueSync: Queueing task synchronously to be processed on the realtime thread. inTaskID=2 inTaskArg1=4429566512 inTaskArg2=0
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::ProcessRealTimeThreadTask: Swapping the shadow maps in BGM_ClientMap
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_Device::AddClient: Adding client 127 (com.apple.quicklook.QuickLookUIService)
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::QueueSync: Queueing task synchronously to be processed on the realtime thread. inTaskID=2 inTaskArg1=4429566512 inTaskArg2=0
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::ProcessRealTimeThreadTask: Swapping the shadow maps in BGM_ClientMap
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_Device::AddClient: Adding client 128 (no bundle ID)
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::QueueSync: Queueing task synchronously to be processed on the realtime thread. inTaskID=2 inTaskArg1=4429566512 inTaskArg2=0
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::ProcessRealTimeThreadTask: Swapping the shadow maps in BGM_ClientMap
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_Device::AddClient: Adding client 129 (com.apple.SiriNCService)
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::QueueSync: Queueing task synchronously to be processed on the realtime thread. inTaskID=2 inTaskArg1=4429566512 inTaskArg2=0
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::ProcessRealTimeThreadTask: Swapping the shadow maps in BGM_ClientMap
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_Device::AddClient: Adding client 130 (no bundle ID)
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::QueueSync: Queueing task synchronously to be processed on the realtime thread. inTaskID=2 inTaskArg1=4429566512 inTaskArg2=0
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::ProcessRealTimeThreadTask: Swapping the shadow maps in BGM_ClientMap
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_Device::AddClient: Adding client 131 (com.apple.TelephonyUtilities)
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::QueueSync: Queueing task synchronously to be processed on the realtime thread. inTaskID=2 inTaskArg1=4429566512 inTaskArg2=0
May 14 00:43:53 Steves-MacBook-Pro coreaudiod[1490]: BGM_TaskQueue::ProcessRealTimeThreadTask: Swapping the shadow maps in BGM_ClientMap
May 14 00:43:55 Steves-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.audio.coreaudiod[1490]): Service exited due to SIGSEGV | sent by exc handler[1490]
May 14 00:43:55 Steves-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.audio.coreaudiod): Service only ran for 2 seconds. Pushing respawn out by 8 seconds.

**Comment by devinroth** [comment]
What’s BGM? Is that Background Music?

**Comment by cliffordinho** [comment]
No, I don't have any other app open other than my browsing. No music playing.

**Comment by cliffordinho** [comment]
[Audio reports.pdf](https://github.com/ExistentialAudio/BlackHole/files/4625316/Audio.reports.pdf)

**Comment by devinroth** [comment]
Have you ever installed this? https://github.com/kyleneideck/BackgroundMusic

That seems to be where the issue is. 

Tey reinstalling it and if it fixes your problem.

**Comment by cliffordinho** [comment]
No, I've never installed that. 

Should I give it a try as a workaround?

**Comment by devinroth** [comment]
Maybe you installed something that used it. 

Try installing and report back. 

Devin

**Comment by cliffordinho** [comment]
I tried it, restarted the mac but the same issue is happening. I've uninstalled BGM as it was interfering with core audio initialization with Logic and zoom. I don't know what to do at this point.

**Comment by devinroth** [comment]
Show me a photo of your HAL folder.

BlackHole is obviously not installed anymore so that can’t be causing the problem. But I do wonder how or what it affected by installing. As a user space driver BH doesn’t have access to anything else on the drive or system processes. The only thing that the installer does is move the .driver to the HAL folder and restart CoreAudio. 

The issues seem to come from something called BGM_driver. We need to figure out what that is.

Just out of curiosity. Did you have any audio applications open when you installed BH?

**Comment by cliffordinho** [comment]
Yes, I'm not sure exactly what the issue is. I think it's isolated to "input" because when I open up Audio MIDI setup and then open Sound Preferences and select input, it then begins to crash and reload over and over...

See video of issue here: https://www.youtube.com/watch?v=hme5bu0eVO0

**From System - HAL**
<img width="1059" alt="Screenshot 2020-05-14 at 18 38 57" src="https://user-images.githubusercontent.com/65312808/81967047-44702780-9612-11ea-9f1b-8fc54a80a409.png">

**From Library to HAL**
<img width="1059" alt="Screenshot 2020-05-14 at 18 38 36" src="https://user-images.githubusercontent.com/65312808/81967067-4c2fcc00-9612-11ea-8aee-5a17ad4f47de.png">

**Comment by cliffordinho** [comment]
I’m also unsure if I had any other application open at the time. Possibly Spotify and I would usually have closed Logic before installing any new drivers/software but I’m unsure.

**Comment by devinroth** [comment]
Try removing everything from the HAL folder. 
Restart CoreAudio. with `sudo launchctl kickstart -kp system/com.apple.audio.coreaudiod`
You can add it back in after. See if that works. Let's try to find where the problem is.

Also I wonder if you have any audio kexts that may be causing problems.

**Comment by cliffordinho** [comment]
Which HAL folder? :)

What are audio kexts?

**Comment by devinroth** [comment]
Do both folders. We’ll deal with kexts after you try this.

**Comment by cliffordinho** [comment]
I've removed Library>HAL contents but I cannot remove System> HAL contents. Won't give me the option.

**Comment by cliffordinho** [comment]
OK, after removing contents from library>HAL the following are now back and fully operational:

- Zoom
- Logic
- Can open other audio software and web browsers while playing audio etc.

The two items in the HAL folder are 'Quantum audio plug-in' and 'Apowersoft audio device new'. I'm not sure what these plug-in's are apart of. I will update if I come across any further issues.

**Comment by devinroth** [comment]
Sounds like one of those is causing the problem. 

If you want to try I bet BlackHole will work normally now.

**Comment by devinroth** [comment]
Let me know if you still have problems.
