### ISSUE TITLE
Audio distortion with Aggregate Device

### ISSUE THREAD

**Issue by theotherstephen** [ExistentialAudio/BlackHole#148]
I've been using BlackHole to record a podcast, and about half the time, it works fine, but the other half the time, the computer audio starts to quickly degrade after about half an hour, and I have no idea what's going on.

I'm on a MacBook Pro running Catalina 10.15.4 with a Blue Snowball plugged in over USB. I have BlackHole set for sound output in Audio MIDI Setup. I have an Aggregate Device created with the Snowball for the first device and BlackHole for the second. I'm recording in Audition with one track recording the Snowball and the other recording BlackHole. Finally, I have a Chrome window open to Google Hangouts, where the conversation is taking place.

When things go south, it's always on the BlackHole channel, it usually doesn't start for about half an hour, and it starts mild but gets unlistenable very quickly. The distortion that occurs is kind of like when a strong wind blows against a cell phone mic, but more digital? Sorry, I'm not sure how to articulate it.

Any idea what's going on?

**Comment by devinroth** [comment]
Sounds like your clock is drifting. 

Do you have drift correction selected on your aggregate?

**Comment by theotherstephen** [comment]
I don't think so (amateur). Should I turn it on for both the Snowball and BlackHole devices?

**Comment by devinroth** [comment]
Yes. That should solve the problem.

**Comment by theotherstephen** [comment]
Thanks! I'll give it a try.
