### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by docob6** [ExistentialAudio/BlackHole#15]
Thanks

You mentioned `Build Installation instructions` on https://github.com/ExistentialAudio/BlackHole#advanced-customization

But I cannot find it...

**Comment by devinroth** [comment]
You need Xcode installed. Open BlackHole.xcodeproj and click build. I don't recommend doing it if you haven't used Xcode before.

**Comment by devinroth** [comment]
Sorry it’s miss labeled. It’s under advanced installation instructions.

**Comment by docob6** [comment]
thanks, I tried install Xcode, and build, and seems OK, but I cannot find anything in the directory. where does the build save to?

**Comment by docob6** [comment]
Ah, I see, it's not saved into the directory, but I can find it in Xcode.
