### ISSUE TITLE
System Audio Stops When Switching To MultiOutput Device

### ISSUE THREAD

**Issue by olexxx** [ExistentialAudio/BlackHole#153]
Hello!

I'm trying to set up the BlackHole to use it with StudioOne+OBS.

I've created the multioutput as instructed. But as soon as I change the system output to it, all system audio freezes - it won't let me even start any file that contains audio - not from Finder, not from YouTube, nothing. It just won't play. As soon as I switch back to some other output device, it plays just fine.

![screenshot](https://cldup.com/aYViRYhz6x.png)

Any suggestions? Thank you

**Comment by devinroth** [comment]
https://github.com/ExistentialAudio/BlackHole/wiki/Multi-Output-Device#system-audio-stops-when-switching-to-multioutput-device

**Comment by devinroth** [comment]
I just added that section because this question comes up a lot.

**Comment by olexxx** [comment]
> I just added that section because this question comes up a lot.

Thanks. It works with the iMac speakers if I set them up as #1. However, I need to route the sound to my audio interface which is Studio 1810c but the audio just plays through the internal iMac speakers. Is there an option to route it to the audio interface instead of built-in iMac speakers? Thanks!

**Comment by devinroth** [comment]
Make sure you have your Studio 1810c on the list too. And then just mute your iMac speakers. Problem solved. Annoying yes. There’s a reason I have the Blame Apple tag.

**Comment by olexxx** [comment]
> Make sure you have your Studio 1810c on the list too. And then just mute your iMac speakers. Problem solved. Annoying yes. There’s a reason I have the Blame Apple tag.
> […](#)

Looks like it works now. I will give it through some tests and see how it performs with OBS! Thanks much.

**Comment by devinroth** [comment]
Awesome!
