### ISSUE TITLE
Audio Sounding phased and distorted from chrome.

### ISSUE THREAD

**Issue by bastiancreations** [ExistentialAudio/BlackHole#154]
Hi there, I'm running blackhole to send music from my ableton to Loola, a web based streaming platform. I'm using an aggregate device of my interface and blackhole to send audio.

Blackhole seems to send the audio fine internally, ie to logic or obs, but in chrome the audio comes out sounding louder, phased, unstable and distorted.

I don't know if you have any idea how to fix it?

Pretty sure I'm syncing clocks ok.

**Comment by devinroth** [comment]
Could you upload a clip?

**Comment by danieldram** [comment]
I have the same issue with chrome, loom and any video recorder 

https://www.loom.com/share/0a69ee214c414e63a8db69ba484f1121

**Comment by devinroth** [comment]
Download the latest version and see if it solves the problem. If not, reopen the issue and I'll take a closer look. I made a number of changes and it might just fix it.
