### ISSUE TITLE
Install Failed - High Sierra

### ISSUE THREAD

**Issue by jstokdyk** [ExistentialAudio/BlackHole#155]
Restarted and still failed. High Sierra 10.13.6 (17G12034)
![Install Failed High Sierra](https://user-images.githubusercontent.com/65690617/82510686-d07dc580-9ad0-11ea-88b8-2cb23140056a.png)
Thanks!

**Comment by jstokdyk** [comment]
I haven't done anything since the earlier screenshot of my Audio MIDI Setup, but now Blackhole is visible in my audio prefs.

![blackhole now in Prefs](https://user-images.githubusercontent.com/65690617/82517878-b7cadb00-9ae3-11ea-9214-4fbcd1841bf4.png)

**Comment by devinroth** [comment]
I suspect the script that restarts core audio failed even though the installation worked. This has happened to a few people. Not sure why.

**Comment by jstokdyk** [comment]
Okay. My Audio MIDI Setup prefs just crashed. Would the crash report be useful for you?

**Comment by devinroth** [comment]
Sure. Although Audio Midi setup does seem to do that a lot. May be completely unrelated to BlackHole. But it’s worth checking.

**Comment by jstokdyk** [comment]
Here you go.
[Audio MIDI Crash Report.txt](https://github.com/ExistentialAudio/BlackHole/files/4660422/Audio.MIDI.Crash.Report.txt)

**Comment by devinroth** [comment]
Unrelated. Just another "normal" Audio Midi Setup Crash. Thanks anyway.

**Comment by jstokdyk** [comment]
Seems to be working. Thanks for the prompt attention.
