### ISSUE TITLE
Audio distortion with AirPods and Multi-Output Device

### ISSUE THREAD

**Issue by davidgu** [ExistentialAudio/BlackHole#156]
When playing audio through a multi-output device with ONLY BlackHole 16ch and AirPods connected: 
* Case 1 (Airpods are 1st device, BlackHole is 2nd): the audio is extremely distorted sounding much deeper, lower quality, and slower.
* Case 2 (Airpods are 2nd device, BlackHole is 1st): the Music app refuses to play

No combination of Drift Correction, Master Device, or Sample Rate resolves this problem. 

**This issue does not occur if Built-in output is also selected as the 1st device.**
The only circumstance the audio is correct with the AirPods is if Built-in Output is included as the first item in the Multi-Output Device. This configuration works with all combinations of Master Device, Drift Correction and Sample Rate.

**Comment by devinroth** [comment]
I have a label for this very reason. Unfortunately if you're using a multi-output nothing can be done.

**Comment by devinroth** [comment]
The trick is to have the built-in output in there but have it muted so no sounds comes out of the speakers.
