### ISSUE TITLE
After installing BlackHole on Catalina no videos play

### ISSUE THREAD

**Issue by ameliavog** [ExistentialAudio/BlackHole#157]
After installing Blackhole on Catalina no videos play. 
- Can't play any in quicktime
- Can play any in youtube (through any browser)

Uninstalled Blackhole and all videos worked fine. 

Reinstalled Blackhole and all videos stopped working.

**Comment by devinroth** [comment]
Are you using a multi output or aggregate?

**Comment by ameliavog** [comment]
Multi output

Arrow Interface  (Universal Audio) + BlackHole

With abundant love,
Amelia

*Needing support during COVID-19 to build immunity and support stress
reduction?  *  I am hosting bi-weekly, pay-what-you-can online energy
clinics starting April 17. Information here
<https://ameliavogler.com/covid-clinic/>.



Amelia Vogler
Specialist in Energy Medicine

*...envisioning a world in which we all live our truth, beauty, and
goodness.*
*AmeliaVogler.com* <http://AmeliaVogler.com>

**Comment by devinroth** [comment]
Multi outputs are really buggy. You need to have built-in output on the top of the list.

**Comment by devinroth** [comment]
More details in the wiki.

https://github.com/ExistentialAudio/BlackHole/wiki/Multi-Output-Device#audio-and-video-wont-play-when-using-a-multioutput-device

**Comment by ameliavog** [comment]
Sounds like this

BuiltIN Output + Arrow Interface + Black Hole

Then mute the built in output when running through a 3rd party app like
Zoom.

Correct?

With abundant love,
Amelia

*Needing support during COVID-19 to build immunity and support stress
reduction?  *  I am hosting bi-weekly, pay-what-you-can online energy
clinics starting April 17. Information here
<https://ameliavogler.com/covid-clinic/>.



Amelia Vogler
Specialist in Energy Medicine

*...envisioning a world in which we all live our truth, beauty, and
goodness.*
*AmeliaVogler.com* <http://AmeliaVogler.com>

**Comment by devinroth** [comment]
Exactly.

**Comment by ameliavog** [comment]
10-4  Ty so much!!!! Have a wonderful Memorial Day weekend and sending well
wishes to you and all who you love.

With abundant love,
Amelia

*Needing support during COVID-19 to build immunity and support stress
reduction?  *  I am hosting bi-weekly, pay-what-you-can online energy
clinics starting April 17. Information here
<https://ameliavogler.com/covid-clinic/>.



Amelia Vogler
Specialist in Energy Medicine

*...envisioning a world in which we all live our truth, beauty, and
goodness.*
*AmeliaVogler.com* <http://AmeliaVogler.com>

**Comment by devinroth** [comment]
Thank you.
