### ISSUE TITLE
Multi-Ouput for Djay Pro (aggregate default)

### ISSUE THREAD

**Issue by seabass9** [ExistentialAudio/BlackHole#159]
Hi, I'm trying to send audio from Djay Pro to 2 outputs (MacBook Pro Speakers + Zoom Device).

The issue is that DjayPro creates an aggregate device of it's own when it's setup to use an external cueing device. Here's my DjayPro setup:
![image](https://user-images.githubusercontent.com/46506823/82985185-6c637180-9fa8-11ea-9761-149d5ec18993.png)
and here's what that looks like in Midi Setup:
![image](https://user-images.githubusercontent.com/46506823/82985237-84d38c00-9fa8-11ea-823a-2d130f9f5d4f.png)

The issue is that DjayPro doesn't work with a simple MOD. So I'm wondering if there is a way to do this with BlackHole. I've been able to make this work with loopback by sending DjayPro audio out to BlackHole and then send that to both Speakers and Zoom:
![image](https://user-images.githubusercontent.com/46506823/82985608-2f4baf00-9fa9-11ea-98cb-20500f7bb00b.png)
Or equivalent with AudioHijack:
![image](https://user-images.githubusercontent.com/46506823/82984850-d0396a80-9fa7-11ea-8d6e-4dc64b73497a.png)
but would prefer to support this project. 

I suspect there might be a way to set this up?

Happy to make a donation as well.

**Comment by devinroth** [comment]
Try creating a multi-output with your macbook pro speakers and blackhole. Then set that as the main output in Djay Pro. That should work. Let me know.

**Comment by seabass9** [comment]
Yeah, I've tried creating the MOD:
![image](https://user-images.githubusercontent.com/46506823/83066024-46c28080-a019-11ea-889a-b3e8c61b0e17.png)
then using it in Djay Pro like this:
![image](https://user-images.githubusercontent.com/46506823/83066072-5a6de700-a019-11ea-9c16-f7dc16a59288.png)
but it still creates it's own Aggregate Device:
![image](https://user-images.githubusercontent.com/46506823/83066128-6fe31100-a019-11ea-9b78-0596f2b4f8ab.png)
and no sound comes out from the MBP speakers.

Apparently [Djay Pro can't correctly output to a MOD](https://community.algoriddim.com/algoriddim/topics/multi-output-devices-only-work-if-there-is-no-output-selected-for-precuing). Hence the need to find a way to pass the audio through somehow.

**Comment by devinroth** [comment]
Okay got it. 

So set the output to BlackHole. 

Then we just need a way to output BlackHole to your speakers. 

Someone wrote a script to do that. Someone posted it around here. I’ll see if I can find it for you.

Or you can do it with Garage Band. Bonus points for Garage Band is you can even record your set at the same time if you wanted to. Set the input to BH and output to your speakers in GB. Make sure you have monitoring selected on your audio track.

**Comment by seabass9** [comment]
OK, using GB to get the audio output works perfectly as I needed to also record this and another Mic which I can also put into the BH device. I can then put the whole mix as a MIC to a zoom session and voilá! Thank you!

**Comment by devinroth** [comment]
Perfect!
