### ISSUE TITLE
OS Catalina issue

### ISSUE THREAD

**Issue by adrianplambert** [ExistentialAudio/BlackHole#160]
I'm finding this very unpredictable.

I’m trying to routing audio from the built in speakers to blackhole then combining that with the mic so as to access from within the built in screen recorder. After I’ve set it up it works usually - audio is recorded from the internal system and the mic. But it’s very fussy. If it stops working (audio is only recorded from the mic) there seems to be no procedure that I can follow to get it up and running again including reboots of the computer or restarting core audio system. I've also tried not adding the mic to the aggregate device and just have the speakers and blackhole. Last Friday I wanted to record a webcast so I tested the settings and found internal audio was recorded. Moments later I started the 2 hour recording of the webcast and found at the end that no audio was recorded at all.

Screenshots of my set up attached...

![Screenshot 2020-05-18 at 20 57 03](https://user-images.githubusercontent.com/65604330/83170165-04c63700-a10c-11ea-9b1f-15649b851fda.png)
![Screenshot 2020-05-18 at 20 57 15](https://user-images.githubusercontent.com/65604330/83170172-07c12780-a10c-11ea-893b-ba94713d02f9.png)
![Screenshot 2020-05-18 at 20 57 28](https://user-images.githubusercontent.com/65604330/83170175-098aeb00-a10c-11ea-8d3f-72636e558b03.png)
![Screenshot 2020-05-18 at 20 57 39](https://user-images.githubusercontent.com/65604330/83170178-0abc1800-a10c-11ea-9aac-552a936db610.png)
![Screenshot 2020-05-18 at 20 57 50](https://user-images.githubusercontent.com/65604330/83170186-0c85db80-a10c-11ea-8f9a-988d60dde9f0.png)
![Screenshot 2020-05-18 at 20 58 10](https://user-images.githubusercontent.com/65604330/83170187-0e4f9f00-a10c-11ea-8fbc-95a05ccfda7b.png)

**Comment by adrianplambert** [comment]
On the second to last image it shows drift correction was turned off. I turned it on after making the screen shots and it's been on since then but the unpredictable situation continues.

**Comment by devinroth** [comment]
What were you using to record? Which browser were you using?

**Comment by adrianplambert** [comment]
Safari

**Comment by devinroth** [comment]
What app were you using to record?

**Comment by adrianplambert** [comment]
Screen Recorder.

**Comment by devinroth** [comment]
From QuickTime? You need to give me detailed instructions so I can try to replicate your issue.

**Comment by adrianplambert** [comment]
I initiate screen recorder usually when safari Is the active app, with shift-command-5. Then choose full screen recording, click on options and choose one of the aforementioned aggregated audio devices,then start recording.

**Comment by devinroth** [comment]
Well that's probably your problem. You should have just selected BlackHole as the audio device. Aggregates are known to be pretty buggy. You can blame Apple for that.

**Comment by devinroth** [comment]
But it's possible that the audio did in fact record but to different channels of audio than 1-2. Do you have the video file? I could inspect it.

**Comment by adrianplambert** [comment]
Yes I do, in fact I have a file with audio working as well that I made only seconds before with exactly same audio settings where the audio is working fine. The webcast recording with no audible audio is >8Gb though.

**Comment by adrianplambert** [comment]
> Well that's probably your problem. You should have just selected BlackHole as the audio device. Aggregates are known to be pretty buggy. You can blame Apple for that.

Can you clarify this as I followed the instructions on the website which said to create an aggregate device. Are you saying that I should choose the multi output device as the system output and blackhole within the screen recording app? Or something else. Also what are the implications for recording the internal mic and the system audio at the same time for video chats? Is this where the buggy apple aggregate devices will experience poor reliability?

**Comment by devinroth** [comment]
Quick question. 

Which Aggregate device did you use for recording. I see a couple in your photos.

I’ll answer your other questions soon.

**Comment by adrianplambert** [comment]
I was using the “input system audio” device when recording the screen casts - and for the short YouTube test recording but both that one and the “input system audio plus mic” exhibited the same unpredictable behaviour. 

Thanks
Adrian

**Comment by devinroth** [comment]
I think I have an idea of what's going on. From the looks of it actually wasn't working during your test. The issue is how the screen capture is grabbing the audio. Try with quick time and see if that helps.  I'll dig into this further when I have some time.

**Comment by adrianplambert** [comment]
After a few goes with QuickTime it’s worked each time so far. I’ll keep testing it though and let you know what happens. I was also wondering about the audio on the move file I sent through to you. You said that it may have recorded but onto another audio channel. I don’t suppose you’ve had a moment to explore that? Be great if I could get the audio back.
Thanks
Adrian

**Comment by devinroth** [comment]
Sorry it didn't record on there.

In Audio Midi setup if you click configure speakers under the device you can set it to stereo and it will work the way you want.

**Comment by adrianplambert** [comment]
Thank you. I’ll check that out. My first thought though is why it worked one minute but not the next as per those example files I sent to you?
