### ISSUE TITLE
Jump Desktop

### ISSUE THREAD

**Issue by Marenta** [ExistentialAudio/BlackHole#162]
Hi
I’m using Jump Desktop on my iPad Pro 11 to remote my Mac mini 2018. It’s supposed to support blackhole sound driver to stream the sound from desktop or my daw and it works kinda. Whatever audio I try to playback is very choppy and a drops out. I’m on latest iOS and macOS.

Any ideas what i could be?

Kind regards mats

**Comment by devinroth** [comment]
Haven't used Jump Desktop before. Could you send me some photos of how you set it up? I can take a look when I get a chance.

**Comment by Marenta** [comment]
Hi Devin,
Well, you can’t really do that much with the setup regarding audio in JD - just allow or not allow audio. I install blackhole driver on my client machine (mac mini), choose the BH sound driver for playback. Then I can remote my mini for the iPad and playback audio, but it’s very choppy. I guess it has something to do with latency, buffering but I’m not sure.

/Mats

**Comment by devinroth** [comment]
Please test with the latest version of BlackHole. If it's still a problem please reopen.
