### ISSUE TITLE
iTunes + Mic

### ISSUE THREAD

**Issue by wanamoa** [ExistentialAudio/BlackHole#163]
Hello !

I must be stupid : i am not able to set BH as i need.
I would want to output my mic (built-in on port mic) + iTunes.

Aggregates devices :
system output
Mic bult-in
BH 16ch

MultiOutput :
System Output
BH 16ch

I have set on TEAMS my output on multi out et my input on aggregated devices.
What's wrong please ?
![Capture d’écran 2020-06-05 à 14 05 32](https://user-images.githubusercontent.com/66473239/83874494-d8c33b00-a735-11ea-8b8a-7c219745d89d.png)
![Capture d’écran 2020-06-05 à 14 05 28](https://user-images.githubusercontent.com/66473239/83874502-dc56c200-a735-11ea-8d44-c6b8380b9c7c.png)

**Comment by wanamoa** [comment]
Hello,

No idea ?

**Comment by devinroth** [comment]
You need to mix iTunes and your mic together. I used Logic Pro X to do that but any DAW will work.

**Comment by Joshfindit** [comment]
This can be done with Loopback. Is it within the realm of possibility to bring that functionality to BlackHole as well?

Ideally I would like not to run a whole DAW just to mix the mic and audio output together when all I really want to do is capture system audio and mic at the same time.

**Comment by devinroth** [comment]
Since BlackHole is only a driver it's not possible without some sort of additional software such as a daw or some simple application to pass the audio from your mic to BlackHole.
