### ISSUE TITLE
No sound output from the native Twitter app

### ISSUE THREAD

**Issue by Brawrdon** [ExistentialAudio/BlackHole#165]
I've just noticed that no sound comes out of the native Twitter app when I have a Multi-Output Device enabled as the output device. The sound works when switching the output device back to either my external speakers or my Mac mini's built in speakers. I haven't noticed issues with any other app so I'm not sure if this is a bug with BlackHole or a problem with the Twitter app itself.

Here are some screenshots of my setup:
![Screenshot 1](https://user-images.githubusercontent.com/9751243/84060839-ca368700-a9b4-11ea-931e-e2a98af1fe43.png)
![Screenshot 2](https://user-images.githubusercontent.com/9751243/84060845-cc98e100-a9b4-11ea-873a-679b5b929159.png)

**Comment by devinroth** [comment]
Probably a bug with multi outputs. Add your Mac mini speakers to the TOP of the multi-output and see if that works. 
Just mute those speakers if you don’t want sound there.
