### ISSUE TITLE
Quicktime not grabbing audio when "Movie recording" (Catalina).

### ISSUE THREAD

**Issue by expora** [ExistentialAudio/BlackHole#166]
Hello. I noticed an issue and I'm not sure where the problem lies (Quicktime or BlackHole).

When I do a "New screen recording" from Quicktime and use BlackHole as the audio input everything goes well and it records the audio coming from another app.

When I do a "New movie recording" using my MacBook's camera or an iPhone camera, even though I can monitor the audio on Quicktime (and even see the volume indicators jumping around), once I record a clip, no audio is recorded.

**Comment by devinroth** [comment]
Try setting up the speaker configuration in audio midi setup for BlackHole to stereo. That may work.

**Comment by expora** [comment]
I didn't even know that was a thing. I'll try it and see if it works, thanks.

**Comment by expora** [comment]
It worked! Thank you very much.
