### ISSUE TITLE
Stopped working after updating to macOS 10.15.5

### ISSUE THREAD

**Issue by rafaeleyng** [ExistentialAudio/BlackHole#168]
Hi, 1 or 2 days ago I've updated my macOS to the latest version, and yesterday I've tried to use BlackHole (which I was using on a weekly basis and worked until last week) and it didn't work. Both input and output stopped working (I can still set them as the in/out device, but I don't get any signal on in/out).

Still haven't had the time to dig deeper but in case anybody knows the solution from the top of the head, I'd appreciate it.

I will try to dig deeper in the next couple of days and will try to report back here.

**Comment by devinroth** [comment]
That's concerning. Did you find out anything?

**Comment by rafaeleyng** [comment]
Hello there, I haven't time do check it yet. I will try to investigate it until tomorrow.

**Comment by renatocast** [comment]
Same problem here. Not working in Ableton Live after MacOs last update...

**Comment by mcuriale** [comment]
Trying blackhole for the first time. It's not working. Seems to be a problem with output. I installed it under macOS 10.15.5 could this be the problem?

**Comment by enzyme69** [comment]
I am also not getting anything I thought I did everything correctly :/

**Comment by devinroth** [comment]
I just tested this out on macOS 10.15.5 and everything worked normally. I used iTunes -> BlackHole -> Logic Pro X and the audio came through without any issues. There is nothing about the update that caused BlackHole to break.

Perhaps updating removed the microphone permissions? 

If you have any issues please be more specific on how things are setup.

**Comment by mcuriale** [comment]
I have a 2013 MacBook Air with 10.15.5. After installing Blackhole, I have no output if I select Blackhole 16ch as the output device. The message on selection instead of showing an output balance slider as seen for internal speaker selection, shows the message “The selected device has no output controls.” Note, I have not tried Blackhole with an earlier Mac OS version.

If there is other information that I might be able to provide, please let me know.

Mike Curiale

**Comment by mcuriale** [comment]
I have it working now. I am not sure why or what happened. It is possible that that the Citrix Workspace app was interfering.

thank you for being patient with me and I apologize for any undo work I caused.

**Comment by devinroth** [comment]
I'm going to close this issue. @rafaeleyng if you are still having issues please create a new issue with more details.

**Comment by rafaeleyng** [comment]
Ok, my bad. I've just tried it again and it is not working, but I don't have time to further investigate now. I will open a new issue with more details when I get to test it better.
