### ISSUE TITLE
Offset channels inputs

### ISSUE THREAD

**Issue by quantuminformation** [ExistentialAudio/BlackHole#169]
Is there any way to tell black hole start channels from three?

![image](https://user-images.githubusercontent.com/216566/84532099-ef453580-ace5-11ea-9687-b56e91ff1699.png)

Its because GarageBand can always select start stero from one or three

![image](https://user-images.githubusercontent.com/216566/84532136-fff5ab80-ace5-11ea-9432-63714cae4258.png)

**Comment by devinroth** [comment]
That’s annoying. 

Not that I know of. But…

As a work around you can just make two mono channels in garage band instead. 

Sometimes GarageBand is too user friendly.

**Comment by quantuminformation** [comment]
yeah, im trying to figure that out 
![image](https://user-images.githubusercontent.com/216566/84532882-56171e80-ace7-11ea-9b45-b294efc9fc21.png)

**Comment by quantuminformation** [comment]
mono fixed it)
