### ISSUE TITLE
brew cask install blackhole just downloads a .pkg file, it doesn't install anything

### ISSUE THREAD

**Issue by justinkterry** [ExistentialAudio/BlackHole#171]
Per the title, your brew formula just downloads the .pkg file. It doesn't install anything. That isn't the expected behavior, if not fixed it and should at least be clarified in the documentation.

**Comment by justinkterry** [comment]
Also, the downloaded .pkg file can't be installed on cataline. It gives the error "“BlackHole.v0.2.6.pkg” cannot be opened because it is from an unidentified developer."

**Comment by devinroth** [comment]
Thanks for bringing that up. I did not setup the brew formula. I'll just remove it. Please just download the notarized copy from the website.

**Comment by devinroth** [comment]
Perhaps I'll add it in correctly at some point if I get a chance.

**Comment by justinkterry** [comment]
Can you make sure it doesn't work for you too before axing it? Something strange just happened.

**Comment by devinroth** [comment]
I’ve been thinking about redoing it for a while. 

I’ll add it to my todo list.
