### ISSUE TITLE
homebrew cask installation broken

### ISSUE THREAD

**Issue by arielelkin** [ExistentialAudio/BlackHole#172]
`brew cask` command no longer works. brew cask expects the .pkg file to be hosted on github but it's no longer there:

```
$ brew cask install blackhole
==> Downloading https://github.com/ExistentialAudio/BlackHole/releases/download/v0.2.6/BlackHole.v0.2.6.pkg
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'blackhole' with message: Download failed: https://github.com/ExistentialAudio/BlackHole/releases/download/v0.2.6/BlackHole.v0.2.6.pkg
```

**Comment by timczsb** [comment]
The homebrew instructions were removed from the readme 2 days ago.  I hope this is temporary though.  Some feedback on the intentions here would be appreciated.

https://github.com/ExistentialAudio/BlackHole/commit/1b962b981cba9b9a4a0f5448d8a9237f4c0980ba

**Comment by devinroth** [comment]
Yeah. There were some issues. I’ll look into adding support again when I have more time next month. Just temporary.

**Comment by vitorgalvao** [comment]
Homebrew Cask maintainer here.

@devinroth “Next month” is a bit far away when the cask for this software gets over 1500 downloads a month, especially because these things tend to get delayed (or abandoned). That’s a lot of bug reports we’re going to get and have no control over fixing. If it’s going to take that long, it might be best for us to delete the cask outright until it’s installable again.

For the most part, we don’t care where the `pkg` is hosted, so if you have a clear working download link not blocked by a signup page and that doesn’t avoid CLI downloads, someone could fix the cask today.

Please let me know if that’s a plan you wish to pursue or if we should go ahead with the removal.

**Comment by devinroth** [comment]
Sorry just crazy busy at the moment but if you help me out we can get it up ASAP.

I’d rather just host it on my website.

How exactly does Homebrew Cask work? 

How does it know how to download the latest version?

I just set it up to be hosted at existential.audio/downloads/BlackHole.v0.2.6.pkg 

Then all subsequent versions are just change the version numbers at the end.

Let me know if that works.

**Comment by devinroth** [comment]
So how can I check to see how many downloads I am getting through homebrew cask? Just curious.

**Comment by vitorgalvao** [comment]
> How does it know how to download the latest version?

It doesn’t. Updates are submitted manually, or automatically if there’s an appcast (such as a Sparkle feed) that we can check for, but it’s always updated on the repo before being pushed to the users.

In this case, [the atom feed auto-generated](https://github.com/ExistentialAudio/BlackHole/releases.atom) from [the releases page](https://github.com/ExistentialAudio/BlackHole/releases.atom) works.

> I just set it up to be hosted at existential.audio/downloads/BlackHole.v0.2.6.pkg
>
> Then all subsequent versions are just change the version numbers at the end.
>
> Let me know if that works.

[Beautifully](https://github.com/Homebrew/homebrew-cask/pull/84603/files#diff-b9d9135cbf164368e10622843cc9f1aa).

> So how can I check to see how many downloads I am getting through homebrew cask? Just curious.

If you have it installed, do `brew cask info blackhole` and you’ll see the analytics at the bottom.

```console
$ brew cask info blackhole
blackhole: 0.2.6
https://github.com/ExistentialAudio/BlackHole
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/blackhole.rb
==> Name
BlackHole
==> Artifacts
BlackHole.v0.2.6.pkg (Pkg)
==> Analytics
install: 1,525 (30 days), 5,521 (90 days), 8,062 (365 days)
```

You can also find [downloadable JSONs of that data on the website](https://formulae.brew.sh/analytics/).

**Comment by vitorgalvao** [comment]
> Thanks for helping out.

Thank you for acting so fast!

> How do I submit the new version to brew cask?

You can either:

1. Directly update [the file](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/blackhole.rb). Unless something changed internally, only `version` and `sha256` should need updating.
2. Use [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask). After a quick setup, you can just do `cask-repair --cask-version NEW_VERSION_HERE blackhole` and it will do everything for you, including submit the PR.

**Comment by iamandrewluca** [comment]
No more `v0.3.0` updates for brew users? 😢 

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/1881266/155767027-bcd51f2d-bf4b-41b6-b28b-89d4c8184c8a.png">
<img width="680" alt="image" src="https://user-images.githubusercontent.com/1881266/155767059-136f5df0-3576-45ef-9bb8-afb3169af03b.png">

**Comment by devinroth** [comment]
I’m going to skip v0.3.0 and jump directly to v0.3.1 when it’s ready. Too many bugs in 0.3.0.

Devin

**Comment by iamandrewluca** [comment]
Thanks a lot!
