### ISSUE TITLE
Use case: audio video sync

### ISSUE THREAD

**Issue by larstobi** [ExistentialAudio/BlackHole#174]
I am looking for a way to add a negative delay for audio output. The use case is to fix audio/video sync issues when using Bluetooth loudspeakers/headphones to play video, which can sometimes add audio delays of about 200 ms.

Some desktop apps support adding custom a/v sync values (setting -200ms audio delay fixes it for me), and thus fix the problem. While using video playback from web streaming from browsers will not let me fix a/v sync when using Bluetooth sound output.

Is this even possible?

**Comment by devinroth** [comment]
There’s an option to add latency. There should be something in the wiki about it.

**Comment by larstobi** [comment]
Can I also add **negative** latency? :-)

**Comment by devinroth** [comment]
Huh? 

BlackHole is current set so there’s zero additional latency. 

You mean you want audio to be heard before it’s played? That’s time travel.

**Comment by larstobi** [comment]
You're right about that! :-D I suppose, what I'm really looking for is a video delay thing, not an audio delay thing.

The problem is that my Bluetooth speakers add 200 ms of audio latency, so the video is played 200 ms before the audio. In some video players, I can set -200 ms audio delay, and that fixes the audio video sync. It's probably not great to talk about it as negative delay.

**Comment by devinroth** [comment]
You may be able to change the reported latency in BlackHole and then just cheat by actually doing it. There may be a way around.

**Comment by lisanet** [comment]
> You're right about that! :-D I suppose, what I'm really looking for is a video delay thing, not an audio delay thing.

You could use IINA video player. https://iina.io 
It comes with a Safari plugin which will let you watch the currently playing web video in a separate IINA player window and so you'll get all of IINA's features, like a 'negative audio sync' aka video delay.

**Comment by rowe-morehouse** [comment]
@larstobi … You could also use "Airfoil" to play to your bluetooth speakers — it has advanced latency correction options. 

https://rogueamoeba.com/support/knowledgebase/?showArticle=AudioDelaysAndSync

**Comment by larstobi** [comment]
Thanks for the tips. I'll try them out!
