### ISSUE TITLE
Audio Output of Apple Messages does not work

### ISSUE THREAD

**Issue by julian-weinert** [ExistentialAudio/BlackHole#175]
I'm totally confused today. I was sent a video by someone of the family of which I couldn't hear any audio from within Messages.
It took me about half an hour to find out that the "reason" was that I'm using BackHole.
I'm so confused since I don't see any technical reason how an app could care about the output device in use...
By now I could not find another app with this issue, but keep you posted if I do so.

I'm using BH as system output and "Hosting AU" (like a micro-DAW) to route the audio to a multi-output device.
Since I still have Soundflower installed I tested it against that and it works.

I'm a developer myself but pretty new to the hardcore audio stuff. I'm happy to mess around / search myself, but would need a little hint where to start...

**Comment by devinroth** [comment]
It seems that BlackHole has trouble with Apple's apps. A number of issues with Facetime, Quicktime, Screen capture, dictation, etc. But seems to work fine with everything else. I have more time to dig into it next month. So no idea at the moment. Feel free to mess around and see if you figure it out.

**Comment by devinroth** [comment]
So it seems that Messages Doesn't support Multi-outputs. If you just use BlackHole only it's not an issue. This is a Blame Apple issue. I'll add messages to the list of Apps that don't work with Multi-outputs.

**Comment by julian-weinert** [comment]
Hey @devinroth, I'd like you to reopen the issue. I used multi-output at that point, but changed my setup since.
So I only use BlackHole to route System Audio to a different App.

To me it seems like an issue with channel layout. I have a few videos and audios, some are mono and some are stereo.
The stereo files play fine, but the mono files stay silent.

Also direct playback from DAWs does not work, but that may be a hole other problem...

**Comment by devinroth** [comment]
But why is this a BlackHole issue? Seems like it's an issue with Messages. I'm not sure there is anything that can be done with BlackHole to fix that. I'm open to suggestions.

**Comment by julian-weinert** [comment]
Of course I forgot some detail. I was about to create a new issue when I remembered this one and forgot to write some details here as well, sorry.

It's not only the Messages. The mono issue I described also comes up with the Quick Time Player and even with Quick Look, wich is the biggest problem for me.

There is a software called [Sessionwire Studio](https://www.sessionwire.com) which comes with two HAL plugins just as BlackHole. Actually they could be considered a secret competitor ;) It is meant to connect DAW sessions over the internet.
The included Plugins from them don't have the same problem. They deal fine with every situation where BlackHole had this problem (messages, mono audio in Quick Time and Quick Look). But since they only use it as routing within DAWs they didn't include volume control.

So it looks like it's not a system issue.
With my limited experience with CoreAudio it still seems like a real strange issue to me anyway.
I'm not sure if it would be a legal or moral issue, but it may be possible to decompile both and compare the API usage if anything obvious sticks out...

**Comment by julian-weinert** [comment]
I'm so sorry Devin, I messed up big time. A bit embarrassing for a fellow dev, but I must have screwed up something.
I just installed the current version again and all issues seem to be fixed.
Mono works in Quick Look and Quick Time Player and even Messages seems to be working fine now.

The only thing that does not work is DAW output. Is that already a known issue?

**Comment by devinroth** [comment]
No worries.

What do you mean by DAW output?

Devin Roth

**Comment by julian-weinert** [comment]
I think my computer wants to drive me crazy... As I wrote the comment I couldn't playback audio from Logic Pro.
Not to embarrass myself again I tried it again and now it works. I'm puzzled.

But you have fixed the issue somewhere down the line.
Thanks for the great work :)

**Comment by devinroth** [comment]
Magic.

Devin Roth
