### ISSUE TITLE
Zoom's "enable stereo" does not work for Black Hole as mic input device

### ISSUE THREAD

**Issue by ndonald2** [ExistentialAudio/BlackHole#176]
I have been using an aggregate device with my audio interface and Black Hole to route DAW audio to other applications. In most cases (e.g. OBS) it works great and I get stereo audio sent between apps. However, this does not work with Zoom, and I'm not sure if it's an issue on the Black Hole side or the Zoom side.

My setup:

* DAW output device: Aggregate Device with my audio interface and Black Hole
* Master bus in DAW is dual-routed to both the interface main output channels and Black Hole channels 1/2
* Zoom mic input is set to Black Hole channels 1/2 (cannot choose channels in Zoom settings - it just uses the first one/s)
* Zoom "Enable stereo" is checked so I can send stereo audio

I get levels in Zoom no problem, other participants can hear my audio as I'd expect. However, it's in mono, and I can't figure out why. I verified Zoom's stereo audio option is working on other audio devices by choosing my interface as the mic input and sending stereo audio through its first two analog input channels - other participants hear stereo in that case.

Any idea what the issue might be? Thanks!

_FYI: I have a temporary workaround by hard-patching the analog main outs from one of my interfaces into the analog input pair on another interface, then choosing the second interface as the Zoom input. It's not ideal, but it works._

**Comment by devinroth** [comment]
It’s because zoom only supports stereo when using their driver.

**Comment by ndonald2** [comment]
That's not true based on my experimentation. As I said, I enabled stereo in Zoom and ran analog signal into the first two inputs of my Focusrite Scarlett 2i4, and chose that as my mic input device. I "enabled original audio" to kill the voice processing as well. Under those conditions - NOT using the Zoom audio driver - participants receive stereo audio. Validated by hard-panning what I was sending in.

It could very well be something Zoom doesn't like about Black Hole vs. a using a hardware audio device as the input in Zoom, but it's definitely possible without using their driver.

**Comment by devinroth** [comment]
Well I haven’t found a way to make it work. If you do, please let me know.

I don’t see how BlackHole would be any different than using the input from the 2i4. I guess you’ll have to play around with it. But please report back if you figure it out. I’ll add a tutorial on the website or wiki.

**Comment by konradkaczmarek** [comment]
A few observations that I've made regarding zoom/virtual audio devices/stereo:
If you select an audio device (physical or virtual) that has greater than 2 channels as the 'microphone input' in zoom, it will sum all channels together and send a mono signal. 

If your audio device has exactly 2 channels, zoom assumes stereo, and if enabled, will pass a stereo signal.  I have tested with a 2ch build of blackhole and a software mixer in Max for panning/spatialization, and it does indeed send stereo.

**Comment by devinroth** [comment]
Wow. That’s great to know. 

And dumb of zoom.

Could you test one more thing for me?

If you are using BlackHole 16ch and you set the speaker configuration to stereo in audio midi setup does stereo in zoom work then?

**Comment by ndonald2** [comment]
Agree, thanks for helping figure this out @konradkaczmarek! I will try a 2ch build of Black Hole next time.

Agree it's dumb of Zoom to do that... I wish they just added channel configuration already.

**Comment by ndonald2** [comment]
> If you are using BlackHole 16ch and you set the speaker configuration to stereo in audio midi setup does stereo in zoom work then?

I have tried this, it doesn't work @devinroth 

Since this is clearly a Zoom issue I'm going to close it out, thanks for helping find the root cause!

**Comment by colinsullivan** [comment]
Thanks for this research.  

I'm going to try two instances of BH - one that is at the end of the aggregate device chain - that I only need for streaming, etc.

This way, Zoom will get handed the 2ch device and it will do the right thing.

![image](https://user-images.githubusercontent.com/94535/100308555-8c76ec00-2f5d-11eb-977a-e36755bbee0c.png)
