### ISSUE TITLE
[deleted]

### ISSUE THREAD

**Issue by rafaeleyng** [ExistentialAudio/BlackHole#177]
My bad, sorry. Two similar words confused me.

**Comment by devinroth** [comment]
You’re totally right. I think it gets a little strange. Because on Mojave system/Library doesn’t exist.

**Comment by rafaeleyng** [comment]
Yeah, the doc is a little strange. But the main problem was that I had 2 drivers named similarly (but one in `/Library` and one in `/system/Library`, and read them as the same thing.

**Comment by devinroth** [comment]
Okay. How should I change the docs to make it more clear?

**Comment by rafaeleyng** [comment]
I honestly don't understand the `NOTE: The directory is system/Library not user/Library` part. I'm not even sure what paths they refer to. I don't know which path is `user/Library` (I'm inclined to understand it as `/Users/<username>/Library`), but I'm not sure whether that is the case. `system/Library` causes me the same confusion (is it `/Library`, `/System/Library`, something else?)

If all we need to run (in point `1` of the uninstallation section) is `rm -fr /Library/Audio/Plug-Ins/HAL/BlackHole.driver`, I would leave just this part, without the `NOTE: ...` part.

**Comment by MaikWaschfeld** [comment]
Hi everybody,

> First of all, I'm not an expert on macOS directory structure.


As the majority of the Blackhole-users are resp. are not, I suppose.


The „Uninstallation Instructions“ on the GitHub page are quite misleading, especially the „Note“ part which is incorrect, if the user is not aware of the differences of „system/Library“ or „System/Library“ or „user/Library".

> Delete BlackHole.driver by running rm -fr /Library/Audio/Plug-Ins/HAL/BlackHole.driver NOTE: The directory is system/Library not user/Library


A bit of background:
Current macOS versions contain three possible locations to hold HAL Plug-Ins:

All paths from the root-level of your system disk, so add [Macintosh HD] or whatever you named your system volume, to the beginning to get the „real“ path.
These paths are case-sensitive!

- [/System/Library/Audio/Plug-Ins/HAL/] is read-only for everyone, except Apple, and should resp. can not be modified by anyone. Period.
- [/Library/Audio/Plug-Ins/HAL/] is the place for Plug-Ins, that every logged-in user may use. The „common“ place.
That’s the place, the Blackhole-installer uses.
- [/Users/<your short user name>/Library/Audio/Plug-Ins/HAL/] is the user’s private place to hold HAL Plug-Ins.
If Blackhole.driver is already in [/Library/Audio/Plug-Ins/HAL/], you don’t need it in your user’s place too, as an installation of a new version of Blackhole.driver don’t checks in this private place and so you can have two different versions running in your system, which is definitely not good!
Even and especially if you are the only user of your machine, you definitely don’t want the driver to be in your private HAL folder and in the „common“ folder.

If you didn’t modify the Blackhole-installer or copied/moved the installed driver, just run the following two commands independently (and without the brackets!) in the terminal:
(rm -fr /Library/Audio/Plug-Ins/HAL/BlackHole.driver)
(sudo launchctl kickstart -kp system/com.apple.audio.coreaudiod).


Side note:
as Eventide has a Plug-In named „Blackhole“, just don’t search for other locations n the „Plug-Ins“ folder, like „Components“ and delete this Plug-In manually or you’ll loose the Eventide „Blackhole“ in your DAW.


With kindest regards…
…Maik Waschfeld

(sent from my MBAir11)

**Comment by MaikWaschfeld** [comment]
Hi everybody,

> First of all, I'm not an expert on macOS directory structure.

… as the majority of the Blackhole-users are resp. are not, I suppose.


The „Uninstallation Instructions“ on the GitHub main page are quite misleading, especially the „Note“ part which is incorrect, if the user is not aware of the differences of „system/Library“ or „System/Library“ or „user/Library".

> Delete BlackHole.driver by running rm -fr /Library/Audio/Plug-Ins/HAL/BlackHole.driver NOTE: The directory is system/Library not user/Library

A bit of background:
Current macOS versions contain three possible locations to hold HAL Plug-Ins:

All paths from the root-level of your system volume, so add [Macintosh HD] or whatever you named your system volume, at the beginning to get the „real“ path.
These paths are case-sensitive!

- [/System/Library/Audio/Plug-Ins/HAL/] is read-only for **everyone**, except Apple, and should resp. can not be modified by any user or admin. Period.
- [/Library/Audio/Plug-Ins/HAL/] is the place for Plug-Ins, that every logged-in user may use. The „common“ place.
That’s the place, the Blackhole-installer uses.
- [/Users/<your short user name>/Library/Audio/Plug-Ins/HAL/] is the user’s private place to hold HAL Plug-Ins.
If Blackhole.driver is already in [/Library/Audio/Plug-Ins/HAL/], you don’t need it in your user’s place too, as an installation of a new version of Blackhole.driver don’t checks in this private place and so you can have two different versions running in your system, which is definitely not good!
Even and especially if you are the only user of your machine, you definitely don’t want the driver to be in your private HAL folder **and** in the „common“ folder.

If you didn’t modify the Blackhole-installer or copied/moved the installed driver, just run the following two commands **independently** in the terminal:

`rm -fr /Library/Audio/Plug-Ins/HAL/BlackHole.driver`

`sudo launchctl kickstart -kp system/com.apple.audio.coreaudiod`

Side note:
as Eventide has a Plug-In named „Blackhole“, just don’t search for other locations in the „Plug-Ins“ folder, like „Components“ and delete this Plug-In manually or you’ll loose Eventide's „Blackhole“ in your DAW.

With kindest regards…
…Maik Waschfeld

**Comment by devinroth** [comment]
Thanks @MaikWaschfeld. That clears a few things up for me.
