### ISSUE TITLE
Blackhole no longer working after using bluetooth.

### ISSUE THREAD

**Issue by weepy** [ExistentialAudio/BlackHole#178]
Blackhole was working fine with a multi-output device (set up as per the instructions).

I then tried to use some wireless blue tooth headphones. I found it to be slightly laggy for what was doing, so reverted. However now nothing plays though Blackhole through the muilti-output device. 

I am able to record internally through it, but not output from it. All the settings look fine the AUDIO + MIDI output. 

Restarting + resinstalling Blackhole making no difference. I also tried Soundflower out of desparation and am getting the same issues. So it's a bit of a weird one. 

J

**Comment by weepy** [comment]
my bad

**Comment by Nithin-anim** [comment]
I am also facing the same issue when using bluetooth headphones.Can you tell me how you resolved the issue.

**Comment by weepy** [comment]
stopped using bluetooth headphones ...
