### ISSUE TITLE
Support for AU Plugins

### ISSUE THREAD

**Issue by xrad** [ExistentialAudio/BlackHole#18]
It would be very nice to be able to stick AU plugins in the processing chain to support things like [AutoEq](https://github.com/jaakkopasanen/AutoEq). SoundSource is an commercial solution for this and I'm using it, but a free alternative would be great to have!

**Comment by xrad** [comment]
Awesome! Let me know if you need any input.

**Comment by devinroth** [comment]
Will do. Probably won't happen for a while.

**Comment by leocoracini** [comment]
Please @devinroth It will definitely be a break deal with AU Plugins. The thing is that just a little percentage of people know how amazing AUGraphicEQ is for the hole output audio on MacOS.
Hope it won't be difficult to build 😊
Thanks

**Comment by xrad** [comment]
@leocoracini In the meantime you can use SoundSource. Commercial, but not overly expensive IMO.

**Comment by danekszy** [comment]
Doesn't AU Lab handle such scenarios?

**Comment by devinroth** [comment]
Yeah AU Lab will do the trick.

**Comment by devinroth** [comment]
Although I have found AU Lab to be buggy. It’s worth trying though.

**Comment by leocoracini** [comment]
Yeah, AU Lab is kinda buggy. Sometimes doesn't work automatically when plug/unplug earphones. It also buggy input when on Skype meeting. Audio is a must have in my daily life, so I prefer some alternative that "just works" all the time.
I've tried the SoundSource in trial mode, really like it but my currency is Brazilian Real, so the price in US dollars is quite expensive 🙁

Thanks guys!

**Comment by v10x** [comment]
The main issue with AU Lab is that apart from bugs and being generally unreliable, it's required to have its GUI always running and cannot be used in any other way.

What I'd like to see is a way to have AU plugins directly into BlackHole's core, this not only would reduce latency to a minimum, but it'd also be non-intrusive.

**Comment by odinian** [comment]
+1 for AU plugins.

**Comment by pbernier** [comment]
+1 for AU plugins.

**Comment by kkanungo17** [comment]
Yep, addition of AU plugins support would make this the perfect open-source solution for system-wide DSP effects.

**Comment by olegnaumenko** [comment]
+1 for AU! it's not not just that AU LAB is buggy but it's also CPU intensive.

**Comment by fjolnir** [comment]
+1 🙏

**Comment by tom-dreamviewer** [comment]
+1

**Comment by rowe-morehouse** [comment]
Great app, thank you. +1 for AU support. Also, you guys got hunted on Product Hunt. You should go over there and claim it as a maker. https://www.producthunt.com/posts/blackhole-1

**Comment by ProfFan** [comment]
+1, I have AU Labs running quite smoothly but it does sometimes have artifacts and loss of audio output

**Comment by jslpc** [comment]
Would absolutely love AU support

**Comment by rowe-morehouse** [comment]
@odinian … Blackhole and SoundSource are complimentary. You can't replace one with the other — they are not the same.

@odinian Blackhole is an audio router (like an advanced Soundflower) while SoundSource allows you to control the volume on individual applications (like a mixer for your apps) and choose different outputs for each app.

For example, if I want to route audio from chrome to record into Audactity, I use SoundSource to route output from Chrome to Blackhole, then use Blackhole as the input on Audacity.

Yes, SoundSource supports AU, you can put effects on any app that is playing sound. It is a great app, worth the $39 in my opinion. I think you'll love it too. 

Also, BLACKHOLE RULES. :)
