### ISSUE TITLE
FYI - Audacity now works on Catalina

### ISSUE THREAD

**Issue by danyork** [ExistentialAudio/BlackHole#180]
FYI, with regard to the note you have on your main page about Audacity not working on Catalina. That _was_ an issue, but the Audacity team fixed it with [Audacity 2.4.1 on May 21, 2020](https://www.audacityteam.org/audacity-2-4-1-released/). And there is now [Audacity 2.4.2 on June 26, 2020](https://www.audacityteam.org/audacity-2-4-2-released/).

It may be better to change that text to say something like:

----

How can I use BlackHole with Audacity in Catalina?

Audacity only works with macOS Catalina as of Audacity version 2.4.1 in May 2020. If you have an older version, you will need to upgrade to the latest release.

----

**Comment by devinroth** [comment]
Great. Thanks for the update. I’ll change it.
