### ISSUE TITLE
CoreAudio settings

### ISSUE THREAD

**Issue by kkanungo17** [ExistentialAudio/BlackHole#182]
Is it possible to set the actual audio output device to the format of the audio file being played?

**Comment by devinroth** [comment]
Sure but it’s kind of useless. CoreAudio runs everything as 32bit float regardless of the input format. And there is no loss of information when converting from other formats to 32 bit float. I may add “virtual” formats but everything gets converted to 32bit float no matter what.

**Comment by kkanungo17** [comment]
I meant as in sampling rate, for example, does BlackHole automatically set itself to 44.1kHz when a music file is played?

**Comment by devinroth** [comment]
It’s up to the audio application playing the file to set the sample rate or handle any sample rate conversion.

**Comment by kkanungo17** [comment]
Ah, thanks for the clarification!
