### ISSUE TITLE
Send audio from specific application only

### ISSUE THREAD

**Issue by loupaw** [ExistentialAudio/BlackHole#183]
Is there any way to route audio only from a specific application to BH ie. send audio only from Premiere Pro (and no other running apps) to BH? If not, is this something that might be in the works?

**Comment by devinroth** [comment]
Just setup a Multi-output and use that as the audio device in Premiere Pro. As long as you don’t set blackhole as the audio device in any other application or as the default output no other device will be using it.

**Comment by loupaw** [comment]
Ah that makes sense - thank you. Don't think this works for Avid Media Composer though, as Media Composer doesn't allow you to select your own audio device for playback (it defaults to whatever the output device is in system prefs).
