### ISSUE TITLE
Gain attenuation when recording system audio output

### ISSUE THREAD

**Issue by arielelkin** [ExistentialAudio/BlackHole#188]
I'm writing a script to record the system's audio output using Blackhole and [Sox](http://sox.sourceforge.net/sox.html).

I'm setting both the input and output audio devices to "Blackhole 16ch". I set the output volume to maximum. 

Then I run this sox command to record the audio output of the system
```
rec --rate 44100 --channels 2 -b 16 --no-dither test-output.aiff -V
```

Then I play back an audio file I have on my disk. 

The resulting recording is always at half the gain:

![image](https://user-images.githubusercontent.com/1756909/88956162-d93f0480-d294-11ea-8148-a845c5621f10.png)

If I use Loopback as the audio device and repeat the experiment, the resulting recording is at parity gain, so I'm thinking that there might be an issue with BlackHole here. 

Any ideas?

**Comment by julian-weinert** [comment]
Did you check the input gain of BH as well?
![Screenshot 2020-08-03 at 10 33 14](https://user-images.githubusercontent.com/3418452/89163011-3c6eb680-d575-11ea-87cb-2ee27858cfe7.png)

**Comment by arielelkin** [comment]
Yep, it's at 1.

**Comment by devinroth** [comment]
Test again on the latest release and let me know.

**Comment by devinroth** [comment]
Any update?

**Comment by arielelkin** [comment]
@devinroth Sorry for the delay. 

Unfortunately the issue persists in 0.2.8

![image](https://user-images.githubusercontent.com/1756909/104910352-1a30ef80-5981-11eb-98eb-dedada0a0e8d.png)

**Comment by devinroth** [comment]
I run a number of tests and cannot replicate your results.

**Comment by devinroth** [comment]
<img width="773" alt="Screen Shot 2021-01-18 at 11 20 57 AM" src="https://user-images.githubusercontent.com/13010961/104955670-611de580-597f-11eb-8639-761a377da76e.png">

**Comment by devinroth** [comment]
As you can see every single test is exactly the same, except that QuickTime does a 400ms fade at the beginning.

**Comment by devinroth** [comment]
Nothing in BlackHole is changing the volume.

**Comment by devinroth** [comment]
My guess is Loopback is boosting the volume.

**Comment by arielelkin** [comment]
do you also get the same results when recording system output via sox? 

```
rec --rate 44100 --channels 2 -b 16 --no-dither test-output.aiff -V
```

**Comment by devinroth** [comment]
QuickTime to SoX is on the bottom. Looks perfectly normal. I don't have a clue what you are doing wrong. 

<img width="930" alt="Screen Shot 2021-01-18 at 10 24 55 PM" src="https://user-images.githubusercontent.com/13010961/104996051-11b9d280-59dc-11eb-8737-981df382ca37.png">

**Comment by arielelkin** [comment]
I'm trying to do integration tests for an iOS app, whereby I'm testing that the app actually outputs the correct sound. So I record (using sox) the iOS Simulator's audio output while it's running the integration test. It could be that the iOS Simulator is doing some gain attenuation itself?

**Comment by devinroth** [comment]
Possibly. Is the volume all the way up in the simulator?

Make sure the sims output is BH and system default mic is BH.

Devin

**Comment by devinroth** [comment]
Closing since I've determined it's not related to BlackHole.
