### ISSUE TITLE
Installing Black Hole Makes Jack Router Disappear

### ISSUE THREAD

**Issue by chigkim** [ExistentialAudio/BlackHole#189]
I installed Black Hole on my machine, and it made Jack Router disappear.
Also my friend has the same problem.
Jack router disappeared on his machine after installing black hole.
How can I get Jack Router back?

**Comment by devinroth** [comment]
Funny. Try reinstalling Jack.

**Comment by chigkim** [comment]
Great, reinstalling Jack worked!

Why did that happen?

Does Black Hole uses Jack as back end?

**Comment by devinroth** [comment]
Doesn’t use Jack at all. 

I’ll look into this.
