### ISSUE TITLE
Mix: SystemSound und Microphone

### ISSUE THREAD

**Issue by fabnoe** [ExistentialAudio/BlackHole#190]
How should I configure Audi Midi Setup to aggregate **System Sound** and **Microphone** as one signal to use with Microsoft Teams.

**Comment by devinroth** [comment]
It can't be done with AudioMidi Setup alone. I use a DAW to combine the two. 

You can check out this tutorial. https://existential.audio/howto/StreamFromGarageBandToGoogleMeet.php.

I'll add Microsoft Teams to my next update but you should get the idea.

**Comment by virgini4** [comment]
I am trying to solve this issue right now.  I downloaded and installed blackhole audio driver.  I am not sure how to configure it so that my airpod mic and my computer audio both play through Microsoft Teams. I was able to move my computer audio to play over Teams, but now my mic isn't playing on Teams.  I need my mic and computer audio to play on Teams in live meetings at the same time.

**Comment by jiangjianping** [comment]
@devinroth ,
Zoom can do with the aggregated input (mic+system audio). What should be done to support this?

**Comment by devinroth** [comment]
What you need is a program that will mix the mic into BlackHole. I suggest looking at my tutorials for GarageBand since they will achieve this goal.

**Comment by delewis13** [comment]
@devinroth first off thank you for this amazing piece of software! 

I'm looking at integrating BlackHole with my app for exactly the functionality described in this thread [my app isn't GPL-3 so i'll reach out to you if I do end up getting to that stage of development, it's some way off yet].

I've gotten your garage band suggestions working on my local, however I want to provision all this automatically and as a black-box for end user. 

Was wondering if that will ever be possible for BlackHole? Seems it is impossible / out-of-scope from your first comment on the thread? If that's so, I was hoping you may have some other software suggestions I could package up alongside BlackHole to silently achieve same results as your GarageBand recommendation?

Cheers 👍

**Comment by devinroth** [comment]
Send me an email at devinroth@existential.audio and we’ll talk about it there.

I’m pretty back logged with emails but I promise I will get to it.

Devin

**Comment by jiangjianping** [comment]
@delewis13 @devinroth,

Solved? or need sponsor for this?

**Comment by devinroth** [comment]
A sponsorship would be great as it will take me some time to get this figured out. I think the best path forward is creating an app that can mix and route audio inputs to different outputs. Like a mixer or something. What do you think?
