### ISSUE TITLE
Audio drop outs for Ableton via HDMI out

### ISSUE THREAD

**Issue by blackbookchris** [ExistentialAudio/BlackHole#191]
Hi there.  So here's my problem.  I'm running Ableton Live on a macbook pro running macOS Mojave, sending my screen capture and audio via HDMI output to an Elgato HD60 S capture card, which is connected to my PC running Stream Labs OBS to stream to twitch.  In my Audio Midi setup on the mac I have set up an multi output device that I've taken screenshot of the settings for below.  I'm monitoring the audio out of Ableton via my headphone out port on the macbook pro.  The audio is running fine and consistently from the mac, but when I look at Streamlabs OBS built in mixer, I can see the audio cutting in and out consistently (I've attached a video of exactly what is going on).  I've made sure the sample rate for ableton, the multi output device, the elgato and Streamlabs OBS is all set to 48000 hz.  I cannot work out what it is I'm doing wrong or what is going wrong and it's very distracting for me whilst streaming of course.  Any help here would be greatly appreciated.  

Here is the video of the problem 

https://www.dropbox.com/s/m5w45kkbdq1izuy/IMG_4970.mov?dl=0

<img width="638" alt="Screen Shot 2020-08-05 at 4 37 48 PM" src="https://user-images.githubusercontent.com/69280080/89474267-02024680-d73a-11ea-8d3c-102995f0d628.png">

**Comment by devinroth** [comment]
This looks like it may be an easy fix. 

Add drift compensation to BlackHole. Let me know if that fixes the issue. If not we’ll dig deeper. 

Devin Roth

**Comment by blackbookchris** [comment]
Yup, this seems to have worked, thank you!

**Comment by devinroth** [comment]
You’re welcome. Let me know if you run into any other issues.
