### ISSUE TITLE
[Question] Codesign Issue

### ISSUE THREAD

**Issue by imbearchang** [ExistentialAudio/BlackHole#193]
Hi, 
I built blackhole on computer A using Xcode.  By following the installing steps, it works fine.

However, I copied the built result from computer A to computer B, which doesn't have Xcode installed, and the driver could not work due to code sign issue.

Is there any step that I missed?

**Comment by devinroth** [comment]
Strange. What is the exact error you are getting?

Try something for me. Change the bundleID in Signing and Capabilities and in BlackHole.h and see if it fixes the issue.

**Comment by imbearchang** [comment]
Ah, I followed your steps, and it worked fine on computer C which doesn't have Xcode installed either!

I saw the message from console app using filter  'coreaudio' on computer B, and I'll update status after repeating these steps on it later. 

Thanks 👍
