### ISSUE TITLE
Having issues picking up local sounds w/Transitions DJ

### ISSUE THREAD

**Issue by lcmusictracks** [ExistentialAudio/BlackHole#194]
![20200813_225900](https://user-images.githubusercontent.com/69680720/90252399-6d6ca800-de0d-11ea-8f5d-f0cea7d580b6.jpg)

I'm running Catalina 10. 15.6 on a 2015 MacBook:

I'm having issues when I screen record. It either picks up the audio from a DJ Mixing Application called "Transitions DJ" WITH the microphone OR it wont pick any sound at all. 

I tested it when playing videos off YT or the internet, and that works. 

At this point, Im not sure if the routing set up I did was wrong or if its a Blackhole issue. 

Any help with this is greatly appreciated as Im a music producer and will eventually be using OBS Streamlabs. 

Thanks so much,

LC

**Comment by devinroth** [comment]
Please send screenshots of how you have it setup with Transitions DJ. And screenshots of the Aggregate Device and Multi-output Device.
