### ISSUE TITLE
Trouble with uninstalling

### ISSUE THREAD

**Issue by Kipkowski** [ExistentialAudio/BlackHole#195]
I have followed the directions on

https://github.com/ExistentialAudio/BlackHole/wiki/Uninstallation

When I use terminal to search for `cd /Library/Audio/Plug-Ins/HAL`, nothing shows up. 

The BlackHole 16c still shows up in the list of audio options in the Mac Settings.

**Comment by devinroth** [comment]
What error do you get?

**Comment by Kipkowski** [comment]
No error, necessarily. It just doesn't return with anything once I enter it in the terminal.

**Comment by devinroth** [comment]
It doesn’t return anything. It only changes your current directory.

Just follow all the commands. Copy paste then and enter and it will do the trick.
