### ISSUE TITLE
How to change the device icon shown in Audio MIDI setup?

### ISSUE THREAD

**Issue by Nithin-anim** [ExistentialAudio/BlackHole#198]
Hi can you tell me how to change the device icon shown in Audio MIDI setup.I am building the project from source.I replaced the BalckHole.icns file with my own icon in the same name.But the change is not reflected in build.

**Comment by Nithin-anim** [comment]
Never mind got it to work.

**Comment by dttlgotv** [comment]
> Never mind got it to work.

can you tell me your solution？ I got same issue like you.

**Comment by dttlgotv** [comment]
> > Never mind got it to work.
> 
> can you tell me your solution？ I got same issue like you.

@devinroth any idea about it?

**Comment by Nithin-anim** [comment]
Hey @dttlgotv  just clone the repo from github and open it in Xcode.Now make sure your icon is in .icns format.Then, navigate the BlackHole.icns icon file inside Xcode which will be inside BlackHole folder.Then drag and drop the new icon in the same place as existing icon.Xcode will prompt you to wether to create folder reference for the new icon.Select yes or create in the prompt.Now build the source code as per the instructions in the Docs.You will then get your new icon for the driver.
