### ISSUE TITLE
Internal sound will not record. Catalina. Screen Shots of my setup included

### ISSUE THREAD

**Issue by LifeAsNix** [ExistentialAudio/BlackHole#199]
The first time I installed black hole and set it up, it recorded my screen audio without a hitch. The next time I went to do another screen recording, it would not pick up sound. I have checked the settings several times and it all seems to be setup correctly but it will not capture sound from the internal audio. These two recordings were done a week apart. I don't know what to do

**Comment by devinroth** [comment]
Send some photos of how you have it setup. Might be something simple you are missing.

**Comment by LifeAsNix** [comment]
<img width="700" alt="Untitled" src="https://user-images.githubusercontent.com/70547471/91874564-fd995280-ec3f-11ea-9d6a-ab348da7ecc1.png">
<img width="700" alt="Untitled 2" src="https://user-images.githubusercontent.com/70547471/91874571-ff631600-ec3f-11ea-8576-65b3ddb6d896.png">

**Comment by devinroth** [comment]
Try just using only BlackHole as the input into QuickTime.

**Comment by LifeAsNix** [comment]
That's how it is set up

**Comment by devinroth** [comment]
Do a quick test. System output to BH. QuickTime input from BH. Does that work?

**Comment by LifeAsNix** [comment]
How do I change the system output to BH? Do you mean just uncheck the head phones under the multichannel labeled "screen recording w/audio"? When i do that, I cannot hear the audio while recording and the sound is still not captured.

**Comment by LifeAsNix** [comment]
now i can't get youtube to play.....site loads quickly but the videos don't play. spinning wheel of death

**Comment by LifeAsNix** [comment]
Figured out the YouTube issue. If i have my sound settings on screen record w/audio selected now, it wont let youtube play. This JUST started.
if I switch to headphones, youtube plays.
Now I have 2 issues

**Comment by LifeAsNix** [comment]
I found the issue:
System Preferences>Security & Privacy>Privacy>Microphone
Make sure that you have allowed QuickTime access to your mic.
I'm not sure how this got deselected but I'm glad I finally figured it out. 

<img width="736" alt="Untitled3" src="https://user-images.githubusercontent.com/70547471/91920933-e84c1480-ec8f-11ea-89bd-885bfd93b712.png">

**Comment by devinroth** [comment]
Awesome.

**Comment by C4RB0N-1** [comment]
> I found the issue:
> System Preferences>Security & Privacy>Privacy>Microphone
> Make sure that you have allowed QuickTime access to your mic.
> I'm not sure how this got deselected but I'm glad I finally figured it out.
> 
> <img alt="Untitled3" width="736" src="https://user-images.githubusercontent.com/70547471/91920933-e84c1480-ec8f-11ea-89bd-885bfd93b712.png">

Thanks for sharing! I followed all the instructions I found but I still couldn't record audio from QuickTime. Turns out microphone access to QuickTime was the culprit!

@devinroth Maybe this could be added to the FAQ in the BlackHole Readme? It would have saved me hours and hours if only I could have read it there.

**Comment by C4RB0N-1** [comment]
> I found the issue:
> System Preferences>Security & Privacy>Privacy>Microphone
> Make sure that you have allowed QuickTime access to your mic.
> I'm not sure how this got deselected but I'm glad I finally figured it out.

@devinroth Maybe this could be added to the FAQ in the BlackHole Readme? It would have saved me hours and hours if only I could have read it there.

**Comment by C4RB0N-1** [comment]
> I found the issue:
> System Preferences>Security & Privacy>Privacy>Microphone
> Make sure that you have allowed QuickTime access to your mic.
> I'm not sure how this got deselected but I'm glad I finally figured it out.

@LifeAsNix Thanks for sharing! I followed all the instruction I could find but still couldn't get audio recording from QuickTime to work.
Turns out microphone access to QuickTime was the culprit!

@devinroth Maybe this could be added to the FAQ in the BlackHole Readme? It would have saved me hours and hours if only I could have read it there.

**Comment by devinroth** [comment]
It’s already in the FAQ.

https://github.com/ExistentialAudio/BlackHole#why-is-nothing-is-playing-through-blackhole

**Comment by C4RB0N-1** [comment]
Ah, my bad. Should have looked more carefully, and shouldn't have tried getting useful answers from youtube comment sections...
