### ISSUE TITLE
distinction from Jack?

### ISSUE THREAD

**Issue by michaelpalumbo** [ExistentialAudio/BlackHole#2]
First off, I'm excited by this project, and look forward to experimenting with it. Thanks for putting it out there. 

Could @devinroth speak to motivations for this project relative to the Jack connection kit? Is there something that this project offers (or will offer) that Jack does not?

**Comment by devinroth** [comment]
The motivation was to replace Soundflower which is no longer being develop and doesn't seem to work on the latest version of macOS. BlackHole is early in the development so it doesn't have the features that Jack does but one thing that differentiates BlackHole from all other pass-through drivers is the latency. With BlackHole I've been able to pass-through audio with no added latency. Unlike both Jack and Soundflower, BlackHole runs in the userspace so there is no need for KEXTs which creates problems with signing and potential security issues. BlackHole is completely safe and worst case scenario with user space drivers is coreaudio will restart vs KEXTs errors that can cause a complete system crash.

**Comment by devinroth** [comment]
I don't actually use jack so I decided to download it to compare. It doesn't seem to run on macOS 10.14. A quick search on the open issues shows it's the KEXT signing issue. Hopefully BlackHole can help revive some of these open source audio projects that have been abandoned as a result of Apple's handling of KEXTs in recent macOS releases.
