### ISSUE TITLE
What do we have to change to change the name of the driver ? 

### ISSUE THREAD

**Issue by Jean-Lochard** [ExistentialAudio/BlackHole#20]
Hi,

I build a 2 channels version of BlackHole with Xcode but it could be nice to rename the driver like "BlackHole(2ch)" to keep both the 16 channels and 2 channels.

So, what do we have to change in the code to achieve that ?

Thanks !

Best,

Jean

**Comment by devinroth** [comment]
Probably won’t work since there is a uuid associated with the driver.

**Comment by devinroth** [comment]
https://github.com/ExistentialAudio/BlackHole/wiki/Running-Multiple-BlackHole-Drivers

**Comment by devinroth** [comment]
I also just pushed a minor update that displays the number of channels in the name. I think this is a good idea in general.

**Comment by devinroth** [comment]
Let me know how it goes.
