### ISSUE TITLE
audio not recording

### ISSUE THREAD

**Issue by jgand** [ExistentialAudio/BlackHole#202]
Hi Devon
installed blackhole + created a multi ouput device in audio midi settings - same settings as for soundflower pre-catalina - and audio not recording after several attempts/restarts. microphone access enabled in privacy/security etc, have attached a screenshot, what might i be missing here?
thankyou J

![1](https://user-images.githubusercontent.com/70788697/92297151-95b87400-ef7f-11ea-8dc2-5f8bcfdfa8ff.png)

**Comment by devinroth** [comment]
Try configuring the BlackHole speaker setup to stereo. See if that makes a difference. QuickTime doesn’t like the fact that there are 16 ch.

**Comment by jgand** [comment]
great thankyou, all working now
