### ISSUE TITLE
Is 0.2.7 released ?

### ISSUE THREAD

**Issue by fatlazycat** [ExistentialAudio/BlackHole#204]
Is 0.2.7 released or just a stepping stone to 0.3.0 ?

Installer still seems to be 0.2.6

Thanks

**Comment by devinroth** [comment]
0.2.7 is released. 0.3.0 isn’t ( I should probably add dev or something there)

I just haven’t build the installer for 0.2.7 yet. 0.3.0 won’t be ready for a while.

**Comment by fatlazycat** [comment]
Ah ok thanks
