### ISSUE TITLE
As a library

### ISSUE THREAD

**Issue by shersoni610** [ExistentialAudio/BlackHole#207]
Hello

Can we use black hole as a library?

Thank

**Comment by devinroth** [comment]
What do you mean “as a library”? It’s a driver.

**Comment by shersoni610** [comment]
I mean I want to set the Blackhole driver in the C++ code while recording. Once recording is done,
I would like to reset to the physical devices. Otherwise, I need to go to the system and change 
everytime.

Thanks for your response. I might have asked a very naive question.

**Comment by devinroth** [comment]
You can set those options directly with CoreAudio.

**Comment by shersoni610** [comment]
I want to record separately speaker sound and microphone sound. I do not know how can I 
do it so that each module set/unset the blackhole drivers within the c++ code.

**Comment by devinroth** [comment]
I can point you in the right direction.

Look up kAudioHardwarePropertyDefaultOutputDevice in AudioHardware.h.

You’re on your own from here.
