### ISSUE TITLE
Blackhole stopped working

### ISSUE THREAD

**Issue by fabiosz** [ExistentialAudio/BlackHole#208]
Hi, I'm not sure what's going on but I have tried re-installing Blackhole multiple times and it won't solve this issue. Blackhole just stopped working. Audio seems to not be routed to the Aggregate device so Skype, Google Meet and other applications just won't get the signal. I need to record the screen+system audio. Since Quikctime Player is unable to record System Audio while recording the screen, the other day I set up the system output to go into Blackhole in the system settings, then I set the Aggregate Device to include Blackhole 16ch and the System Built-in Output in the MIDI settings. Then, I set QuickTime to record from Blackhole or the Aggregate Device and it was working fine. The resulting video got the audio from the Aggregate Device. I also set up Garage Band to let me hear the audio while playing getting the input from the aggregate device and pushing it out of the built-in speakers. At a point it just stopped working and I have no idea why nor how to fix this. It also won't work with other applications either. Could you please help? Thank you in advance!

**Comment by devinroth** [comment]
Send a screenshot of your multi output from audio midi setup. 

Devin

**Comment by fabiosz** [comment]
Hi Devin, here it is. 
<img width="634" alt="Screenshot 2020-09-27 at 16 30 52" src="https://user-images.githubusercontent.com/64060666/94367432-0ebe6d80-00df-11eb-993f-a3533c1db88a.png">

**Comment by fabiosz** [comment]
Are the settings right?

**Comment by devinroth** [comment]
Did you switch BlackHole so it’s not the on top of the list as suggested?

**Comment by fabiosz** [comment]
Ok it seems to be working now. I had totally forgotten about that setting. Thank you!

**Comment by fabiosz** [comment]
But how do I also hear the system sound while recording the screen? In this configuration I set QuickTime to get sound from Blackhole and it works. But I cannot hear any sound. Setting GarageBand to get sound from Blackhole or Aggregate Device and pushing it to the Built-in Output is not working? What am I getting wrong? Thank you in advance for your kind help!

**Comment by devinroth** [comment]
Set the system output to a multioutput with your speakers and blackhole in that order.

**Comment by fabiosz** [comment]
The settings are as in the pic attached. It worked for a few minutes and then something went wrong. Now I won't hear any audio in the video recorded no matter what I select as output and even selecting Blackhole as input source in QuickTime. What happened? What should I do? Thank you in advance for your help!

<img width="632" alt="Screenshot 2020-10-06 at 18 09 01" src="https://user-images.githubusercontent.com/64060666/95227999-137dd280-07ff-11eb-98b9-22b9134c7801.png">
<img width="631" alt="Screenshot 2020-10-06 at 18 08 54" src="https://user-images.githubusercontent.com/64060666/95228003-14aeff80-07ff-11eb-98c4-bdb6ad649dc9.png">

**Comment by devinroth** [comment]
You need drift correction on BlackHole.

**Comment by fabiosz** [comment]
Thank you Devin. I tried with drift correction on Blackhole but it's still not working. But do you mean in the Aggregate Device or in the Multioutput one? Or in both? And how about the Built-In Output? Should it have the drift correction on and where? Always thanks for your kind help!

**Comment by devinroth** [comment]
Both Aggregate and Multi output need drift correction for BH. You don’t need it for built-in on either.

**Comment by devinroth** [comment]
Closing. Let me know if you have any other problems.
