### ISSUE TITLE
How can I send audio to Discord or other program?

### ISSUE THREAD

**Issue by quantuminformation** [ExistentialAudio/BlackHole#209]
I can't find any way to give my BH audio to a friend of Discord or another program like AnyDesk, does BH support?

I can record from BH fine as always,

**Comment by devinroth** [comment]
Did you test it with the 2ch version? I don’t see why it wouldn’t work. 

There’s a Catalina bug recently reported and i wonder if that may be related. Still looking into that one. 

Devin

**Comment by quantuminformation** [comment]
still using the 16 ch one

will uninstall and add other

thx

**Comment by quantuminformation** [comment]
Is there a special link for the 2 ch version?

**Comment by quantuminformation** [comment]
found it
