### ISSUE TITLE
Blackhole does not record application sound

### ISSUE THREAD

**Issue by khvnhtung** [ExistentialAudio/BlackHole#212]
Hi,
I downloaded and installed the 2ch version of Blackhole on my Mac.
After that, I configured an aggregate device with Blackhole 2ch enable, and a Multi-device output with Mac Speakers and BlackHole 2ch enabled and then change the output and input in Sound (System Preferences). 
This works wonderfully when I try to record some Youtube videos, I can also hear sounds coming from the speaker. However, I cannot hear and record sound coming out from other applications such as a game I'm playing (World of Tanks Blitz). 
I hope somebody can help me out, thanks.

**Comment by devinroth** [comment]
Is there an audio setting in the game that lets you select the output?

**Comment by khvnhtung** [comment]
Hi, there are no audio settings in the game that let me change the output

**Comment by andreagrandi** [comment]
What is this "2ch" version I read about and where can I find it? I installed BlackHole from `brew` and I only got the "16ch" one. Thanks

**Comment by devinroth** [comment]
Brew currently only has the 16ch. 2ch can be found downloaded from existential.audio/blackhole

**Comment by devinroth** [comment]
Closing. Reopen if you still have a problem.
