### ISSUE TITLE
0.2.7 link for Homebrew/cask

### ISSUE THREAD

**Issue by ykursadkaya** [ExistentialAudio/BlackHole#213]
In the docs it says 

> Install via Homebrew `brew cask install blackhole`

but with current links it still installs older 0.2.6 version.

Is it possible you to provide a versioned download link for every release for the Homebrew/cask project like in here with v0.2.6?
[https://github.com/Homebrew/homebrew-cask/blob/master/Casks/blackhole.rb](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/blackhole.rb)

**Comment by devinroth** [comment]
It might be as simple as updating the version. @MikeMcQuaid. Also I have a 2ch version now. Maybe we should add that to brew cask. Something like `brew cask install blackhole2ch`

**Comment by ykursadkaya** [comment]
Not sure but that can go to [Homebrew/homebrew-cask-versions](https://github.com/Homebrew/homebrew-cask-versions) I think.

**Comment by 0alpha** [comment]
It would be great if you could push the built 2ch/16ch versions to GH with each release – this may end up being easier for updating the casks.

**Comment by leafac** [comment]
I’m following through we this here:

https://github.com/Homebrew/homebrew-cask/pull/94528

**Comment by leafac** [comment]
0.2.7 is available for download through homebrew with the `blackhole-2ch` and the `blackhole-16ch` casks. We may close this issue.

**Comment by ykursadkaya** [comment]
> 0.2.7 is available for download through homebrew with the `blackhole-2ch` and the `blackhole-16ch` casks. We may close this issue.

Thanks, closing.
