### ISSUE TITLE
Installing multiple versions of Blackhole

### ISSUE THREAD

**Issue by poulhoi** [ExistentialAudio/BlackHole#214]
Hello. Is it possible to install a 2-channel version alongside a 16-channel one?

**Comment by devinroth** [comment]
Yes.

**Comment by poulhoi** [comment]
Ok, great. When I try and build a second BlackHole driver, it seems to overwrite the first one in Audio Midi Setup. I'm not sure exactly what steps I have to take to prevent this?

**Comment by devinroth** [comment]
There are a few extra things you need to change. 

Look in the wiki. It explains it.

**Comment by poulhoi** [comment]
Hey David. Sorry, I must have missed that section in the wiki. I thought I looked through it. Thanks a lot for your help

Best regards,
Poul Høi
