### ISSUE TITLE
Installed 2ch and 16ch 0.27 and my system sound effects are gone

### ISSUE THREAD

**Issue by Shrapnel21** [ExistentialAudio/BlackHole#215]
As stated in the subject.
I installed the 2ch version first, and then the 16ch version.
They both show as separate entities in SoundSource, so everything seems fine.
SoundSource also lists system output and sound effects as normally routed to builtin speakers, but after installing BlackHole the sound effects for alerts and such are gone.

**Comment by devinroth** [comment]
You can change which speakers the alerts go in audio midi setup.

**Comment by Shrapnel21** [comment]
Did that as well, but didn't work.
Ended up removing and reinstalling both BlackHole drivers and everything went back into place, looks like somehow I experienced some kind of botched install process. =P

**Comment by devinroth** [comment]
The installer does not change the output of your system audio or sound effects. Perhaps SoundSource does? 

Where you unable to change which audio device has sound effects?

**Comment by Shrapnel21** [comment]
I could actually change the device the effects were sent to, but they still didn't come out.
And despite knowing the output is not modified by the installer, and knowing SoundSource didn't change anything since its outputs are always visible, a reinstall solved the issue.
Again, I have no idea why. =D

**Comment by devinroth** [comment]
Strange. I have no idea why. Well I’m glad it’s fixed.

**Comment by Shrapnel21** [comment]
I'm sure it has something to do with my system, I made quite a mess on it during these past 7 years and never reinstalled it. =D
But yep, it was an easy and quick fix and BlackHole keeps helping me *a lot*!
