### ISSUE TITLE
issue on 10.14.6 Mojave

### ISSUE THREAD

**Issue by SmokeDoepferEveryday** [ExistentialAudio/BlackHole#217]
hello,

I have the latest build of BlackHole running on Mojave 10.14.6.
The issue I'm having is no sound is produced from screen recordings (both Quicktime and Grab)
my settings are as follows:

<img width="748" alt="Screenshot 2020-10-21 at 11 15 36" src="https://user-images.githubusercontent.com/73227566/96707807-4348e080-1390-11eb-80b4-043f498f9a02.png">
<img width="748" alt="Screenshot 2020-10-21 at 11 15 44" src="https://user-images.githubusercontent.com/73227566/96707822-46dc6780-1390-11eb-9664-cd6f5ae16b20.png">

I hear audio via this routing but no recorded audio from any apps or Chrome/Safari

thanks

**Comment by devinroth** [comment]
Check your microphone access in security.

**Comment by SmokeDoepferEveryday** [comment]
thanks I did do that but there's no BH icon there – is this unusual?

**Comment by devinroth** [comment]
BlackHole doesn’t need to be there but QuickTime and Grab do.

**Comment by SmokeDoepferEveryday** [comment]
Quicktime is, Grab isn't. I did test with Qt earlier and no sound.

**Comment by devinroth** [comment]
Are you using 16ch or 2ch?

**Comment by SmokeDoepferEveryday** [comment]
NB: I say "Grab" it's called 'Screenshot' on this os. But doesn't appear in Microphone access.

**Comment by SmokeDoepferEveryday** [comment]
16ch

**Comment by devinroth** [comment]
Do you have BlackHole set the as mic in QT?

Also QT doesn’t like audio devices with over a certain number of channels. Go into audio midi setup, select BlackHole, click configure speakers, change configuration to Stereo and make sure channels 1 and 2 are set as left front and right front. 

Try that.

**Comment by SmokeDoepferEveryday** [comment]
just tried that, speakers were set below already:

<img width="748" alt="Screenshot 2020-10-21 at 18 42 57" src="https://user-images.githubusercontent.com/73227566/96757598-8e351900-13cd-11eb-8518-3363c37a6bb4.png">

and Blackhole was set in Qt, still no sound recorded

**Comment by devinroth** [comment]
Okay. Do a test. 

Set BH as the default speaker. Play something from Safari and try recording that in QT. See if anything records then.

**Comment by SmokeDoepferEveryday** [comment]
tested, no sound recorded.

**Comment by devinroth** [comment]
Okay try recording with GarageBand.

Do you get any errors in console?

**Comment by SmokeDoepferEveryday** [comment]
I don't have Garageband installed, but do have Logic, which I tried earlier with same result

**Comment by devinroth** [comment]
Hmmm. 

Do you have any errors in console?

**Comment by SmokeDoepferEveryday** [comment]
how would I check that sorry?

**Comment by SmokeDoepferEveryday** [comment]
btw, the Blackhole routing I had was working the last time I tried it before today (about a month ago) so this is strange to me

**Comment by devinroth** [comment]
Just do a spotlight search for Console and then search for BlackHole.

Try restarting your computer. Maybe that will work. You never know.

**Comment by SmokeDoepferEveryday** [comment]
I see, "BlackHole" as a command?
Tried a restart, no change

**Comment by SmokeDoepferEveryday** [comment]
I'm guessing that's not what you meant but the command returns: "zsh: command not found: BlackHole"

**Comment by devinroth** [comment]
Haha hope. Should look like this.

**Comment by SmokeDoepferEveryday** [comment]
"Should look like this" sorry can't see what you mean?

**Comment by devinroth** [comment]
Oh yeah forgot that I can't post pictures via email. Here.

<img width="1051" alt="Screen Shot 2020-10-21 at 12 16 09 PM" src="https://user-images.githubusercontent.com/13010961/96777277-fddfdf80-139e-11eb-9727-cbdea8830b39.png">

**Comment by SmokeDoepferEveryday** [comment]
ah apologies!

I have this reading:

`default	22:31:13.288657 +0100	coreaudiod	HALS_IOEngine2.cpp:1090:_UpdateTotalStreamUsage:  'BlackHole_UID': Updating 1 output stream(s)
default	22:31:13.288683 +0100	coreaudiod	HALS_IOEngine2.cpp:1090:_UpdateTotalStreamUsage:  'BlackHole_UID': Updating 1 input stream(s)
default	22:31:13.288703 +0100	coreaudiod	HALS_IOContextDescription.cpp:1128:PushStreamUsageToEngines_block_invoke:  IOContext 1330: pushing 1 output stream(s) to 'BlackHole_UID'
default	22:31:13.288719 +0100	coreaudiod	HALS_IOContextDescription.cpp:1132:PushStreamUsageToEngines_block_invoke:  IOContext 1330: output stream[0] => Enabled: 'BlackHole_UID'
default	22:31:13.288738 +0100	coreaudiod	HALS_IOContextDescription.cpp:1128:PushStreamUsageToEngines_block_invoke:  IOContext 1330: pushing 1 input stream(s) to 'BlackHole_UID'
default	22:31:13.288752 +0100	coreaudiod	HALS_IOContextDescription.cpp:1132:PushStreamUsageToEngines_block_invoke:  IOContext 1330: input stream[0] => Disabled: 'BlackHole_UID'
default	22:31:13.288752 +0100	coreaudiod	HALS_IOEngine2.cpp:1090:_UpdateTotalStreamUsage:  'BlackHole_UID': Updating 1 output stream(s)
default	22:31:13.288782 +0100	coreaudiod	HALS_IOEngine2.cpp:1090:_UpdateTotalStreamUsage:  'BlackHole_UID': Updating 1 input stream(s)
default	22:31:13.290845 +0100	coreaudiod	HALS_IOEngine2.cpp:1090:_UpdateTotalStreamUsage:  'BlackHole_UID': Updating 1 output stream(s)
default	22:31:13.290869 +0100	coreaudiod	HALS_IOEngine2.cpp:1090:_UpdateTotalStreamUsage:  'BlackHole_UID': Updating 1 input stream(s)
default	22:31:13.290921 +0100	coreaudiod	HALS_IOContextDescription.cpp:1128:PushStreamUsageToEngines_block_invoke:  IOContext 1331: pushing 1 output stream(s) to 'BlackHole_UID'
default	22:31:13.290942 +0100	coreaudiod	HALS_IOContextDescription.cpp:1132:PushStreamUsageToEngines_block_invoke:  IOContext 1331: output stream[0] => Enabled: 'BlackHole_UID'
default	22:31:13.290963 +0100	coreaudiod	HALS_IOContextDescription.cpp:1128:PushStreamUsageToEngines_block_invoke:  IOContext 1331: pushing 1 input stream(s) to 'BlackHole_UID'
default	22:31:13.290971 +0100	coreaudiod	HALS_IOEngine2.cpp:1090:_UpdateTotalStreamUsage:  'BlackHole_UID': Updating 1 output stream(s)
default	22:31:13.290979 +0100	coreaudiod	HALS_IOContextDescription.cpp:1132:PushStreamUsageToEngines_block_invoke:  IOContext 1331: input stream[0] => Enabled: 'BlackHole_UID'
default	22:31:13.291003 +0100	coreaudiod	HALS_IOEngine2.cpp:1090:_UpdateTotalStreamUsage:  'BlackHole_UID': Updating 1 input stream(s)
default	22:31:13.295193 +0100	coreaudiod	HALS_IOEngine2.cpp:1090:_UpdateTotalStreamUsage:  'BlackHole_UID': Updating 1 output stream(s)
default	22:31:13.295216 +0100	coreaudiod	HALS_IOEngine2.cpp:1090:_UpdateTotalStreamUsage:  'BlackHole_UID': Updating 1 input stream(s)
default	22:31:13.295234 +0100	coreaudiod	HALS_IOContextDescription.cpp:1128:PushStreamUsageToEngines_block_invoke:  IOContext 1333: pushing 1 output stream(s) to 'BlackHole_UID'
default	22:31:13.295250 +0100	coreaudiod	HALS_IOContextDescription.cpp:1132:PushStreamUsageToEngines_block_invoke:  IOContext 1333: output stream[0] => Enabled: 'BlackHole_UID'
default	22:31:13.295268 +0100	coreaudiod	HALS_IOContextDescription.cpp:1128:PushStreamUsageToEngines_block_invoke:  IOContext 1333: pushing 1 input stream(s) to 'BlackHole_UID'
default	22:31:13.295277 +0100	coreaudiod	HALS_IOEngine2.cpp:1090:_UpdateTotalStreamUsage:  'BlackHole_UID': Updating 1 output stream(s)
default	22:31:13.295283 +0100	coreaudiod	HALS_IOContextDescription.cpp:1132:PushStreamUsageToEngines_block_invoke:  IOContext 1333: input stream[0] => Enabled: 'BlackHole_UID'
default	22:31:13.295302 +0100	coreaudiod	HALS_IOEngine2.cpp:1090:_UpdateTotalStreamUsage:  'BlackHole_UID': Updating 1 input stream(s)
default	22:31:14.505596 +0100	coreaudiod	HALS_IOContextDescription.cpp:1128:PushStreamUsageToEngines_block_invoke:  IOContext 245: pushing 1 output stream(s) to 'BlackHole_UID'
default	22:31:14.505660 +0100	coreaudiod	HALS_IOContextDescription.cpp:1132:PushStreamUsageToEngines_block_invoke:  IOContext 245: output stream[0] => Disabled: 'BlackHole_UID'
default	22:31:14.505742 +0100	coreaudiod	HALS_IOEngine2.cpp:1090:_UpdateTotalStreamUsage:  'BlackHole_UID': Updating 1 output stream(s)
default	22:31:14.505797 +0100	coreaudiod	HALS_IOContextDescription.cpp:1128:PushStreamUsageToEngines_block_invoke:  IOContext 245: pushing 1 input stream(s) to 'BlackHole_UID'
default	22:31:14.505831 +0100	coreaudiod	HALS_IOContextDescription.cpp:1132:PushStreamUsageToEngines_block_invoke:  IOContext 245: input stream[0] => Disabled: 'BlackHole_UID'
default	22:31:14.505880 +0100	coreaudiod	HALS_IOEngine2.cpp:1090:_UpdateTotalStreamUsage:  'BlackHole_UID': Updating 1 input stream(s)
default	22:31:14.570931 +0100	coreaudiod	HALS_IOEngine2.cpp:1090:_UpdateTotalStreamUsage:  'BlackHole_UID': Updating 1 output stream(s)
default	22:31:14.570967 +0100	coreaudiod	HALS_IOEngine2.cpp:1090:_UpdateTotalStreamUsage:  'BlackHole_UID': Updating 1 input stream(s)
default	22:31:14.571167 +0100	coreaudiod	HALS_IOEngine2.cpp:1090:_UpdateTotalStreamUsage:  'BlackHole_UID': Updating 1 output stream(s)
default	22:31:14.571195 +0100	coreaudiod	HALS_IOEngine2.cpp:1090:_UpdateTotalStreamUsage:  'BlackHole_UID': Updating 1 input stream(s)
default	22:31:14.571653 +0100	coreaudiod	HALS_IOEngine2.cpp:1090:_UpdateTotalStreamUsage:  'BlackHole_UID': Updating 1 output stream(s)
default	22:31:14.571683 +0100	coreaudiod	HALS_IOEngine2.cpp:1090:_UpdateTotalStreamUsage:  'BlackHole_UID': Updating 1 input stream(s)
`

**Comment by devinroth** [comment]
What do you get after trying to record?

**Comment by SmokeDoepferEveryday** [comment]
hello, apologies (uk time here)  I tried again Qt and Safari, no audio in a recording – same settings as the console reading I sent you

**Comment by mikenye** [comment]
@SmokeDoepferEveryday can I just say that your username is amazing.

**Comment by SmokeDoepferEveryday** [comment]
@devinroth would it be worth reverting to an earlier version perhaps?

**Comment by devinroth** [comment]
I doubt it. But worth trying I guess. But first...

Have you tried uninstalling and reinstalling?

**Comment by devinroth** [comment]
I have an installer linked somewhere. There’s also manual instructions in the wiki.

**Comment by SmokeDoepferEveryday** [comment]
good news @devinroth I uninstalled via the wiki steps and installed 2ch and it is working fine! thanks again.

**Comment by devinroth** [comment]
You’re welcome.

Still don’t have a clue what went wrong.

**Comment by SmokeDoepferEveryday** [comment]
indeed, the only thing I could think is I had installed BlackHole twice (i.e. I didn't uninstall at any point) as I decided to get the latest release. I do not know at what point it stopped working but it was working when I initially updated. *shrugs* but I'm super happy to have it working again as it's a life saver recording screen content.
