### ISSUE TITLE
Where are the number of channels suppose to appear ? 

### ISSUE THREAD

**Issue by jlochard** [ExistentialAudio/BlackHole#22]
Hi, 

I just tried to build a 2ch version with the instructions on the Wiki. Finally the two devices are visibles but they are named "BlackHole 1 " & "BlackHole 2".

So no number of channels in the name. Is it normal ?

I used Xcode 10 on High Sierra..

Jean

**Comment by devinroth** [comment]
In `Localizable.strings` change `DeviceName = "BlackHole";` to "BlackHole 2ch". That should do the trick. 

I'll work on pushing an update.

**Comment by jlochard** [comment]
I tried but I have the same result...

Another idea ?

J

**Comment by devinroth** [comment]
I just put an update. Use that.

**Comment by devinroth** [comment]
Any luck?

**Comment by jlochard** [comment]
Hi,

I try with the last update and it work perfectly !

Thanks !

Jean

**Comment by devinroth** [comment]
You’re welcome.
