### ISSUE TITLE
Digital Noise on my streaming

### ISSUE THREAD

**Issue by gabidrums** [ExistentialAudio/BlackHole#220]
Hello how are you? I use BlackHole together with Logic without problems on a macbook pro with OSX El Capitan. But when I use a mac mini with OSX Yosemite, I hear digital noises like when they are misconfigured between 44khz and 48kzh. Does anyone know if it is a problem with the version of the operating system or something else?

Thank You!!!

**Comment by devinroth** [comment]
How do you have it setup on the mini?

**Comment by devinroth** [comment]
Try with the latest release 0.2.8. Reopen if you still have issues.
