### ISSUE TITLE
Periodic Static/Noise Using Blackhole (every few minutes) using Garageband and JamKazam

### ISSUE THREAD

**Issue by ecogedi** [ExistentialAudio/BlackHole#223]
Mac os x (10.15.7) running GarageBand with MOTU828 DAW, and JamKazam

MOTU828 with multiple instrument inputs and microphone into Mac/Garage band routed through BlackHole to JamKazam.  When in JamKazam a periodic loud static and distortion appears every few minutes then disappears. This did not happen with JamKazam and the MOTU before, only after using BlackHole.  MOTU clock is driving everything, 44 kHz.   Static makes the set-up unusable. Any ideas where this could be coming from. Here is the setup, including the aggregate device, in the screenshots below.

[Jamkazam w:Garageband.pdf](https://github.com/ExistentialAudio/BlackHole/files/5484701/Jamkazam.w.Garageband.pdf)

**Comment by devinroth** [comment]
Make sure you enable drift correction on BH. It solves most of the problems.
