### ISSUE TITLE
Issues with blackhole on Big Sur - sound slurring and drawn out

### ISSUE THREAD

**Issue by amelluk** [ExistentialAudio/BlackHole#226]
Anybody else seen this on OSX 11 Big Sur? I am using Blackhole 2ch as a replacement for Soundflower but it is not working properly. The sound coming through the speakers/headset from Multi-Output device is very distorted and slurred.

All quite urgent for me, as its an essential part of my daily work to be able to get captions up. Is Blackhole able to replace soundflower entirely in OSX 11?

The configuration I am using is this with Blackhole 0.2.7 (it is the same in 2ch and 16ch):

https://blog.otter.ai/how-to-live-transcribe-zoom-meetings-with-otter-ai-and-soundflower-on-mac/

Thank you

**Comment by devinroth** [comment]
I just tested and it works normally on my mac. I’ll try your specific setup when i get a chance. In the mean time try reinstalling. 

Did it work normally for you on previous OS versions?

Devin

**Comment by amelluk** [comment]
Thank you for responding so quickly. I never used Blackhole on the previous OSX versions as Soundflower was working fine. I switched to Blackhole for OSX 11 because I understood the Soundflower kext was no longer supported.

I shall reboot and reinstall and come back if there’s any improvement.

**Comment by devinroth** [comment]
Sure. It’s worth a try.

**Comment by devinroth** [comment]
Sure it’s worth trying.

**Comment by amelluk** [comment]
I have tried a number of things. Rebooted mac a number of times. Downgrade driver to 0.2.6 from 0.2.7.

Nothing I have found works. the sound is badly distorted.

Some screenshots, if anyone has ideas.

![Screenshot 2020-11-15 at 21 22 11](https://user-images.githubusercontent.com/8729761/99197166-a3148a80-2788-11eb-93e7-2d1b8cb23414.png)
![Screenshot 2020-11-15 at 21 22 27](https://user-images.githubusercontent.com/8729761/99197173-ac055c00-2788-11eb-84e6-6029ff6bd747.png)
![Screenshot 2020-11-15 at 21 22 56](https://user-images.githubusercontent.com/8729761/99197185-bcb5d200-2788-11eb-92b2-41f348eb042c.png)
![Screenshot 2020-11-15 at 21 23 33](https://user-images.githubusercontent.com/8729761/99197196-d35c2900-2788-11eb-87b1-60dd06826f6b.png)
![Screenshot 2020-11-15 at 21 24 30](https://user-images.githubusercontent.com/8729761/99197217-f555ab80-2788-11eb-9143-ea28cdf83b21.png)

**Comment by devinroth** [comment]
The first thing I would do is enable Drift Correction on your aggregate device.

**Comment by imluckie** [comment]
Whenever I do Live monitoring on Logic Pro X I get this error saying "No driver selected" or "No driver found".
It works fine for a while but if I open Discord or Hangout to call someone, I get that error out of nowhere. 

Note: I have enabled Drift correction as well but still I either get that error or there would be a massive lag.

After restarting Logic Pro X everything becomes normal but I got to do it several times and it is so annoying that it happens in the middle of the conversation. As, I have a habit of listening to my own voice(Live Monitoring) while talking on a call because I apply some set of Voice presets.

**Comment by devinroth** [comment]
@imluckie open a different issue since this is not related.

**Comment by devinroth** [comment]
@amelluk download the 2ch version and try with that. Put it as the top and master clock for both the aggregates and multi-output.

**Comment by amelluk** [comment]
Hi, sorry about the delay coming back to you. I have been busy with this issue and had to wait for an external drive to dual boot (it is surprisingly long winded to go from Big Sur to Catalina and have dual boot)

I went back to Catalina on external drive, and was able to confirm Blackhole was working correctly in Catalina.

I went back to Big Sur and after some fiddling, this exact configuration is now working. 
It does not seem to work in 16ch for some reason. 
I also don't get my own voice transcribed, but this is enough for me to get by on.

Many thanks for your assistance. It is greatly appreciated.

<img width="998" alt="Screenshot 2020-11-18 at 11 02 16" src="https://user-images.githubusercontent.com/8729761/99522418-86956f80-298d-11eb-9263-01106a6dafbe.png">
<img width="998" alt="Screenshot 2020-11-18 at 11 02 25" src="https://user-images.githubusercontent.com/8729761/99522432-8b5a2380-298d-11eb-9c21-ded9e879ac6f.png">
<img width="998" alt="Screenshot 2020-11-18 at 11 02 34" src="https://user-images.githubusercontent.com/8729761/99522446-91500480-298d-11eb-8e53-709331944c87.png">
<img width="998" alt="Screenshot 2020-11-18 at 11 02 44" src="https://user-images.githubusercontent.com/8729761/99522462-97de7c00-298d-11eb-9cfc-1ffacd387496.png">
<img width="998" alt="Screenshot 2020-11-18 at 11 03 12" src="https://user-images.githubusercontent.com/8729761/99522506-a88ef200-298d-11eb-803b-251411155227.png">
![Screenshot 2020-11-18 at 11 03 57](https://user-images.githubusercontent.com/8729761/99522591-c3f9fd00-298d-11eb-887b-664553bd8358.png)
![Screenshot 2020-11-18 at 11 04 13](https://user-images.githubusercontent.com/8729761/99522640-ceb49200-298d-11eb-9103-c43d8f47bd83.png)
![Screenshot 2020-11-18 at 11 04 38](https://user-images.githubusercontent.com/8729761/99522681-dd02ae00-298d-11eb-9a64-88d526ba3ffa.png)
![Screenshot 2020-11-18 at 11 05 12](https://user-images.githubusercontent.com/8729761/99522756-f146ab00-298d-11eb-86f3-5a816cb2996a.png)
![Screenshot 2020-11-18 at 11 05 25](https://user-images.githubusercontent.com/8729761/99522777-fb68a980-298d-11eb-86c0-e1496457d89f.png)

**Comment by devinroth** [comment]
Multi-outputs and aggregates are buggy when dealing with audio devices are aren’t exactly 2ch. Which is why I suggested switching to 2ch. I’ve reported it to Apple. Who knows when they will actually fix it.

Devin

**Comment by dschinkel** [comment]
It does not work anymore with this same setup I had working in Catalina:


reinstalling it (`v0.2.7`) on Big Sur **does not make any difference**.. 2ch or not.  I tried both 16 and 2 and it's still not working.

multi-output was **never** a problem in Catalina so I'm not agreeing with your conclusion here.
![Screen Shot 2020-11-20 at 12 47 00 AM](https://user-images.githubusercontent.com/338798/99768408-53a4c600-2aca-11eb-916a-20e8ef1d412f.jpg)

**Comment by devinroth** [comment]
My guess is this is a different issue. 

How do you have it setup? make sure drift correction is enabled. Try putting BH first. And does it work normally without a multi output?

Devin

**Comment by dschinkel** [comment]
hmm it's working know, don't know.  Rebooted a couple times. 🤷‍♂️

**Comment by jeremygc** [comment]
> Please re-open this.
> 
> It does not work anymore with this same setup I had working in Catalina:
> ![Screen Shot 2020-11-20 at 12 47 00 AM](https://user-images.githubusercontent.com/338798/99768458-661eff80-2aca-11eb-92d2-1ba558246e0a.jpg)
> 
> reinstalling it (`v0.2.7`) on Big Sur **does not make any difference**.. 2ch or not. I tried both 16 and 2 and it's still not working.
> 
> **multi-output** was **never** a problem in **Catalina** so I'm not agreeing with your conclusion here. It's also not working as an **aggregate** device.
> 
> I have to use multi-input, I rely on it when I stream code or gaming.
> 
> **BUG**: Also I accidentally selected both 2 and 16 channel blackhole in aggregate device and now I can't even open MIDI, it crashes every time I try to open it.

I can confirm that I cannot get audio to route on Big Sur either. Also tried reinstalling without any luck.

Had no problems with Catalina.

Jeremy

**Comment by devinroth** [comment]
Try with 0.2.8. Reopen if there are still problems.

**Comment by mrquatsch** [comment]
I just wanted to add that I also had problems getting the 16ch version working on my M1 Mac w/ Big Sur. Switched to 2ch and everything worked fine.

**Comment by cjonasw** [comment]
I'm getting this issue specifically with Bluetooth headsets. Switching from 16ch to 2ch helped slightly, but still slurred. I switch from Bluetooth to Mac Speakers and it's fine. Weird.

**Comment by devinroth** [comment]
This has been discussed a few times. Take a look at some of the issues.

Devin

**Comment by aZealot** [comment]
Did anyone manage to fix the slowing/slurring issue? Like a few others here I tried both multi-output and aggregate, 2ch and 16ch. Still slurring.

**Comment by devinroth** [comment]
It’s your 16kHz Bluetooth headphones that are the problem.

Devin

**Comment by aZealot** [comment]
> It’s your 16kHz Bluetooth headphones that are the problem. Devin
> […](#)
> On Jul 7, 2021, 8:19 PM -0700, aZealot ***@***.***>, wrote: Did anyone manage to fix the slowing/slurring issue? Like a few others here I tried both multi-output and aggregate, 2ch and 16ch. Still slurring. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

It actually says they're at 48kHz, or do you mean it's the fact that I'm using Bluetooth headphones in general?

**Comment by devinroth** [comment]
Sort of.

Are they Air Pods?

Devin

**Comment by aZealot** [comment]
Yeah.

**Comment by devinroth** [comment]
So if you’re using the microphone on AirPods they automatically switch the output Frequency to 16kHz mono. That’s by design. There is no going around it.


Devin

**Comment by aZealot** [comment]
Oh okay. Thanks for the help.

**Comment by devinroth** [comment]
Someone suggested that I build in 16kHz into BlackHole. Not sure if that will help or not but I’ll test it out at some point.

Devin

**Comment by zilynnow0303** [comment]
Check the box for drift collection for your audio devices
