### ISSUE TITLE
Is BlackHole compatible with Apple Silicon?

### ISSUE THREAD

**Issue by EddaAkikusa** [ExistentialAudio/BlackHole#227]

**Comment by devinroth** [comment]
Not yet. Do you have a machine? Are you willing to test it out?

**Comment by EddaAkikusa** [comment]
I'll get the new MacBook Pro in few days, and I'm willing to test it out.
I'm not sure whether Big Sur on ARM has more restrictions than Intel's.

**Comment by devinroth** [comment]
Awesome. Well let me know when you get it and we’ll try it out.

Devin

**Comment by devinroth** [comment]
Try this out. Or if anyone else has the new M1 chip please test. 

[BlackHole.driver.zip](https://github.com/ExistentialAudio/BlackHole/files/5558242/BlackHole.driver.zip)

**Comment by EddaAkikusa** [comment]
My new Mac will ship next week...

**Comment by devinroth** [comment]
Great. Turns out it was really easy to build it for the M1. Let me know how it goes when you get the new Mac.

**Comment by illegalmp3** [comment]
Hey there @devinroth ,

I just came across BlackHole while searching for an iShowU Audio Capture replacement, and I appreciate you making a build for the new M1 Macs. I received my M1 MBP yesterday.

I installed the driver from the zip you provided, and unfortunately, I experienced the distorted/slurred audio that someone else reported elsewhere in this Issues section. I noticed that the new build you provided was the 16ch version of Blackhole, so I uninstalled it and installed the 2ch (non-M1) version. 2ch works perfectly with OBS on my M1 MBP. I'll definitely be snagging a 2ch M1 build, should you get around to it soon. :)

**Comment by devinroth** [comment]
Wow. So the 2ch non M1 version works. I'm quit impressed. As I'm sure you saw in the other thread, the issues with the 16ch are unfortunately not a BlackHole issue. I'll post a 2ch version here for you to test out.

**Comment by devinroth** [comment]
[BlackHole2ch.driver.zip](https://github.com/ExistentialAudio/BlackHole/files/5562458/BlackHole2ch.driver.zip)

**Comment by illegalmp3** [comment]
Huh! Well, I downloaded the BlackHole2ch.driver.zip version you provided just above this post, overwrote the previous non-M1 2ch driver, restarted CoreAudio using the terminal language under the 'Uninstall' instructions, and now I'm experiencing the same slurring/distortion that occurred with the 16ch M1 version.

I'm gonna try removing the driver altogether and 'clean' installing the 2ch M1 driver, restart CoreAudio after that and see if it works properly.

**Comment by devinroth** [comment]
Is it in fact the 2ch one? Just double check that I didn’t accidentally give you the wrong one.

Devin

**Comment by devinroth** [comment]
May have miss labeled it.

Devin

**Comment by illegalmp3** [comment]
Just double checked, and you indeed gave me a 2ch version of BlackHole in BlackHole2ch.driver.zip.

My 'clean install' idea didn't work, since manually pasting the contents of the above .zip into Library/Audio/Plug-Ins/HAL and restarting CoreAudio via Terminal kept giving me one of these security messages.

<img width="260" alt="Screen Shot 2020-11-18 at 1 49 15 PM" src="https://user-images.githubusercontent.com/38093668/99592690-62458d00-29a5-11eb-8b69-6bb381651746.png">

I've seen this message plenty of times before, went into the Security settings to tell macOS to 'Open Anyway', but doing so just opened a new Finder window for BlackHole2ch.driver in the HAL folder. Because of that, the above security message just kept displaying itself every time I restarted CoreAudio.

So I used BlackHole2ch.v0.2.7.pkg to install the non-M1 2ch version, tested that with a Multi-Output Device in OBS, still worked great. I manually pasted the contents from your BlackHole2ch.driver.zip over the existing non-M1 driver, restarted CoreAudio, and with the M1 2ch driver, the slurring/distortion has returned when sending audio through a Multi-Output Device.

**Comment by devinroth** [comment]
I probably forgot to sign the driver. I'll try again soon.

**Comment by devinroth** [comment]
Try this one.
[BlackHole2ch.driver.zip](https://github.com/ExistentialAudio/BlackHole/files/5563675/BlackHole2ch.driver.zip)

**Comment by illegalmp3** [comment]
Unfortunately, I'm experiencing the same behavior as before with the new .zip you provided. I tried all the same things; overwriting the previous non-M1 driver with the new driver produced the same slurring and distortion, and installing the new driver fresh with the previous one removed still gave me that Security pop-up, even after I tried rebooting immediately after dropping the new driver into the HAL folder.

**Comment by devinroth** [comment]
Could you send me a clip of the slurring/distortion you are experiencing?

**Comment by moyitpro** [comment]
[RPReplay_Final1606272923.zip](https://github.com/ExistentialAudio/BlackHole/files/5594164/RPReplay_Final1606272923.zip)
I have the same issue with Jump Desktop, which uses the BlackHole audio driver to redirect audio. See clip, the audio is garbled up. This is on a M1 Mac Mini.

**Comment by devinroth** [comment]
What version of the driver are you on?

Devin

**Comment by devinroth** [comment]
If anyone wants to donate a M1 mac mini 16gb, i’ll gladly make this my #1 priority. ;)

Devin

**Comment by devinroth** [comment]
Try the latest M1 build from this thread and report back.

Devin

**Comment by CestDiego** [comment]
After trying last build from thread I can confirm that this does not work for me either :'(  When I select the multiple output to listen to I hear noises and sounds garbled up.

**Comment by moyitpro** [comment]
> If anyone wants to donate a M1 mac mini 16gb, i’ll gladly make this my #1 priority. ;) Devin
> […](#)

Get you own. I am not giving up my $1099 Mac mini I paid my hard own cash for. I’m pretty sure you can afford it from the funding you receive.

**Comment by devinroth** [comment]
@moyitpro First off, it was tongue in cheek hence the wink at the end (although I wouldn't argue if someone actually did). It's pretty hard for me to test/debug on a machine I don't own. 2nd, I don't receive any funding for this project. I have a few donors that equals approximately ~$100 a month which doesn't even begin to cover the time and resources that I spend on this project. 3rd, you are welcome for providing a free and open source. 

I do not appreciate your comment. If you are not supportive of open source projects you are absolutely free to use and support closed source alternatives.

**Comment by devinroth** [comment]
@CestDiego perhaps it's the multi-output that is the problem. Could you run a test with only BlackHole?

**Comment by moyitpro** [comment]
> @moyitpro First off, it was tongue in cheek hence the wink at the end (although I wouldn't argue if someone actually did). It's pretty hard for me to test/debug on a machine I don't own. 2nd, I don't receive any funding for this project. I have a few donors that equals approximately ~$100 a month which doesn't even begin to cover the time and resources that I spend on this project. 3rd, you are welcome for providing a free and open source.
> 
> I do not appreciate your comment. If you are not supportive of open source projects you are absolutely free to use and support closed source alternatives.

I don"t  appreciate this comment either as I work on my own open source project. I just find the comment wanting someone to donate a expensive M1 Mac mini as a sense of entitlement. Don(t say I am not supportive of open source projects as I develop open source iOS/Mac apps and receive less in donatiions than you. I ifnd this highly offensive.

**Comment by illegalmp3** [comment]
@devinroth My apologies, I just got back to my laptop after some time away and I’ll be taking some clips of the results I’m getting with the M1 2ch build after some family time this evening.

Really, I just wanted to jump in and say that it was _incredibly_ obvious to me that @devinroth was joking about accepting donations of a Mac Mini, but I guess even winky smileys at the end of a sentence aren’t clear enough for _all_ people. 😂

**Comment by devinroth** [comment]
Thanks for the support @illegalmp3. I'm just going to delete all of those comments as they are off topic.

**Comment by devinroth** [comment]
Could someone with an M1 try building BlackHole on their machine and report back?

**Comment by devinroth** [comment]
I've been working on some bug fixes. I wonder if they will solve some of the M1 issues. 

Anyone willing to try building the driver from the 0.2.8 branch and see how it goes?

**Comment by wookayin** [comment]
@devinroth I tried building the 0.2.8 branch, placed the driver file into HAL, but Blackhole does not show up on M1. I am not an expert app developer; do you have any idea how can we troubleshoot or look at the log files?

**Comment by devinroth** [comment]
Did you run `sudo launchctl kickstart -kp system/com.apple.audio.coreaudiod` in terminal?

**Comment by wookayin** [comment]
Yes I did. It was my bad -- I was supposed to copy the driver, not sym-linking (it had worked for me before). After that, Blackhole shows up. However it seems it is not working: I cannot hear any sound (maybe it is outputting some non-audible sounds) and the volume bar fluctuates randomly.
![blackhole-test-1127](https://user-images.githubusercontent.com/1009873/100493675-4a89a980-3107-11eb-8e52-6e63b00a2e9e.gif)

**Comment by devinroth** [comment]
BlackHole doesn’t output sounds. Create a multi output and try that.

Devin

**Comment by wookayin** [comment]
When I say "I cannot hear any sound" I meant one after multi output settings or a sound recording from the Blackhole's virtual microphone input. Actually, the only thing I hear is some crackles.

Actually I somehow posted a wrong screenshot, sorry. Here is the "fluctuation" behavior:

![blackhole-test-1127-2](https://user-images.githubusercontent.com/1009873/100493972-dcdf7c80-310a-11eb-8a27-113d73db045d.gif)

**Comment by devinroth** [comment]
Hmmm.  Not sure what to make of that.

**Comment by z1r0-** [comment]
I'm usually using multiple Blackhole Drivers with SoundSource (to redirect app output to different channels) and WaveLink (to mix volume of the channels with streamdeck). It works with x64 version of the blackhole driver (i compiled on my old mac). If I recompile blackhole driver on m1 macbook the sound is broken.

To eliminate possible problems with wavelink (there is no arm version yet) and other software closed them all. set my output to the Blackhole driver and used Music app to play some music and quicktime to record the audio-output of the blackhole device. The result is the same noisy output. 

> BlackHole doesn’t output sounds. Create a multi output and try that.

I didn't manage to create a multi-output or whatever in this midi-stuff which I'm able to output over my speaker. Just don't know how to do it. But the test described above was the closest I could get to "with only Blackhole".

btw. I used 0.2.8 branch to build the driver.

**Comment by devinroth** [comment]
Thanks for the update.

I think I will need to test it on an M1 myself. I’ll take a Month or so to get here.

Devin

**Comment by douglydoright** [comment]
I have downloaded the installer package and installed 2 channel BH on a new M1 MacBook Air and can report it has been working for my purpose flawlessly without issue. Recording browser streams with Audacity.  Blackhole 2ch appears in the mac sound drop down, audio preferences, midi app, all related menus/boxes, etc. Audacity running fine on ‘rosetta’ and smokes various tasks. The Soundflower ‘kext’ failed to make the jump to the new pc. A fresh SF install is not allowed in Big Sur so I am delighted to find this replacement. Thanks very Much!

**Comment by calebcbaker** [comment]
> Thanks for the update. I think I will need to test it on an M1 myself. I’ll take a Month or so to get here. Devin

@devinroth Does this require an Apple Developer account? If not I can attempt to compile on mine.

**Comment by devinroth** [comment]
No you don’t need a dev account.

Devin
