### ISSUE TITLE
Loud distortion Noise at start of using BlackHole

### ISSUE THREAD

**Issue by farbefreak** [ExistentialAudio/BlackHole#230]
Hello Dev,

I do use BlackHole with Audio Hijack. 
I have both 2ch and 16CH installed.
I pipe all system audio into BlackHole. (setting it as default output device in systempreferences)
I use BackHole as a audio input into Audio Hijack, inside Audio Hijack I use many AU plugins to modifiy the sound, Audio Hijack that outputs to my Analog outputs (Sound Card). See attached routing chain for reference.

If I start a session, it seems like the BlackHole "pipe" is filled with just ones so starting the session results in full Audio volume output for multiple ms, clipping my preamps and everything that follows resulting in my ears bleeding :D.
After these multiple ms full volume sound "bleep" everything works as expected. 

I did use the same setup with sound flower before, it did work flawlessly, no noise while starting the session.
<img width="1434" alt="Bildschirmfoto 2020-11-27 um 22 54 57" src="https://user-images.githubusercontent.com/36580519/100486430-1791e680-3104-11eb-8e41-0ebb5dd71bf2.png">

**Comment by devinroth** [comment]
Thanks. I’m aware of this and will include the fix in the next release.

Devin Roth

**Comment by farbefreak** [comment]
WOW that was fast!

Thanks for your work!
Hope everything goes well fixing this.

**Comment by quantuminformation** [comment]
I am also hearing it, is it released?

**Comment by quantuminformation** [comment]
I'm hearing a loud buzzing noise with all my recording

**Comment by devinroth** [comment]
The fix is on the 0.2.8 branch. Still in development. Volume won't work yet but you're free to give it a try.

**Comment by quantuminformation** [comment]
i restarted, issue fixed)

**Comment by KonVas** [comment]
Sorry if I am hijacking this thread, I might have a problem that relates to this issue. When I start use Blackhole with Audacity and OBS selecting Blackhole driver in the later it bursts for couple of ms. After this all sounds are periodically chopped like clipping very close timely. I am using Blackhole-2ch for what's worth. (MacOS/10.15.7).

**Comment by devinroth** [comment]
All of this is solved with v0.2.8 whenever I can get that released.

Devin Roth

**Comment by diskandarnerd** [comment]
Hi I am using BH 0.29 still having distorted sound. Already check the drift.

The strange thing, after restart it will work but once I opened OBS and put the audio setting to multi-aggrerate - the sound distorted again.

**Comment by devinroth** [comment]
Upload a photo.

Devin Roth
