### ISSUE TITLE
Uninstall fails, OSX 10.15.7

### ISSUE THREAD

**Issue by roginium** [ExistentialAudio/BlackHole#232]
Devin,

The instructions and package for deleting the blackhole driver may need an update.  On my system the driver pathing is:

/Library/Audio/Plug-Ins/HAL/Oka Mirror Audio Driver.driver

Thank you-

**Comment by devinroth** [comment]
Contact Oka Mirror. Looks like they forked BlackHole.

**Comment by roginium** [comment]
I should have know. My error.  Thank you.
