### ISSUE TITLE
Can I pass my desktop audio and mic audio to skype? 

### ISSUE THREAD

**Issue by yaquawa** [ExistentialAudio/BlackHole#233]
Hi @devinroth! Thanks for your work on Blackhole.

I was trying to send my desktop audio along with my mic audio together to skype with this configuration:
(my earphone was plugged into the "***BLUE USB Audio 2.0***" )
<img width="881" alt="1" src="https://user-images.githubusercontent.com/13927101/100773318-0cacbe00-3444-11eb-8f5d-de653840b745.png">
<img width="881" alt="2" src="https://user-images.githubusercontent.com/13927101/100773371-1fbf8e00-3444-11eb-86ff-2f5fbd5332b3.png">
<img width="780" alt="3" src="https://user-images.githubusercontent.com/13927101/100773420-32d25e00-3444-11eb-897d-74a5e12fc0fa.png">
<img width="780" alt="5" src="https://user-images.githubusercontent.com/13927101/100773486-4a114b80-3444-11eb-8901-070ec032cd9d.png">
<img width="812" alt="6" src="https://user-images.githubusercontent.com/13927101/100773554-60b7a280-3444-11eb-808b-bc34dbc0be33.png">

The problem is that Skype only picks my mic audio(BLUE USB Audio 2.0).  
I want to include the desktop audio into Skype too.
Is there any problem with my configuration?

**Comment by devinroth** [comment]
Please follow this setup. 

https://existential.audio/howto/StreamFromGarageBandToSkype.php

**Comment by yaquawa** [comment]
@devinroth If I set the "Microphone" of Skype to BlackHole, Skype only records my desktop audio.

**Comment by devinroth** [comment]
That's where GarageBand comes in. It will mix your mic into BlackHole.

**Comment by yaquawa** [comment]
@devinroth Did you to send both desktop and mic audio to Skype, I must use GarageBand as a middleware?

**Comment by devinroth** [comment]
Correct. You can use any type of DAW. Audacity works too.

**Comment by yaquawa** [comment]
@devinroth Thanks! Actually I have no knowledge about DAW, would you show me how to achieve this with Audacity?

**Comment by devinroth** [comment]
I’m working on a similar guide for Audacity but it won’t be ready for a bit. Please just use garage band. It’s free.

Devin

**Comment by yaquawa** [comment]
@devinroth Yes, thanks, but it requires the version of macOS greater than 11😓

> GarageBand can’t be installed on “macOS” because macOS version 11 or later is required.

**Comment by devinroth** [comment]
Well you’ll need to wait.

Int a nutshell. Input is your mic, output is BlackHole and setup monitoring. Just google how to do that if you’re confused.

Devin

**Comment by yaquawa** [comment]
@devinroth Thanks for your kind words, I'm sorry for my ignorance, I even don't know what's the keyword could be used for search... can you give me some keywords for searching? thanks..!

**Comment by yaquawa** [comment]
Thanks! I just figured it out by using Adobe Audition.
