### ISSUE TITLE
BlackHole disappeared from Audio MIDI Setup

### ISSUE THREAD

**Issue by jtmathes** [ExistentialAudio/BlackHole#239]
After using it for about a year, BlackHole seems to have removed itself from my Audio MIDI Setup. My multi-output device was still there and showed BlackHole as a checked, greyed-out option, but once I interacted with it the option removed itself from there as well.  Since then, I've attempted to restart and re-install a couple of times, including using the method described in Issue #119 with the ZIP file, to no avail.
Catalina 10.15.7, I haven't installed the 10.15.7 Supplemental Update yet.

**Comment by devinroth** [comment]
Type `ls -l /Library/Audio/Plug-Ins/HAL` And  `ls -l /Library/Audio/Plug-Ins/HAL` in terminal and show me the results.

**Comment by jtmathes** [comment]
Those look like identical commands to me: was `ls -l /Library/Audio/Plug-Ins/HAL` typed twice on accident? The result of which is:
> `total`
`drwxr-xr-x  3 joshua  wheel  96 Feb  9  2020 BlackHole1.driver`

As you can see, I went ahead and attempted to rename the .driver file per a couple of things I've seen on various replies to Issues and [Running Multiple BlackHole Drivers](https://github.com/ExistentialAudio/BlackHole/wiki/Running-Multiple-BlackHole-Drivers).  That did not resolve the issue.

**Comment by devinroth** [comment]
It might be a permissions issue.

Sorry the other command should be the same without HAL at the end. Try that. The permissions should be root wheel.

Devin

**Comment by jtmathes** [comment]
The command `ls -l /Library/Audio/Plug-Ins` resulted in:
```
total 0
drwxr-xr-x  6 root  wheel  192 Dec  8 22:43 Components
drwxrwxr-x  3 root  wheel   96 Dec  8 21:49 HAL
drwxr-xr-x  2 root  wheel   64 Aug 24  2019 MAS
drwxr-xr-x  3 root  wheel   96 Sep 17  2019 RemoteInput
drwxr-xr-x  6 root  wheel  192 Dec  8 22:43 VST
```

**Comment by devinroth** [comment]
Do.

sudo chown root:wheel /Library/Audio/Plug-Ins/HAL/BlackHole1.driver

Or whatever the driver is currently called. Restart and let me know if that works.

If not, I have a few other tricks up my sleeve.

Devin

**Comment by jtmathes** [comment]
Didn't work. 
```
% ls -l /Library/Audio/Plug-Ins/HAL

total 0
drwxr-xr-x  3 root  wheel  96 Feb  9  2020 BlackHole1.driver
```
```
% ls -l /Library/Audio/Plug-Ins

total 0
drwxr-xr-x  6 root  wheel  192 Dec  8 22:43 Components
drwxrwxr-x  3 root  wheel   96 Dec  8 21:49 HAL
drwxr-xr-x  2 root  wheel   64 Aug 24  2019 MAS
drwxr-xr-x  3 root  wheel   96 Sep 17  2019 RemoteInput
drwxr-xr-x  6 root  wheel  192 Dec  8 22:43 VST
```

**Comment by devinroth** [comment]
Do you have Xcode?

Devin

**Comment by jtmathes** [comment]
Yes

**Comment by devinroth** [comment]
Excellent.

Two things I want you to try.

First try building and installing the 0.2.8 branch. Don’t forget to reboot core audio.

If that doesn’t work change the UID of BlackHole to something else. And try again.

Please let me know the results.


Devin

**Comment by jtmathes** [comment]
Installing 0.2.8 via Xcode worked.
Your help was much appreciated.

**Comment by devinroth** [comment]
Awesome. 0.2.8 is still not released yet. Volume and Mute won’t work. And let me know if you run into any issues.

Devin
