### ISSUE TITLE
BlackHole disappears

### ISSUE THREAD

**Issue by coldrick** [ExistentialAudio/BlackHole#24]
I've tried to install BlackHole: it puts up a dialogue saying it installed successfully, but I can't find it anywhere. This is on Catalina, 10.15.1

Any ideas?

Regards,
David

**Comment by devinroth** [comment]
Did you restart your computer?

Devin

**Comment by coldrick** [comment]
Yes. But the app doesn't appear in Applications, or anywhere else

**Comment by arvidtp** [comment]
It’s an audio interface, it just shows up in audio MIDI setup or the sound preference pane.

**Comment by coldrick** [comment]
Ah. OK, thanks.

David
