### ISSUE TITLE
Intermittent crackle/distortion and/or latency in Ableton

### ISSUE THREAD

**Issue by i-am-dan** [ExistentialAudio/BlackHole#240]
Hi! First of all, love the app. thank you.

The audio sometimes starts to crackle and latency randomly gets introduced. It seems like changing the sample size fixes this every time I get some audio distortion. So, lets say I have the buffer to be 512. I get some latency, I change to 128/256 etc. Latency goes away. Audio distorts, I change to 128/64/512... etc. The distortion goes away. 

I'm on Mojave.

Any thoughts on this would be VERY helpful! TY!

**Comment by devinroth** [comment]
Sounds like you don’t have drift correction enabled for BlackHole.

Devin
