### ISSUE TITLE
macOS 11.1 Driver in /Library... but doesn't appear in MIDI or Sound Outputs

### ISSUE THREAD

**Issue by weedinmonz** [ExistentialAudio/BlackHole#245]
Firstly, thank you for developing this amazing software. 
As title reads. I can't get the BlackHole driver to appear in either Audio Devices (Audio MIDI Setup) or inside System Preferences > Output.  A new aggregate device (of just two outputs) appears instantly in both places.

I have (re)-installed several times, kickstarted the audio drivers via terminal, restarted etc, [read this thread](https://github.com/ExistentialAudio/BlackHole/issues/239) and changed/checked permissions.   I have also had it working on OS 11.1 (yesterday, 15 Dec 20) but this is now a clean install and isn't working.

Greatly appreciate any help. Uploading my permissions. Just downloading XCode now.
<img width="682" alt="Screenshot 2020-12-16 at 13 27 21" src="https://user-images.githubusercontent.com/76110071/102354427-711e6000-3fa2-11eb-9390-4cdbd116fef2.png">

**Comment by weedinmonz** [comment]
OK. I created a new volume / fresh install and was able to repeat not being able to install 2ch or 16ch with no other programs installed, just a fresh 11.1 install.

Came back to my original OS I was trying to get this working on this morning, and it's appeared BUT with these two dialog boxes as errors, which I'm hoping help you diagnose why this happened for me.

But for now, it's appeared in Sound. So strange! 

<img width="1440" alt="Screenshot 2020-12-16 at 15 13 14" src="https://user-images.githubusercontent.com/76110071/102367983-44724480-3fb2-11eb-9f73-69336e89ff0c.png">

**Comment by devinroth** [comment]
The solution was use the driver from the 0.2.8 branch. Unfortunately it’s not released yet.

Devin

**Comment by weedinmonz** [comment]
I see, thank you... well I'll wait for that. Meanwhile I've got the drivers to appear (I don't actually know how).... but now I think that perhaps AU Lab doesn't have permission to use the Microphone as shown in another thread.

I too am getting the malware notice about the driver when I launch it, you mention something about [changing the bundle ](https://github.com/ExistentialAudio/BlackHole/issues/119#issuecomment-671156951) name, where can I do this, is that within /Library/Plugins ?   Thanks

**Comment by weedinmonz** [comment]
I triggered the Microphone prompt by opening an old .dmg version of AU Lab I have which encourages you to put it into Utilities folder.  

I hate how annoying current macOS' is around what it thinks I want to do! Hours spent fixing due to its 'security' settings.
