### ISSUE TITLE
Blackhole seemingly not running after upgrade to 11.1

### ISSUE THREAD

**Issue by jairenee** [ExistentialAudio/BlackHole#246]
Blackhole now appears greyed out in Audio MIDI Settings, and no longer routes audio. I'm unsure what to do in this situation, or why it's suddenly stopped working. The only change to my device overnight is the upgrade to 11.1. I'm on an M1 Mac Mini

Any assistance is appreciated. Thanks.

![Screen Shot 2020-12-20 at 1 30 41 PM](https://user-images.githubusercontent.com/36556956/102721231-96bfa800-42c7-11eb-82c1-faf48da5d2d5.png)

**Comment by wookayin** [comment]
Did it work on 11.0 before? I don't think BlackHole is yet compatible with M1 mac. Please also follow https://github.com/ExistentialAudio/BlackHole/discussions/227.

**Comment by jairenee** [comment]
@wookayin It did indeed and an uninstall and reinstall has fixed the issue. It certainly does work on M1
