### ISSUE TITLE
For some apps (in this case, Apple Podcasts) can't record with BlackHole and listen on speakers at the same time

### ISSUE THREAD

**Issue by hanbzu** [ExistentialAudio/BlackHole#249]
From the documentation, it seems possible to **record blackhole output and at the same time listen to the audio from the speakers**, by using the multi-output configuration described at https://github.com/ExistentialAudio/BlackHole/wiki/Multi-Output-Device.

Still, when I pick "BlackHole 16ch" in the "Select a device for sound input" area the sound cuts off from the speakers. I know it's routing the sound (because I can record it) but I cannot get it simultaneously on the speakers. Is this a bug or am I understanding the docs wrong?

I'm running Catalina (10.15.7).

Updated: **This happens in Apple Podcasts** -- but it works fine for audio played in the browser, for example.

**Comment by devinroth** [comment]
Show me screenshots.

Devin

**Comment by hanbzu** [comment]
![image](https://user-images.githubusercontent.com/684539/102943749-d990a400-44b0-11eb-93aa-036bbda71a3f.png)

In this configuration, the output can be recorded but I cannot hear anything from the speakers.

**Comment by devinroth** [comment]
What’s the volume set at for your headphones?

Devin

**Comment by hanbzu** [comment]
@devinroth sorry for the late reply. I have the volume at its maximum set.

![image](https://user-images.githubusercontent.com/684539/103152557-05e24400-4781-11eb-9a46-f3fd1179319d.png)

- Output is "Headphones + BlackHole"
- Input is "BlackHole"

And I cannot hear anything.

As soon as I switch either 
- the output to "Built-in output" (the jack headphones), or
- the input to microphone

I hear audio again through the headphones. It's as if the multi-output device stopped working when I set BlackHole as input devide.

**Comment by devinroth** [comment]
I’ve seen something similar before. Try using BlackHole2ch and see if that fixes it.

Devin

**Comment by hanbzu** [comment]
@devinroth I just uninstalled and installed the other version.

Unfortunately `blackhole-2ch`give me the same result.

![image](https://user-images.githubusercontent.com/684539/103155855-2b7c4700-479b-11eb-962d-ab30d3613bf2.png)

I don't know. Could it be maybe something related to my MacOS version (10.15.7) or the privacy/permissions setup?

**Comment by hanbzu** [comment]
@devinroth Okay. Mistery somewhat solved. It's app dependent.

I can hear some sound produced on the browser both on the headphones and record it with BlackHole. But I cannot do the same when I'm listening to a podcast in Apple Podcasts.

It must be that somehow they are blocking the audio in that case?

**Comment by devinroth** [comment]
Possibly. I know that they do same strange stuff with FaceTime, Dictation, etc. I'll leave this around to take a closer look at some point. Thanks for updating the title to be more specific.

**Comment by devinroth** [comment]
It seems that Podcasts only uses the first device in a Multi-Output device. Nothing we can do about that. But....there may be a work around. If you output to BlackHole directly, and then in your recording app monitor the output to your speakers you can record and listen. But it appears that Podcasts will only output to one device regardless of wether its is a multi-output or not. From my understanding of the low level audio code it actually kind of makes sense, unfortunately.

**Comment by devinroth** [comment]
In a nutshell, some apps will not work with Aggregates and Multi-outputs.

**Comment by devinroth** [comment]
I'm just going to add this information to the FAQs. Going to make a list of apps that don't work with multi-outputs.

**Comment by Scryb** [comment]
Just wanted to add that FaceTime also doesn't work with Multi-Output device, when it works with with e.g. Music and other apps. In fact, on my machine it's even weirder: Selecting system output in FaceTime and setting the system audio to the multi-output device, things seem fine until I receive a call. As soon as I pick up, sound stops being routed to either of the devices in the multi-output device, but FaceTime starts routing its own audio to a completely different device (one of my monitors, connected over DP).

Your tip to select Blackhole as the only output in FaceTime and then turning on monitoring works for recording (I'm using OBS). Thank you!
