### ISSUE TITLE
I'm lost...can you support me?

### ISSUE THREAD

**Issue by xdibellax** [ExistentialAudio/BlackHole#25]
I have blackhole downloaded and installed on Mac OS 10.15. First off should there be an application in the apps folder? I have played around and set Audio Midi Setup yet I'm not sure things are working properly. I am trying to record auto from a video online and it still the sound still have that low echo type sound to it. I played around with Audio Hijack and when doing so the sound came out clear...I was under the impression this would be aiming to do that same sort of thing...Can anyone support me with this?

**Comment by devinroth** [comment]
It's a driver only so no application in the apps folder. 

How exactly do you have it setup? What programs are you using? Could you send me a recording of what you capture vs how it's suppose to sound?

If I had to guess you probably are listening to the audio directly from a multi-output and audio being pass-through a daw which is causing the audio to create an echo. But I need more information before I can help.

**Comment by xdibellax** [comment]
Hey Devin,

Good to hear back from you promptly! 
I’m in bed at the moment but will send you a recording in the morning. It’ll be first thing on my list. 
I didn’t understand all that technical talk but you are prolly right. I’m just trying to find a solution to record quality audio while I record the video (even if it has to be with crap sound) from a few lessons for this course I’m in.

I’ll get all you ask first thing in the morning and hopefully by the evening I’ll be all set, yay! 


Cheers,
 Di Bella

**Comment by xdibellax** [comment]
<img width="642" alt="Midi recorder setup" src="https://user-images.githubusercontent.com/5334231/68345527-89ddf600-00bf-11ea-9e17-41013541d803.png">

<img width="2560" alt="how auto is set up when doing a screen recording" src="https://user-images.githubusercontent.com/5334231/68345538-92363100-00bf-11ea-9e39-80eb3c6c2adf.png">

https://drive.google.com/file/d/1rSSXJILlWDBNbKIGNB4CzW6CD3vKmAMt/view?usp=sharing

https://drive.google.com/file/d/1-soBw54QIJnb-JUqideOUSvCuSN_fgSO/view?usp=sharing

**Comment by devinroth** [comment]
Use BlackHole not the aggregate to record. You were recording with your build in microphone instead of passing through with BlackHole. If you would like you can setup a multi-output device instead. 

Devin

**Comment by devinroth** [comment]
And you need to set BlackHole as your default output device. 

Devin

**Comment by xdibellax** [comment]
AWESOME!!! Thank so so much, this is all new to me. I appreciate you taking the time to support me. Cheers!

**Comment by devinroth** [comment]
You’re welcome.

**Comment by xdibellax** [comment]
> And you need to set BlackHole as your default output device. Devin
> […](#)

So I need to set blackhole as default output device in Midi Setup, have built in audio as default audio input and then when screen recording select blackhole? 

I've tried a few different things with doing various setup but. most of the time there is no audio on the screen record...back to being stumped. 

Also anytime I try to set-up a multi-out device the video does not even play. 

I need to know how to pass thru the audio in to blackhole...I tried keeping builtin Audi as the microphone in midi setup then selecting blackhole when in screen record...

Just so stumped now :/

**Comment by devinroth** [comment]
First off you shouldn't be hearing audio if you're just using BlackHole. It passes audio through without sending to the speakers. My guess is it was working fine. As for the multi-output device, there seems to be a bug with multi-output where you have to have the build-in audio output first on the list. https://github.com/ExistentialAudio/BlackHole/wiki/Multi-Output-Device

**Comment by xdibellax** [comment]
So if there is now just to be clear when trying to screen record audio an video, I need to have Blackhole set as default audio output and as audio input then be sure to select blackhole when using the screen record correct? or is the audio in supposed to be the mic in midi setup and then simply select blackhole in the screen record?? I guess my main question if the video doesn't record the sound where do I find the stored sound file to layer? I thought it would all record at once...

**Comment by devinroth** [comment]
Yes to the first question. And it should record together.

**Comment by xdibellax** [comment]
and success!! Thank you for your patience and support
