### ISSUE TITLE
2 ch not working on OSX Big Sur Apple Silicon

### ISSUE THREAD

**Issue by boblund** [ExistentialAudio/BlackHole#251]
I have configured an aggregate device on OSX Big Sur (Apple Silicon). When I use the device to route between applications, only one channel is detected on the recording app and I hear computer audio on the playing app. Below is my aggregate device config.

![image](https://user-images.githubusercontent.com/7492275/103174173-34adf800-481d-11eb-9622-1e8e91f63e26.png)

**Comment by devinroth** [comment]
Chances are you have it setup wrong. What apps are you using? How do you have them setup? Also, BlackHole is not technically ready for M1 although people have had success using Rosetta.

**Comment by boblund** [comment]
Spotify is writing to the 2 channel aggregate device and audacity is reading. I've done this before with 2 chan soundflower (which doesn't work on OSX Big Sur Apple Silicon). Turns out though that if I delete the aggregate device shown in my original post and use BackHole 2 Ch instead it seems to work as expected.

**Comment by devinroth** [comment]
You should be using a multi-output not an aggregate.

Devin

**Comment by devinroth** [comment]
Just tested this out and it works completely fine with a multi-output. Using Apple Music instead of Spotify. So unless Spotify doesn't work with Multi-Outputs (which is possible, see #249) it should be completely fine.
