### ISSUE TITLE
Unintelligible Static Noise when routing DAW to Zoom call

### ISSUE THREAD

**Issue by kookoo820** [ExistentialAudio/BlackHole#252]
Hello,

I've had this problem for about a month or two now. I usually use BlackHole to route mic and MIDI audio from Logic to my Skype and Zoom calls and my headphones via Multi-Output device on Mac. A while ago, during a call, my audio just turned into static, and didn't resolve itself until I swiped back to view the Logic window. It then was fixed again (with a new mic input latency issue). When I swipe back to my call window, my audio is fine for about a minute, and then the static comes back again. Hopefully someone can help me fix this, so I can continue to use my DAW as a call input; if it can't be fixed, the next thing for me to do is to ditch the DAW and BlackHole, and just use an aggregate device straight from my audio interfaces. I've tried reinstalling BlackHole, checking clock drift on different devices, using different DAWs (GarageBand and MainStage), and testing both Zoom and Skype, but unfortunately the problem is consistent for all cases.

<img width="629" alt="Screen Shot 2020-12-27 at 11 25 33 PM" src="https://user-images.githubusercontent.com/76679646/103197478-f35c2d80-489a-11eb-8a80-ec8128d63d12.png">
<img width="1792" alt="Screen Shot 2020-12-27 at 11 25 44 PM" src="https://user-images.githubusercontent.com/76679646/103197493-f820e180-489a-11eb-91a2-fbec2adad8a6.png">

**Comment by devinroth** [comment]
I've had this problem too. Unfortunately it's not a BlackHole problem but a Logic Problem. The issue is that when Logic is in the background the audio thread is no longer a priority and ends up dropping audio. As soon as Logic is back in focus the issue goes away since priority is given to the thread. This is unfortunately the way Logic or other Apple DAWs are programmed. What other DAWs have you tried? I haven't had problems with non Apple ones. What computer/OS are you using?

**Comment by devinroth** [comment]
You can try increasing the buffer size in Logic but I've found that that doesn't solve the problem. Still worth trying.

**Comment by devinroth** [comment]
Also worth testing out the 0.2.8 branch. I wonder if that will make any difference.

**Comment by kookoo820** [comment]
Glad to hear I’m not the only one experiencing this. At least I know it’s not a problem with any of my gear. I’ve only tried this with the Apple DAWs. I’m running the latest Big Sur, I think. Can you tell me what the “0.2.8 branch” is? I don’t understand; I’m no expert! I can also see what happens if I route Logic’s audio to Audacity and then route Audacity to the Multi-Output Device. In theory, I don’t see it making a difference, but I’ll try it.

**Comment by devinroth** [comment]
What computer are you using?

**Comment by kookoo820** [comment]
I’m on the 16 inch MacBook Pro.

**Comment by devinroth** [comment]
What year? What are your specs?

**Comment by devinroth** [comment]
Give the latest release 0.2.8 a spin. Maybe it will solve the problem.

**Comment by devinroth** [comment]
Reopen if you still have issues.
