### ISSUE TITLE
Big Sur Malware Warning

### ISSUE THREAD

**Issue by Clock-Drift** [ExistentialAudio/BlackHole#253]
Version 11.1, notification warning that Blackhole.driver will damage my system appears on login.

<img width="420" alt="Screenshot 2020-12-31 at 18 51 14" src="https://user-images.githubusercontent.com/48359410/103422611-3a4b6b00-4b9a-11eb-9125-344946bf1627.png">

**Comment by devinroth** [comment]
Make sure you have Security and Privacy set to "Allow Apps downloaded from App Store and identified developers. "
<img width="780" alt="Screen Shot 2020-12-31 at 11 03 44 AM" src="https://user-images.githubusercontent.com/13010961/103422781-f3d51c80-4b57-11eb-89de-5a67a545a626.png">

**Comment by Clock-Drift** [comment]
Already set to allow from anywhere, notification only emerged today on a reboot into safe mode and then on regular boot

<img width="308" alt="Screenshot 2020-12-31 at 19 08 17" src="https://user-images.githubusercontent.com/48359410/103422884-9a8edc80-4b9b-11eb-81c5-2ce28c992d1e.png">

**Comment by devinroth** [comment]
Did you download it from existential.audio?

**Comment by devinroth** [comment]
Maybe try reinstalling.

**Comment by Clock-Drift** [comment]
Reinstalling 16out version seems to have cleared it up for now

**Comment by mourner** [comment]
I got the same issue after upgrading Big Sur from 11.2 to 11.3 — the warning just popped up after the reboot. Reinstalling with the installer did not help. Installing through `homebrew` did.

**Comment by devinroth** [comment]
All homebrew does is install the driver. It’s literally the exact same thing.

Devin Roth

**Comment by joeynotjoe** [comment]
@devinroth that's what I would think, too, but I reinstalled via homebrew, and it fixed the issue for me as well.

**Comment by devinroth** [comment]
That may be so but like I said, all Homebrew does is download and run the installer. The exact same installer.

Devin Roth

**Comment by schwie** [comment]
My Mac updated to Big Sur 11.4 overnight and this morning (likely after a restart) it showed the screenshot @Clock-Drift posted. I clicked "Show in Finder" and then posted here.
