### ISSUE TITLE
"Download Installer' link seems to not cope with already registered users.

### ISSUE THREAD

**Issue by timboxyz** [ExistentialAudio/BlackHole#255]
The Link takes one to page where the only option seems to be to subscribe, even if one is already registered. After 15mins I have seen nothing in my inbox/spam folder.

**Comment by devinroth** [comment]
I’ll work on setting up an upgrade link.

**Comment by devinroth** [comment]
Regardless you should still get the link even if you already subscribed. I’ve been having issues with email providers silently blocking my emails. Has to do with being on a shared IP. Time to upgrade.

**Comment by timboxyz** [comment]
Eventually the email did come through, but after probably 1/2 hour or so. An upgrade link sounds a good idea.

**Comment by devinroth** [comment]
Great. I'll work on it.
