### ISSUE TITLE
Package "tampered or edited"

### ISSUE THREAD

**Issue by xPqin** [ExistentialAudio/BlackHole#259]
Hello!

So I wanted to download the 16ch version of this because I got the 2ch version of BlackHole. When I tried opening the .pkg file of the 16ch BlackHole, it says "This package has been tampered with or changed" or something along those lines. I dont know how to fix this

**Comment by devinroth** [comment]
Yes. I’m aware of this issue. What OS version are you on. It seems to affect 10.11.

Devin

**Comment by xPqin** [comment]
I am currently running on OS X El Capitan 10.11.6.

**Comment by devinroth** [comment]
Yup. Same as all the other people that have problem.

The solution for now is use the 0.2.7 installer. I’ll work on fixing it soon.

Devin

**Comment by devinroth** [comment]
[BlackHole2ch.v0.2.7.pkg.zip](https://github.com/ExistentialAudio/BlackHole/files/5800296/BlackHole2ch.v0.2.7.pkg.zip)

**Comment by xPqin** [comment]
Sorry for replying late, I had to do some things. Thank you for helping me! By any chance, is there anyway you can give me the link/file for the 16ch version? Thanks!

**Comment by devinroth** [comment]
I already uploaded it to this thread.

Devin

**Comment by xPqin** [comment]
Are you sure? It only says the 2ch one?

**Comment by devinroth** [comment]
Did you need the 16ch one?

Devin

**Comment by xPqin** [comment]
I would prefer it if you can put the 16ch one.

**Comment by devinroth** [comment]
[BlackHole16ch.v0.2.7.pkg.zip](https://github.com/ExistentialAudio/BlackHole/files/5860639/BlackHole16ch.v0.2.7.pkg.zip)

**Comment by devinroth** [comment]
Fixed it. Not sure why but code signing on Big Sur is not value on El Capitan (10.11).
