### ISSUE TITLE
Echo from voice call

### ISSUE THREAD

**Issue by jayychang** [ExistentialAudio/BlackHole#260]
I am using BH to route my computer sound (Spotify) and mic voice to a VoIP such as Discord. The setup works but there seems to be an echo for the other people.

Since BH is capturing my desktop sounds, it captures both Spotify and Discord (what the other people are saying) and shooting it back up through BH; causing an echo for the other people. Is there a way to capture specific application sounds and not the call sound? I am using Garageband to capture my mic and the Garageband setup guide for reference.

**Comment by devinroth** [comment]
Are you using headphones? If not, try and see if that makes a difference.

You also shouldn’t have BH as the output of Discord so if you are doing that change it.

Devin

**Comment by jayychang** [comment]
I tried earphones, but it seems to be a software routing issue.

I believe it has to be that Discord has 'built in' as output, but the multi-output in MIDI routes the 'built in' into Blackhole; which is causing the echo.

<img width="396" alt="Screen Shot 2021-01-13 at 20 23 43" src="https://user-images.githubusercontent.com/14225768/104544701-434a2c80-55dd-11eb-956e-866201c63852.png">

The discord settings is input is Blackhole and output is default (`built-in`)

**Comment by devinroth** [comment]
Could you send me a screenshot of Discords settings?

**Comment by jayychang** [comment]
<img width="725" alt="Screen Shot 2021-01-18 at 18 28 38" src="https://user-images.githubusercontent.com/14225768/104980284-0c985b80-59bb-11eb-904c-558f52e0f247.png">

Computer sound is connected to blackhole through MIDI multi-ouput.
Mic is connected to blackhole through garageband.

I did some more testing with friends, in very rare cases, they (recipient) don't hear their own voices at the start, but after a few seconds, the echo always ends up happening. (only discord output/participent voice echos, everything else works)

**Comment by devinroth** [comment]
Set the output of Discord to Built-in Output not Default.

**Comment by jayychang** [comment]
Thanks, I think it solved the issue.
