### ISSUE TITLE
Blackhole stops working after about 20 minutes

### ISSUE THREAD

**Issue by bunmiles** [ExistentialAudio/BlackHole#261]
Hello,

I have started to stream games to twitch from my new MacBook Pro through streamlabs, and have noticed that after twenty minutes, any sound from the games/music I have playing in the stream completely cut out. Today, every twenty minutes I would have to go back and change the Multi-Output Device and StreamLabs audio back and forth between 44.1hz and 48hz for it to start working again (only for 20 minutes). I want to be able to stream with audio for longer than 20 minutes, and was wondering if there is something I can do to fix this permanently.

Thank you!

**Comment by devinroth** [comment]
There is a discussion about this already in discussions. And I put a faq on the readme.

Multi-outputs are bugging out. Someone suggested turning off drift correction.

Devin

**Comment by bunmiles** [comment]
Okay thank you! I was having a little trouble finding it so I figured I would ask!

**Comment by devinroth** [comment]
Discussions is a new feature on GitHub.

Devin
