### ISSUE TITLE
QuickTime setup to screen record system audio+microphone

### ISSUE THREAD

**Issue by twebb13** [ExistentialAudio/BlackHole#265]
Hello there,

I need to be able to record both the system audio of the machine and record my voice using a external microphone at the same time so I can speak over music as it plays.  is there someone that can help with this?! using MacBook 2020

**Comment by devinroth** [comment]
Create a multi output. BlackHole 2ch + Speakers.
Create an aggregate. BlackHole 2ch + Mic
Set system output to multi output.
Use GarageBand.
Set input to aggregate.
Create 2 tracks. One for mic and one for system audio.
Set inputs of tracks to BlackHole 2ch and your mic.

Devin

**Comment by twebb13** [comment]
This is amazing! Thanks so much for getting back to me…! Is it possible to gain of mic and volume of system audio once recording?

**Comment by devinroth** [comment]
You can mix it however you want in GarageBand.

Devin

**Comment by twebb13** [comment]
Amazing thank you…spent bout half a day doing this you really helped


Tom UK

**Comment by twebb13** [comment]
Is it possible to include system audio in a Microsoft Teams meeting using something like this?

**Comment by devinroth** [comment]
Yeah. Follow some of the guides on the website. Should be similar.

Existential.audio/BlackHole/support

Devin

**Comment by twebb13** [comment]
I’m on a new MacBook with m1 chip and just noticed the note about it crashing every 20 mins ... but I think this was last month. Has there been an update since or should I expect this to happen. I’m just screen capturing on QuickTime. and recording the audio of the computer so I can narrate over the top. 

Thank you again for your help

**Comment by devinroth** [comment]
Yeah some issues with Apple's multi-outputs. Not using drift correction seems to fix it.

**Comment by twebb13** [comment]
Turn off any drift in the multi output?

**Comment by devinroth** [comment]
If you don’t know what it is, then don’t worry.

Devin

**Comment by devinroth** [comment]
Just let me know if you notice a crash every 20 minutes.

Devin

**Comment by twebb13** [comment]
Ok awesome. Thank you again.
