### ISSUE TITLE
Cannot play computer audio through Blackhole

### ISSUE THREAD

**Issue by orangeovereasy** [ExistentialAudio/BlackHole#266]
I'm using Blackhole to stream my mic, Logic, and computer audio through Streamlabs OBS. I can stream my live mic and Logic simultaneously, but when I do this, it cuts audio from my computer. 

In my Audio MIDI Setup (images 1, 2)
Input: Aggregate Input (Blackhole 16ch and then Audio interface)
Output: Multi-Output (Audio interface and then Blackhole 16ch). 
<img width="862" alt="Screen Shot 2021-01-20 at 3 03 50 PM" src="https://user-images.githubusercontent.com/77758124/105252502-640d0780-5b32-11eb-93c3-d7a831bda520.png">
<img width="864" alt="Screen Shot 2021-01-20 at 3 04 26 PM" src="https://user-images.githubusercontent.com/77758124/105252582-9454a600-5b32-11eb-9df5-c63416a6fea1.png">

In Logic (image 3)
Ouput: Multi-Output
Input: Aggregate Input
![Screen Shot 2021-01-20 at 3 08 24 PM](https://user-images.githubusercontent.com/77758124/105252600-9b7bb400-5b32-11eb-8e23-ea9db9cdfcae.png)

In Streamlabs OBS (image 4)
Mic/Aux: Aggregate Input
<img width="828" alt="Screen Shot 2021-01-20 at 3 09 28 PM" src="https://user-images.githubusercontent.com/77758124/105252619-a3d3ef00-5b32-11eb-94c5-973b3ed5bb3a.png">

Plus, separate source inputs for the audio interface and Blackhole (image 5)
<img width="618" alt="Screen Shot 2021-01-20 at 3 10 50 PM" src="https://user-images.githubusercontent.com/77758124/105252624-a8000c80-5b32-11eb-8f1c-98c4d1affddb.png">

Similar to the previously reported issue (https://github.com/ExistentialAudio/BlackHole/issues/3), I cannot play anything with audio from my laptop with the above setup. YouTube videos, mp3s, etc., will open but freeze and immediately unfreeze when I switch the computer output to anything else besides the current Multi-output option I have chosen. I can't even take a screenshot with the above setup because it freezes the audio component of the computer screenshot (like everything else, the screenshot happens again as soon as I change the outputs).

I've tried numerous configurations, but can't find a way to stream my computer audio. The closest I've come is to add my computer speakers to the MIDI output, but this plays audio through BOTH the stream and my laptop speakers and I can't mute the laptop speaker audio. 
<img width="859" alt="Screen Shot 2021-01-20 at 3 25 36 PM" src="https://user-images.githubusercontent.com/77758124/105253165-cadef080-5b33-11eb-9426-a801fbb373b6.png">

My goal is to have audio from laptop audio/video files (e.g., YouTube), Logic, and my audio interface all going into my stream without audio coming out of my computer speakers. I know it's possible because I see other people doing it. 

Thank you for your help.

**Comment by devinroth** [comment]
https://github.com/ExistentialAudio/BlackHole/wiki/Multi-Output-Device#4-select-output-devices

Read up on this. It’s a known issue with Aggregates/Multi-outputs.

Devin

**Comment by orangeovereasy** [comment]
> https://github.com/ExistentialAudio/BlackHole/wiki/Multi-Output-Device#4-select-output-devices 

Read up on this. It’s a known issue with Aggregates/Multi-outputs. Devin

Thanks, Devin. So there is no known workaround to port laptop sound without it going through the main speakers? I'm reading that it might also be specific to blackhole. Do you know if other virtual audio drivers can bypass the issue?

Thanks

**Comment by devinroth** [comment]
The issue is the first audio device needs to have 2ch. You can use BlackHole 2ch or built-in speakers and just mute them.

Devin

**Comment by orangeovereasy** [comment]
I tried Blackhole 2ch first, but had the same issue. I'll try again. I can't mute the built-in speakers because running through blackhole disables the audio controls on the computer.

**Comment by devinroth** [comment]
Mute the speakers as shown on the right.

Devin

**Comment by devinroth** [comment]
<img width="763" alt="Screen Shot 2021-01-20 at 3 52 24 PM" src="https://user-images.githubusercontent.com/13010961/105255017-a422b900-5b37-11eb-886e-4d8d0287fc06.png">

**Comment by orangeovereasy** [comment]
YES! OF COURSE. THANK YOU. That's the solution. Now I can just unmute the computer speakers through the MIDI setup when I'm done streaming. Thank you so much.
