### ISSUE TITLE
I don't hear anything when i choose the multi output devis 

### ISSUE THREAD

**Issue by Juradus** [ExistentialAudio/BlackHole#268]
i've tried a lot, because i'll like to stream and to get the desktop audio recognized, but when I choose the multi output device, in which i have my headphones and blackhole, i don't hear anything, and i'll like to know why and how can i hear something with that chosen

**Comment by devinroth** [comment]
This has been addressed numerous times. Please read this  https://github.com/ExistentialAudio/BlackHole/wiki/Multi-Output-Device#4-select-output-devices and here was the most recent thread on the topic. https://github.com/ExistentialAudio/BlackHole/issues/266
