### ISSUE TITLE
sound playing through mpd is choppy.

### ISSUE THREAD

**Issue by onodera-punpun** [ExistentialAudio/BlackHole#273]
Sound playing through [mpd](https://www.musicpd.org) is very choppy. Attached is a recording of me playing a youtube video (works fine), and me playing a 44.1kHz flac using mpd (choppy), recorded using audacity:

https://camille.sh/pvbM.mp3

## System

Mac mini M1
Big Sur 11.2
BlackHole  0.2.8

Related issue: https://github.com/HEnquist/camilladsp/issues/90

**Comment by devinroth** [comment]
I'll look into it.

**Comment by devinroth** [comment]
You said you were having issues just using BlackHole and Audacity? What exactly is your setup?

**Comment by onodera-punpun** [comment]
It happens when I play a 44.1kHz flac using mpd to blackhole, which I then use as a source in audacity. What more do you want to know?

**Comment by devinroth** [comment]
Nah that's good. I guess I was slightly confused reading through the other thread.

**Comment by devinroth** [comment]
Having never used mpd before I'm still getting up to speed. But have you tried increasing the buffer? 

It seems odd to me that this would be a BlackHole issue since I am able to play audio through BlackHole and record it with Audacity without any issues using numerous sources. 

Does it work normally when played through other non BlackHole devices? A quick google search shows that many people are having a similar issue using mpd on macOS.

**Comment by devinroth** [comment]
Good news. I'm able to replicate the issue. And I have a good idea why. Let me dig deeper and get you the answer.

**Comment by devinroth** [comment]
So it looks like this is a problem with Audacity. Recording using the same setup causes issues in Audacity but no problems in Logic X. Something that is even more interesting is BlackHole 2ch causes problems while BlackHole 16ch doesn't. There is no difference between the two except for the number of channels. If you want a quick fix, use BlackHole 16ch with Audacity or a different daw.

**Comment by devinroth** [comment]
I think we need to open an issue with Audacity. Wow, what a wild goose chase for you.

**Comment by devinroth** [comment]
BlackHole 2ch on the top and BlackHole 16ch on the bottom. What is perplexing is this is only an issue with mpd -> BlackHole 2ch -> Audacity. Change any element in the equation and it works normally. No unusual errors in the console.  And as you said, something else playing in the background and it isn't an issue. What it seems like is the audio thread is not getting priority and audio is getting dropped. I've noticed the drop outs happen every 4096 samples. 

<img width="1552" alt="Screen Shot 2021-01-24 at 12 18 39 AM" src="https://user-images.githubusercontent.com/13010961/105624900-131f3c80-5dda-11eb-809f-f6d3e2c2632b.png">

**Comment by HEnquist** [comment]
This whole thing is quite strange. The problem started as choppy sound in CamillaDSP, and then I suggested to use Audacity to see if it was possible to reproduce without CamillaDSP. So it also happens with mpd -> Blackhole 2ch -> CamillaDSP.

**Comment by devinroth** [comment]
What does CamillaDSP and Audacity have in common?

**Comment by devinroth** [comment]
Give it a run with BlackHole 16ch with CamillaDSP and see if that works normally.

**Comment by HEnquist** [comment]
> What does CamillaDSP and Audacity have in common?

They have nothing in common! Trying with the 16 ch version seems like a good idea.

**Comment by onodera-punpun** [comment]
Use the 16ch version indeed fixes audio output through camilladsp for me.

**Comment by HEnquist** [comment]
Great! Pretty weird but hey if it works :) Does it help in Audacity for you too?

**Comment by devinroth** [comment]
Yup.

Devin

**Comment by devinroth** [comment]
I have a hunch.

**Comment by devinroth** [comment]
<img width="828" alt="Screen Shot 2021-01-24 at 9 14 18 AM" src="https://user-images.githubusercontent.com/13010961/105637951-ff4cf800-5e24-11eb-88f4-d95d133b0d0a.png">

**Comment by devinroth** [comment]
From the docs, the buffer size is 8192. That's the problem.

**Comment by devinroth** [comment]
BlackHole starts clearing audio after 8192 samples.

**Comment by devinroth** [comment]
Also explains why when you have another app open using BlackHole the problem goes away. It's because other apps use a lower buffer size.

**Comment by devinroth** [comment]
Never did I imagine that an app would use a buffer size larger than 4096.

**Comment by devinroth** [comment]
So the solution to this is add `audio_buffer_size "1024"` to mpd.conf.

**Comment by devinroth** [comment]
This can also be solved in BlackHole by increasing the time to clear the internal ring buffer to > 8192.

**Comment by devinroth** [comment]
Wow. That was a tricky one to track down.

**Comment by HEnquist** [comment]
Great! That was quick!
I'm just confused by one detail.. why did it work when you recorded with Logic X? 
Would it make sense to increase the default size of the ring buffer? I guess the only cost is a small increase of ram usage.

**Comment by devinroth** [comment]
Logic’s buffer size was over riding mpd’s buffer size. That wasn’t happening with Audacity. I tied messing around with Audacity’s buffer size but that didn’t help.

Yes it makes sense to increase the max buffer size in BlackHole. The trade off is definitely worth it. But if I can somehow limit the max buffer size that will be the best. Probably do both. But there has to be an upper limit or may happen again.

Time to do some research.


Devin

**Comment by onodera-punpun** [comment]
What a rabbit hole, thanks a lot for the help! What does this max buffer size actually do though? is a higher buffer size more or less efficient in general?

**Comment by onodera-punpun** [comment]
After running blackhole-2ch for a few hours the exact same choppiness appears, though now not only for mpv but also when playing YouTube videos. Restarting camilladsp (the output) doesn't fix it, neither does switching back and forth between my dac (which works just fine) and blackhole (which is choppy) , so I suspect it is this sam problem but somehow only appearing after a few hours of running and system wide...

**Comment by devinroth** [comment]
I have not fixed this yet.

The temporary fix was to use 16ch.

Devin

**Comment by devinroth** [comment]
This is a bit of a whack a mole. In order to fix this it breaks a different bug fix.

**Comment by onodera-punpun** [comment]
Seems like I'm actually getting the same issue with the 16ch version...

**Comment by devinroth** [comment]
Okay. I know how to fix this. It’ll be on the next release.

Devin

**Comment by mohshaat1990** [comment]
I have the same issue in Mac mini M1 . any update about the fix of this issue ?

**Comment by devinroth** [comment]
The issue is BlackHole.c line 3938. 
```
ringBuffer[((mSampleTime+frame+8192)%kDevice_RingBufferSize)*NUMBER_OF_CHANNELS+channel] = 0;
```
Comment out that line and it should work. It's a bit of a whack-a-mole issue since that was put there to fix another bug. Now I'm trying to figure out how to fix both at the same time.

**Comment by devinroth** [comment]
This is fixed. v0.4.0.
