### ISSUE TITLE
Recorded sound distorts after 20-30 minutes

### ISSUE THREAD

**Issue by Clifford-Yen** [ExistentialAudio/BlackHole#274]
Dear developer,

I recently migrated from my old MacBook Pro 2014 13" (Mojave, BlackHole v0.2.7 installed) to the new MacBook Air M1 model (Big Sur). Although both v0.2.7 and v0.2.8 work on the MacBook Air, both suffer from the sound distortion issue.

This is how I set up the recording session:
1. Plug the headphones
2. Switch the sound output to the Multi-Output device (which is set up in the Audio MIDI Setup. Picked External Headphones and BlackHole 2ch. The sampling rate is 44.1kHz.)
3. Record the whole screen with QuickTime Player, and select BlackHole 2ch as the Microphone.

All the sounds that go through the external headphones will be normal. However, when I check the recording, I found that some noises will appear around 20 to 30 minutes, and it will be louder and louder after that to the extent that it's inaudible. Then the interesting part is, the overall sound volume will be smaller and smaller gradually until it's totally silent like it's faded out.

I tried to set the output directly to BlackHole 2ch, and it's the same. I also tried to tick the drift correction for BlackHole 2ch, it's the same (and the sound quality after the noise appears is even worse).

Any suggestion, or it's a bug? Thank you.

**Comment by devinroth** [comment]
Known issue related to Multi-outputs. There's a number of threads on this including an entry on the FAQ. 

https://github.com/ExistentialAudio/BlackHole#why-does-multi-outputs-crash-every-20-minutes-on-apple-silicon

**Comment by Clifford-Yen** [comment]
Ah, sorry I didn't notice that. I will look further into it. Thank you.

**Comment by Clifford-Yen** [comment]
Update for anyone who are also suffering from this issue:

So I take a look at some threads, and I found that if I uninstall v0.2.8 completely and reboot, then install v0.2.7 (yes, the version that is not optimized for M1), this issue goes away. Have no idea why.
