### ISSUE TITLE
BlackHole not showing up in Audio Midi Set Up

### ISSUE THREAD

**Issue by alexsherman01** [ExistentialAudio/BlackHole#278]
Hey guys, I have the new macbook pro m1 2020 Big Sur, I downloaded BlackHole it said it installed successfully, I made sure all applications were closed during installation, but BlackHole still doesn't show under Audio Midi Set Up on the left sidebar. Can you guys help me resolve this please? 

Thank You

**Comment by devinroth** [comment]
Upload  me a screenshot of audio midi setup. And /Library/Audio/Plug-Ins/HAL/

Devin Roth

**Comment by alexsherman01** [comment]
<img width="552" alt="Screen Shot 2021-01-29 at 3 43 43 PM" src="https://user-images.githubusercontent.com/78204040/106338593-ff942b80-6248-11eb-9094-b5465ce324c9.png">
<img width="644" alt="Screen Shot 2021-01-29 at 3 44 06 PM" src="https://user-images.githubusercontent.com/78204040/106338628-15095580-6249-11eb-9c4b-27200a6bbc25.png">

**Comment by devinroth** [comment]
In Terminal type `ls -l /Library/Audio/Plug-Ins/HAL`
And also do `ls -l /Library/Audio/Plug-Ins/`

And let me know the results.

I assume you've already tried restarting.

**Comment by alexsherman01** [comment]
I've done what you suggested in Terminal and still nothing showing under Audio Midi Set Up, also restarted the computer and nothing.

**Comment by devinroth** [comment]
Oh sorry. I mean show me the results.

Devin Roth

**Comment by alexsherman01** [comment]
![Uploading Screen Shot 2021-01-30 at 2.16.50 PM.png…]()

**Comment by alexsherman01** [comment]
<img width="548" alt="Screen Shot 2021-01-30 at 2 16 50 PM" src="https://user-images.githubusercontent.com/78204040/106369422-092f9900-6306-11eb-9e8d-fc83cf5b3987.png">

**Comment by devinroth** [comment]
It doesn't look like it's even installed. 

On the BlackHole2ch.driver folder above right click and Get Info. Then tell me what it says under "Where". 

And in Terminal type `ls -l /Volumes` and show me the results.

Then try just reinstalling.

**Comment by alexsherman01** [comment]
<img width="250" alt="Screen Shot 2021-01-30 at 3 06 29 PM" src="https://user-images.githubusercontent.com/78204040/106370231-ece32a80-630c-11eb-8226-7b778302562e.png">
<img width="497" alt="Screen Shot 2021-01-30 at 3 07 21 PM" src="https://user-images.githubusercontent.com/78204040/106370233-ee145780-630c-11eb-9b3b-900df6d4866e.png">

**Comment by alexsherman01** [comment]
I re-installed and restarted and it's the same nothing shows under midi audio set up

**Comment by alexsherman01** [comment]
I am using the new M1 13inch 2020 macbook pro btw which shouldn't be a problem as others have been able to install it successfully

**Comment by devinroth** [comment]
Yeah I’m a little stumped. Did you restart?

Devin Roth

**Comment by alexsherman01** [comment]
I have

**Comment by devinroth** [comment]
Try installing the 16ch version. See if that works.

**Comment by alexsherman01** [comment]
I did that before out of curiosity and it's the same, I wonder if there certain settings that need to be adjusted in the computer or if it could be a result of a glitch with my operating system?

**Comment by devinroth** [comment]
I can dig deeper into this but it might take a long time to figure out. Are you game?

Devin Roth

**Comment by alexsherman01** [comment]
Well I have an absolute need to use this as this is my replacement for Soundflower, if you are game to help me out I'm more than game to find a solution, thank you
 By long time you mean months? Weeks?

**Comment by devinroth** [comment]
I don't know how long.  But let's go.

**Comment by devinroth** [comment]
First step, remove BlackHole from the HAL folder and restart core audio. `sudo launchctl kickstart -kp system/com.apple.audio.coreaudiod`

Then we're going to try installing Apple's NullAudio.driver which does nothing just to see if that works. I'll attach a zip for you. Unzip and move it to the HAL folder and restart core audio again as above. 
[NullAudio.driver.zip](https://github.com/ExistentialAudio/BlackHole/files/5898969/NullAudio.driver.zip)

**Comment by devinroth** [comment]
Check audio midi setup again after. Let me know the results.

**Comment by alexsherman01** [comment]
nothing new shows under audio midi set up but I don't know if this is right after I put in that text in terminal I got this
<img width="572" alt="Screen Shot 2021-01-30 at 4 05 47 PM" src="https://user-images.githubusercontent.com/78204040/106371105-77c82300-6315-11eb-9122-39530c12b241.png">

**Comment by devinroth** [comment]
Enter your password (you won’t see anything) and press enter.

Devin Roth

**Comment by alexsherman01** [comment]
nothing new in audio midi set up

**Comment by devinroth** [comment]
Type "system_profiler SPAudioDataType” in Terminal and show me the results. Also check Security and Privacy -> General. Make sure it has Allow apps from App Store and identified developers.

Devin Roth

**Comment by alexsherman01** [comment]
security and privacy is correct with allow apps from app store and developers checked
<img width="572" alt="Screen Shot 2021-01-30 at 4 31 53 PM" src="https://user-images.githubusercontent.com/78204040/106371400-c7f4b480-6318-11eb-9a4c-c7854fb2be1c.png">

**Comment by alexsherman01** [comment]
what should I do next?

**Comment by devinroth** [comment]
Did you check the security and privacy settings?

Devin Roth

**Comment by devinroth** [comment]
I have a thought. Let's try some other audio drivers. See if those work. I think this is a issue specific to BlackHole from the NullAudio test.

**Comment by alexsherman01** [comment]
Yes I have checked the security and privacy settings and it's checked to allow outside apple developed apps. What other audio drivers are you referring to?

**Comment by alexsherman01** [comment]
Good news, after installing the new Big Sur update, BlackHole now appears in Audio Midi Set up, thanks for your time and help

**Comment by devinroth** [comment]
Great! I don’t have a clue what the issue was. If someone else has issues I’ll tell them to update.

Devin Roth

**Comment by mattahorton** [comment]
> I have a thought. Let's try some other audio drivers. See if those work. I think this is a issue specific to BlackHole from the NullAudio test.

I know this issue is dead, Devin, but I'm building my own driver atm and having this exact issue. What was your hunch here?

**Comment by devinroth** [comment]
No idea. Never figured this one out.

Devin Roth

**Comment by deevannaveed** [comment]
This is also happening to me, I am building the BlackHole locally and I am able to generate the .pkg installer but when I install it, I cannot see the new driver listed in the sound output devices. I am not sure if its because the notarization step was failed for me, but in the `Plug-Ins/HAL` folder I can see the new driver after installation.
I tried to restart the coreaudio and it did not help.
I am on macOS Monterey which I think should be fine because when I install from the installer provided by the BlackHole it works.

**Comment by devinroth** [comment]
Could be you didn’t sign the driver.

Devin
