### ISSUE TITLE
Audacity 2.3.2.

### ISSUE THREAD

**Issue by bmb80** [ExistentialAudio/BlackHole#28]
I cannot get the audio from BlackHole into Audacity. I followed all instruction and selected BlackHole as the recording device but no audio is entered. Any suggestions?

**Comment by devinroth** [comment]
Did you check this already?

https://github.com/ExistentialAudio/BlackHole/wiki/Audacity#troubleshooting

**Comment by bmb80** [comment]
Yes I have already checked this

**Comment by devinroth** [comment]
Okay explain your setup, OS and give screenshots. I'll see what I can do to help.

**Comment by bmb80** [comment]
OS Catalina 10.15.5

[image: Screen Shot 2019-11-16 at 2.10.07 PM.png]
[image: Screen Shot 2019-11-16 at 2.10.14 PM.png]
[image: Screen Shot 2019-11-16 at 2.09.27 PM.png]
   As stated earlier the Audacity version is 2.3.2.
Prior to the upgrade to MacOS Catalina I was using SoundFlowerBed, however
with the upgrade Soundflower is not working. I am now looking for an
alternative.

**Comment by devinroth** [comment]
That’s your problem. Audacity isn’t supported on Catalina.

**Comment by devinroth** [comment]
https://www.audacityteam.org/macos-10-15-catalina-is-not-yet-supported-by-audacity/

**Comment by bmb80** [comment]
OMG. What a mess this upgrade has had on my life. Can you recommend a
replacement DAW for Audacity?

**Comment by devinroth** [comment]
I not free but Cubase is Catalina compatible. I use Cubase. Not sure about open source stuff. Sorry. I think there is a website that lists all the daws that are compatible with Catalina. Best of luck on your search.

**Comment by bmb80** [comment]
Something interesting. I am using a trail version of LOOPBACK. It IS
working with Audacity in MacOS Catalina. GO FIGURE???

**Comment by devinroth** [comment]
Interesting. Then maybe you just have it setup wrong. 

Is BlackHole working with other daws on Catalina? Does it work with screen record?

**Comment by bmb80** [comment]
Not familiar with Screen Record, is that Screencast? Can you think of
another way to test if BlackHole is configured properly?

**Comment by devinroth** [comment]
You need to know this trick. macOS built-in screen record is awesome.

Press command + shift + 5. 

Select Record entire screen
Under options select BlackHole. Make sure BlackHole is set as default output. And record a video or something with audio. You wan’t hear it while it records.

After your are done. Change default device to your internal speakers and see if it worked.

**Comment by bmb80** [comment]
OK now we're getting somewhere. It works in that mode.
