### ISSUE TITLE
Strange noise after playing for few minutes 

### ISSUE THREAD

**Issue by alexshelkov** [ExistentialAudio/BlackHole#282]
Hello,

I have really strange problem. I am using Blackhole + Apple Au Lab (but I got same problem with Hosting AU) to use Apple Audio unit (AuEqBand in particular as a paramedic equaliser). Everything working normal from the start, but after few minutes of playback there is small noise appear, which become more and more audible during next few minutes and now all I can hear is mostly clean white noise. If I restart capture audio in Apple AU (or Hosing AU) everything come back to normal, but then 20 min later same problem. I tried different MIDI settings and Apple AU settings, but it not helping problem remain the same. 

Would appreciate any help. Thank you.

Hardware: MacBook Pro 16
MacOS version: MacOS Catalina 10.15.6
Blackhole version: 0.2.9

**Comment by devinroth** [comment]
Sounds like clock drifting. Make sure you have drift compensation on.

Devin Roth

**Comment by alexshelkov** [comment]
Thanks for reply. But I am not sure how I can do it. There is no setting for this in MIDI, should I create aggregate device and then use it? My goal is simple use Apple AU Lab as an equaliser and output music to my USB DAC (but noise problem persist even if I am using my MacBook speakers).

**Comment by devinroth** [comment]
Try with an aggregate and see how that goes.

Devin Roth

**Comment by alexshelkov** [comment]
So the aggregate device and drift compensation fixed the problem.
