### ISSUE TITLE
Aggregate microphone + BlackHole not working correctly

### ISSUE THREAD

**Issue by BuffMcBigHuge** [ExistentialAudio/BlackHole#283]
I have created an audio input source where I have merged my microphone and BlackHole 2ch as an input device. When I test it in system preferences, I see the mic input working as well as the audio output of my machine acting as input. All is well!

However, when I try and use this aggregate input device in any other software (Google Meet, Voice Memo, etc), it doesn't seem to function correctly, and oftentimes I get input device errors.

I am able to use my microphone and BlackHole separately in Twitch Studio, so it works fine there. Thank you for this awesome software!

**Comment by devinroth** [comment]
Some apps don’t correctly use Aggregates.

What you should be doing is use BlackHole2ch as the only input into these programs. Then you need to mix your Mic into BlackHole. There are a number of guides that I’ve written on the topic.
http://existential.audio/blackhole/support/

Devin Roth
