### ISSUE TITLE
Unable to Use Multi-Output Device for Sound Output

### ISSUE THREAD

**Issue by stevebanik** [ExistentialAudio/BlackHole#288]
Any idea what's causing me to not be able to "use this device for sound output?"  Running the latest version via brew.  

macOS Big Sur 11.2
Mac mini (M1, 2020)

<img width="647" alt="Screen Shot 2021-02-03 at 9 05 00 PM" src="https://user-images.githubusercontent.com/3835734/106839311-930f9700-6663-11eb-9af5-22104d927e50.png">

**Comment by devinroth** [comment]
The only times.I’ve seen this is if a device that disables it is on the top. Does creating a new one have the same problem?

Devin

**Comment by devinroth** [comment]
Or try changing the order of the devices.

**Comment by stevebanik** [comment]
Suddenly I'm able to select it.  I didn't have to change the order.  

I am not sure what changed.

There's an exclamation mark by one of the devices, not sure why that's there either, or what it means.

**Comment by devinroth** [comment]
exclamation mark? I don’t think I’ve ever seen that before. Could you upload a screenshot?

Devin

**Comment by stevebanik** [comment]
<img width="653" alt="Screen Shot 2021-02-05 at 8 45 44 PM" src="https://user-images.githubusercontent.com/3835734/107106813-21fee980-67f3-11eb-89f3-f69b86828ca9.png">

It's right up there by the UMC404HD.

**Comment by devinroth** [comment]
Oh that. It means the sound effects will be played out of that device.

Devin

**Comment by tduarte** [comment]
I'm having the same issue on the Apple M1 Mac mini, did you manage to get it working? I have the same Audio Interface as well.

**Comment by devinroth** [comment]
Try the beta version on the Apple Silicon thread.

I plan on pushing a new version that fixes this sometime this week.

Devin

**Comment by tduarte** [comment]
I actually managed to make it work using this selection in that exact order:

![image](https://user-images.githubusercontent.com/631208/108274325-986fe580-7129-11eb-93e0-c945316064fd.png)

**Comment by tduarte** [comment]
> Try the beta version on the Apple Silicon thread. I plan on pushing a new version that fixes this sometime this week. Devin
> […](#)
> On Feb 17, 2021, 1:11 PM -0800, Thiago Duarte ***@***.***>, wrote: I'm having the same issue on the Apple M1 Mac mini, did you manage to get it working? I have the same Audio Interface as well. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

But thank you very much, I will take a look at the Apple Silicon thread.
