### ISSUE TITLE
Significant cpu occupation after installation

### ISSUE THREAD

**Issue by gushiqi** [ExistentialAudio/BlackHole#291]
I'm using M1 Mac mini and installed blackhole-2ch: v0.2.9 through home brew.
When I run the game, the cpu usage of coreaudiod and Core Audio Driver(BlackHole2ch.driver) gets significant increase. I didn't set anything in Audio Midi Setup but it got this issue just after the installation completed:
<img width="756" alt="Screen Shot 2021-02-07 at 1 25 39 AM" src="https://user-images.githubusercontent.com/11550866/107138842-f2300e80-68e4-11eb-912d-813e6ebb9541.png">

And after I uninstalled the Blackhole, it went normal immediately:
<img width="756" alt="Screen Shot 2021-02-07 at 1 26 49 AM" src="https://user-images.githubusercontent.com/11550866/107138859-1be93580-68e5-11eb-9828-bb37ea770879.png">

But when I play some local video or music when the driver is installed, the cpu usage looks normal.

**Comment by devinroth** [comment]
So there are a few things I noticed.

1st off, it looks like it’s the intel version? Does that mean that I accidentally didn’t compile 0.2.9 for Apple Silicon? If so there is a beta version on the Apple Silicon thread. Give that a spin.

Wait, so you’re not even using BlackHole and it has a 47% cpu? Or are you using it for the game when you get those numbers?

Games will generally use the lowest buffer size for lowest latency which means higher CPU. Different audio drivers have different buffer size limits so this could be a factor.

And last but not least, it’s really really hard to compare cpu usage on the M1 chips. They don’t really mean what you think they mean. It’s not a 1-1 comparison. It largely depends on which core is being used. 47% on a power efficient core is not equal to 4% on a performance core. The M1 chip decides what to put where depending on numerous circumstances. I saw this a lot when doing testing. CPU would jump between 30% and 2% in my tests depending on which apps are being used.

Ultimately the real question is, are you experiencing any audio issues? If not, then everything is probably working normally. Strange I know.

Devin

**Comment by devinroth** [comment]
You should be able to see which cpus have the most usage by opening up the CPU usage history window.

Devin

**Comment by gushiqi** [comment]
Hi Devin,

I checked the driver and it looks like an intel version:
$ file BlackHole          
BlackHole: Mach-O 64-bit bundle x86_64

I was running the game but not using Blackhole and got those numbers.

It was using the performance core and the power consumption was much higher than I only ran the game.

I tried to use it in OBS and did't find audio issue at that time. But the high cpu usage made the game laggy. I'll try the native version.


> So there are a few things I noticed. 1st off, it looks like it’s the intel version? Does that mean that I accidentally didn’t compile 0.2.9 for Apple Silicon? If so there is a beta version on the Apple Silicon thread. Give that a spin. Wait, so you’re not even using BlackHole and it has a 47% cpu? Or are you using it for the game when you get those numbers? Games will generally use the lowest buffer size for lowest latency which means higher CPU. Different audio drivers have different buffer size limits so this could be a factor. And last but not least, it’s really really hard to compare cpu usage on the M1 chips. They don’t really mean what you think they mean. It’s not a 1-1 comparison. It largely depends on which core is being used. 47% on a power efficient core is not equal to 4% on a performance core. The M1 chip decides what to put where depending on numerous circumstances. I saw this a lot when doing testing. CPU would jump between 30% and 2% in my tests depending on which apps are being used. Ultimately the real question is, are you experiencing any audio issues? If not, then everything is probably working normally. Strange I know. Devin
> […](#)

**Comment by devinroth** [comment]
Let me know the results. And give me specific instructions on how you have it setup so I can reproduce.

Devin

**Comment by gushiqi** [comment]
Hi Devin,

The beta version(BlackHole2ch.v0.2.9-beta.pkg.zip) works good. The cpu usage goes back to normal. Thanks!


> Let me know the results. And give me specific instructions on how you have it setup so I can reproduce. Devin
> […](#)

**Comment by devinroth** [comment]
So it entirely has to do with it being Intel vs Apple Silicon build.

That was clearly my error and must have published the wrong build. Oh well I’ll fix it soon.

Devin

**Comment by Duarte475** [comment]
I ran into the same problem, I tried installing BlackHole using the website version and the brew version. Both installed the intel version

**Comment by devinroth** [comment]
Yup haven’t fixed it yet. Been a busy week. I won’t be able to until the weekend so follow the same fix.

Devin

**Comment by devinroth** [comment]
Fixed. I updated the installer.
