### ISSUE TITLE
16 channel is missing, only 2 channel installed

### ISSUE THREAD

**Issue by jmuheim** [ExistentialAudio/BlackHole#294]
I tried to follow a tutorial about how to set up QuickTime to record both system audio and microphone while screen recording.

I installed BlackHole, but I don't have a "16 channel" item available, only a "2 channel":

![image](https://user-images.githubusercontent.com/1814983/107583451-311ed680-6bfb-11eb-87b0-d7b6069090f3.png)

What's going on here? I'm on Mojave.

**Comment by devinroth** [comment]
16ch version is a separate installer. Just use the 2ch version.

Devin

**Comment by jmuheim** [comment]
Thank you!
