### ISSUE TITLE
Constantly needing to reinstall Blackhole

### ISSUE THREAD

**Issue by isca72** [ExistentialAudio/BlackHole#297]
Hi,

I am working on an M1 Mac mini with Big Sur. My sound is frequently dropping out. Completely. Changing preferences doesn't sort it. If I reinstall Blackhole, it's fine.

It seems to be POSSIBLY associated with Google Meet. I'm a teacher and am on Google Meet A LOT. And it always seems to be when I'm signed on to Meet that the sound drops out. But it drops out systemwide. It also doesn't CONSISTENTLY drop out.

Sorry, I know this is not an ideal bug report. I'll try to pay better attention to what's going on...

**Comment by devinroth** [comment]
Try the beta version from the Apple Silicon thread. I kind of goofed up on the latest release and working on fixing it.

**Comment by devinroth** [comment]
Fixed.
