### ISSUE TITLE
Won't install on Mavericks 10.9.5

### ISSUE THREAD

**Issue by andrewtoups** [ExistentialAudio/BlackHole#298]
When I try to install the 16 channel Blackhole on my mac, which is running Mavericks, the installation proceeds as normal but then after the installer message "Validating Packages", it fails and says "The Installation Failed - The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance."

I'm using a 2014 Macbook Pro with 2.4 GHz Intel Core i5 processor.

I wish I could provide more information.

**Comment by devinroth** [comment]
Try just restarting your computer. Sometimes the scripts fail.
