### ISSUE TITLE
Aggregate Output issue on Mojave-based Mac

### ISSUE THREAD

**Issue by ryohajika** [ExistentialAudio/BlackHole#3]
Thank you for this brilliant work on BlackHole development... looks super interesting.
I've tried BlackHole on Mojave-based MacBook Pro (2018 15inch 10.14.6). It works if it's single-channel BlackHole output->BlackHole input, but it doesn't work if I use composite output composed of BlackHole output and headphones or speakers output. Is there any method to compose an aggregate output device with BlackHole in Audio MIDI Setup app?

**Comment by devinroth** [comment]
If I understand you correctly you want to be able to output to BlackHole and your speakers at the same time. I do this by creating a Multi-Output Device in Audio Midi Setup. Once setup I set the output device to the new Multi-Output Device and now I can listen to the audio through my speakers and also capture the audio within my DAW. 

<img width="743" alt="Screen Shot 2019-10-15 at 10 13 30 PM" src="https://user-images.githubusercontent.com/13010961/66889956-143baa00-ef99-11e9-93c6-69730126f435.png">

**Comment by Hzikajr** [comment]
Yes you are right, and I did the same thing on Audio MIDI Setup, but it doesn't work. If I switch to the multi-output device and play any media, it stops to play automatically. I think the setting is as same as yours...

<img width="630" alt="Screen Shot 2019-10-16 at 20 04 42" src="https://user-images.githubusercontent.com/4526634/66895871-393f2400-f050-11e9-95d8-019b8d321197.png">

**Comment by devinroth** [comment]
I see you have Soundflower. Does it work normally with Soundflower? You can also try to set master device to BlackHole. Make sure you have the latest version of BlackHole. And try restarting your your computer. Let me know if any of those work.

**Comment by Hzikajr** [comment]
So the one with Soundflower works without any issue. I downloaded the BlackHole installer from the GitHub page which is the latest one...

**Comment by Hzikajr** [comment]
Should I uninstall Soundflower first to make BlackHole working?

**Comment by devinroth** [comment]
There shouldn’t be any conflicts with soundflower. And you restarted right?

Open console and search for coreaudio and see what errors are there when you try to use it.

**Comment by devinroth** [comment]
And I just want to check. BlackHole is working normally by itself right?

**Comment by devinroth** [comment]
I think I've been able to replicate the issue. I'm still not sure what's going on since I am having the same problems with the Apogee Quartet. I have no idea why try unselecting both all devices and then check the External Headphones first and then BlackHole. For some reason if BlackHole (or any other driver) is selected first the clock doesn't start. Let me know if that fixes the issue.

**Comment by opiyokach** [comment]
Did you manage to resolve this? I'm not able to monitor incoming audio when set up for recording with blackhole on logic pro. I'm using apogee duet as interface.

**Comment by devinroth** [comment]
As far as I can tell it’s an issue with Apple’s multi output. But I’ll look into it more.

**Comment by opiyokach** [comment]
thanks

**Comment by devinroth** [comment]
So I think you need to have the build-in output or input in the aggregate to work.

**Comment by devinroth** [comment]
I'm addressing this question with a wiki page.

**Comment by opiyokach** [comment]
Got it. Used the multi-output setup in wiki to be able to monitor audio in Logic while recording. 
Thanks

**Comment by Deano73** [comment]
I think I'm problems with MID set up on Mac similar to what has been discussed here. Basically my blackhole channel records monitoring and speaker output, which when played back on speakers is fine but on headphones you can hear the monitoring too?

**Comment by akshaygupta1311** [comment]
Hi Guys, I think I am able to solve this problem. 
I was also facing the same issue of pushing output to OBS using BlackHole and to my headphones at the same time using Mac.
Below is my Setup which solves my problem. Remove Aggregate Device Settting and Add only Multi Output Device.Let me know if it works.

![Screen Shot 2021-04-16 at 15 53 03](https://user-images.githubusercontent.com/43351926/115034868-43074900-9ecc-11eb-8913-e5a11cb3cd66.png)

**Comment by Deano73** [comment]
Hi

My issue is sound leaking from the headphones into the recording (I now use zoom to record my sets). I tried multi output device but couldn’t get it to play on the monitors in the studio at the same time so gave up. 

Playback is spoiled with cueing noise from the deck not playing! 

Regards

D
