### ISSUE TITLE
blackhole device not showing into Audio Midi

### ISSUE THREAD

**Issue by guillaumeldc** [ExistentialAudio/BlackHole#302]
Hi, 

So I read a previous thread #278 where someone at the same issue. 
He updated the system to latest Big Sur and Blackhole showed up. 
I followed the process but I still can't get to see BlackHole in the list of devices. (2ch and 16ch tested).

I tried to install with both brew and the installer but nothing solved the issue. 

I'm running Big Sur 11.2.1 (20D74) on M1 chip. 

Please let me know if there are steps I can take to try to resolve. 

Thanks!

![Screen Shot 2021-02-16 at 4 35 16 PM](https://user-images.githubusercontent.com/48495334/108124234-f4c4fd80-7074-11eb-857a-29eda47fc8f9.png)

**Comment by devinroth** [comment]
Try installing the beta version from the Apple Silicon Thread.

Devin Roth

**Comment by odev1952** [comment]
Hi Devin,
I followed the procedure to build on Xcode from v0.3.0 branch.
The build went fine, I however can't find the following folder:
/Library/Audio/Plug-Ins/HAL

Could you please advise?

Thanks!

**Comment by devinroth** [comment]
Don’t use 0.3.0 branch.

There’s a 0.2.9 beta installer you should use.

Devin Roth

**Comment by odev1952** [comment]
Thank you.
It works as expected
