### ISSUE TITLE
Is it possible to monitor audio input (hear what is coming from it)?

### ISSUE THREAD

**Issue by 40detectives** [ExistentialAudio/BlackHole#303]
I've been trying to setup an audio monitor to my line in (an external irig 2) or the built-in mic input from my MBP to no avail. If you're familiar with Windows, there you just active the check for "Listen to this device":
![imagen](https://user-images.githubusercontent.com/9024463/108188736-3787e380-7110-11eb-9fe1-d402ad79efe0.png)

Is it possible to configure an aggregated audio device with Blackhole able to do that?

**Comment by devinroth** [comment]
No. Not possible.

You need to use a daw.

Devin Roth
