### ISSUE TITLE
Unable to set input source volume

### ISSUE THREAD

**Issue by zhudongyong** [ExistentialAudio/BlackHole#305]
Unable to set input source volume

v0.2.9

**Comment by devinroth** [comment]
That’s because I removed it. You should be using the output volume.

Or give me a good reason to bring it back.

Devin Roth

**Comment by zhudongyong** [comment]
> Unable to set input source volume
> 
> v0.2.9

I set the output volume of Blackhole to 0.5, and the sound I heard is 0.5, which is normal, but the recorded volume is only about 0.25 times;
