### ISSUE TITLE
Target symbol in Audio MIDI

### ISSUE THREAD

**Issue by poyki** [ExistentialAudio/BlackHole#306]
Hi there...moving over to BlackHole from NDI. May seem dumb but all the walk through and set up for Mac have a black hole symbol in Audio Midi. Mine is a red target. Any ideas if this is causing issue between OBS and my multi out  device? Has it not been installed correctly? I have restarted my computer, deleted multiple times (manually) and re downloaded.

Any help would be great.

Basically the I am getting now sound into OBS
![Screenshot 2021-02-19 at 11 26 42](https://user-images.githubusercontent.com/79313012/108499104-bb270900-72a5-11eb-8d43-bebb4bdf903e.png)

**Comment by devinroth** [comment]
There was an error in linking the BlackHole icon in the latest release. Will fix it soon. But it doesn’t affect anything else.

Devin Roth

**Comment by devinroth** [comment]
Fixed icon in updated installer. Won't make a difference to your OBS issues. Create a discussion if you are still having problems.
