### ISSUE TITLE
Deinstaller doesn't work with the 128 channel version

### ISSUE THREAD

**Issue by Normandeau** [ExistentialAudio/BlackHole#308]
Just to let you know!

**Comment by devinroth** [comment]
You’re right. I’ll build one for the 128 ch version.

In the meantime you man manually remove it by  going to /Library/Audio/Plug-Ins/HAL/ and removing the driver. Then restart CoreAudio in terminal with “sudo launchctl kickstart -kp system/com.apple.audio.coreaudiod”.

https://github.com/ExistentialAudio/BlackHole/wiki/Uninstallation

Devin

**Comment by devinroth** [comment]
[BlackHole128chUninstaller.pkg.zip](https://github.com/ExistentialAudio/BlackHole/files/6019013/BlackHole128chUninstaller.pkg.zip)

Here use this. Let me know if you have any issues.
