### ISSUE TITLE
Cannot adjust volume (not multiple-output device)

### ISSUE THREAD

**Issue by saneef** [ExistentialAudio/BlackHole#31]
I cannot change the volume while using BlackHole. I'm not using it through multiple-out device like mentioned in #16.

Or, is it a limitation of BlackHole? 

I could change volume when using soundflower.

**Comment by devinroth** [comment]
Good point. I never actually implemented this. I meant to but forgot. It’s an easy fix. I’ll update that soon.

**Comment by devinroth** [comment]
Just pushed the changes. I'll draft a new release later.
