### ISSUE TITLE
Unable to set input volume

### ISSUE THREAD

**Issue by zhudongyong** [ExistentialAudio/BlackHole#312]
I set the output volume of Blackhole to 0.5, and the sound I heard is 0.5, which is normal, but the recorded volume is only about 0.25 times;

**Comment by devinroth** [comment]
How about at 1?

**Comment by zhudongyong** [comment]
the same

发自我的iPhone

> 在 2021年2月22日，上午10:47，Devin Roth <notifications@github.com> 写道：
> 
> ﻿
> How about at 1?

**Comment by devinroth** [comment]
Just ran some tests. Everything is working normally. The input volume at 1.0 creates an identical copy. With the volume at 0.5 aka -32.0 dB the audio is exactly -32.0 dB. 
<img width="677" alt="logic" src="https://user-images.githubusercontent.com/13010961/108682545-49b5a900-74a5-11eb-84fb-3066444d9025.png">
<img width="399" alt="audiomidi" src="https://user-images.githubusercontent.com/13010961/108682550-4b7f6c80-74a5-11eb-97d6-0841c5e47227.png">

**Comment by devinroth** [comment]
You must have volume set on whatever you are using to record.
