### ISSUE TITLE
SHA mismatch installing 0.2.9 through homebrew

### ISSUE THREAD

**Issue by thegreatape** [ExistentialAudio/BlackHole#313]
Hello! I've started getting this error when installing the latest version of blackhole via homebrew:

```
$ brew install blackhole-2ch

==> Downloading https://existential.audio/downloads/BlackHole2ch.v0.2.9.pkg
Already downloaded: /Users/thomas/Library/Caches/Homebrew/downloads/961bb8d7315e174ad2b1d52be186712744c8022c309c330222aef49c0b240406--BlackHole2ch.v0.2.9.pkg
Error: SHA256 mismatch
Expected: ae7a405afc224bf0f6df2f58f4826e77c2b51fcbaba11561ba0c63616858e432
  Actual: 34c7333a7502ad17f62019f10e7d477dbf644bfd7b6203b3f7fe0dd420df86b5
    File: /Users/thomas/Library/Caches/Homebrew/downloads/961bb8d7315e174ad2b1d52be186712744c8022c309c330222aef49c0b240406--BlackHole2ch.v0.2.9.pkg
To retry an incomplete download, remove the file above.
```

Does something homebrew-side need to be updated here?

**Comment by devinroth** [comment]
PR has already been submitted to Homebrew.

**Comment by geeheim** [comment]
I am facing the same issue, just with a slightly different checksum (Apple Silicon Machine)

Error: SHA256 mismatch
Expected: 9cd3ed37e7d3ed29074487ff40f4c3698b5c780372c9d27c928d4b5d04766ca4
  Actual: cb9d0488bcf403b028ada911c80fd43699b43227989ebc6b23dc4500adbfa0c2
    File: /Users/geert/Library/Caches/Homebrew/downloads/b30f0ac2e57a3fe1ae8628f23a645e5502bbf9447e1086dc8e9d35974cd99b63--BlackHole16ch.v0.2.9.pkg
To retry an incomplete download, remove the file above.

**Comment by devinroth** [comment]
https://github.com/Homebrew/homebrew-cask/pull/100244
https://github.com/Homebrew/homebrew-cask/pull/100243

**Comment by devinroth** [comment]
Merged.
