### ISSUE TITLE
No sound with MacBook Air M1

### ISSUE THREAD

**Issue by myershse** [ExistentialAudio/BlackHole#318]
I had successfully used Blackhole with my former MacBook Air 2019.  I recently upgraded to the MacBook Air M1, and now having a problem with no sound being recorded with Quicktime.  Also tried it with Spotify, and again no sound.  I have attached screenshots of my setup and looking for suggestions.  
<img width="692" alt="Screen Shot 2021-02-25 at 8 42 44 AM" src="https://user-images.githubusercontent.com/4411827/109170174-2bbaa380-7746-11eb-85af-79fb1faddb28.png">
<img width="665" alt="Screen Shot 2021-02-25 at 8 41 42 AM" src="https://user-images.githubusercontent.com/4411827/109170179-2c533a00-7746-11eb-899e-c130664c7108.png">
<img width="668" alt="Screen Shot 2021-02-25 at 8 41 30 AM" src="https://user-images.githubusercontent.com/4411827/109170182-2cebd080-7746-11eb-8412-27c951133abc.png">

**Comment by devinroth** [comment]
Check mic permissions.
