### ISSUE TITLE
Release v0.2.4 not working for me

### ISSUE THREAD

**Issue by saneef** [ExistentialAudio/BlackHole#32]
The latest release v0.2.4 is not working for me. I'm using macOS Catalina. Tried installing and restarting a couple of times. ;)

 The v0.2.3 release works though.

**Comment by devinroth** [comment]
Strange. I thought I tested it. I'll take a closer look.

**Comment by devinroth** [comment]
What exactly isn't working? Doesn't pass audio through? Does it show up in audio midi setup?

**Comment by devinroth** [comment]
This latest release allows you to control volume and mute. You can check to make sure the volume is up and the mute is off on both input and output in audio midi setup.

**Comment by saneef** [comment]
@devinroth you are right! The input volume was at zero.

<img width="631" alt="Screenshot 2019-11-29 at 10 22 54 PM" src="https://user-images.githubusercontent.com/81863/69882686-05b21380-12f7-11ea-9638-761d8180550e.png">

Didn't think of checking in Audio MIDI Setup. While I was using soundflower this input volume set to `0` never happened to me.

Thanks for pointing it out.

**Comment by devinroth** [comment]
I’ll take a look since it’s possible that it’s set to zero by default. That will cause all sorts of issues out of nothing.
