### ISSUE TITLE
Macbook pro quicktime screen recording choppy

### ISSUE THREAD

**Issue by celestialbyte** [ExistentialAudio/BlackHole#323]
Hello,

I've tried to setup quicktime so that it record only the internal audio. It works fine for the first hour or so, into the second hour the sound become very glitchy and choppy, and into the third hour, there's no more sound. Should I enable drift correction?

**Comment by celestialbyte** [comment]
<img width="640" alt="Screen Shot 2021-02-28 at 11 25 05 PM" src="https://user-images.githubusercontent.com/79822996/109451778-32823880-7a1c-11eb-9085-bcd0076428af.png">
<img width="644" alt="Screen Shot 2021-02-28 at 11 25 21 PM" src="https://user-images.githubusercontent.com/79822996/109451789-3ada7380-7a1c-11eb-9dc3-861dfdab0afa.png">

**Comment by devinroth** [comment]
Audio drift. Use drift correction.

Devin
