### ISSUE TITLE
Catalina microphone permission's

### ISSUE THREAD

**Issue by Holphana** [ExistentialAudio/BlackHole#33]
I cannot give permission to blackhole for microphone.

I noticed in the instructions: "check your privacy settings for microphone if it's not working" I am currently running the latest operating system and it has not asked me for permission nor is an option available. The program seems to take audio from the computer itself but does not pick up anything from my mic.

EDIT: yes I did restart the computer after installing.

**Comment by devinroth** [comment]
BlackHole doesn’t require permission. Only the app that uses BlackHole does. BlackHole also doesn’t take audio from your microphone. Setup an aggregate if you need both.
