### ISSUE TITLE
Using bluetooth headphones as my audio output

### ISSUE THREAD

**Issue by SameAyaya** [ExistentialAudio/BlackHole#331]
I hope this isn't a repeat question, I apologize if it is. I cannot get desktop audio(Discord) into my stream. I have followed the instructions but am wondering whether the issue could be that I'm picking the wrong output options. 

My setup is: Streamlabs; Bluetooth headphones to hear the audio (mix of game audio, discord); headphone jack microphone plugged into the computer; a mac laptop running Big Sur.
![Screenshot 2021-03-02 at 16 21 05](https://user-images.githubusercontent.com/60540034/109670348-5015e600-7b73-11eb-8c15-fed71f9eab3d.png)
(Blaster is the name of my bluetooth headphones and when connected they aren't greyed out so please just ignore that part)

I'd really, really appreciate any help! Thanks!

**Comment by devinroth** [comment]
As a test, does it work with BlackHole by itself?

Devin

**Comment by SameAyaya** [comment]
> As a test, does it work with BlackHole by itself? Devin
> […](#)

What exactly do you mean? And thanks for replying!

**Comment by devinroth** [comment]
Discord -> BlackHole -> Stream.

Devin

**Comment by SameAyaya** [comment]
If I understood correctly, I just opened the voice chat in discord to test audio input, connected discord output to BlackHole and opened streamlabs again but the audio indicator showed no input

**Comment by devinroth** [comment]
Does streamlabs have mic permission?

Devin

**Comment by SameAyaya** [comment]
Yes it does. I've been streaming and everything has worked so far, I simply can't get the desktop sound to run

**Comment by devinroth** [comment]
Send a screenshot of audio midi setup.

Devin

**Comment by SameAyaya** [comment]
![Screenshot 2021-03-02 at 17 40 25](https://user-images.githubusercontent.com/60540034/109682093-64131500-7b7e-11eb-913d-234462238d26.png)
![Screenshot 2021-03-02 at 17 40 09](https://user-images.githubusercontent.com/60540034/109682115-670e0580-7b7e-11eb-8b3d-bb725b7f286c.png)

**Comment by devinroth** [comment]
The whole thing.

Devin

**Comment by SameAyaya** [comment]
![Screenshot 2021-03-02 at 17 41 57](https://user-images.githubusercontent.com/60540034/109682333-9b81c180-7b7e-11eb-8c18-93dd75619847.png)
oops sorry. Is this right?

**Comment by devinroth** [comment]
Test
System output (play YouTube or something) -> Discord Multi-output
BlackHole -> Audacity

Devin

**Comment by SameAyaya** [comment]
That seemed to work
![Screenshot 2021-03-02 at 18 05 45](https://user-images.githubusercontent.com/60540034/109685818-efda7080-7b81-11eb-8d04-8976ae4f8338.png)

**Comment by devinroth** [comment]
And that doesn’t work with streamlabs?

Devin

**Comment by SameAyaya** [comment]
Yes now I'm getting audio input! So now what I need to solve is that I can actually hear the audio myself.

**Comment by devinroth** [comment]
Just add your headphones to the multi-output.

Devin

**Comment by SameAyaya** [comment]
Thanks so much, it's working now. You've really made my day (that might sound ridiculous but I struggled for such a long time to get this working). Anyway, thanks again!

**Comment by devinroth** [comment]
You’re welcome.

Please consider sponsoring.

Devin
