### ISSUE TITLE
Cannot change icon for AudioMIDI

### ISSUE THREAD

**Issue by IraNikolenko** [ExistentialAudio/BlackHole#333]
I saw the issue #198 https://github.com/ExistentialAudio/BlackHole/issues/198. I did everything as described in the last answer, but still the icon hasn't changed. Even when I remove the icon from the project, build it, move the driver folder to the HAL folder in Library folder, run the command to restart core audio, but the audioMidi displays a Blackhole with the old icon, that is, no effect from my actions. Please, help me..

**Comment by devinroth** [comment]
Probably using the wrong format for icns. Bundle ID needs to match. Just check the system logs and see what error you're getting.

**Comment by arafatshahed** [comment]
> Probably using the wrong format for icns. Bundle ID needs to match. Just check the system logs and see what error you're getting.

Icon not showing for blackhole in Audio MIDI. I build Blackhole after adding signing certificates from xcode and provided commands. Icon is not showing up. Tried restarting core audio. Icon shows if I use the blackhole installer.
