### ISSUE TITLE
Able to record audio from Youtube/streaming audio, but not Google Hangouts or FaceTime

### ISSUE THREAD

**Issue by JoeNoPhoto** [ExistentialAudio/BlackHole#34]
I'm trying to record the audio from a Google Hangout through Adobe Audition, but none of the input channels seem to be giving me anything. But, when I record audio from, say, YouTube, it records perfectly. I'm using a mic connected to a Scarlett 2i2 audio interface and the setup that I've gotten to work correctly is:

**Audio MIDI Setup**
Aggregate Device named **Scarlett & BlackHole**: 
![image](https://user-images.githubusercontent.com/6269501/70088089-69279400-15ca-11ea-933c-c6d73a432966.png)

**Multi-Output Device:**
![image](https://user-images.githubusercontent.com/6269501/70088011-45644e00-15ca-11ea-9a64-1e8fc0d827bc.png)

**Sound**
**Input:** 
![image](https://user-images.githubusercontent.com/6269501/70087950-1ea61780-15ca-11ea-9755-1dbb7c3f2cdc.png)

**Output:**
![image](https://user-images.githubusercontent.com/6269501/70089952-089a5600-15ce-11ea-8b11-77b16b841395.png)

**Audition Audio Hardware Settings**
![image](https://user-images.githubusercontent.com/6269501/70087915-08985700-15ca-11ea-801b-6671aedaf47d.png)

**Audition Tracks**
![image](https://user-images.githubusercontent.com/6269501/70087846-e1da2080-15c9-11ea-891b-c32d87031059.png)

That's a recording of both my mic and youtube playing at the same time. If instead of Youtube, I try to record the sound coming from either a Google Hangout or Facetime, the levels are completely flat and nothing records. 

I've also included Built-In Output in the agg and multi-out setups as per the wiki instructions, but I still get no audio recording regardless. 

The one thing that I found strange is the naming of the Scarlett Inputs in Audition. 
![image](https://user-images.githubusercontent.com/6269501/70089575-3cc14700-15cd-11ea-9643-5446ea8db718.png)

Its labeled as BlackHole 16ch Input 1 and 2? It doesn't affect anything with the youtube recording, and I've tried using the BlackHole inputs 3-16 but no sound goes in or comes out when I use them. I'm new to all of this so I'm not positive if I'm screwing up somewhere.

**Comment by JoeNoPhoto** [comment]
I just called my computer via FaceTime and recorded the audio. Audition was able to record the FaceTime ringtone and pick up tone but no other audio recorded after that. 

![image](https://user-images.githubusercontent.com/6269501/70091808-c83cd700-15d1-11ea-97b9-739e7a575e34.png)

**Comment by devinroth** [comment]
BlackHole is only going to grab system audio not audio from your mic. You’ll need to use a separate input from you scarlet for your mic.

**Comment by devinroth** [comment]
Use a multi output for your system audio. Use a aggregate into Audition. The system audio will be on the first BlackHole channel and your mic will be on whatever input from your interface.

**Comment by devinroth** [comment]
Did you figure it out?

**Comment by devinroth** [comment]
Closing to keep thing tidy. Let me know if you still haven’t figured it out.
