### ISSUE TITLE
BlackHole and iOS app on M1

### ISSUE THREAD

**Issue by EddaAkikusa** [ExistentialAudio/BlackHole#346]
Hello devs.
Thanks for your great job.
I'd like to stream an iPad game using OBS and BlackHole, but I noticed that BlackHole can only capture the sound from Mac apps.
When I pause the **Mac** music player.
<img width="968" alt="1" src="https://user-images.githubusercontent.com/4312700/111405629-cbe36700-870b-11eb-8584-0be0ef2524b9.png">
When I resume the **Mac** music player.
<img width="968" alt="2" src="https://user-images.githubusercontent.com/4312700/111405884-35637580-870c-11eb-94f9-4d024cbb2b5d.png">

**Comment by devinroth** [comment]
How are you playing the game? What is your audio output?

Devin

**Comment by EddaAkikusa** [comment]
I don't know the audio output used exactly in the iOS App...

**Comment by devinroth** [comment]
You’ll have to tell me exactly how you have everything setup.

Devin

**Comment by EddaAkikusa** [comment]
I just install the Genshin Impact following [this guide](https://www.reddit.com/r/macgaming/comments/lc234r/running_genshin_impact_on_an_apple_silicon_m1_mac/)
And setup BlackHole 0.2.9 as below.
<img width="763" alt="0" src="https://user-images.githubusercontent.com/4312700/111413559-6b5b2680-8719-11eb-8b3c-fb0412831079.png">
`多输出设备` means `Multi-Output Device`, `外置耳机` is my external headphone.

**Comment by devinroth** [comment]
Some apps don’t work with multi outputs. Try just using BlackHole by itself.

Devin

**Comment by EddaAkikusa** [comment]
Oh it works.
Thanks.

**Comment by jjrolk** [comment]
I am experiencing the same issue, failing to capture audio from an iPad application running on a M1 Macbook Pro. Selecting Blackhole as the sound output allows me to capture the app audio in OBS, but I'm no longer able to hear the game audio on my speakers.

The Multi-Output option records some desktop audio (e.g., videos playing in Chrome), but does not capture the iPad game's audio although I'm able to hear both through the speakers.

Is there an option to still be able to hear the audio on my speakers?

**Comment by devinroth** [comment]
Doesn’t OBS have an option to monitor the audio?

Devin

**Comment by jjrolk** [comment]
Yes, OBS does have audio monitor. Thank you for the response and apologies for my delay. I am able stream (and hear) game sound by setting my mac sound output to BlackHole 2ch and the OBS source set to audio monitor and output.
