### ISSUE TITLE
Where is BlackHole.h ?...

### ISSUE THREAD

**Issue by GGBoCa** [ExistentialAudio/BlackHole#35]
Hey,

I'm really sorry to ask a question like this... I would like to increase the number of channel, possibly to 128 for my needs, and looks so simple in FAQ.

BlackHole.h is a file hide somewhere on my computer ? Or...

Thanks anyway !
GG

**Comment by devinroth** [comment]
https://github.com/ExistentialAudio/BlackHole/blob/master/BlackHole/BlackHole.h

**Comment by devinroth** [comment]
You need to be familiar with programming if you want to make the changes. I added a short guide https://github.com/ExistentialAudio/BlackHole/wiki#advanced-customization.

**Comment by GGBoCa** [comment]
Hey, 
I finally download XCode. I don't understand why it was so long. Hours even on the official AppStore and on a wired university network. Anyway.

Finally so simple. Thank you so much for the guide. Maybe it could be easy for programmers but if your not familiar with IDE it could be a little bit long.

I will make some tests with 128 channels and I'll tell you whats happened. In 2020, there is a huge lack in the domain of internal audio routing (I know you know). As a pro, I still use OSXJack, wish is great but so old. Dante via is limited. Sound flower isn't great. So if your stuff work, you'll have great perspectives !

It's not the last time I talk to you.

Thanks for your work.
GG

**Comment by devinroth** [comment]
Awesome. Let me know how it goes!
