### ISSUE TITLE
Cannot capture zoom meetings audio

### ISSUE THREAD

**Issue by jpogs02** [ExistentialAudio/BlackHole#351]
Hello,

I just want to reach out for this problem that I experienced.

I cannot capture zoom meetings audio through OBS. But with other softwares like google chrome and spotify while playing them the audio levels on OBS starts to Grab the audios

Is there any solution to this?

Thanks

Im running a new macbook pro 2019 16inch
and With BigSur

**Comment by devinroth** [comment]
Are you using an multi output? If so, does it work just BlackHole?

Devin Roth

**Comment by jpogs02** [comment]
Hi devin,

Yes i used Multi output. Im using windows capture on obs. when using other programs like chrome and spotify the program does work with peeking audio. But when i use  zoom meetings i cannot see peeking audio on the OBS.

**Comment by devinroth** [comment]
Try without the multi output and report back.

Devin Roth

**Comment by nucatus** [comment]
Using the latest version, 0.2.9, I was not able to route the zoom audio through and record it with QuickTime. Although the setup perfectly worked to record youtube videos, for instance, recording a zoom screen cast didn't pick up the sound input.

I tried this with both multi output and single output setups. In the case of a multi output setup, I attach two photos of the configuration.
![Screenshot 2021-04-22 at 19 53 10](https://user-images.githubusercontent.com/5102852/115763081-6cc8e000-a3a4-11eb-99b2-c70297784d2a.png)
![Screenshot 2021-04-22 at 19 53 01](https://user-images.githubusercontent.com/5102852/115763083-6d617680-a3a4-11eb-970a-f904663314e4.png)


I'm using the 16ch version of the application, v0.2.9 on OSX BigSur 11.2.3 and zoom version 6.5.3

**Comment by nucatus** [comment]
@devinroth, I just wanted to ask if this is a known issue or is it just a bad setup. Did anybody else encounter this issue? Are there any other ways to setup blackhole so that this issue is mitigated?

Thank you!

**Comment by devinroth** [comment]
You need drift correction enabled.

Devin Roth
