### ISSUE TITLE
BlackHole + Google meet + Google Chrome + Mac

### ISSUE THREAD

**Issue by AnnaSmrz** [ExistentialAudio/BlackHole#355]
Hello, I would like to ask.. so I've recently installed BlackHole on my mac and I try to record google meet with internal sound - /on the video/ everything is ok for the first 10 minutes, after that time, the voice of the presenter starts to sound a bit odd, like a bad radio signal, it's worse and worse until its stops completely and I can't hear anything. The same scenario happened to me with more than a month-long interval, so it looks like a system problem. (YT, zoom app, or anything else works perfectly - the setting is ok) 
Any suggestions? 
Thanks a lot.

**Comment by devinroth** [comment]
Enable drift correction.

Devin Roth

**Comment by ronkorving** [comment]
Lately, half the time I open Google Meet, all my audio devices disappear.
I don't know for sure if this is related to BlackHole. It *definitely* seems related to Google Meet on Chrome.
If this sounds familiar, I wonder if this is related.

**Comment by devinroth** [comment]
Could you posts the system logs related to blackHole from Console?

Devin Roth

**Comment by orchetect** [comment]
Stale issue - closing.
