### ISSUE TITLE
Audio all the way down.

### ISSUE THREAD

**Issue by OreoCenturion45** [ExistentialAudio/BlackHole#359]
When I go into Audio-Midi setup for blackhole 16ch, the master input is turned all the way down. I cannot adjust the input volume or drag the sliders. I am using Blackhole to record computer audio for YouTube videos.

**Comment by devinroth** [comment]
Because the master input volume is disabled by design. Just use the output volume.

Devin Roth

**Comment by OreoCenturion45** [comment]
what does this mean, it still doesnt work.

**Comment by devinroth** [comment]
It means you’re doing something wrong and has nothing to do with input volume.

Devin Roth
