### ISSUE TITLE
Possible system badness from Blackhole

### ISSUE THREAD

**Issue by jamesb93** [ExistentialAudio/BlackHole#36]
Hi Blackhole team,

Since installing blackhole (among other programs to be fair), I have had some system wide crashes where all applications shut down and my computer almost goes into total lock down where I cannot restart/shutdown manually but have to resort to `sudo reboot`. 

I have been monitoring the issue for a while and found two crash logs which coincide time-wise with this crash event happening.

The logs are attached here:

[crash1.txt](https://github.com/ExistentialAudio/BlackHole/files/3939911/crash1.txt)
[crash2.txt](https://github.com/ExistentialAudio/BlackHole/files/3939912/crash2.txt)

It is entirely possible blackhole has nothing to do with this, but the crashes appear after the phase in which I moved from JACK to Blackhole and not before. Also, there is nothing else in my logs I can find related to the crash.

Would someone be able to have a look at this and investigate the possibility that Blackhole is doing something unintended?

**Comment by devinroth** [comment]
Thanks for the report. Since BlackHole runs entirely in the user space worst case it should only reboot coreaudio. I definitely have crashed coreaudio many times in development but none have led to a system wide crash so I am surprised by this. 

Are you using an aggregate device? Explain how you are using BlackHole and how you have it setup. 

Devin

**Comment by jamesb93** [comment]
Hi Devin,

I was using Blackhole as an aggregate device with a number of sound cards as each room I use at my institution has a slightly different device. In general it would be some card + blackhole, although one aggregate device was Built in Audio + Blackhole. I also had Drift Correction enabled for all devices involved whatever the aggregate device was (perhaps this was a misinformed choice).

My main use scenario was piping REAPER output into Max and then Max out of the sound card. Effectively making Max an expensive VST/FX.

**Comment by devinroth** [comment]
Thanks. I’ll look deeper into this. Seems like it is related to an aggregate device. I’ve been having issues with those. 

Make sure you update to the latest version of BlackHole too.

**Comment by jamesb93** [comment]
Yep, I use `brew` as my package manager and it was a minor version behind. Right now I need stability so I'm JACK (unfortunately) but once the aggregate device aspect matures I'll be sure to come home to Blackhole ;)

**Comment by devinroth** [comment]
Unfortunately I don’t have the ability to fix the aggregate device problem since that’s fully a macOS problem. I completely understand why people don’t recommend using aggregates. My solution going forward is to replace the need for aggregates all together. Development is really a matter of time unfortunately. 

Devin

**Comment by jamesb93** [comment]
Yes I suppose JACK does solve those kinds of issues by having its own inter-application routing built in. One day? Feature request if not? :)

**Comment by devinroth** [comment]
I’ll add it to the feature requests. 

Devin

**Comment by devinroth** [comment]
Could you do me a favor and send me a screenshot of audio midi setup? Also do you happen to know exactly which aggregate device you were using?

**Comment by jamesb93** [comment]
I've gotten rid of it now actually but I'll briefly re-create it for you.

<img width="735" alt="Screen Shot 2019-12-09 at 19 12 33" src="https://user-images.githubusercontent.com/13281862/70465012-f16cd400-1ab7-11ea-8f79-383b04dca657.png">

Pretty much where built-in is could be substituted by some sound card too. Drift Correction applied similarly across different aggregates.

**Comment by devinroth** [comment]
Yeah got it. But do you remember which device you were using when the system crashed? BlackHole and what?

**Comment by jamesb93** [comment]
Actually, it must’ve been my Built-in + Blackhole.

**Comment by devinroth** [comment]
I think I may be on to something. In both cases the crash happened after returning from sleep. It seems to be a common problem with audio drivers. 

Apogee suggests turning off automatic sleep mode. 
https://knowledgebase.apogeedigital.com/category/duet-2-usb/troubleshooting-duet-2-usb/

https://www.sweetwater.com/sweetcare/articles/resolving-audio-interface-issues-on-mac/

It looks like the issue and can be solved by disabling automatic sleep mode on your end. 

On my end I think there is a way for me to disable automatic sleep while the driver is running. I may have it set already and it's possible that the aggregate device overrides BlackHole driver preferences.

**Comment by jamesb93** [comment]
Ah this sounds like it might be the issue. Is there a way you can make an aggregate device force sleep off? Or perhaps something more low level like a persistent systemd service that I can run?

**Comment by arvidtp** [comment]
Amphetamine is a free menu bar app that will keep your mac awake.

**Comment by devinroth** [comment]
@jamesb93 my fix to #54 might also fix this.

**Comment by jamesb93** [comment]
I believe this has fixed it... I don't have the same problem anymore.
