### ISSUE TITLE
Failed to create AV capture input device: Cannot use BlackHole 2ch

### ISSUE THREAD

**Issue by pratikbs** [ExistentialAudio/BlackHole#363]
FFmpeg fails to record due to the following error: 
`Failed to create AV capture input device: Cannot use BlackHole 2ch`

Full ffmpeg stack trace
`ffmpeg version N-73633-g07ae8fa-tessus Copyright (c) 2000-2015 the FFmpeg developers
  built with Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --as=yasm --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzmq --enable-version3 --disable-ffplay --disable-indev=qtkit --disable-indev=x11grab_xcb
  libavutil      54. 28.100 / 54. 28.100
  libavcodec     56. 46.102 / 56. 46.102
  libavformat    56. 40.100 / 56. 40.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 21.100 /  5. 21.100
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100
[avfoundation @ 0x7fadb4008a00] Selected pixel format (yuv420p) is not supported by the input device.
[avfoundation @ 0x7fadb4008a00] Supported pixel formats:
[avfoundation @ 0x7fadb4008a00]   uyvy422
[avfoundation @ 0x7fadb4008a00]   yuyv422
[avfoundation @ 0x7fadb4008a00]   nv12
[avfoundation @ 0x7fadb4008a00]   0rgb
[avfoundation @ 0x7fadb4008a00]   bgr0
[avfoundation @ 0x7fadb4008a00] Overriding selected pixel format to use uyvy422 instead.
[avfoundation @ 0x7fadb4008a00] Failed to create AV capture input device: Cannot use BlackHole 2ch`

**Comment by devinroth** [comment]
You need to add your code.
> But the problem is probably related to this

> “Selected pixel format (yuv420p) is not supported by the input device.
Make sure you read your error messages.
