### ISSUE TITLE
If I install BlackHole, Siri does not longer work with internal microphone (Catalina 10.15.7)

### ISSUE THREAD

**Issue by mexbeb** [ExistentialAudio/BlackHole#364]
Hello, I installed BlackHole (2ch+16ch) some months ago and I noticed only these days that Siri was not working with the built-in microphone, but only when using bluetooth headset or an external soundcard. Today I tried to uninstall both versions of BlackHole and Siri worked again with the built-in mic. 
It's not that I didn't put the built-in as default mic, I put it and still didn't work. I think that's a problem related to Blackhole.

**Comment by devinroth** [comment]
Doesn’t seem related but I’ll check it out.

**Comment by camner** [comment]
FWIW, this isn't the only "sound capture" kext that has this symptom.  I use Screencast-o-matic to make educational videos, and they have a "capture computer audio" kext that, well, captures computer audio (so it can become part of a screen capture video).  The iMac's behavior is the same: with their kext installed (it doesn't even have to be set up in Audio Midi Setup), audio muting doesn't occur on the internal speakers or external headphones.  Just as with BlackHole, uninstalling followed by a restart fixes things.

I don't know that this means that the behavior is inherent in sound capture kexts, but...

**Comment by devinroth** [comment]
Going to close. Reopen if you continue to have issues.
