### ISSUE TITLE
Does not seem to work with rack+garage band

### ISSUE THREAD

**Issue by Euphorbium** [ExistentialAudio/BlackHole#37]
I've installed it through brew. In rack I choose it as an output, and in garage band I add a new audio track and choose the first channel of black hole as an input. The output of the garage band is set as a multi output device which is made of default output and black hole. When I press record in garage band, I can not hear anything and neither does it record anything. Monitoring in garage band is turned on. What am I missing? 
macOS Catalina

**Comment by devinroth** [comment]
Be careful when monitoring when you have BlackHole set as an input and an output. You will create a feedback loop. 

First check to make sure Garage Band has microphone access.
https://github.com/ExistentialAudio/BlackHole#why-is-nothing-is-playing-through-blackhole

**Comment by Euphorbium** [comment]
Garage band does have microphone access, I can record from inbuilt microphone. It does not matter how I set up monitoring (on or off, with multioutput device or without) it still is receiving nothing, when I choose blackhole as the input device.

**Comment by devinroth** [comment]
What version are you using?

Check audio midi setup to see what the volume is set as on the input and output.

**Comment by Euphorbium** [comment]
This is it, for some reason by default black hole output was turned all the way down in the midi setup.

**Comment by devinroth** [comment]
I fixed that in the latest version.
