### ISSUE TITLE
Distortion in Jamulus sound with BlackHole

### ISSUE THREAD

**Issue by chrisrimple** [ExistentialAudio/BlackHole#381]
I've emailed this to @devinroth as well, but adding a bit more detail here...

THANK YOU for BlackHole.  I’ve been using it for some time, and for the last 6 months or so to route sound:

Audio Interface (keyboards/mic) > MainStage > BlackHole > Jamulus > Audio Interface (headphones)

For the last couple months, I’ve been experiencing intermittent “scratchiness” in the sound.  I believe that I’ve isolated the issue to BlackHole – if I replace it in the routing above with Loopback (demo), the problems disappear.

The settings that I’m using in Jamulus are:

Device = in:BlackHole/out:Audio Interface
Input L = channel 1
Input R = channel 2
Output L = channel 5
Output R = channel 6

MainStage outputs to BlackHole channels 1-2, so they’re the input to Jamulus.  Sound returned from the Jamulus server outputs to Audio Interface channels 5-6, which are the headphone jack.

What’s most interesting is that it’s usually the Jamulus server sound that is distorted – other musicians tell me that they’re continuing to get good sound from me even when my/their sound comes back “bad” from the server.  This leads me to believe that something about BlackHole is causing problems for the Jamulus client or CoreAudio.

2015 MBP 16GB 1TB SSD MacOS 10.14.6 Mojave
MainStage 3.4.4 (latest)
Jamulus 3.7.0 (latest)
Jamulus Server 3.7.0 (latest)
BlackHole 16ch v0.2.9 (latest)

**Comment by chrisrimple** [comment]
@devinroth has responded that Jamulus is likely missing drift correction, so I've logged [an issue to the Jamulus github issues list](https://github.com/jamulussoftware/jamulus/issues/1598).

**Comment by devinroth** [comment]
Well it might be a combination of things.

Devin Roth

**Comment by softins** [comment]
I think we need a bit more information:
1. What exactly is drift correction, and how should it be provided?
2. Why/how does Loopback appear to avoid the problem, when Blackhole doesn’t?

**Comment by chrisrimple** [comment]
@softins Here's a few links to information on drift correction...

https://support.apple.com/guide/audio-midi-setup/set-aggregate-device-settings-ams094c7edb4/mac

https://apple.stackexchange.com/questions/59390/what-is-sound-drift-correction-on-os-x-and-how-should-i-use-it

FWIW, I'm unclear why drift correction would be a factor, since the sound coming from the Jamulus Server, which is not routed through BlackHole, shouldn't need to be synced with other audio source/hardware device clocks or timing.

**Comment by j-rahman** [comment]
The same happens for me in OBS Studio. After about an hour or so of recording on my mac with appropriate drift correction settings applied, the scratchiness begins to kick in and gets really worse from that point on. Can't fix that in post-processing! I used to use the soundflower kext before I installed the "more modern" BH kext; and there I did not seem to have this distortion problem. Hoping that it would get fixed soon! 👍🏼

**Comment by gilgongo** [comment]
This comment (and the fact that @softins question to the author has so far got no answer) implies the problem may not be due to Jamulus: https://github.com/ExistentialAudio/BlackHole/issues/381#issuecomment-859358548

**Comment by chrisrimple** [comment]
After doing a bunch of experiments, the problem seems to be related to CPU utilization.  There are times when MainStage pegs the CPU above 100% - it's during those moments that I'm experiencing scratchiness.  I've solved this by ensuring that I'm using MainStage only in Perform mode when on Jamulus, which keeps CPU utilization below 40%.

@j-rahman You might look at CPU utilization with OBS - perhaps the load is so high that drift (or some other issue related to CPU load) is causing the scratchiness.

It's unclear to me that this is a BlackHole problem, given my test results, so I'm closing this issue.
