### ISSUE TITLE
Possible to get 16 bit audio depth rather than 32 on M1 Mac?

### ISSUE THREAD

**Issue by ridarf** [ExistentialAudio/BlackHole#382]
It seems like no virtual cables or audio software has less than 32 bits on the new M1 Macs, but it's a requirement for my current setup. Is there any way to get a 16-bit audio interface on my device using BlackHole?

**Comment by ridarf** [comment]
For the sake of transparency, I have Voicemeeter running on a laptop using VBAN to output to VBAN Receptor on my Mac, which allows me to select an output. If I select BlackHole as my VBAN receiver output, and then use BlackHole as an input elsewhere the sound is very choppy & glitchy. Especially over time. 

The original Voicemeeter output to the VBAN receiver is PCM 16 bits at a 48000Hz sample rate with 2 channels. Outputting to a 2 channel, 48000Hz 16 bits headphone works perfectly fine, but then using any 32 bit outputs with otherwise similar specifications gives choppy, glitchy audio.

**Comment by devinroth** [comment]
Here’s the reason. With 32bit float there is no loss of resolution for 24bit and 16bit audio. And   macOS audio system is only 32bit float. Everything is converted to 32bit float even if it says 16bit etc. I could in theory create a virtual input that says 16 bit but behind the scenes it would still be 32 big float.

Devin Roth

**Comment by ridarf** [comment]
Got it, I'll start looking into other issues then.
