### ISSUE TITLE
16ch Not Working In Conjunction With 2ch

### ISSUE THREAD

**Issue by SirSoundfont** [ExistentialAudio/BlackHole#385]
I'm using 16ch as my system output device, so I can send stuff like Youtube into Logic, which works great. However, I'm outputting Logic to my Aggregate Device, which sends it to both my headphones and BlackHole 2ch, and 2ch isn't receiving any audio from what I can tell. It's not recording anything in Audacity, and using it as my Discord input shows no input either. Am I not allowed to use 16ch and 2ch together like this? If not, I'm assuming my best other free choice is using VB Audio Cable in my Aggregate Device instead of BlackHole 2ch.

**Comment by devinroth** [comment]
1st. Do you have drift correction enabled.
2nd. Does 2ch or 16ch work fine separately with the aggregate?

If the answer is yes to both I think I may know what the problem is.

Devin Roth

**Comment by SirSoundfont** [comment]
I've tried a combination of clock sources and drift correction on my outputs, including the built-in speakers that I muted (because I read that sometimes an OSX quirk requires it to be enabled), but it doesn't actually appear that it's working with the aggregate device. I recall getting it to work briefly at one point (possibly with a multi-output device instead?), but now no audio is getting sent through either 2ch or 16ch in my aggregate device.

**Comment by devinroth** [comment]
Send screenshots of your aggregate device and logic setup.

Devin Roth

**Comment by SirSoundfont** [comment]
For right now, I've just been trying to get it to work without Logic first, because I'm fairly confident that part was being routed properly. I set my aggregate device to be my system output, and I'm testing it with my browser and trying to record 2ch in Audacity. It's being sent to my headphones correctly, but the BlackHole portion isn't working. Here's my setup for that.
<img width="390" alt="Screen Shot 2021-05-03 at 5 25 50 PM" src="https://user-images.githubusercontent.com/18604470/116936201-7c161c00-ac35-11eb-8817-d79b82646f7a.png">

**Comment by devinroth** [comment]
You are treating the aggregate as a multi-output. https://support.apple.com/en-ca/HT202000

Is this case you are only sending audio to the headphones.

Devin Roth

**Comment by SirSoundfont** [comment]
Oh thank you, it was my understanding that an aggregate device also worked as a multi output device. I switched everything to a multi output, and now I'm successfully able to send YouTube through 16ch into Logic Pro and run effects on it, and then route Logic's output through 2ch into something else. Have a wonderful day!
