### ISSUE TITLE
MPCBeats (or daw) to logic using Blackhole.. confused!!!

### ISSUE THREAD

**Issue by rayface** [ExistentialAudio/BlackHole#386]
So I'm using my DAW(MPCBeats) trying to record the system audio into Logic Pro X. My Mac audio is set to multi output device... my DAWmpc output is set to Multi output device.... and plays fine through my mac system speakers... but in logic I've tried a few different combos of inputs including blackhole 2ch / system setting... and just can't crack the code to get logic to show any audio coming in... I know it could be just a few settings either on my Mac audio/Daw/or logic... any help would be appreciated as I'm going CRAZY!!!

**Comment by devinroth** [comment]
Screenshots please.

Devin Roth

**Comment by rayface** [comment]
I also should note that the multi output was set up with system out on top and blackhole both checked...

**Comment by devinroth** [comment]
Does it work with just BH 2ch? Some apps don’t actually work with multi-outputs. Not much we can do about that if that’s the case.

Devin Roth

**Comment by rayface** [comment]
I've tried it with soundflower and it worked... I didn't update anything just simply restarted my computer and it stopped working..so I looked up a thread on github on that issue and saw this program but seems to be same thing with both... was hoping I was just dumb and didnt have a setting right on one of the programs like a routing conflict... I did try on mpc out BH2 and MacSystem Audio BH2 (without logic) and it does not work either.. but wasn't sure if my settings were correct on that either.. 

Not sure how I got it to work the 1st time but it's like a new Rubix cube that I fd up and can't put it back lol...appreciate any advice

**Comment by rayface** [comment]
It has BH2 selected from trying previous recommendation from you

**Comment by rayface** [comment]
![16204425173428760226917688140033](https://user-images.githubusercontent.com/83848378/117523610-f2d94f00-af7e-11eb-8bba-2e7e0e831d1b.jpg)

**Comment by rayface** [comment]
I figured it out... it was a setting on my logic defaulting to a different audio input.... thanks so much for getting my brain to think different.... wasn't your software at all so happy with it now 😀
