### ISSUE TITLE
Recording with Audacity

### ISSUE THREAD

**Issue by klopfdreh** [ExistentialAudio/BlackHole#39]
Hi,

I just installed v0.2.5 of blackhole and tried to record audio beside I wanted to hear it. Here are some points I setup to do so:

1. Created a multi output device within the Audio-Midi-Setup with the primary device being set to the internal speakers - drift correction applied to BlackHole 16ch
2. Started the system preferences for audio and set the input to BlachHole 16ch
3. Started Audacity and set the recording device to BlackHole 16ch and the output to the multi output device

What I am facing is that in the system preferences the input is recording the signal correctly - I can see it right there, but Audacity is not recording anything.

Any Ideas what I made wrong?

Beside that I am using macOS 10.15.2, Audacity 2.3.2

Thanks a lot and kind regards 

Note: QuickTime is recording the audio without any issues. Maybe it is related to Audacity but I just wanted to ensure.

**Comment by devinroth** [comment]
Have you read everything here?

https://github.com/ExistentialAudio/BlackHole/wiki/Audacity

**Comment by klopfdreh** [comment]
Yes I read it and setup everything like explained.

**Comment by devinroth** [comment]
Just to confirm.

Are you using Catalina?
Does Audacity have microphone access?

**Comment by klopfdreh** [comment]
Yes micro has access and I am using macOS 10.15.2

**Comment by devinroth** [comment]
Sorry Audacity isn’t supported on Catalina.

https://www.audacityteam.org/macos-10-15-catalina-is-not-yet-supported-by-audacity/ <https://www.audacityteam.org/macos-10-15-catalina-is-not-yet-supported-by-audacity/>

**Comment by klopfdreh** [comment]
Well the editing and everything is working like expected, except the recording.

But if it is not officially supported I am fine closing this ticket.

Thanks for your time!

**Comment by devinroth** [comment]
No problem. You’ll have to take the issue up with Audacity. It does sound like some people have figured out a work around.
