### ISSUE TITLE
channel HDMI output to blackhole on mac

### ISSUE THREAD

**Issue by theshuklz** [ExistentialAudio/BlackHole#40]
My speakers are connected to the monitor. when I connect my mac to the monitor, normally it doesn't allow adjusting volume mac. Soundflower had this feature where I could provide the desktop output to it and then I can control it.
Is it possible to do the same in Blackhole, if yes, how?

**Comment by devinroth** [comment]
Not currently. Another piece of the puzzle is needed to map BlackHole's output to a different output.

**Comment by devinroth** [comment]
But this is an often requested feature. I'll keep this up.

**Comment by kimsyversen** [comment]
This would be really great feature!

+1

**Comment by ByteSkater** [comment]
+1, as currently the only solution I found for this is a commercial product and soundflower also doesn't work anymore.

**Comment by connorworley** [comment]
This would be great.

**Comment by jorijnsmit** [comment]
+1

**Comment by aryadaroui** [comment]
This would be great. +1

**Comment by no-Legend** [comment]
This would be great for me too. +1

**Comment by egyedia** [comment]
+1

**Comment by redstrike** [comment]
+1
I plugged in USB Audio Device into my MacBook, and cannot find any way to control its volume.

**Comment by jbuecker** [comment]
+1

**Comment by alexanderchuranov** [comment]
+1
I have a similar scenario: purchased a professional audio interface and suddenly the usual mac up/down volume buttons do not work (device offers its own volume controls). I'd like to route all applications to Blackhole and from there to the audio interface. Loopback certainly offers that option, but it is not open-source.

**Comment by igem0n** [comment]
+1

**Comment by WickedColdfront** [comment]
This would be great!

**Comment by MichaelGrundie** [comment]
+10 I want :)

**Comment by bockbilbo** [comment]
+1

I use the speaker of my external monitor and this would allow using the volume controls of mac to change the volume :)

Thank you!

**Comment by inter-faced** [comment]
+1 adjusting volume control with media keys would be a major feature for me. Too bad apple make this so cumbersome

**Comment by carlosfilhoadm** [comment]
+1

Yes, please. This feature would prove itself very useful for a lot of users.

Thank you.

**Comment by PRosenb** [comment]
As a workaround, audio output of BlackHole can be redirected to the output device with a simple Python script.

[forwardAudio.py](https://gist.github.com/PRosenb/2ce5159a334af203fca7ef06501775f0)

I hope it's useful.

**Comment by rvlak** [comment]
+1

**Comment by baptisteArnaud** [comment]
+1

**Comment by Coriou** [comment]
+1 =)

**Comment by jorijnsmit** [comment]
Isn't it weird Apple hasn't picked this up? Should we contact them somehow?

Judging by the popularity of this everybody just wants to control their peripherals' volume using their keyboard, which is more than logical :-)

**Comment by fchu** [comment]
+1

**Comment by jcperez-iti-upv** [comment]
+1

**Comment by briankendall** [comment]
I hope this sort of self-advertising isn't considered inappropriate, but I wrote a virtual audio device a little while ago for precisely this purpose uncreatively called [Proxy Audio Device](https://github.com/briankendall/proxy-audio-device). I too had an audio interface whose manufacturer couldn't be bothered to allow the system volume to work, and I wasn't having it.

I'll leave that link with the caveat that it's the first audio driver I've ever written, and while I haven't abandoned it I don't have the time to support that I might otherwise like. So if another dev takes up the mantle of providing a driver that can do this, I'd be quite happy! I want people to have the best experience possible, and I worry that I'm not the best person to provide that.

(Also, my driver does some stuff that's _probably_ pretty hacky. If someone who knows what they're doing a bit better than me took a stab at it, that might be for the best!)

**Comment by devinroth** [comment]
Thanks for sharing Brian. I’m sure it will be helpful for some.

**Comment by karthicraghupathi** [comment]
Great work. Thank you!

+1 for this feature.

**Comment by saucebing** [comment]
+1 Now when I want to adjust the volume I need to switch to the internal speakers and then switch back to multi-output device. The volume adjustment is necessary.

**Comment by bwagner** [comment]
+1: I'd need it with as little latency as possible (using it for looping live).

**Comment by jcrystal** [comment]
+1. The ability to monitor specific BlackHole channels via physical hardware would be so great.

**Comment by paulreimer** [comment]
If I understand correctly, part of the solution proposed for this issue would also make it possible to monitor the output without needing to create a Multi-Output Device? (that's the feature I'm looking for).

Sometimes I want to monitor but mostly I don't, and (currently) I need to switch audio devices to do that (causing hiccups and requiring selecting the new device in all apps that are using it).

**Comment by loupaw** [comment]
+1 this would be really awesome, especially if it could be configured using a menu bar app.

**Comment by godly-devotion** [comment]
+1 Having this exact scenario. This feature would be immensely helpful.

**Comment by n8gray** [comment]
Same scenario: monitor without volume controls, but I also find lots of value in random uses for tools like this.  I'm currently using **Hosting AU** to forward from BH to the monitor.  It works, but it doesn't handle changes like disconnections and sleep well.  I've been playing with Apple's **CAPlaythrough** sample code and it works, but there's a sync problem and after about 40 minutes the ring buffer starts to clip.  I'd like to learn how to fix it, but it's hard to find the time.

**Comment by tspangler** [comment]
+1, but in the meantime, @briankendall's [Proxy Audio Device](https://github.com/ExistentialAudio/BlackHole/issues/40#issuecomment-642743519) driver works beautifully, and none of the Soundflower lag I grew accustomed to!

**Comment by pawitrawarda** [comment]
+1 this would be nice feature!

**Comment by heavyinfo** [comment]
> +1, but in the meantime, @briankendall's [Proxy Audio Device](https://github.com/ExistentialAudio/BlackHole/issues/40#issuecomment-642743519) driver works beautifully, and none of the Soundflower lag I grew accustomed to!

Audio seems to be lost after sleep, how are you handling it with Proxy Audio Device?
