### ISSUE TITLE
Sample rate not set by application?

### ISSUE THREAD

**Issue by BitPerfectAudio** [ExistentialAudio/BlackHole#41]
BlackHole doesn't seem to set the sample rate based on the actual stream as requested by an application, or at least it doesn't show it on the MIDI panel. Tested with Audacity and IINA player. Verified with IINA player -> Hecate USB SPDIF out card -> Roland Quad Capture SPDIF input, Roland MIDI panel shows the correct input sample rate. 
A test program that reads an input stream from the Blackhole inputs and displays the actual audio sample rate would be greatly appreciated. Test case would be a) launch test program with nothing playing and Blackhole mnually set to 48KHz, b) play a 96KHz file and verify that the sample rate is correct, c) play a 192KHz file and verify that the sample rate changes to the correct value.

**Comment by devinroth** [comment]
As mentioned in my previous email. 

"AudioMidi setup should show the current sample rate for BlackHole. If you change the sample rate in a daw or other program (assuming they programmed it correctly) it will immediately be changed in AudioMidi setup." 

I'm using Logic Pro in this clip. 

![blackholesamplerate](https://user-images.githubusercontent.com/13010961/71839205-7c1d0080-306f-11ea-8716-4f75c8eef87b.gif)

BlackHole also notifies CoreAudio of all sample rates changes so if that app is programmed correctly it will update when BlackHole sample rates changes. 

Now I tested with Audacity and it looks like it doesn't notify CoreAudio of any changes or respond to any changes in CoreAudio. That's an issue you need to take up with Audacity.
