### ISSUE TITLE
unable to adjust volume when using blackhole with multi-output device

### ISSUE THREAD

**Issue by DARKDRAGON532** [ExistentialAudio/BlackHole#416]

**Comment by devinroth** [comment]
Blame Apple.

Devin Roth

**Comment by DARKDRAGON532** [comment]
Any way to fix it or should i just close this issue?

**Comment by devinroth** [comment]
Nope. Apple decided to have no volume control on multi-outputs. Nothing we can do about it. Just close. s

Devin Roth
