### ISSUE TITLE
After using quicktime to (audio) record a zoom conference, it corrupted

### ISSUE THREAD

**Issue by eamon360** [ExistentialAudio/BlackHole#422]
Hi there,

I have a strange issue. We do screen recordings of zoom and skype conferences multiple times a day. For some, we just record the audio. For both, we use Quicktime to do it.

Randomly, whenever we use Quicktime audio recordings this occurs:
1) We select audio recording. Press the red button.
2) We can see the level bars reacting to the voices speaking, so we know the blackhole plugin is selected and working.
3) When the online meeting is over, we hit the stop button. And we can see the length of the recording (e.g. 51:45)
4) When we save, the time changes and goes down to (00:03). The file that's saved is a few KB and the sound is completely corrupt. It sounds like a storm of noise. And it lasts for 3 seconds.

We have literally no idea what causes this issue and have tried to replicate it with no success. It seems to happen whenever it wants to with no indication at all. It's never happened when we do screen recordings, but it could just be we've been lucky.

This is very troubling as these meetings are quite important and happen daily. We've started doing multiple recordings as backup because of this.

Any idea what's causing the problem? Thanks, in advance.

**Comment by devinroth** [comment]
What if you use GarageBand or Audacity to record audio only?

It really sounds like a QuickTime issue. And sounds like it’s a tricky one to replicate.

Devin Roth
