### ISSUE TITLE
Cannot completely uninstall BlackHole.driver

### ISSUE THREAD

**Issue by ewegener1** [ExistentialAudio/BlackHole#434]
I keep getting this warning when restarting my Mac. I have already removed BlackHole.driver from `/Library/Audio/Plug-Ins/HAL`.

I am not sure where macOS find detects this driver - I can't find it in settings or anywhere else.

![2021-07-27 14 19 36](https://user-images.githubusercontent.com/47779296/127228883-ae9ddf78-f0f4-4010-aabe-0c36d312a646.png)

Running macOS 11.4 (20F71) on an iMac Pro.

**Comment by devinroth** [comment]
What version of BlackHole was installed? Where did you download it from? I assure you that BlackHole does not contain malware.

Did you restart your computer after uninstalling?


Devin Roth

**Comment by ewegener1** [comment]
I downloaded it from GitHub. I know there is no malware, but I'm concerned that I cannot uninstall it completely.

Yes, I restarted.

**Comment by devinroth** [comment]
I have no idea. Find Any File works great for searching everything.

**Comment by kolchurinvv** [comment]
in terminal run this:
```bash
sudo find / type f -name "*BlackHole.driver*" 2&>-
```
to find the file
