### ISSUE TITLE
Audio stops after long periods of time

### ISSUE THREAD

**Issue by JonathanGale** [ExistentialAudio/BlackHole#437]
I'm running BlackHole on an iMac running Mojave, and occasionally the audio stops working. I'm using it to send audio from ProPresenter to Zoom, no aggregate or anything in between, and have had 2 instances where the audio stopped despite my best efforts. ProPresenter is outputting audio, but BlackHole isn't picking it up.

The first time was with the 2ch, so I flipped everything over to 16ch, and had it happen again this week. It's possible it's happening after a long period of running, as I'm leaving the computer on for days at a time.

If there's a way to reboot BlackHole from the command line that would probably help, but I'm open to suggestions. if this is a known/solved issue already, great.

**Comment by devinroth** [comment]
You’re probably missing drift correction.

Devin Roth

**Comment by JonathanGale** [comment]
It's not an aggregate device, so Drift Correction isn't available.

**Comment by devinroth** [comment]
You can reboot core audio with `sudo launchctl kickstart -kp system/com.apple.audio.coreaudiod`.  BlackHole by itself wouldn't do this. Still sounds like drift. Are you using an input audio from mics etc into ProPresenter? And how long are we talking?

**Comment by JonathanGale** [comment]
Shortest time frame was probably 16 hours, the issue also happened after a couple days. Just a video playing out of ProPresenter, into Blackhole, into Zoom. It's running ProPresenter 6, which uses the system audio output.

I've changed it from 44.1k to 48k to make sure it aligns with the video, and can run it through an aggregate device to add drift correction, if that's what will fix it.

**Comment by devinroth** [comment]
It’ll be hard for me to test that.

Can you confirm that it works normally when using a different device than BlackHole?

Devin Roth

**Comment by JonathanGale** [comment]
Good question - I'll start a video looping, and check tomorrow if the audio is still outputting from the speakers properly.

**Comment by orchetect** [comment]
Stale issue - closing. If a solution was found let us know.
