### ISSUE TITLE
BlackHole 64ch v0.2.10.pkg install error

### ISSUE THREAD

**Issue by iphoneio** [ExistentialAudio/BlackHole#438]
Hi, I test "BlackHole 64ch v0.2.10" Extension but this Installer say "digital signature is not trusted."😫
Please update your pkg signature.

## Environment:
- OS: macOS 11.5 Big Sur Build 20G71
- MacBook Pro (M1, 2020)

![BlackHole-64ch-v0-2-10-Signature-issue](https://user-images.githubusercontent.com/9293598/128617411-e2cc1f2d-55cf-4352-80c5-1d2abfbe818b.jpg)

**Comment by devinroth** [comment]
Turns out I screwed up. Try now.

Devin Roth

**Comment by iphoneio** [comment]
i confirmed that is working correctly.
Thank you for your swift response.👏
![Install-BlackHole-64](https://user-images.githubusercontent.com/9293598/128618577-ff882528-b9fe-47ed-baf2-d73727742dcc.jpg)
