### ISSUE TITLE
Latest update to v. 0.2.10 greys out drift correction for BH in Multi-Output Device configuration

### ISSUE THREAD

**Issue by j-rahman** [ExistentialAudio/BlackHole#440]
Everything was working relatively fine until I updated to v. 0.2.10 using Homebrew on macOS 11.5.1. Now, BlackHole 2ch is greyed out in the Multi-Output Device configuration inside the Audio MIDI Setup app. One is **unable to apply Drift Correction to BlackHole 2ch** or use it as the Master Device.
<img width="898" alt="Audio Devices" src="https://user-images.githubusercontent.com/24459756/128998927-8c7233ad-8297-428d-a843-5505df900b19.png">
The audio still works and passes through to both the audio output channels. However, I am worried that when I am doing longer recordings, the inability to apply drift correction to BlackHole 2ch might introduce some nasty distortions.

Is this intended behaviour? If not, how should we fix this? Thanks.

**Comment by j-rahman** [comment]
> Try restarting your computer.

Done that. Does not help.

> ... try deleting the multi-output and recreating it.

Done that as well. Does not help.

I have also tried completely uninstalling the app using Homebrew, cleaning up the brew caches, restarting the system, then doing a fresh install of blackhole-2ch using Homebrew. That does not help either.

**Comment by devinroth** [comment]
Could you send me another photo of your Audio MIDI setup please?

Devin Roth

**Comment by j-rahman** [comment]
It is exactly the same as I have shown before.
<img width="903" alt="Audio Devices" src="https://user-images.githubusercontent.com/24459756/129100242-a5fc1b05-aff3-420a-9a3f-b0b784ca53b5.png">
Thank you for trying to help.

**Comment by devinroth** [comment]
Does BlackHole work normally without the multi-output?

Devin Roth

**Comment by j-rahman** [comment]
I have not used or know of any use case of BH without the multi-output. If you would like me to test something in particular, kindly elaborate a little on what I must do. Thank you.

If it helps, as I have said before, the multi-output device is capable of routing system audio to both the component output devices (including BH 2ch). However, in the Audio Devices list, if I right-click on just "BlackHole 2ch" (second entry in the screenshot), and try to select "Use This Device For Sound Output", then nothing plays anymore on my mac. On the other hand, in the Multi-Output Device configuration, if I just select BH 2ch, then it shows that the Master Device is offline, but system audio still successfully routes through to the output channel.

**Comment by devinroth** [comment]
Yeah this is a new one that I’ve never heard of happening before. I’ll think of a few things for you to test.

First thing I noticed is that the icon isn’t right. I’ll get back to you soon.

Devin Roth

**Comment by joergquak** [comment]
Dear @devinroth, I'm another user with the same problem. BlackHole 2ch is greyed out in Multi-Output Device and Aggregate Device on my Audio-MIDI-Setup (Apple M1). So I can't select drift correction. Is there any progress on this?
Thank's, Joerg.

**Comment by devinroth** [comment]
Just delete the multi-output and create a new one. Should fix that issue.

Devin Roth

**Comment by devinroth** [comment]
0.3.0 has some issues so I didn’t build an installer. I’ll get 0.4.0 out soon.

Devin Roth

**Comment by joergquak** [comment]
Thank you very much, I will wait, Joerg.

**Comment by devinroth** [comment]
v0.4.0 is released. Reopen if you still have issues.

**Comment by joergquak** [comment]
Thanks @devinroth, for the installation I prefer the MacPorts though:
sudo port selfupdate && sudo port upgrade BlackHole
sudo launchctl kickstart -kp system/com.apple.audio.coreaudiod
I need just the 2-ch version as before with Soundflower too, Jörg.
