### ISSUE TITLE
Noise on my videos

### ISSUE THREAD

**Issue by rcarrascoz** [ExistentialAudio/BlackHole#442]
Hi, I have detected that my record vídeos with quicktime (shift+command+f5) when the vide has a time, 30minutes in this cause, it start to save a noise on videogame. Only I can listen to when I listen to my record video.... :(

**Comment by rcarrascoz** [comment]
Hi, if I have 3 out devices, I have to enable drift on the devices? I am only on 1 device and it was not on Blackhole...

**Comment by devinroth** [comment]
Yes put drift on all devices.

Devin Roth
