### ISSUE TITLE
FAQ section in the installer looks a bit broken

### ISSUE THREAD

**Issue by dstd** [ExistentialAudio/BlackHole#443]
The installer has following text in "Why is nothing playing through BlackHole?" section of FAQ:
> If you are using a multi-output device, due to issues with macOS a 2ch audio driver must be enabled and< listed as the top device in the Multi-Output.

While README.md contains:
> If you are using a multi-output device, due to issues with macOS the Built-in Output must be enabled and listed as the top device in the Multi-Output.

**Comment by devinroth** [comment]
Thanks. I’ll update that for the next release.

Devin Roth
