### ISSUE TITLE
repeated crackles when feeding Blackhole16ch via Ableton

### ISSUE THREAD

**Issue by designerfuzzi** [ExistentialAudio/BlackHole#448]
no matter what amount of channels i compile and use then i get audio drops and cracles each 3 - 5 minutes that disappear after about 5 seconds and come back again..
Tried to change settings to system Samplerate (MacBookPro 2009) 44100.0f but it falls back to 48.000 .. guessing there is a buffer issue in code. Drift correction is not available when using with Ableton, because then you route directly..

my Setup routing is 
> Ableton Master Out 1&2
>> Blackhole 16ch on 1&2
>>> into my own Audio App catching Blackholes Audio via CoreAudio
>>>> from there Output to External Audio Device (Allen&Heath Studio Mixer, an Class Compliant USB Device with 24In and 22out)..

first of all it works, 
second noticeable crackles now and then after about 3-5minutes that disappear again.

That lets me think it is a ringbuffer issue that sums up 
or another idea is a repeated system task that blocks the drivers process.. difficult to know

As i can record the Blackhole Output in my App i can even record the crackles.. meaning they appear between
 Ableton and Blackhole and HAL system not down the chain..
When my own App is not running and i route from Ableton to Blackhole16ch on 1&2 and use Blackhole as system output i also have the very same crackles in the same time spans..

**EDIT:** evaluation..
PART1
made a intense blackhole.c read up in Xcode.. checking for mutex placement, even wrote testcode to see if the samplerate is properly parsed for sanity, because i have seen i can not change it in Audio-Midi-Setup.app.. 

PART2
compiled an BlockHole4ch.driver ..
with 4 Channels of course, 
and a basic Samplerate of 48000.
(before i had a 16ch version running) 

So this works better and clearly the crackles are about 4times shorter and appear about two times later..
That lets me think it is not a system issue blocking some task.. tending more to the ring buffer and mutexes

**Comment by designerfuzzi** [comment]
And something i notice.. when i turn some Controls on the External Mixer the crackles appear.. Not sure yet if this is coincidence or closer to the root of the isse

**Comment by devinroth** [comment]
What buffer size are you using?

Devin

**Comment by devinroth** [comment]
I just did some tests with Live playing a sine wave. Crackles were completely dependant on buffer size. Some issues with 32 but completely go away with 128.

**Comment by devinroth** [comment]
As for sample rate. Changes work completely normally. Although apps at times will block a sample rate change. Possibly what you're seeing.

**Comment by devinroth** [comment]
To test I played a 220 Hz sine wave in Live out to BlackHole 16ch and recorded it in Audacity. Absolutely no issues with a buffer size of 128.

**Comment by designerfuzzi** [comment]
yep, if buffer size could solve it that wold be nice. 
But when you write about buffer size, which of them are you referring to? 
this one?
https://github.com/ExistentialAudio/BlackHole/blob/17a21e9c8d0f03c9b83c6ebf77342bb1288e022c/BlackHole/BlackHole.h#L168

i compiled with those, see the difference?
```c++
#define   RING_BUFFER_FRAME_SIZE   ((32768 + LATENCY_FRAME_SIZE) * NUMBER_OF_CHANNELS)
```
```c++
static const UInt32                 kDevice_RingBufferSize              = 16384;
```

i noticed also the RING_BUFFER_FRAME_SIZE is multiplied with NUMBER_OF_CHANNELS again? 
```c++
        ringBuffer = calloc(RING_BUFFER_FRAME_SIZE * NUMBER_OF_CHANNELS, sizeof(Float32));
```
well should be right... first you calculate framesize (distance to next frame), 
then you calculate this applied to the amount of channels 

and then when clearing the ringBuffer my code says..
```c++
// clear ring buffer after 8192 samples.
ingBuffer[((mSampleTime+frame-8192)%kDevice_RingBufferSize)*NUMBER_OF_CHANNELS+channel] = 0;
```
but  that seems to have changed recently to subtract 16384 ..
and in `BlackHole_DoIOOperation()` this mentioned line of code is kicked out, just used for "// From BlackHole to Application"


also changed in my version the mutex sorting in `BlackHole_PerformDeviceConfigurationChange()` so it wraps only the setting of the 2 global variables but not `mach_timebase_info(&theTimeBaseInfo);`.. since then i can change the sampleRate in Audio-Midi-Setup which looks now like...
```c++
//	recalculate the state that depends on the sample rate
struct mach_timebase_info theTimeBaseInfo;
mach_timebase_info(&theTimeBaseInfo);
Float64 theHostClockFrequency = (Float64)theTimeBaseInfo.denom / (Float64)theTimeBaseInfo.numer;
theHostClockFrequency *= 1000000000.0;
Float64 hostTicksPerFrame = theHostClockFrequency / inChangeAction;
    
//    lock the state mutex
pthread_mutex_lock(&gPlugIn_StateMutex);
    
gDevice_HostTicksPerFrame = hostTicksPerFrame;
//    change the sample rate
gDevice_SampleRate = inChangeAction;
    
//	unlock the state mutex
pthread_mutex_unlock(&gPlugIn_StateMutex);
```

**Comment by devinroth** [comment]
Ummmm. You set the buffer size in your audio application.

Devin

**Comment by designerfuzzi** [comment]
rrrrrrgh! But thats sampling-size (aka buffersize but not the buffer size), misleading translation of Ableton.. its the size of the spoon we eat the soup and the cook is cooking with. Its just controlling the amount of memory that is shuffled each time, not the buffer size itself. Lower "Puffergröße" leads to more CPU load of course, because we use the spoon much more often to eat the same soup. Increasing just makes the CPU less responsive to changes because the spoon is bigger to taste the soup each time we eat. Of course when this is too tiny the memory work becomes disproportional to the calculation that cant be done in the time of one eaten spoon. While testing my ableton (lets call it chunk size) chunk size was 512 or 1024.. that works nicely even without Blackhole with a "ableton" CPU load of 1%-2%.
Apart from that buffer theory, the same rules apply to Blackhole somehow. 
Because too small means too often emptying the buffer and refilling.
I would expect a bigger buffer size to eat more RAM and introduce more latency but resulting in less disturbed signal.
So to solve i would tend to increase the buffer size rather than lowering as you pointed out with 128 (or more) instead of 32.

to me this part of the code is suspicious..
`((mSampleTime+frame-8192)%kDevice_RingBufferSize`
as the modulo keeps the result in boundaries, what happens if modulo fails or the result is negative? (and is also a more heavy cpu operation)
Then we have memory access to data that is undefined. Or i am wrong?

**Comment by devinroth** [comment]
I have a plan to remove that code. But it’s completely unrelated to your problem.

In English it is universally called “buffer size” or “audio buffer size” or “buffer frame size". Please stick with established terms instead of inventing your own.

Devin

**Comment by devinroth** [comment]
Regardless this should solve your problem.

(mSampleTime+frame-8192+kDevice_RingBufferSize)%kDevice_RingBufferSize

There are better ways to improve CPU than complain about this line of code.

Devin

**Comment by designerfuzzi** [comment]
for the records.. measured the timing of appearance from crackles..
exactly each `190seconds` or `3min:10sec`, With Abletons Samplesize is 512 Samples it is one full round messed up.
Indeed lets not mess up the naming.

**Comment by devinroth** [comment]
You are over thinking this.

The problem is audio is being read from the driver before it is written.

Increase the latency if you have a problem. You can do this by either increasing the buffer size in Live, adding additional latency in Live, or increasing the latency in BlackHole.

On my M1 there is no problems with even 32 sample buffer size. My 2015 MacBook Pro has no issues with a buffer size over >128.

You just need to tweak the settings until you get the results that you want.

If you find unrelated bugs in my code please create a different issue.

Devin

**Comment by designerfuzzi** [comment]
this is an answer i can work with.. maybe i can figure out more fitting values for my constellation..
Thanks

**Comment by vespakoen** [comment]
@devinroth Did you compile Blackhole yourself with different settings?

I tried using Blackhole on:

- M1 - Macbook Air
- M1 Pro - Macbook Pro
- Ableton Live 11
- Ableton Live 11.1 Beta (which is compiled for arm64 / has M1 support)

And experience the crackling sounds every couple of minutes with 512 samples and below, which adds too much latency to use it for any kind of live performance.
I don't think the hardware is the problem in this case...

**Comment by vespakoen** [comment]
Just installed "Loopback" (https://rogueamoeba.com/loopback/) and am having the same issue there, which gives me some sanity at least...

I'll do some more experimenting and comparisons and report back.

**Comment by vespakoen** [comment]
I just downloaded Logic Pro and routed the audio from Blackhole to my USB Audio Interface (Behringer UMC404HD) and with 32 samples buffer size experience no crackles at all!

**Comment by devinroth** [comment]
So live is the problem.

Devin

**Comment by designerfuzzi** [comment]
we could ask Ableton what they are doing each 190secs. Or someone has some nice method to debug whats going on in with their audio thread mutex. Also of interest if this problem could be replicated in Ableton versions below 11.1beta

**Comment by devinroth** [comment]
@designerfuzzi if you do take the time to do all that testing please let me know the results.

**Comment by devinroth** [comment]
We've determined that this is an Ableton issue. Going to close.
