### ISSUE TITLE
Will this driver be using user space DriverKit in the future?

### ISSUE THREAD

**Issue by ioanalexme** [ExistentialAudio/BlackHole#450]
Hello guys, great project here.
But I have a question. Apple is moving the drivers from kernel space to user space with the new DriverKit.
https://developer.apple.com/documentation/audiodriverkit/creating_an_audio_device_driver
https://developer.apple.com/videos/play/wwdc2021/10190/
Will BlackHole move to this new frameworks as well?
Thank you.

**Comment by devinroth** [comment]
BlackHole uses the user space AudioServerPlugIn API and not the already obsolete kernel driver for audio. The primary reason for building BlackHole was to replace Soundflower which was build on the kernel audio driver API. So there is no need to change anyway.

Devin
