### ISSUE TITLE
2ch picking up mic sound in Streamlabs, I can hear my voice echoing

### ISSUE THREAD

**Issue by susieqzcreates** [ExistentialAudio/BlackHole#454]
Hello guys,

This is a new thing that just randomly started happening, I don't know what changed as I haven't changed any settings on my Mac or Streamlabs.  I use Black hole to route desktop audio to my Streamlabs dashboard so my viewers can hear music.  Last night when I started up my stream, I was hearing my voice echoing in my headphones. Through lots of long winded trial and error, I discovered that my voice is being picked up through my mic in the Black hole 2ch audio output device on my stream.  I have made sure the audio is set to output only (no monitor), I have uninstalled and reinstalled Black hole, restarted my computer numerous times, I have unplugged my mic (which stopped the problem), I have tried everything I know to try. I hope someone can help fix this problem or give some guidance!

Thank you!

**Comment by valentingalmand** [comment]
HI!
I have got the same problem, did you find a fix? @susieqzcreates
Thank you!

**Comment by susieqzcreates** [comment]
@valentingalmand hello! Nope never found a solution. I ended up just switching to a new program called SWB Audio Capture and it's worked way better!

**Comment by valentingalmand** [comment]
@susieqzcreates thank you! I'll try that! 🙏

**Comment by valentingalmand** [comment]
@devinroth I use a Multi-Output Device, when I uncheck BlackHole the problem is solved 🤔 
In OBS I've my Microphone and Desktop Audio, when I speak, I can see the Desktop Audio is activated.

Maybe I should create a new issue?

**Comment by devinroth** [comment]
No need. BlackHole has no possible way of accessing your microphone. It’s literally impossible that BlackHole is the cause of this.

I can only explain BlackHole. I can’t vouch for multi-outputs which are extremely buggy, or OBS.

Unfortunately I do not have time to test every possible scenario.

But one thing you can try is this beta version of BlackHole. There are some changes that maybe make OBS or multi-outputs behave.

**Comment by devinroth** [comment]
[BlackHole2ch.v0.2.11-beta.pkg.zip](https://github.com/ExistentialAudio/BlackHole/files/7688758/BlackHole2ch.v0.2.11-beta.pkg.zip)

**Comment by valentingalmand** [comment]
@devinroth thanks, I'll take a look! 🙏

**Comment by devinroth** [comment]
try v0.4.0. Just released. Reopen if you continue to have issues.
