### ISSUE TITLE
FEAT: configurable latency

### ISSUE THREAD

**Issue by geoHeil** [ExistentialAudio/BlackHole#455]
Can you make https://github.com/ExistentialAudio/BlackHole/wiki/Adjust-Driver-Latency configurable (so that a re-build is not required?

It would be awesome as I could then get rid of obs and vb-audio cable in my life streaming setup where I need to add additional latency on the audio from my USB microphone to get it lined up with the video from the camera.

**Comment by devinroth** [comment]
Pro version will have that. Still working on it.

Devin

**Comment by geoHeil** [comment]
awesome.
