### ISSUE TITLE
How to hide virtual audio driver if it is not used, like tecent driver, webex driver

### ISSUE THREAD

**Issue by youlianqi** [ExistentialAudio/BlackHole#456]
Copy BlackHole.driver to HAL, it will appear in voice input device list.
But other virtual audio driver, like from Tecent, Cisco Webex, Zoom, it doestn't appear n voice input device list. Only use the virtual audio driver, it will appear.

**Comment by devinroth** [comment]
It really depends on what you want to accomplish. There are a couple ways to approach this. If you need help with development I am available for consulting. Also be sure to contact me for a license if you plan on bundling BlackHole. devinroth@existential.audio.

**Comment by NeGitR** [comment]
Actually,  i have the same issue, but care about the Output device list more.

**Comment by youlianqi** [comment]
@devinroth , I download and build latest BlackHole code, generate a BlackHole.driver.
                      
sudo cp -Rf BlackHole.driver   /Library/Audio/Plug-Ins/HAL/
sudo launchctl kickstart -kp system/com.apple.audio.coreaudiod
                      
BlackHole driver will appear in system voice input device list. The driver name also can be listed in system api AudioObjectGetPropertyData.

But I find Webex, Zoom, Tecent or other driver, cp driver into HAL, they will not appear n system voice input device list, but the driver name also can list in system api AudioObjectGetPropertyData.
                      
Could we change something can implenet the same as Zoom driver base on latest code.
                      
Thanks very much.
