### ISSUE TITLE
Simultaneous headphone + speaker output?

### ISSUE THREAD

**Issue by opyate** [ExistentialAudio/BlackHole#457]
Hello,

Will BlackHole enable me to output audio to both headphones and speakers?

My use-case: a headphone jack broke off and is now firmly lodged inside the plug. As such, audio on the speakers is disabled. 

I know that it's not a hardware block, as I hear the Apple chime on reboot.

Thanks!

**Comment by devinroth** [comment]
Nope sorry.

Devin Roth

**Comment by opyate** [comment]
OK, thanks for the reply!
