### ISSUE TITLE
AirpodPro does not work properly

### ISSUE THREAD

**Issue by arangari** [ExistentialAudio/BlackHole#464]
I have created MO device with AirpodPro and BH16 for output, and Aggregate Device Also with same for input.
however the sampling rate for MO device was only 16Hz and voice is garbled.

Also, I want to divert the audio from zoom to OneNote or Skype to OneNote or Teams to oneNote. 
what is the setting for these

**Comment by arangari** [comment]
any help here?

**Comment by devinroth** [comment]
This is an issue with Aggregates. But I added 16kHz to BlackHole now so perhaps it will help.
