### ISSUE TITLE
Certificate used to sign package is not trusted

### ISSUE THREAD

**Issue by 3gyptian** [ExistentialAudio/BlackHole#469]
Hi - I'm receiving this error when launching the BlackHole2ch.v0.2.10.pkg on El Captain (10.11.6).  

I get the same error when attempting to install from the command line:

```
/usr/sbin/installer -pkg ./BlackHole2ch.v0.2.10.pkg  -target / 
installer: Package name is BlackHole: Virtual Audio Driver 2ch v0.2.10
installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.
```
And it still fails unfortunately when attempting with allowUntrusted override:

```
/usr/sbin/installer -pkg ./BlackHole2ch.v0.2.10.pkg -allowUntrusted -target / -verbose
installer: Package name is BlackHole: Virtual Audio Driver 2ch v0.2.10
installer: Installing at base path /
installer: Preparing for installation….....
installer: Preparing the disk….....
installer: Preparing BlackHole: Virtual Audio Driver 2ch v0.2.10….....
installer: The install failed.
```

I know this is an ancient version of OS X and I wouldn't have posted this if I didn't see it mentioned in Readme that Blackhole is compatible back to 10.9! 

Thank you for any suggestions on how to resolve this.

**Comment by devinroth** [comment]
Here is the discussion on the topic. https://github.com/ExistentialAudio/BlackHole/discussions/460
