### ISSUE TITLE
Audio input & output gone missing every now and then

### ISSUE THREAD

**Issue by swswsws583** [ExistentialAudio/BlackHole#477]
<img width="780" alt="Screenshot 2021-10-20 at 11 38 11" src="https://user-images.githubusercontent.com/92858558/138078781-86b1c80a-6a17-4cc9-946a-2ed0a1d92c85.png">
Hi,

I am having trouble with Blackhole 2ch on my M1 MacBook Air. Audio input and output disappear from time to time, and each time I have to use this command to reset my audio settings: sudo launchctl kickstart -kp system/com.apple.audio.coreaudiod

I am using BlackHole2ch.v0.2.10 and macOS Big Sur 11.6
 
Can somebody help please? Thanks!

**Comment by devinroth** [comment]
Yeah that sounds like a core audio crash.

Could you give me the errors from Console when it happens?

Devin

**Comment by devinroth** [comment]
Are you using BlackHole at the time of the crash?

Devin

**Comment by hoflz5** [comment]
I also get error in Logic Pro on my M1.
But I only seem to get it when I'm currently using my sound card driver (Audient iD14).
If I switch to the "Multi-Output Device" as output, which includes BlackHole 2CH, then it doesn't kill core audio like this.

`ct 21 11:21:55 MacBook-Air-M1 akd[1410]: objc[1410]: Class AKCarrierBundleUtilities is implemented in both /System/Library/PrivateFrameworks/AuthKit.framework/Versions/A/AuthKit and /System/Library/PrivateFrameworks/AuthKit.framework/Versions/A/Support/akd. One of the two will be used. Which one is undefined.
Oct 21 11:21:56 MacBook-Air-M1 remindd[1414]: objc[1414]: Class REMCDChangeTrackingState is implemented in both /System/Library/PrivateFrameworks/ReminderKit.framework/Versions/A/ReminderKit and /usr/libexec/remindd. One of the two will be used. Which one is undefined.
Oct 21 11:21:58 MacBook-Air-M1 com.apple.siri-distributed-evaluation[1419]: sandbox initialization failed: <internal init prelude>:456:12: unable to open common.sb: not found
		(apply error x)
Oct 21 11:21:58 MacBook-Air-M1 com.apple.xpc.launchd[1] (com.apple.siri-distributed-evaluation[1419]): Service exited with abnormal code: 1
Oct 21 11:21:59 MacBook-Air-M1 Core Audio Driver (BlackHole2ch.driver)[1421]: BlackHole_GetControlPropertyData: the item in the qualifier is not valid for kAudioSelectorControlPropertyItemName for the data source control
Oct 21 11:22:00 --- last message repeated 3 times ---
Oct 21 11:22:00 MacBook-Air-M1 Core Audio Driver (BlackHole2ch.driver)[1421]: BlackHole Start IO
Oct 21 11:22:00 MacBook-Air-M1 com.apple.geod[1427]: objc[1427]: Class GEOETAProvider is implemented in both /System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/GeoServices and /System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/XPCServices/com.apple.geod.xpc/Contents/MacOS/com.apple.geod. One of the two will be used. Which one is undefined.
Oct 21 11:22:00 MacBook-Air-M1 com.apple.geod[1431]: objc[1431]: Class GEOETAProvider is implemented in both /System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/GeoServices and /System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/XPCServices/com.apple.geod.xpc/Contents/MacOS/com.apple.geod. One of the two will be used. Which one is undefined.
Oct 21 11:22:02 MacBook-Air-M1 rtcreportingd[1440]: objc[1440]: Class UpdateAndReportServices is implemented in both /System/Library/PrivateFrameworks/RTCReporting.framework/Versions/A/RTCReporting and /usr/libexec/rtcreportingd. One of the two will be used. Which one is undefined.
Oct 21 11:22:02 MacBook-Air-M1 rtcreportingd[1440]: objc[1440]: Class RTCReportingDeallocNotifier is implemented in both /System/Library/PrivateFrameworks/RTCReporting.framework/Versions/A/RTCReporting and /usr/libexec/rtcreportingd. One of the two will be used. Which one is undefined.
Oct 21 11:22:02 MacBook-Air-M1 rtcreportingd[1440]: objc[1440]: Class RTCReportingAggregationObject is implemented in both /System/Library/PrivateFrameworks/RTCReporting.framework/Versions/A/RTCReporting and /usr/libexec/rtcreportingd. One of the two will be used. Which one is undefined.
Oct 21 11:22:02 MacBook-Air-M1 rtcreportingd[1440]: objc[1440]: Class RTCReporting is implemented in both /System/Library/PrivateFrameworks/RTCReporting.framework/Versions/A/RTCReporting and /usr/libexec/rtcreportingd. One of the two will be used. Which one is undefined.
`

**Comment by devinroth** [comment]
Should be solved with 0.4.0. Reopen if you continue to have issues.
