### ISSUE TITLE
Having trouble recording system audio with Blackhole

### ISSUE THREAD

**Issue by itzawrap** [ExistentialAudio/BlackHole#48]
Downloaded and installed but can't get system audio from Safari page to show up in Quicktime Player or Uniconverter (screen recorder tool) all inside Catalina 10.15.2

Really baffling. Under Mojave I had Soundflower working fine for this same function.

Any help is appreciated.

Thanks.

**Comment by devinroth** [comment]
Have you checked the volume? Try that first.

**Comment by itzawrap** [comment]
The instructions on this site are useless. Found a YouTube video that explains it well.

Followed along and then tweaked it to use in the apps I needed it to work with. Voila...system audio pass through from Safari to Quicktime or Audition. Works beautifully well.

https://youtu.be/9aGU1sr-_Tw

**Comment by devinroth** [comment]
Feedback on how to make it better would be helpful.

**Comment by itzawrap** [comment]
My feedback is to watch the video I recommend. That will clear up the confusion anyone like me would experience trying to use the directions posted about Blackhole, which I read and did not find to be helpful. Here is the link to the YouTube video again: https://youtu.be/9aGU1sr-_Tw 

I learn best by watching and listening. Reading instructions are hard for me to understand, unless there are pictures with it.

I hope this feedback helps because there are probably other people with the same learning style as me.

**Comment by Kohlkarpfen** [comment]
I got the same problem. I followed the instructions here on Git but I can't record with Audacity. Also the video doesn't help. On the input gauge in the system settings I can see someting id comming in, but Audacity won't record.
I can record with Quicktime, but it's only mono and adds 16 empty channels as well.
I've no idea what am I doing wrong.
macOS Catalina 10.15.2

**Comment by itzawrap** [comment]
I read in several posts that Audacity and Catalina do not play well together. That could be your main issue. Do a search about it on Duck Duck or Google to see what you can find.

**Comment by Kohlkarpfen** [comment]
I found a simple workaround to get recording with Audacity working: https://forum.audacityteam.org/viewtopic.php?t=107162

Just start Audacity form the Terminal and recording works well, including BlackHole as source.
