### ISSUE TITLE
Not Working on macOS Monterey

### ISSUE THREAD

**Issue by msrivette** [ExistentialAudio/BlackHole#480]
Ive been using BlackHole for streaming on my mac with no issue. Today, after updating the OS, I noticed that OBS was no longer picking up my mic

**Comment by msrivette** [comment]
I have been playing around with it all morning. I uninstalled everything and reinstalled everything and it is now working. Not sure what broke when I updated the OS but its working now!

**Comment by devinroth** [comment]
Great. Yeah I’ve heard of issues with that happening after some people upgraded to Big Sur. Probably the same thing happening with Monterey. No idea why.

Devin
