### ISSUE TITLE
Configured a Blackhole Aggregate Device - but system sound failed for Web Gotomeeting 

### ISSUE THREAD

**Issue by tierenz** [ExistentialAudio/BlackHole#481]
We configured properly on my MacBook Pro for Blackhole Agregate Device, with Build in Micorphone and Blackhole, 

It worked well for Guicktime Recording with Mic and system sound, but it failed to send the system sound to the meeting attendees when a Browser based GoTo Meeting is used on a Chrome or Firefox browser. 

But on other Macbook computer it just worked well, what is the problem and how to fix it.  
The link below shows the bug or the problem, 

https://kloud.cn/document/2135436

**Comment by devinroth** [comment]
Probably because Aggregate devices don’t work the way you think they do. Goto probably only uses the first 2 channels in an aggregate device.

Devin
