### ISSUE TITLE
Screen recording with quicktime and blackhole, recording won't save to external drive 

### ISSUE THREAD

**Issue by matchala** [ExistentialAudio/BlackHole#482]
Hi there, 
I'm using quicktime in conjunction with blackhole in order to make screen recordings that record internal audio. This does work when the save location is on my mac (running on Catalina), however the recordings will not appear on my external hard drive when I change the save location there. Once I stop recording the screen recording files just seem to disappear. I have tried saving the quicktime recordings onto my external drive (without blackhole) on a completely new user which worked, and this lead me to the conclusion that the issue was blackhole itself. Has anyone else found a workaround for this or come across this issue?

**Comment by devinroth** [comment]
Sounds like a Quicktime issue. Try contacting Apple.

Devin

**Comment by devinroth** [comment]
Especially since it works in one situation and not the other.

Devin

**Comment by matchala** [comment]
Apple told me it was an issue with the plugin which is why I'm here aha

**Comment by devinroth** [comment]
Did they say why or just shift the blame?

Devin

**Comment by matchala** [comment]
From what I remember, the people at apple said that it's likely that blackhole might not recognise the file path on the external drive which is why it fails to save there, since blackhole + quicktime can successfully save files on my desktop without an issue. Could have just been them grasping a straws to shift the blame though. Another possible theory was due to the mac permissions, since blackhole is not a classified as an application you can't switch the permissions to access/save to the external drive while using it.

**Comment by devinroth** [comment]
Lol. BlackHole doesn’t save files. That’s solely on QuickTime.

Permissions are also the responsibility of the application.

Sorry that you had to deal with a clueless Apple support person. Definitely blame shifting. It’s clear from your comments that the Apple person you spoke with knows nothing.

**Comment by matchala** [comment]
Thanks for clearing that up for me Devin! I'm really not a tech person so I wasn't sure how valid their advice/theories were. I think I'm just going to look for an alternate software instead instead of messing around with this more.

**Comment by devinroth** [comment]
Here so a simple test. Use BlackHole2ch as the input into QuickTime and BlackHole2ch as your audio output from the program. Test if that works. If that works then it’s either an issue with aggregate / multi-output devices or QuickTime.
