### ISSUE TITLE
Support higher sample rate

### ISSUE THREAD

**Issue by Wang-Yue** [ExistentialAudio/BlackHole#486]
Today many 'hifi' system or premium ADC/DACs  support higher sample rates up to 768kHz. 
Wouldn't it be great if we could support those higher sample rate as well? Thanks.

**Comment by devinroth** [comment]
Should be relatively easy. I can put it on the todo list.

384kHz and 768kHz? Any others.


Devin

**Comment by Wang-Yue** [comment]
Thanks. 
Here're the sample rates I see when using those ADC/DACs. 
 44100, 48000, 88200, 96000, 176400, 192000, 352800, 384000, 705600, 768000

**Comment by devinroth** [comment]
Cool. I’ll add them to the next release.

Devin

**Comment by batou069** [comment]
The real deal regarding bitrate and sample rate would be bit perfect playback.
If the file is a 24bit 192khz file then that's what should be sent to the sound device, with no up/down sampling or any dsp. 
I guess this would become problematic if we mix multiple streams and only possible if that 24/192 file would play exclusively

**Comment by devinroth** [comment]
But converting 24bit to 32bit float and back to 24bit would be completely lossless. So why does it matter? It’s not like it’s expensive for the cpu. Perhaps I’m not grasping why 24bit vs 32bit float is an important issue to you. I’m all ears.

Devin

**Comment by devinroth** [comment]
New sample rates were added in v0.3.0. Just release v0.4.0.
