### ISSUE TITLE
blackhole volume control

### ISSUE THREAD

**Issue by deeloke** [ExistentialAudio/BlackHole#49]
Hi

Firstly, thanks for making this wonderful driver. 

I have one question: I am unable to manipulate the volume when i route audio via blackhole. What's the trick?

The volume level slider has no effect on the output stream either via the finder menu bar or the Audio Midi Setup app.

When I used Soundflower previously the volume level slider worked which was quite convenient.

**Comment by devinroth** [comment]
Make sure you have the latest version and try again.

**Comment by deeloke** [comment]
Thanks, Although I was running the latest version, I reinstalled via brew cask and the volume control works now.

**Comment by devinroth** [comment]
Strange. Well I’m glad that solved the problem.
