### ISSUE TITLE
ARD/VNC Support?

### ISSUE THREAD

**Issue by yokhoe** [ExistentialAudio/BlackHole#492]
Hello,
Is it possible for this utility to work via ARD or VNC protocols?  My institute is conducting research to serve remote desktop through Apache Guacamole.  It does have some support for PulseAudio, but it seems like (PA) support has been sparse since the release of MacOs a couple of versions ago.

**Comment by devinroth** [comment]
I’m not super familiar with ARD or VNC. Do you have some papers you can link to so I can read up on audio for those protocols.

I don’t see why BlackHole wouldn’t work for that but I just don’t know.

Devin

**Comment by orchetect** [comment]
ARD ([Apple Remote Desktop](https://apps.apple.com/app/apple-remote-desktop/id409907375))
VNC ([Virtual Network Computing](https://en.wikipedia.org/wiki/Virtual_Network_Computing))

What is the use case?

BlackHole is currently a local audio loopback driver only. Audio over network is different entirely and may be a planned feature in future but it likely will not have anything to do with ARD or VNC.

RealVNC supports "HD remote audio" and may be worth checking out first.
