### ISSUE TITLE
dosnt pick up Firefox

### ISSUE THREAD

**Issue by richmailYT** [ExistentialAudio/BlackHole#497]
Catalina 10.15.7 lastest blackhole, dosnt pickup firefox

**Comment by devinroth** [comment]
Can you test out this beta version?
[BlackHole2ch.v0.2.11-beta.pkg.zip](https://github.com/ExistentialAudio/BlackHole/files/7621476/BlackHole2ch.v0.2.11-beta.pkg.zip)

**Comment by richmailYT** [comment]
dosnt show anything. How DO you add apps?
