### ISSUE TITLE
Changer le nombre de canaux

### ISSUE THREAD

**Issue by monsieurtruc** [ExistentialAudio/BlackHole#50]
Bonjour et merci pour cette appli bien necessaire. Je voudrais utiliser Blackhole pour router 36 canaux audio. J'ai bien lu la notice qui propose de le faire mais je ne comprends pas la methode, en tout cas je ne trouve pas balckhole.h.
Pourriez vous m'éclaire svp
merci

**Comment by devinroth** [comment]
https://github.com/ExistentialAudio/BlackHole/blob/master/BlackHole/BlackHole.h

I don't recommend doing this if you don't have experience using Xcode. Best of luck.

**Comment by monsieurtruc** [comment]
Merci de votre réponse. 
Effectivement je n'ai pas la connaissance.  C'est si compliqué? Je ne comprends même pas ce que je dois faire avec ce code. 
N'avez vous une version du logiciel, déjà paramétré en 32 ou 36 sorties?

d'avance merci

**Comment by devinroth** [comment]
I plan on releasing a Pro version in the next month or so where you can easily configure the channels with a user-interface. Follow me on twitter and you’ll get notified when it’s out. 

I may need some beta testing done if you’re interested. 

Devin

**Comment by monsieurtruc** [comment]
Bonjour,
merci encore
oui je suis interessé de tester votre logiciel. Par contre je ne suis pas
sur tweeter, mais j'irais voir sur le site régulièrement.

Cordialement
Marc

Le mer. 5 févr. 2020 à 20:01, Devin Roth <notifications@github.com> a
écrit :
