### ISSUE TITLE
BlackHole disappeared and reappeared on Audio MIDI Setup every few days

### ISSUE THREAD

**Issue by bubbly-soul** [ExistentialAudio/BlackHole#508]
I'm updated my MacBook to Monterey quite some time ago.
BlackHole seems to disappear from my audio midi setup every few days. I usually record my classes with BlackHole and external headphones as aggregate device. 

<img width="297" alt="Screenshot 2021-12-16 at 7 41 59 PM" src="https://user-images.githubusercontent.com/96238936/146365808-c8e4b8cb-fa3b-4b9f-8dc7-f6f7ba124430.png">

3 days ago, I checked audio midi setup before recording and saw that BlackHole device disappeared from the list of sound output so I restarted the laptop and it reappeared. 
Today, before recording, I didn't think to open the audio midi setup app to check whether the BlackHole audio driver is there. I selected the aggregate device (BlackHole and external headphones) thru the Sound Preferences before recording.. to find out that the video recording picked up only the external audio and not internal audio. 

It reappears again about 4 hours or so after I finished the recording. I know that if I checked audio midi setup before recording and restarted the laptop, the video recording would have picked up the internal audio but I'm just wondering, is it a compatibility thing with Monterey that cause this or is it something that I have set up wrongly? It is hectic to always open up audio midi setup to check if BlackHole is there and restart my laptop if it isn't..

<img width="723" alt="Screenshot 2021-12-16 at 7 41 35 PM" src="https://user-images.githubusercontent.com/96238936/146365793-172ca8c4-9dd5-4853-b330-a1c24bf32354.png">
(BlackHole appears after a few hours of disappearing)

<img width="663" alt="Screenshot 2021-12-16 at 7 41 47 PM" src="https://user-images.githubusercontent.com/96238936/146365804-bc7e8fbd-be89-4755-9007-03e495841292.png">

**Comment by gchilds** [comment]
Check the crash logs

**Comment by bubbly-soul** [comment]
<img width="729" alt="Screenshot 2021-12-30 at 10 00 54 PM" src="https://user-images.githubusercontent.com/96238936/147758607-88905076-9ce6-4f55-97b9-6563de1d187c.png">
sorry for the delayed reply. it disappeared again today so I checked the logs but I didn't see anything..

**Comment by RomanCastroG** [comment]
This have been happening me as well. It seems to disappear on system restart. Really annoying. I usually reinstall again but it is quite a nuisance. 

I am on a M1 Mac mini running Monterey

**Comment by devinroth** [comment]
Every time you restart?

Devin Roth

**Comment by RomanCastroG** [comment]
Yes from what I can tell. I usually leave my mac running for a couple of days to a week and that's usually when it happens. I just finished reinstalling but will keep note on when it happens again.

**Comment by gtutunaru** [comment]
Happens to me as well, even after reinstalling. Didn't find any crash logs

**Comment by niugm** [comment]
I had the same problem

**Comment by devinroth** [comment]
Should be solved with 0.4.0. Reopen if you continue to have issues.
