### ISSUE TITLE
OBS/Mac/Catalina Help

### ISSUE THREAD

**Issue by Fortis-create** [ExistentialAudio/BlackHole#51]
Hey all, so I don't know where down the workflow this is not working but I can't seem to get this to work with OBS. 

For output device in OBS, Blackhole is not listed. OBS is listed as a microphone source in Privacy and Security.

Any help would be appreciated!

**Comment by Fortis-create** [comment]
Essentially, what I would like to do is to route audio from the Desktop or a program into Blackhole and then into OBS for live/recorded output.

**Comment by devinroth** [comment]
Unfortunately I don’t use OBS so hopefully someone will chime in. If I get some time over the next week I’ll download it and try to setup a guide in the wiki.

**Comment by Fortis-create** [comment]
Thanks

**Comment by devinroth** [comment]
Haven’t had a chance to take a closer look yet but i found this video.  Might be helpful. https://www.youtube.com/watch?v=miexiUIusts

**Comment by Fortis-create** [comment]
Thanks! The video got me through halfway. As I am only using a YETI microphone and not an external device like in the video, I had to do a few tests to get it work, but it worked! 

Thanks so much!

**Comment by devinroth** [comment]
Awesome. You’re welcome.
