### ISSUE TITLE
New installer does not appear

### ISSUE THREAD

**Issue by OPStellar** [ExistentialAudio/BlackHole#511]
The external link to ExistentialAudio only returns version 0.2.1. The advance installation instructions show a .pkg for version 0.2.2, and there's nothing but source code for version 0.3.0
Something needs to be updated, it seems.
Also, the front page does not list the 64-channel uninstaller, though I was able to obtain it by changing the url that the other two uninstallers linked to.

**Comment by devinroth** [comment]
Yup. I just released v0.3.0 but haven’t updated website or anything else yet. Taking some time off for Christmas.

I’ll get to it after Christmas. Check back in a couple weeks. I plan on streamlining everything so my life is easier.

Devin

**Comment by yujinqiu** [comment]
@devinroth Have a nice Christmas,  and thanks for your great effect.

**Comment by lukestein** [comment]
Thanks @devinroth and no request to rush. One thing that would be easy and nice might be adding the available version number to the Installer Download Request website; that way we wouldn't have to keep re-adding our email address and waiting for a new download link to see if the update has been posted ;)

**Comment by orchetect** [comment]
Duplicate - moved to discussion: #484
