### ISSUE TITLE
Noises in recording after about 10 to 11 mins

### ISSUE THREAD

**Issue by tsuyurinana** [ExistentialAudio/BlackHole#512]
Hi all,

I was able to install and setup BlackHole to record sound with QuickTime player on a MacBook Air running macOS Big Sur 11.5.2. However, the recorded audio is distorted by noises after 10 to 11 mins.  I tested quite a couple times and noise always starts after that time range. Does anyone run into the same issue or know how to fix it?

thanks in advance

**Comment by devinroth** [comment]
Audio drift.

Check the fAq.

Devin

**Comment by tsuyurinana** [comment]
> Audio drift. Check the fAq. Devin
> […](#)

thanks for the reply. using audio drift as a keyword and I found related FAQs. 

for anyone stumble upon this post, if you have the same issue, just go to Audio Midi Setup and tick the drift correction box next to the audio device named as BlackHole
