### ISSUE TITLE
Issues compiling with XCode

### ISSUE THREAD

**Issue by TheRico12** [ExistentialAudio/BlackHole#517]
Hi,

I'm encountering some issues while compiling the code with XCode.
I'm just following the wiki and changing the name of the instance, nothing elese... 
Any clues?

Thanks in advance

<img width="1434" alt="Schermata 2022-01-07 alle 23 59 54" src="https://user-images.githubusercontent.com/77631741/148618049-7916531d-4e34-42e9-8fa9-1040f6e6bcd7.png">

**Comment by devinroth** [comment]
Just a warning. It still compiles. Just ignore it.

Devin Roth

**Comment by TheRico12** [comment]
Thank you so much!
