### ISSUE TITLE
BlackHole gets forgotten

### ISSUE THREAD

**Issue by yourule** [ExistentialAudio/BlackHole#52]
Hi, I love your piece of work. I'm using is to route audio from Ableton Live to my own application written in cycling 74 Max. It works perfect. When I quit all applications and restart them all audio is still routed from one to the other application. But when I close the lid of my macbook Live forgets BlackHole was the selected audio output device. So I tried making an aggregated audio device with just BlackHole in this device selected, but then still Live forgets this Aggregated device when I close the lid. I'm letting other people work with this setup who are not aware live's in the background. You can imagine I don't want to send them to the live preferences every time they close the lid of their Macbook.  I'm on a late 2019 16" Macbook Pro which shipped with Catalina (10.15.3)

FYI I also posted this question with Ableton.

But again, what great work have you done!

**Comment by devinroth** [comment]
That annoying. I’m 99.9% sure that an Ableton bug. There seems to be no issues like that on other daws.

**Comment by devinroth** [comment]
Okay it looks like I was wrong. Looking into it.

**Comment by devinroth** [comment]
@yourule I fixed it! See #54. It would be great if you are able to test it out. The fix is on the dev branch.

**Comment by yourule** [comment]
@devinroth Sorry for my late reply. I wanted you to know that installing 0.2.6 resolved this problem for me. Thank you very much!

**Comment by yourule** [comment]
> @yourule I fixed it! See #54. It would be great if you are able to test it out. The fix is on the dev branch.

Thank you, this fixed the problem for me.
