### ISSUE TITLE
Level drop after about 2 seconds

### ISSUE THREAD

**Issue by jmcbade** [ExistentialAudio/BlackHole#525]
Using the latest code as of today: 1-25-2022 with Audition.  After about 2 seconds, the level drops.  I don't have any limiters on that I know of.

**Comment by devinroth** [comment]
Does the volume change on the BlackHole audio device in Audio Midi Setup?

Can you compare the volume output with another DAW such as Audacity and compare?

Devin

**Comment by jmcbade** [comment]
I don't see a change in the MIDI Setup.  If I start the record again, it starts high and reduces again.  I don't use Audacity but I do use Studio One.  I guess I could also test with Garage Band. 

I'll test and let you know.

**Comment by devinroth** [comment]
Record on both at the same time and compare.

Devin

**Comment by jmcbade** [comment]
I tried Garageband and it doesn't happen.  Must be something in Audition.  Sorry for the distraction.  Thanks for responding right away.  Top notch sir :)

**Comment by Ahmed-su-do** [comment]
import server
server =mol{4444. 9602}
int
set string
while
tabel is stable
a=33
b=22
{a&b}÷server=ghlogin


في الأربعاء، ٢٦ يناير ٢٠٢٢ ٣:٢٤ م Ahmed Ahmed elkholy <
***@***.***> كتب:

> Dear
> The debugging
> Is so awesome keep going
> The error in the line 357.44
> You try to add to it simple Colon
> Wish to you best hacking
>
> في الثلاثاء، ٢٥ يناير ٢٠٢٢ ٨:٣٧ م Devin Roth ***@***.***>
> كتب:
>
>> Does the volume change on the BlackHole audio device in Audio Midi Setup?
>>
>> Can you compare the volume output with another DAW such as Audacity and
>> compare?
>>
>> Devin

**Comment by Ahmed-su-do** [comment]
Dear
The debugging
Is so awesome keep going
The error in the line 357.44
You try to add to it simple Colon
Wish to you best hacking

في الثلاثاء، ٢٥ يناير ٢٠٢٢ ٨:٣٧ م Devin Roth ***@***.***> كتب:

> Does the volume change on the BlackHole audio device in Audio Midi Setup?
>
> Can you compare the volume output with another DAW such as Audacity and
> compare?
>
> Devin

**Comment by bell86103** [comment]
I am having this issue even when BlackHole is not selected as an input or output device.  Just listening to music in iTunes, every time I audio resumes there is 2 seconds at a higher level then it drops.
