### ISSUE TITLE
FaceTime in Monterey 12.1 does not see BlackHole as a Mic Input

### ISSUE THREAD

**Issue by chazzzzy** [ExistentialAudio/BlackHole#526]
Hi, It appears that since Monterey update 12.1 (possibly earlier, not sure), FaceTime will not recognize BlackHole as a Mic input. It sees it as an Output, just not as a Mic Input. If I create an Aggregate device with Blackhole as the device and choose that as the Mic in FaceTime, FaceTime will not hear anything. 

I'm on a MacMini M1 chip Mac.

Thanks,
Charles

**Comment by chazzzzy** [comment]
Additional info on BlackHole not being recognized as a mic input by FaceTime in Monterey 12.1.

I installed BlackHole 2ch again like people in the past who had troubles when updating versions in Monterey before did to get things working. Still does not see BlackHole 2ch. It sees an Aggregate Device with only BlackHole 2ch as the device, but no sound passes through.

I tested it on QuickTime and QuickTime recognizes BlackHole no problem when recording a movie.

The reason why I'm trying to get BlackHole to work is that I'm trying to introduce Audio Delay (Sample Delay) into the audio that goes into my FaceTime as I have a DSLR as my camera and there is a noticeable video delay with the audio.

I am using GarageBand (or Hosting Au) to make the audio delay outputting to BlackHole 2ch following the procedure you have listed on the Existential Audio website on how to use GarageBand with FaceTime.... to output everything to BlackHole and then use BlackHole as the Mic input in FaceTime.

Those instructions just don't appear to work anymore with Monterey 12.1.

Thanks!

**Comment by z1r0-** [comment]
I can confirm this. But I believe it's a Facetime bug. Because I have the same problem with other **real** USB devices, too. Some show up, some (like Elgato Wave:3 mic) don't (or only as output). The devices work flawless in other apps and show up as input devices in sound-settings but not in Facetime. And even if I set Facetime to use "System Default" and set it to my Wave:3 it will use some other input device.. I submitted a bug through their feedback app and hope they'll fix it soon..

**Comment by devinroth** [comment]
Confirmed. I've also see this problem. But as @z1r0- said, it affects other devices too. It looks like the only devices that are listed are input only devices.

**Comment by chazzzzy** [comment]
I can confirm what @z1r0- says, I updated to 12.3 today and it fixed all the input issues (including with the RodeCaster Pro Stereo inputs as well.)

Woo hoo!

**Comment by devinroth** [comment]
Yup. I updated to 12.3 and it appears that Apple fixed the bug!
