### ISSUE TITLE
Audio stutter with external DAC

### ISSUE THREAD

**Issue by kyrregjerstad** [ExistentialAudio/BlackHole#528]
Hi! 

I got an issue with audio stuttering while using BlackHole. The strange thing is that it's only occurring when I'm monitoring through my Audio Quest Dragonfly Cobalt DAC. The stuttering occurs before the output in the signal flow, so I don't believe it's coming from the DAC itself.  I've tried both the 2ch and 16ch versions.

My signal flow is: 
MacOS > BlackHole 2ch > Ableton Live > Dragonfly > Headphones

If I record the output from BlackHole in Ableton the stuttering is already in the recording, but it only happens when I monitor through the Dragonfly. If I use my Mac's headphones out it does not occur (or very seldomly) and if I monitor directly from MacOS > Dragonfly I also don't get the stuttering.

I have tried different buffer sizes in Ableton Live as well, without any success.  

It does not seem to be performance-related since I can do heavy multitasking in the background without any issues and Ableton's CPU meter is idling around 10%.

I've attached a quick recording below to help diagnose, where you can hear the stutter 3 times.

https://user-images.githubusercontent.com/98534972/151699029-9f13fc50-43dc-4366-a5b2-e92cb2fd70ed.mov

<img width="698" alt="Screenshot 2022-01-30 at 13 02 24" src="https://user-images.githubusercontent.com/98534972/151698809-9e31d292-a3f4-43a8-ab87-b198b1fbede2.png">

**Comment by devinroth** [comment]
Could you do a sanity check and test this on Logic or Garageband? There has been some wonky stuff with Abelton and M1.

**Comment by kyrregjerstad** [comment]
Wow, monitoring through Logic totally solved the issue! Thanks!
