### ISSUE TITLE
Channel configuration is not stored in Audio MIDI Setup

### ISSUE THREAD

**Issue by phud-eppu** [ExistentialAudio/BlackHole#53]
When I am configuring BlackHole's output as surround device (e.g. 5.1) in speaker configuration of macOS Audio MIDI setup, the channel order is not stored, it always goes back to 1:L , 2:R and other channels are not assigned. My OS is Sierra (10.12.6).

btw. BlackHole is awesome! Great job!

**Comment by devinroth** [comment]
I think I might know why. I’ll look into it.

**Comment by devinroth** [comment]
Fixed. Currently in the dev branch.
