### ISSUE TITLE
How to upgrade to v0.3.0 via Homebrew?

### ISSUE THREAD

**Issue by TJDev** [ExistentialAudio/BlackHole#531]
I have installed Blackhole via Homebrew and wanted to upgrade it, but it is still listed as v0.2.10

How can I upgrade to version 0.3.0?

**Comment by devinroth** [comment]
Don’t have 0.3.0 on Homebrew yet. Working out a couple kinks.

Devin Roth

**Comment by orchetect** [comment]
Duplicate - moved to #484
