### ISSUE TITLE
Black Hole suddenly stopped working, not sure why

### ISSUE THREAD

**Issue by Kaevonb** [ExistentialAudio/BlackHole#535]
Hey, I'm a music producer and DJ and have been using BlackHole both to route Rekordbox (DJ software) to OBS and to screen record Ableton (a DAW) with audio successfully for a few weeks. Suddenly none of these things are working anymore, and I'm not sure why--the only change I made recently was installing the software Wine and Wine Bottler, but I'm not sure why that would affect this. Below are my settings. I'm on Mac High Sierra 10.13.6. 

Thanks for your help 

![Screen Shot 2022-02-07 at 5 42 52 PM](https://user-images.githubusercontent.com/99228571/152902588-169d6d01-4085-42d1-8732-af32b0d8ea86.png)
![Screen Shot 2022-02-07 at 5 43 27 PM](https://user-images.githubusercontent.com/99228571/152902592-c5f2d470-0460-471c-a1b9-9047901af7a7.png)

**Comment by maximeg** [comment]
I'm doing a lot of brew reinstall those days to have it working again

**Comment by devinroth** [comment]
I’ve been told the latest 0.3.1 fixes this. Are you able to build and test?

Devin

**Comment by devinroth** [comment]
That just sounds like you don’t have mic permissions set.

Devin

**Comment by dusiema** [comment]
> 



> 

You mean in Security&Privacy -> Microphone and then choose the app that wants to access the mic? 
I tested it using Zoom and Google Meet. Both are in that list. 
Or is there another "mic permission" that you refer to?

**Comment by dusiema** [comment]
I also tried a `sudo chown -R root /Library/Audio/Plug-Ins/HAL/BlackHole.driver` (and restarting CoreAudio) but that also did not help. 

<img width="763" alt="image" src="https://user-images.githubusercontent.com/1201607/157909522-27033536-37ee-4df2-8ebe-a0dd67bdafe8.png">

I can change between external mic, internal macbook mic and blackhole 2ch in the Audio Devices. Whatever device is the first in the list (with a checkmark) comes through but nothing else...

**Comment by devinroth** [comment]
Are you using any other apps with BlackHole?

Devin

**Comment by dusiema** [comment]
Not that I would be aware of. Is there any way I could check this?

**Comment by dusiema** [comment]
I also tested using Garageband and taking a recording from the aggregated device.
But it shows the same result. Only the first item in the list of aggregated devices comes through.

**Comment by devinroth** [comment]
>  Only the first item in the list of aggregated devices comes through. 

That's how aggregates work. It doesn't combine them like multi-outputs. And GarageBank only takes the first 2 channels.

**Comment by dusiema** [comment]
Oh, I didn't know that. But thank you very much for your help and for offering blackhole as open source! 
(And sorry for kind of hijacking this issue.)

**Comment by devinroth** [comment]
Closing. Reopen a new issue if there's still problems with the latest release. v0.4.0.
