### ISSUE TITLE
Play through with noise after a few minutes

### ISSUE THREAD

**Issue by niugm** [ExistentialAudio/BlackHole#539]
Hi, I need some guidance, I use BlackHole as the default output device, then use a PlayThrough Process as playback, the path of the audio stream is Music APP -> BlackHole-> CAPlayThrough -> Physical device.

The current problem is, after N minutes, listen to there will be noise in the resulting sound, then the noise will gradually increase, and finally there will be no sound at all.

About The N value: 

1、On devices with i7 CPU, the N is greater than devices with i5 CPU.
2、When increase the kDevice_RingBufferSize value, the N will be increase, but there is no rule found.

I want to know:

1、What the differents between kDevice_RingBufferSize and kRing_Buffer_Frame_Size？
2、Is it the right way to adjust kDevice_RingBufferSize? 
3、The suggested value range is?

CAPlayThrough is mac's example app
[CAPlayThrough](https://github.com/jasminlapalme/caplaythrough-swift)

When I recreate the play through instance, playback returns to normal, but after N minutes, the noise is back

I don't have much knowledge in audio direction, hope to get help, thanks a lot

PS: on my MBP(2015 i7), even if it runs for a few hours for a long time, there is no problem, i don't know why

**Comment by devinroth** [comment]
CAPlayThrough sucks. Don’t use it.

Also certain code it in is deprecated so it won’t work with latest OS.

**Comment by niugm** [comment]
> 

Someone refactored this program using swift 5, now it can work on my macOS Monterey 12.2.1. I think it's the CAPlayThrough's problem, but don't know how to fix it

**Comment by devinroth** [comment]
Oh it’s definitely CAPlayThrough. The drift correction they use wasn’t well done. I wrote my own drift correction and it’s flawless with BlackHole.

Believe me, this isn’t a BlackHole issue.

**Comment by niugm** [comment]
> Oh it’s definitely CAPlayThrough. The drift correction they use wasn’t well done. I wrote my own drift correction and it’s flawless with BlackHole. Believe me, this isn’t a BlackHole issue.
> […](#)
> On Feb 15, 2022, 6:53 PM -0800, niugm ***@***.***>, wrote: Someone refactored this program using swift 5, now it can work on my macOS Monterey 12.2.1. I think it's the CAPlayThrough's problem, but don't know how to fix it — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Thank you very much for your reply, BlackHole is a great project, any suggestion for the value range of kDevice_RingBufferSize?

**Comment by chenyangxx** [comment]
I met the same situation. Have you solved it?

**Comment by chenyangxx** [comment]
@niugm
I met the same situation. Have you solved it?
