### ISSUE TITLE
Blackhole2ch not working on Monterey 12.3.1

### ISSUE THREAD

**Issue by Ethkeef** [ExistentialAudio/BlackHole#548]
I have just updated my iMac M1 to Monterey 12.3.1 and unfortunately blackhole is no longer working, when i try to screen record via quicktime and when i play it back i am not getting any audio. the audio MIDI is set up and sound input and output is set to multi-output device and input is blackhole 2ch.

Any suggestions? or does Blackhole no longer work with this update.

**Comment by devinroth** [comment]
It works fine.
Try just uninstalling and reinstalling.

Devin

**Comment by Ethkeef** [comment]
tried that, i will try again now and let you know.
