### ISSUE TITLE
Way to lock or set a maximum channel volume

### ISSUE THREAD

**Issue by zboralski** [ExistentialAudio/BlackHole#549]
It would be nice to have a way to lock the channel volume at for example -18db... 

I use Ableton as a live mixer and anyone can play to the Blackhole 2ch input... However there is no way to remove the Sound widget from the control centre and sometimes people have the habit of going there to increase the volume.

If you give me some pointers on how you think this should be implemented I'll be happy to submit a PR.

**Comment by devinroth** [comment]
Probably a toggle button that shows up in Audio Midi setup that connects to an internal bool. Then change the current volume settings to read only. 

Honestly I don't know how many people would use this feature. It's a decent amount of work to do it right. It would probably just be simpler for you to just hard code it for your own personal use. Take a look at https://github.com/ExistentialAudio/BlackHole/blob/67f2510109f1b6a144ca10207e3179a47ea164e6/BlackHole/BlackHole.c#L3817 . 

You could easily hard code a specific volume.
