### ISSUE TITLE
can't uninstall on monterey m1

### ISSUE THREAD

**Issue by ospop** [ExistentialAudio/BlackHole#557]
installed through brew and now I can't uninstall it, ran the code correctly replacing the x, tried the other alternatives on the wiki, refreshed audio drivers, even restarted my device a few times but it still shows on 'brew list' under casks

**Comment by devinroth** [comment]
Is it actually still installed or just still listed in casks?

Devin

**Comment by ospop** [comment]
nevermind, 'brew uninstall' worked, it doesn't show up anymore
thanks for the quick reply
