### ISSUE TITLE
Unable to bump version on Homebrew due to the Package not being available on server

### ISSUE THREAD

**Issue by phao5814** [ExistentialAudio/BlackHole#561]
The current version of Blackhole on Homebrew is v0.2.10.

I wanted to update to the latest version of Blackhole, which is version 0.3.0 so I decided to try bumping the version using the following Homebrew command (as outlined by the [Homebrew documentation](https://nicedoc.io/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md)):

`brew bump-cask-pr --version=0.3.0 blackhole-2ch`

However, I got the following error:

> ❯ brew bump-cask-pr --version=0.3.0 blackhole-2ch
> ==> Downloading https://existential.audio/downloads/BlackHole2ch.v0.3.0.pkg
> curl: (22) The requested URL returned error: 404
> 
> Error: Download failed on Cask 'blackhole-2ch' with message: Download failed: https://existential.audio/downloads/BlackHole2ch.v0.3.0.pkg

It appears `https://existential.audio/downloads/BlackHole2ch.v0.3.0.pkg` does not exist on the server. I have independently confirmed this with `curl` as well.

Would you be able to update the server with the new package and also update Homebrew formula to the latest version? Super keen to use the latest version! :)

**Comment by trevormeier** [comment]
I also ran into this issue today. It'd be great to get the latest on Brew!

**Comment by devinroth** [comment]
0.2.x is still the most stable. I’ll update brew when I release 0.4.0.

Devin Roth

**Comment by orchetect** [comment]
README has been updated to clearly show that latest Homebrew release is BlackHole 0.2.10. It will be updated when the new version ships.
