### ISSUE TITLE
Channels 3-16 silent

### ISSUE THREAD

**Issue by MrSimmo** [ExistentialAudio/BlackHole#563]
Ignore this - couldnt find a way to delete the post

**Comment by devinroth** [comment]
I’m pretty sure that’s a limitation of ffmpeg. Record with something else to test but I’ve run that issue before.

Devin

**Comment by MrSimmo** [comment]
> I’m pretty sure that’s a limitation of ffmpeg. Record with something else to test but I’ve run that issue before. Devin
> […](#)

Cheers; I found the issue - was a configuration problem with the Apple audio/midi settings app - it want applying the 7.1 speaker setup properly, managed to get it to force save the settings and it all started working fine.
