### ISSUE TITLE
MacBook Pro 14 inch - problem with driving high impedance headphones

### ISSUE THREAD

**Issue by mrxiatix** [ExistentialAudio/BlackHole#566]
### Discussed in https://github.com/ExistentialAudio/BlackHole/discussions/565

<div type='discussions-op-text'>

<sup>Originally posted by **mrxiatix** May 16, 2022</sup>
Hi,
My problem is a quite strange one... I have a pair of 80 ohm dt770pros which I use basically all day with my MacBook Pro. In order to put a systemwide equalizer on the Mac, ,I use BlackHole paired with Hosting AU, where I use the AUNbandEQ. Here is where my problems begin. If as audio output I use 'external headphones' the sound of the headphones is perfectly fine, since the Mac recognises the impedance of  and delivers enough power to drive them, however when I pass the audio through BlackHole, the headphones don't get enough power and they sound empty and not loud enough. How can this be solved? </div>

**Comment by devinroth** [comment]
Do you have the volume of BlackHole all the way up?

Devin

**Comment by mrxiatix** [comment]
Hello, yes! I put the volume of external headphones all the way up before passing it through hosting AU and then modulate the volume as normal with blackhole so that max volume blackhole = max volume external headphones. The thing is that the MacBook Pro 14 inch has an adjustable voltage range output on the 3.5mm jack depending on the ohm value of the headphones you plug in. Being mine 80 ohms it draws more volts than when powering a regular 32 ohms one. I fear that passing the audio from blackhole is making it so that the Mac does not detect the ohm value of the headphones and powering them in the 'normal' way.

**Comment by mrxiatix** [comment]
> Do you have the volume of BlackHole all the way up? Devin
> […](#)
> On May 17, 2022, 12:59 PM -0700, mrxiatix ***@***.***>, wrote: Discussed in #565 Originally posted by mrxiatix May 16, 2022 Hi, My problem is a quite strange one... I have a pair of 80 ohm dt770pros which I use basically all day with my MacBook Pro. In order to put a systemwide equalizer on the Mac, ,I use BlackHole paired with Hosting AU, where I use the AUNbandEQ. Here is where my problems begin. If as audio output I use 'external headphones' the sound of the headphones is perfectly fine, since the Mac recognises the impedance of and delivers enough power to drive them, however when I pass the audio through BlackHole, the headphones don't get enough power and they sound empty and not loud enough. How can this be solved? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Hello, yes! I put the volume of external headphones all the way up before passing it through hosting AU and then modulate the volume as normal with blackhole so that max volume blackhole = max volume external headphones. The thing is that the MacBook Pro 14 inch has an adjustable voltage range output on the 3.5mm jack depending on the ohm value of the headphones you plug in. Being mine 80 ohms it draws more volts than when powering a regular 32 ohms one. I fear that passing the audio from blackhole is making it so that the Mac does not detect the ohm value of the headphones and powering them in the 'normal' way.

**Comment by devinroth** [comment]
We’ll if the volume going out of BlackHole is all the way up then it’s has to be something else. BlackHole doesn’t output audio to your headphones at all so unfortunately your question is beyond the scope of this project. Can’t really help you beyond that but perhaps point you in the right direction. I would look into whatever app you are using to output audio to your headphones.

Best of luck getting to the bottom of this.

Devin

**Comment by mrxiatix** [comment]
> We’ll if the volume going out of BlackHole is all the way up then it’s has to be something else. BlackHole doesn’t output audio to your headphones at all so unfortunately your question is beyond the scope of this project. Can’t really help you beyond that but perhaps point you in the right direction. I would look into whatever app you are using to output audio to your headphones. Best of luck getting to the bottom of this. Devin
> […](#)

Thank you very much for your help. I will try asking in the forums of Hosting AU if anyone else has this issue.
