### ISSUE TITLE
Blackhole stopped working with last MacOS update 12.4

### ISSUE THREAD

**Issue by whydiditstopworking** [ExistentialAudio/BlackHole#572]
I try to record system audio but all I hear is what's picked up by the microphone.

I tried reinstalling the package and creating a MIDI multi-output device, but I get the same result (no system audio, just what's picked up by the microphone).

**Comment by devinroth** [comment]
You’re obviously recording mic and not black hole. Make sure that your input is set to black hole.

Devin Roth

**Comment by whydiditstopworking** [comment]
I did that also, or course. Before that last update, all I had to do was set output to Blackhole and it worked great. Since last week's MacOS update (12.4), I tried all kinds of system preference combinations and I always get the same result, just what's picked up by the microphone.

**Comment by devinroth** [comment]
Sounds like an issue with the recording program. BlackHole does not capture or even access the microphone of your computer.

Devin Roth

**Comment by whydiditstopworking** [comment]
Thanks Devin, that was it. I guess the MacOS update modified QuickTime capture settings.

(I see you're a fellow jazz enthusiast. I used to play tenor sax for a living. Favorite jazz pianist ?)

**Comment by devinroth** [comment]
Top influences are probably Herbie, Bill, McCoy. But I also really dig Robert Glasper and Brad Mehldau. It’s a really long list.

Devin Roth

**Comment by whydiditstopworking** [comment]
Herbie and McCoy also come to mind first for me. Thanks again Devin.

**Comment by orchetect** [comment]
Have to say I love the dedication. 😂 Welcome to GitHub.

![Screen Shot 2022-06-03 at 3 11 18 PM](https://user-images.githubusercontent.com/11605557/171960947-00e4a4c4-3679-42d6-94b3-5514838d8e76.png)
