### ISSUE TITLE
Website Down?

### ISSUE THREAD

**Issue by alexchang-wdc** [ExistentialAudio/BlackHole#573]
Hi there,

For people wanting to download the installer/binaries, is there an alternative source where we can get BlackHole? It seems like the website to the installer is down, and Brew equally does not work for me. If anyone had suggestions, it would be greatly appreciated!

Cheers,

**Comment by sunknudsen** [comment]
Looks like website is back up.

**Comment by devinroth** [comment]
It's working now.
