### ISSUE TITLE
Multiple Input on Aggregate Device

### ISSUE THREAD

**Issue by mafulafunk** [ExistentialAudio/BlackHole#59]
Maybe I'm misunderstanding something.

Situation: In Skype I'd like to pick up form an USB-Mic and an application like QuickTimePlayer.

Skype is configured to use an Aggregate Device as its Microphone.

I can configure the Aggregate Device that it picks up the USB-Mic or the QuickTimePlayer, but never both!

Which one gets picked up depends on their order in the Aggregate Device config. Whatever is configured right after the Build-in Output gets taken.

In this case it is the Rode Podcaster Mic.

<img width="1049" alt="Screenshot 2020-02-11 at 18 27 46" src="https://user-images.githubusercontent.com/99756/74262811-e293df00-4cfd-11ea-8b82-c57abead1179.png">

**Comment by devinroth** [comment]
Use a multi output device instead.

**Comment by mafulafunk** [comment]
Multi output devices are not selectable as a Microphone for Skype.
<img width="568" alt="Screenshot 2020-02-12 at 08 51 43" src="https://user-images.githubusercontent.com/99756/74314095-27a72800-4d75-11ea-8597-b628e3e71695.png">

**Comment by devinroth** [comment]
Ah sorry I think I miss understood your question then. You'll need to mix Your Rode and BlackHole into the same 2 channels.

**Comment by devinroth** [comment]
We'll need add another program into the mix to do it. I'll think up a solution for you.

**Comment by devinroth** [comment]
If you have a daw like Logic Pro or Garage Band you would be able to mix the signals. That's what I do. Should work with Audacity too.
