### ISSUE TITLE
Question about Screen Recording

### ISSUE THREAD

**Issue by YujiShen** [ExistentialAudio/BlackHole#6]
Found this project when trying to use SoundFlower on Catalina. Thanks for developing!

Is it possible to use BlackHole to record audio when record screen using system recording tool (QuickTime Player) and also can listen to system audio from speaker? Currently I have to set output as BlackHole in both Sound and Screen Recording to record system audio. But I can not hear system audio under this situation.

Compared to other screen recording tools like Snagit and ScreenFlow, I found they both have slight latency in sound for recording system audio. There is no latency when using BlackHole with QuickTime. However, can not listen to audio is a problem.

**Comment by devinroth** [comment]
You can setup a multi output. 

https://github.com/ExistentialAudio/BlackHole/issues/1#issuecomment-543914337

**Comment by YujiShen** [comment]
Thanks! It works! Is it possible to adjust volume of Multi-output device?

**Comment by devinroth** [comment]
No. Apple doesn’t let you. But I believe you can adjust individual volumes in Audio Midi setup.

**Comment by YujiShen** [comment]
Got it. Thanks!
