### ISSUE TITLE
Audio drops and crackles

### ISSUE THREAD

**Issue by orchetect** [ExistentialAudio/BlackHole#600]
## Originally posted by @designerfuzzi in #444. Moved to new Issue.

No matter what amount of channels i compile and use then i get audio drops and cracles each 3 - 5 minutes that disappear after about 5 seconds and come back again..
Tried to change settings to system Samplerate (MacBookPro 2009) 44100.0f but it falls back to 48.000 .. guessing there is a buffer issue in code. Drift correction is not available when using with Ableton, because then you route directly..

my Setup routing is 
> Ableton Master Out 1&2
>> Blackhole 16ch on 1&2
>>> Into my own Audio App catching Blackhole Device via CoreAudio
>>>> From there Output to External Audio Device..

It works fine, just the crackles now and then..

As i can record the Blackhole Output in my App i can even record the crackles.. meaning they appear between
 Ableton and Blackhole and HAL system not down the chain..

Maybe good to mention that the crackles are the same when the system plays out from Blackhole

**Comment by devinroth** [comment]
Going to close. Reopen if there continues to be issues.

**Comment by araujobarret** [comment]
I have the same issue, my setup is a bit different but I was using something simple like:
- Logic Pro with Scarlett 2i2
- Blackhole 16ch in a multi-output device

Black channel 2ch or 16ch will break around 3-5 minutes using it, I also noticed in my audio midi settings when entering in this broken state the icon on my interface inside the multi-output device accordion in my midi settings: <img width="37" alt="image" src="https://user-images.githubusercontent.com/15792853/179258134-f32131e5-374a-431a-874f-04a78f056d71.png">

To make it back to work I have to do any dummy change in my audio settings in the DAW I'm using and apply(kinda re-establish connection with blackhole)
