### ISSUE TITLE
Brew requires a password on 0.4.0 install

### ISSUE THREAD

**Issue by amedve** [ExistentialAudio/BlackHole#618]
**Describe the bug**
Brew requires a password on 0.4.0 install

**Steps to Reproduce**
I have blackhole-2ch 0.2.10 installed.
`brew update && brew upgrade

**Expected behavior**
No password is required.

**Screenshots**
<img width="992" alt="image" src="https://user-images.githubusercontent.com/23156422/173249534-24e94d90-e459-447c-b5d5-1d42d27ad919.png">

**System Information**
Mac model: MacBook Pro (13-inch, M1, 2020)
macOS version: 12.4

**Comment by devinroth** [comment]
BlackHole requires a password to install in the HAL folder. This is any different from previous versions.
