### ISSUE TITLE
[MacOS 13 Ventura] No sound output

### ISSUE THREAD

**Issue by atanaskanchev** [ExistentialAudio/BlackHole#621]
**Describe the bug**
Does not work on MacOS 13 Ventura

**Steps to Reproduce**
Install BlackHole v0.4.0

**Expected behavior**
To have sound output coming out of the speakers

**Screenshots**
Please include screenshots of Audio MIDI Setup (BlackHole, your Multi-Output Device, etc.) and any app configuration windows in question.

**System Information**
Mac model: MacBook Pro 16 2021
macOS version: MacOS 13 Ventura

**Comment by devinroth** [comment]
Just tested on Ventura. Everything works fine with no issues. 

Please check the FAQ to see if it fixes your issues. https://github.com/ExistentialAudio/BlackHole#why-is-nothing-playing-through-blackhole

If you're continuing to have issues please post screenshots of your setup.
