### ISSUE TITLE
Audio cutting out until no audio except my mic

### ISSUE THREAD

**Issue by SOMESWITCHUSER** [ExistentialAudio/BlackHole#622]
**Describe the bug**
audio cutting out until no audio except my mic

**Steps to Reproduce**
I do not know exactly how to reproduce it, I was recording and when I checked on the footage, the audio got glitchier and glitchier until you heard no audio except my microphone

**Expected behavior**
Recording audio consistently with little to no glitches

**System Information**
Mac model: Macbook Air M1 2020
macOS version: 12.3.1

**Comment by devinroth** [comment]
Please read the faq. If you continue to have issues then reopen with steps to reproduce including which apps you use, routing, and screenshots.
