### ISSUE TITLE
I have installed Blackhole but it isn't showing up in Audio Midi Setup 

### ISSUE THREAD

**Issue by Sdavis333** [ExistentialAudio/BlackHole#625]
I have seen this previously reported but there didn't seem to be an answer. I am on Mac Book pro see screen shot below.  I tried restarting and installed all three versions but removed all but the basic 2ch now. 

I have screen shot below for you in terms of the questions you asked the previous person. Any help is greatly appreciated. 
![Screen Shot 2022-06-27 at 11 27 58 AM](https://user-images.githubusercontent.com/108296080/176010749-b9bda654-3283-4c42-9767-1ae60465004e.png)

![Screen Shot 2022-06-27 at 11 30 41 AM](https://user-images.githubusercontent.com/108296080/176010980-27330054-2a73-48ed-b7be-f510350a3a74.png)

**Comment by Sdavis333** [comment]
![Screen Shot 2022-06-27 at 11 33 04 AM](https://user-images.githubusercontent.com/108296080/176011415-d033370e-5e8d-4bc1-b91f-e87fd9000d48.png)

**Comment by devinroth** [comment]
What version of BlackHole? You can check in Library/Audio/Plug-Ins/HAL/BlackHole2ch.driver/contents/Resources/VERSION

**Comment by Sdavis333** [comment]
![Screen Shot 2022-06-27 at 11 47 40 AM](https://user-images.githubusercontent.com/108296080/176013708-1f87d59a-1b14-41b0-8c4a-5faed0e820e7.png)

**Comment by devinroth** [comment]
Show me the output of "ls -l /Library/Audio/Plug-Ins/HAL"

**Comment by Sdavis333** [comment]
![Screen Shot 2022-06-27 at 11 53 30 AM](https://user-images.githubusercontent.com/108296080/176014655-bcd03d80-7205-42fd-923c-f55043ed8987.png)

**Comment by devinroth** [comment]
What do you see when you Get Info on BlackHole2ch.driver from your first picture? Right click -> get info.

**Comment by Sdavis333** [comment]
You nailed it. It installed on my crucial exterior hard driver. That's the problem right? PS Thanks

**Comment by Sdavis333** [comment]
I moved all of my garageband audio files and that as well. THANKS!

**Comment by Sdavis333** [comment]
Hi guys,

Sorry for the delay in my reply I am editing right now and my hotmail isn't my primary email. Orchetect is correct and I used Symboliclinker. Thanks again for the help. Now all I need to do is find my internal microphone to finish using LOL. What you have probably already guessed is I know just enough about my computer to be dangerous and I am by no means at your level in terms of skill or knowledge. Having said that, thanks again! All the best s

**Comment by orchetect** [comment]
Symlinking can have unexpected effects, as not all software knows how to deal with them properly -- especially when you link a system folder like that. If possible, the Audio folder and everything in it should be put back in its original place without the link. Then if you have plugin content like sample libraries then those could be offloaded to another drive.

**Comment by Sdavis333** [comment]
Thanks and I appreciate it. I changed up my symlink to the folder and put it back into the folder yesterday. It now sees blackhole. I will check to see if I link the micro phone too. Really appreciate the heads up!

**Comment by hongshao361** [comment]
> Symlinking can have unexpected effects, as not all software knows how to deal with them properly -- especially when you link a system folder like that. If possible, the Audio folder and everything in it should be put back in its original place without the link. Then if you have plugin content like sample libraries then those could be offloaded to another drive.

Hello, I have the same problem, but my installation path is fine, it just doesn't show in MIDI. Please help me answer, thank you
![WeChat6fefeda8793c7b8d6a53a3e3d0af54b8](https://github.com/ExistentialAudio/BlackHole/assets/38657410/fca4f6d0-3e33-4ac2-8552-4a3909b68a29)

**Comment by hongshao361** [comment]
> Symlinking can have unexpected effects, as not all software knows how to deal with them properly -- especially when you link a system folder like that. If possible, the Audio folder and everything in it should be put back in its original place without the link. Then if you have plugin content like sample libraries then those could be offloaded to another drive.
![WeChat0db4d20c27fe0630b0608e0a53272336](https://github.com/ExistentialAudio/BlackHole/assets/38657410/752b9e6b-ee86-4c98-890d-5c2cee71d663)

**Comment by devinroth** [comment]
Try restarting.

Devin

**Comment by hongshao361** [comment]
> Try restarting. Devin
> […](#)

Hello, I have read issue 302,278. I pulled the code of the master branch from github, pulled it to the local, switched the certificate, changed the team ID in create_installer.sh, and generated the installation package after executing create_installer.sh. It is not displayed in MIDI after installation

**Comment by devinroth** [comment]
Why didn’t you say so earlier. You need to notarize the driver. You’ll even get an error in Console about that.

Devin

**Comment by hongshao361** [comment]
I'm sorry I didn't make myself clear.
I did report "Error: No Keychain password item found for profile: notarize" when executing the script
"
Because I don't know how to generate a notarytool keychain profile, but I notarized it this way, And success of the "xcrun notarytool submit/Users/hongshao/Downloads/BlackHole - master/Installer/BlackHole2ch. 2.0 PKG \
--apple-id support@hitecloud.net \
--team-id 74UGXPHK9S \
--password uchp-ycae-aoby-hrgq \
-v \
-f "json"”
![3746775494](https://github.com/ExistentialAudio/BlackHole/assets/38657410/ca8d2edf-7594-430c-81fc-10e80fd46882)

**Comment by devinroth** [comment]
@hongshao361 I just deleted your comment because you included your notarization password. Quickly go and change all your Apple ID passwords. it's possible that your developer ID has now been compromised. That was a massive mistake. Hopefully you can change your security before any damage is done.

**Comment by hongshao361** [comment]
Thank you for reminding me
I've created the notarytool keychain profile and notaryTool Keychain profile and there are no errors. But I still get an error when executing create_installer.sh and the installed PKG package is not displayed in MIDI
![813823029](https://github.com/ExistentialAudio/BlackHole/assets/38657410/55087431-beb6-4ac9-ade4-8ba44dbae6db)

**Comment by hongshao361** [comment]
May I ask if you can modify the name if you download your installation package? I have been failing to notarize now, but I need to modify the name
![2506776078](https://github.com/ExistentialAudio/BlackHole/assets/38657410/330253ad-bf6b-4e24-95c4-d0403149c15c)

**Comment by orchetect** [comment]
> But I still get an error when executing create_installer.sh and the installed PKG package is not displayed in MIDI ![813823029](https://user-images.githubusercontent.com/38657410/277254684-55087431-beb6-4ac9-ade4-8ba44dbae6db.png)

I noticed something strange in this screenshot. The installer script should not be producing a filename formatted as `BlackHole128ch.2.0.pkg` - did you modify anything in the create_installer.sh script other than the variables at the top of the file?

**Comment by hongshao361** [comment]
Yes, I changed the version number
![3504298186](https://github.com/ExistentialAudio/BlackHole/assets/38657410/32ca0824-d00d-45d3-9787-ca83aaf0997c)
If you don't modify it, it looks like this


[create_installer.sh.zip](https://github.com/ExistentialAudio/BlackHole/files/13068065/create_installer.sh.zip)

**Comment by orchetect** [comment]
Oh that's probably happening if you download the repo as a zip file instead of cloning the repo. The zip file doesn't include the hidden `.git` folder which provides the version tag that the script uses.

What if you try changing the version to "0.5.0" - does that succeed?

**Comment by hongshao361** [comment]
![image](https://github.com/ExistentialAudio/BlackHole/assets/38657410/80be482c-ddea-439b-bcfe-c65a08a752ed)
The result is the same
