### ISSUE TITLE
Multi-Output Device blocks tv decoder program (HDHomerun)

### ISSUE THREAD

**Issue by jswnhart** [ExistentialAudio/BlackHole#65]
If the audio output is set to Headphones, HDHomerun (silicondust.com) works normally decoding video and audio.

If the audio output is set to BlackHole 16ch, HDHomerun starts up and decodes video, but audio is silent.  I think this would be expected.

If the audio output is set to Multi-Output Device, HDHomerun is blocked and does not display the opening screens.  To close the program I must use the menu Quit option as the "X" does nothing.

![Screen Shot 2020-03-03 at 12 19 28 PM](https://user-images.githubusercontent.com/1922747/75811253-50ee1f00-5d49-11ea-979b-908be040da78.png)

**Comment by devinroth** [comment]
Unfortunately the multi-output is kind of buggy. Make sure BlackHole isn’t the first device in the list. 

https://github.com/ExistentialAudio/BlackHole/wiki/Multi-Output-Device#4-select-output-devices

Try that first to see if it solves the problem.

**Comment by jswnhart** [comment]
Yes, Built-in Output (Headphones) is first in the multi-output group.

**Comment by devinroth** [comment]
Does the multi-output work with other programs? Does it work if you use it as the default output?

**Comment by devinroth** [comment]
Does HDHomerun work with a multi-output using just the headphones?

**Comment by jswnhart** [comment]
For Software Defined Radio SDRUno audio out (Multi-Output) connects to WSJT-X audio in (BlackHole).  This works in both the Mac and Parallels Windows environments.

**Comment by devinroth** [comment]
Just to confirm. 

The multi-output works fine with other programs but not HDHomerun. Correct?

**Comment by jswnhart** [comment]
Correct

**Comment by devinroth** [comment]
Last question. 

Does HDHomerun work with a multi-output without BlackHole selected?

**Comment by jswnhart** [comment]
Yes, HDHomerun works as expected on Multi-Output Device when Blackhole is not selected.

**Comment by devinroth** [comment]
Are you using the latest version of BlackHole?

**Comment by jswnhart** [comment]
I think so - just updated this week. 
BlackHole v0.2.6 <https://github.com/ExistentialAudio/BlackHole/releases/tag/v0.2.6>
 <https://github.com/devinroth> devinroth <https://github.com/devinroth> released this 23 days ago · 180 commits <https://github.com/ExistentialAudio/BlackHole/compare/v0.2.6...master> to master since this release

**Comment by devinroth** [comment]
It doesnt make any sense unless they are blocking BlackHole. I’ll take a closer look.

Devin

**Comment by jswnhart** [comment]
Here is how Blackhole is set up

**Comment by jswnhart** [comment]
Meant to send this one too

**Comment by devinroth** [comment]
Sorry your photos didnt upload.

**Comment by jswnhart** [comment]
Screen shots again

**Comment by devinroth** [comment]
I don’t think works over email. Still nothing.

**Comment by jswnhart** [comment]
﻿
﻿
Looks like they are png format. 
Converted to jpeg

**Comment by devinroth** [comment]
I don't have HDHomerun so I don't think I can actually test this out. 

Does is work with other loopback devices?

**Comment by jswnhart** [comment]
The only other problem I have experienced is the program SongSurgeon occasionally  crashes. I am working with the developers and now testing with the headphone output and with the Multi-Output. So far I haven’t duplicated the crash with the Headphone output, but it's not definitive.

**Comment by devinroth** [comment]
Multi-outputs are buggy as hell. Most audio device makers will not support them. I completely understand.

Keep me updated.

**Comment by devinroth** [comment]
So it seems like some applications won't work with Multi-outputs. This is one of them.

**Comment by devinroth** [comment]
I'm going to add a list to the FAQ.
