### ISSUE TITLE
BlackHole issues with screenrecording Macbook Intel

### ISSUE THREAD

**Issue by dgraficoingevias** [ExistentialAudio/BlackHole#660]
### Please Confirm

- [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
- [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
- [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)

### macOS Version

macOS 12 Monterey

### BlackHole Build(s) Affected

- [X] 2 channel
- [ ] 16 channel
- [ ] 64 channel
- [ ] other/custom build

### Describe the bug

The built in mac screen record option immediately closes everytime i select blackhole as sound source, if i change it to none the screen records normally but not the other way.

I remember that i was able to record sound and screen with blackhole a while back, but now after some months passed cant.

Uninstalled, restarted, did the multi output on the Audio midi Setup again but i can't find a workaround.

Thank you for your work.

### Reproduction Steps

1. CMD + Shift + 5 
2. Option - Select BlackHole
3. Start Recording
4. Application Closes

### Expected Behavior

Record Screen with Audio using the application BlackHole.

### Screenshots

<img width="639" alt="Screen Shot 2022-09-21 at 10 31 02 AM" src="https://user-images.githubusercontent.com/114092022/191547177-cc57542c-e1a1-46ea-b8f9-9bf9a9146693.png">
<img width="288" alt="Screen Shot 2022-09-21 at 10 31 24 AM" src="https://user-images.githubusercontent.com/114092022/191547209-dba06220-ed86-4278-b403-80696ef1e21f.png">

**Comment by whitebear60** [comment]
can't confirm, did a fresh install of blackhole-2ch via homebrew, the mac's screen recording works fine with system audio being captured properly via blackhole

macOS 12.5.1
BlackHole 0.4.0

**Comment by whitebear60** [comment]
<img width="840" alt="image" src="https://user-images.githubusercontent.com/42472132/192548830-93ffc7b9-cd5f-4269-a238-ae1e2651f82e.png">
probably that can be something with device order in your Audio MIDI Setup list with BlackHole being the first one, and not the build-in output, but idk...

**Comment by 01GOD** [comment]
Sadly it only seems to function when blackhole is selected as input and output. NOT when it's part of a multi output. Sad that it doesn't function properly. More sad that apple doesn't include something so basic.
