### ISSUE TITLE
Blackhole breaks "About this Mac/System report/Audio" 

### ISSUE THREAD

**Issue by Badsheep** [ExistentialAudio/BlackHole#661]
### Please Confirm

- [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
- [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
- [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)

### macOS Version

macOS 11 Big Sur

### BlackHole Build(s) Affected

- [ ] 2 channel
- [X] 16 channel
- [ ] 64 channel
- [ ] other/custom build

### Describe the bug

When Blackhole (16ch) was installed on my Mac mini, in "About this Mac / System Report / Audio" there was no data shown.

![signal-2022-09-30-074812_002](https://user-images.githubusercontent.com/46049911/193447564-17b1619d-0af9-4dc8-820f-d8b297bf9912.png)

The shell command "system_profiler SPAudioDataType" gave the same empty result.

When deinstalled, everything worked.

### Reproduction Steps

Install Blackhole.
Open "About this Mac / System Report / Audio".

### Expected Behavior

Everything working.

**Comment by devinroth** [comment]
First try restarting.

Send a screenshot of audio midi setup and the hal folder.

Devin

**Comment by Badsheep** [comment]
Hello,

I tried several restarts, without success.
I tried to re-install (put back the "BlackHole16ch.driver" folder in the HAL folder) : the bug appears immediatly. 

Here are the required screenshots : 

![Capture d’écran 2022-10-02 à 17 38 42](https://user-images.githubusercontent.com/46049911/193462801-06fadfe7-3d18-438b-a8d7-bcbba10c2cd5.png)

![Capture d’écran 2022-10-02 à 17 39 36](https://user-images.githubusercontent.com/46049911/193462807-373146ed-0ba0-4bdd-8a2e-306c61fef935.png)

Here is a screenshot of a shell request : 

![Capture d’écran 2022-10-02 à 17 38 00](https://user-images.githubusercontent.com/46049911/193462780-bba6f235-c8ba-4b7b-907b-231ab8839027.png)

And maybe it could be interesting,  I find this in the Mac OS Console when I do the Shell command : 

BlackHole_GetControlPropertyData: the item in the qualifier is not valid for kAudioSelectorControlPropertyItemName for the data source control

And finally : Thank you very much for your very nice software !!
It has been very usefull for me (thought I don't need it anymore)

**Comment by devinroth** [comment]
That error doesn’t cause any issues.

And I see BlackHole is loaded correctly in audio midi setup.

Does it work properly when you uninstall BlackHole?

Devin

**Comment by Badsheep** [comment]
Yes absolutely when removed from the HAL folder System_profiler works.
![Capture d’écran 2022-10-02 à 19 22 26](https://user-images.githubusercontent.com/46049911/193467415-f5a1f9e6-6938-4857-be37-3e76a3ca95ec.png)

And I confirm that it doesn't cause any issue in the use of the driver, everytinhg works fine, BUT it breaks the system_profiler command. And I need that command for some reasons...

**Comment by devinroth** [comment]
Okay I’ll fix that error and see if it makes a difference.

Devin

**Comment by devinroth** [comment]
I’ll do my best to get to it this week.

Devin

**Comment by devinroth** [comment]
Oddly enough I can't reproduce the issue.

**Comment by devinroth** [comment]
<img width="475" alt="Screen Shot 2022-10-02 at 1 02 19 PM" src="https://user-images.githubusercontent.com/13010961/193473867-294789d2-f372-49c0-a057-817e316f31fb.png">

**Comment by devinroth** [comment]
Wait, that was only the 2ch version. Wonder if it's related to 16ch version.

**Comment by devinroth** [comment]
Still works correctly.

**Comment by devinroth** [comment]
<img width="475" alt="Screen Shot 2022-10-02 at 1 04 50 PM" src="https://user-images.githubusercontent.com/13010961/193473986-54ccca0e-6aa5-4724-b130-7fb392b2ff3b.png">

**Comment by devinroth** [comment]
I'll test on Big Sur. Are you on Intel or Apple Silicon?

**Comment by Badsheep** [comment]
Intel... but I understand !
I was using (and testing) and old version (0.2.10).
I just downloaded the new version (0.4.0) and with this version everything is ok...

I'm sorry for the waste of time...
Thanks again for this really nice application !

**Comment by devinroth** [comment]
No problem.

I should add a question about which version to the issues.

Devin
