### ISSUE TITLE
Can't Build Output Only

### ISSUE THREAD

**Issue by surrain** [ExistentialAudio/BlackHole#665]
### Please Confirm

- [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
- [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
- [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)

### macOS Version

macOS 12 Monterey

### BlackHole Build(s) Affected

- [ ] 2 channel
- [ ] 16 channel
- [ ] 64 channel
- [X] other/custom build

### Describe the bug

If I try to change kDevice_HasInput to false, it still builds, but then Audio Devices hangs when I try to use it.

My builds work as long as I don't include changes to "is hidden," "has input," or "has output" constants.

My goal is a driver with 10 outputs and no inputs.

Thanks. BlackHole is awesome.

### Reproduction Steps

1a. change kDevice_HasInput to false in BlackHole.c
1b. ...or set the pre-compiler constant kDevice_HasInput to false
2. build
3. move the built driver folder to /Library/Audio/Plug-Ins/HAL
4. restart core audio

### Expected Behavior

Audio Devices window should present all of the drivers including my new one; instead it shows no drivers.

### Screenshots

<img width="1366" alt="Screen Shot 2022-10-15 at 8 07 13 PM" src="https://user-images.githubusercontent.com/3791193/196013233-6519dc8a-9c3b-45a4-80a5-6d64714b28a7.png">

**Comment by devinroth** [comment]
Might be related to my other issue.

I’ll look into it.

Although I just did a custom build with this recently so I don’t know what the issue is off hand.

Devin

**Comment by surrain** [comment]
Many thanks.

If custom builds are working for you and it wouldn't be too much trouble, could you send me a custom with 10 outs, no ins, and sample rates just "8000"?

Best,
Aaron

**Comment by devinroth** [comment]
Try doing a debug build and see if that works.

Devin

**Comment by surrain** [comment]
I didn't know how to do a debug build from the script so I tried building from Xcode by first changing all the variables in BlackHole.c then choosing build from the menu and finding the driver by using "Show Build Folder in Finder" and that driver worked for me. Thanks.
