### ISSUE TITLE
Does not work with Shazam

### ISSUE THREAD

**Issue by Alessi0X** [ExistentialAudio/BlackHole#67]
Hi there,
I am trying to let Shazam recognise songs as I play them (e.g., youtube compilations).

I successfully created a multi-output device with Built-in Audio (Master) and Blackhole (Drifted).
I did some tests and everything's fine (e.g., I am able to record on Logic Pro whatever I'm listening to).

However, Shazam seems to get no audio: it's not able to recognise even the most famous songs of all times.

Any thoughts? Am I missing something?

**Comment by Alessi0X** [comment]
Last update: so far, Shazam for mac seems to be buggy. It can't even recognise music using the plain input microphone.

I'll keep you updated

**Comment by Alessi0X** [comment]
Everything's fine. 

It was just a Shazam issue.

All the best

**Comment by SebastianBoyd** [comment]
@Alessi0X  Im having the same issue right now. Were you able to resolve it?

**Comment by Alessi0X** [comment]
@SebastianBoyd in my case it was just an issue related to Shazam, not Blackhole. I tried capturing the very same music using the plain built-in microphone and it didn't work either. After several minutes everything was back to normal so I think Shazam had some minor issues on their side
