### ISSUE TITLE
Problem with macOS + iOS + Continuity audio

### ISSUE THREAD

**Issue by mbierman** [ExistentialAudio/BlackHole#679]
### Please Confirm

- [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
- [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
- [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)

### macOS Version

macOS 13 Ventura

### BlackHole Build(s) Affected

- [X] 2 channel
- [ ] 16 channel
- [ ] 64 channel
- [ ] other/custom build

### Describe the bug

When using iOS Continuity with iPhone 12 mini as the input to macmini  and blackhole, things tend to crash. I could not play youtube, it said to restart. Another time, it would not let me record. Using Camo Studio and disabling Continuity makes everything fine. 
![image](https://user-images.githubusercontent.com/1205471/202343329-59f89171-2c2a-487a-a1a6-186e8c322bfe.png)

### Reproduction Steps

1. set as shown in the PDF
2. Try to play a video on youtube and record the screen using macOS built in screen recorder. 
3. It won't work reliably and youtube says to restart computer. 

etc...
[Audio Recording Screen.pdf](https://github.com/ExistentialAudio/BlackHole/files/10027356/Audio.Recording.Screen.pdf)

### Expected Behavior

Before the Continuity feature in macOS Ventura this setup used to work fine. In fact, it still does if I disable Continuity. Not sure if this is definitely something you can solve or not.

**Comment by mbierman** [comment]
@devinroth I can check. Can you suggest what I am looking for?

**Comment by devinroth** [comment]
Search for coreaudiod in Console, reproduce the issue, and dump the logs here.

Devin

**Comment by mbierman** [comment]
Having trouble reproducing it right now. Will reopen if I can nail it.
