### ISSUE TITLE
2ch and 16ch version can't coexist ?

### ISSUE THREAD

**Issue by jlochard** [ExistentialAudio/BlackHole#68]
He,

I'm trying to compile again a two channels version of BlackHole by following the wiki instructions.
The compilation succeed. So I changed the name of the folder and copy it in the right folder next to the 16ch version as what did in November.

But after the "sudo killall coreaudiod" command I find just one BlackHole with a strange mix regarding the name on the left which displays 16 channels and the number of in/out on the right.

Can you help please ?

Best regards,

Jean

![Capture d’écran 2020-03-17 à 15 20 20](https://user-images.githubusercontent.com/57224810/76865696-64c67480-6863-11ea-8e3b-8b154b53dc27.png)
![Capture d’écran 2020-03-17 à 15 20 50](https://user-images.githubusercontent.com/57224810/76865714-68f29200-6863-11ea-9507-ac2349b4dbff.png)

**Comment by devinroth** [comment]
Did you rename the UID?

**Comment by jlochard** [comment]
No, but I see that there is a topic on the wiki since our last exchange in November...
I did not remember it !

I will follow the instructions carefully and get it to work. Sorry for your time.

Jean

**Comment by jlochard** [comment]
...and everything is fine when changing the UID.

Thanks !

Jean
