### ISSUE TITLE
Possible to merge Headphones Microphone and other playing apps like Spotify

### ISSUE THREAD

**Issue by TerenzeY** [ExistentialAudio/BlackHole#69]
Hi,

I have tried a few things but couldn't get it to work.

I am looking to;
1. Combine the audio from Spotify
2. Headphones's Microphones
3. Route into Blackhole.

Is this possible?

**Comment by devinroth** [comment]
What have you tried?

**Comment by TerenzeY** [comment]
So correction, this is what I have tried:
In Zoom, I set Speaker to Blackhole.
<img width="772" alt="Screenshot 2020-03-17 at 15 32 10" src="https://user-images.githubusercontent.com/47614487/76872563-79573c80-6864-11ea-85d2-8a3922eac608.png">

Then I select BlackHole as Input recording in Quicktime.
<img width="354" alt="Screenshot 2020-03-17 at 15 33 31" src="https://user-images.githubusercontent.com/47614487/76872697-aa377180-6864-11ea-8094-5ad1ff807d02.png">

This works but I need to Record:
1. Input audio from Zoom app
2. My Microphone

And also hearing the Zoom app's audio while recording, possible?

**Comment by devinroth** [comment]
Yes it's possible. You'll need to try a few things to make it work. I've done something similar. You'll need a DAW like GarageBand or Logic to do it. 

Use the same setup as you have in Zoom. Create an aggregate device and use that Aggregate in your DAW. Output to your speakers from the Aggregate and record audio from BlackHole and Your Speakers. 

Hope that makes sense.

**Comment by TerenzeY** [comment]
Thanks, kinda make sense – will try.

One thing though, if set the audio to BlackHole in Zoom, I can no longer hear the audio. Can I still hear the audio (pass through or something)?

And is BlackHole similar to LoopBack?
https://rogueamoeba.com/loopback/

**Comment by devinroth** [comment]
Yeah BlackHole is similar to loopback.

**Comment by devinroth** [comment]
Use a multi-output. That way you can route the audio with BlackHole and still hear.

**Comment by TerenzeY** [comment]
@devinroth I have got this working thanks. But if I use an AirPods the sample rates become 16 kHZ, the audio slows down. Any workaround?

Settings is:
[] AirPods Pro
[] Blackhole  (Drift on)

**Comment by devinroth** [comment]
So AirPods runs on 16kHz? I guess I could add 16kHz to BlackHole.

**Comment by TerenzeY** [comment]
Yes (painfully). Appreciate it.

A bit random question – possible to know which App the audio comes from?

**Comment by devinroth** [comment]
That’s too bad about AirPods. 

Short answer: Yes it’s possible to know which app the audio comes from.

**Comment by TerenzeY** [comment]
Thanks, that's good news. Complicated? I would like to contribute if there's a direction.

**Comment by devinroth** [comment]
Complicated? Kind of. Basically it would take me more time to explain it then to just do it myself. But I do appreciate the willingness to contribute.

**Comment by TerenzeY** [comment]
Thanks, I'll contribute in another way then!
