### ISSUE TITLE
input(or output) only device bug

### ISSUE THREAD

**Issue by JaegyuNoh** [ExistentialAudio/BlackHole#692]
### Please Confirm

- [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
- [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
- [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)

### macOS Version

macOS 11 Big Sur

### BlackHole Build(s) Affected

- [ ] 2 channel
- [ ] 16 channel
- [ ] 64 channel
- [X] other/custom build

### Describe the bug

When the pre-compiler constants are set according to the mirror device setting guide, the driver does not run normally.

Specifically, it occurs when setting to support only input (or output).

### Reproduction Steps

After setting like the example below, problems occur during installation.

kDevice_HasInput=true
kDevice_HasOutput= false

kDevice2_HasInput= false
kDevice2_HasOutput=true

### Expected Behavior

Blackhole drivers are loaded.

**Comment by devinroth** [comment]
Pretty sure this is the same as #623

**Comment by JaegyuNoh** [comment]
It's same the #623 issue, so it's closed.
And I think I've found a solution.

It seems to be caused by not properly specifying `kDevice_ObjectList[]` to be processed according to `inObjectID` in the method - `BlackHole_GetDevicePropertyData()`.

**Comment by devinroth** [comment]
Oh sweet. Mind creating a pr for this and I’ll merge right away.

Devin
