### ISSUE TITLE
Configuration options menu

### ISSUE THREAD

**Issue by LwsBtlr** [ExistentialAudio/BlackHole#7]
[Discussion] Will there be any configuration options for this, or is it going to remain as a simple pass through tool like it is now?

I’d like to be able to, for example, pass a flag to start a new file ever 5 minutes (or every chapter if the source has chapters, or pass a list of time codes). Not sure if this is something that might be done or something totally out of the scope of the project (I suspect the latter).

Is It possible to integrate it into a command line pipe chain? So I could direct my audio app to play to blackhole and tell… I don’t know, FFmpeg to listen to blackhole? Or does it make more sense just to use black hole to get the audio and then reprocess the audio after the fact?

**Comment by devinroth** [comment]
I have plans to implement some configuration options. I want to the ability to change the number of channels with a simple menu option along with changing the clock source and output/input mapping. 

For the other ideas that you have I think they are beyond the scope of what I intend with his. All of those make more sense to me to be done in a DAW. At least for now I intend to keep things simple but if enough people are asking for specific functions I may roll them in.

**Comment by Andertve** [comment]
Hi, would be great to have the option of choosing the numbers of channels in the menu rather than configure and make custom build Blackhole

**Comment by Andertve** [comment]
Would be great to have a configuration/menu to increase the number of channels without having to make a custom build.

**Comment by devinroth** [comment]
Agree. It’s in the works.

**Comment by QuentinBrown** [comment]
> I have plans to implement some configuration options. I want to the ability to change the number of channels with a simple menu option along with changing the clock source and output/input mapping.
> 
> For the other ideas that you have I think they are beyond the scope of what I intend with his. All of those make more sense to me to be done in a DAW. At least for now I intend to keep things simple but if enough people are asking for specific functions I may roll them in.

And here's one additional request that I hope you might consider - the ability to launch and possibly manage additional instances of blackhole from the configuration options menu. This way, when combined with the ability to change the number of channels for each instance running, you wouldn't need to build and install multiple fixed instances to cope with the need to send and receive between multiple non-channel aware apps like Skype or zoom. Hopefully anyway. I'm not sure if macOS architecture allows things to work this way on the fly or if it has to actually have a driver instance hard installed.

For now, I'm off to try and follow the instructions for building my own extra 2 channel instances with different UIDs. Thanks for putting those up!

**Comment by ivanvfer** [comment]
It would be great to support additional Blackhole 2ch instances. This would provide more flexibility in routing traffic among multiple non-channel aware apps. 

A way to support this could be to have a Blackhole 2ch installer that uses a random UID/name suffix. This way, the same installer could be used to create multiple BlackHole 2ch instances, which would run as independent versions.
