### ISSUE TITLE
Skype and other Interface

### ISSUE THREAD

**Issue by bassitsch** [ExistentialAudio/BlackHole#70]
Hi, does anyone know a way to use Skype with another interface. Im using a Motu Ultralite, there is my E-Bass pluged in an another Microphone. The Idea is, that i can give an online Lesson and my student is listening to a really good audiosignale. Is this possible with blackhole and does some one know how. I've tried id now for some hours, but it didn't worked.

**Comment by devinroth** [comment]
You'll have to mix the audio in a DAW and the send it out via BlackHole to Skype.

**Comment by JohnSandoval3** [comment]
@devinroth Hello Sir, I cant figure out how to do this at all. Can you please assist? I read the "README" and looked through the Issues but I just cant figure it out. I am using LPX as my DAW. I would like to Skype with sending my voice and LPX audio to the recipient while being able to hear LPX at the same time in my headphones, thank you sir. I know how to do this using Soundflower but I no longer have it

**Comment by devinroth** [comment]
BlackHole works exactly the same as Soundflower. Just set it up exactly the same way. If you can’t figure it out tell me exactly how you have everything setup and include screen shouts so i can better help.

**Comment by JohnSandoval3** [comment]
Thank you so much, ill have to send screen shots later, I do not know how or where to set up like soundflower. I tried Audio Midi Setup and creating an Agg Device but had no luck, I feel like im getting stuck at the routing somewhere. I had success recording Audio into LPX from my computer but no luck getting LPX audio and my voice (Built In Mic) both out to Skype. Again, thank you for the response, also, i will keep trying

**Comment by bassitsch** [comment]
Here is a Video on Youtube where they show how to use Multichannel on Skype. It is the same with LPX, exepte that you have to use the 4th channel for Logic. Here is the video: https://www.youtube.com/watch?v=Q4hCVPJAaJY&t=161s

Does this help you?

**Comment by JohnSandoval3** [comment]
Thank you both! I have time today to get this right, my session is in 12 hours LOL. For some reason, well my own ignorance/inability, I cant figure out the routing from LPX and the Internal Mic, to Skype using Ladiocast

**Comment by JohnSandoval3** [comment]
I got it, thank you so much

**Comment by devinroth** [comment]
You're welcome.
