### ISSUE TITLE
Blackhole not showing up on Apple M1 Max

### ISSUE THREAD

**Issue by NicoleJaneway** [ExistentialAudio/BlackHole#704]
### Please Confirm

- [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
- [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
- [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)

### macOS Version

macOS 13 Ventura

### BlackHole Build(s) Affected

- [X] 2 channel
- [ ] 16 channel
- [x] 64 channel
- [ ] other/custom build

### Describe the bug

Blackhole not showing up on Apple M1 Max

### Reproduction Steps

1.  Download from website or using homebrew

### Expected Behavior

Unfortunately, Blackhole is not showing up in Audio MIDI

**Comment by devinroth** [comment]
Send a screenshot of the HaL folder.

**Comment by NicoleJaneway** [comment]
<img width="682" alt="Screenshot 2023-02-05 at 1 05 35 PM" src="https://user-images.githubusercontent.com/44853527/216845761-843c5efc-16d8-4800-af1c-bc4c0eefbd6e.png">

**Comment by devinroth** [comment]
Needs to be /Library not ~/Library.

**Comment by NicoleJaneway** [comment]
Ah, okay

<img width="682" alt="Screenshot 2023-02-05 at 1 17 55 PM" src="https://user-images.githubusercontent.com/44853527/216846383-1e23b647-bfd9-4a3a-b4d6-0e1881479676.png">

**Comment by devinroth** [comment]
Do you have root access?

**Comment by NicoleJaneway** [comment]
...unsure...

This is a work laptop. 

so maybe not?

**Comment by devinroth** [comment]
what happens when you type “sudo”

You need root access to install BlackHole. I suspect that might be the issue.

**Comment by NicoleJaneway** [comment]
<img width="682" alt="Screenshot 2023-02-05 at 2 16 50 PM" src="https://user-images.githubusercontent.com/44853527/216849062-644402a8-c9f6-4d9e-acd0-d41a3650954c.png">

**Comment by devinroth** [comment]
Sorry. Try “sudo ls”

**Comment by NicoleJaneway** [comment]
<img width="682" alt="Screenshot 2023-02-05 at 2 23 25 PM" src="https://user-images.githubusercontent.com/44853527/216849328-53e39363-fc93-4277-9222-08a215405aa6.png">

**Comment by devinroth** [comment]
Okay use sudo ls on the HAL directory.

**Comment by NicoleJaneway** [comment]
Oh, cool
<img width="682" alt="Screenshot 2023-02-05 at 2 35 39 PM" src="https://user-images.githubusercontent.com/44853527/216849841-eeeaa845-d74a-4838-ba65-0cc51efa36f1.png">

Still not seeing Blackhole in Audio MIDI though — what's next?

**Comment by devinroth** [comment]
In Console search for coreaudiod and then reboot core audio in terminal with "sudo launchctl kickstart -kp system/com.apple.audio.coreaudiod”. Paste the results here.

**Comment by NicoleJaneway** [comment]
That worked!!  Now I see Blackhole 😊 

<img width="682" alt="Screenshot 2023-02-06 at 11 03 01 AM" src="https://user-images.githubusercontent.com/44853527/217061628-11f5ee05-bfea-4b15-abcf-16abe0c5cfef.png">

<img width="763" alt="Screenshot 2023-02-06 at 11 03 04 AM" src="https://user-images.githubusercontent.com/44853527/217061640-517280ea-07c6-4e83-a24a-df07b0b5ba5a.png">

**Comment by devinroth** [comment]
Did you get any errors when trying to install?

**Comment by NicoleJaneway** [comment]
No, at the time of install, it said completed successfully

**Comment by devinroth** [comment]
Odd.

In that case, simply restarting your computer would have fixed the issue. I should have suggested that first.

**Comment by NicoleJaneway** [comment]
Hmmm, no.  I downloaded the 16ch version months ago.  And restarting was
the first thing I tried after 2ch didn't work.

**Comment by devinroth** [comment]
Okay. I think I might know what the issue is. If it disappears again let me know.

**Comment by NicoleJaneway** [comment]
Will do, thanks for your help!!
