### ISSUE TITLE
Choppy audio Apple Music -> Google Meet

### ISSUE THREAD

**Issue by JesterMan** [ExistentialAudio/BlackHole#708]
### Please Confirm

- [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
- [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
- [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)

### macOS Version

macOS 13 Ventura

### BlackHole Build(s) Affected

- [X] 2 channel
- [X] 16 channel
- [ ] 64 channel
- [ ] other/custom build

### Describe the bug

Audio played from the Apple Music App, or music.apple.com in chrome is choppy.

I've tried 44.1 and 48 mHz, drift correction enabled.

I'm not sure the version of blackhole, but I installed it on 2/15/2023
Chrome Version 110.0.5481.100 (Official Build) (arm64)
MacOS Ventura 13.2.1 (22D68)
Mac mini M1, 2020 16 GB

### Reproduction Steps

1. Play music in app or browser
2. Set sound output to Blackhole (2 or 16 ch)
3. Set mic in Meet to the same Blackhole

### Expected Behavior

When sharing a tab in Meet, I can hear the music clearly. When sending through Blackhole it's choppy.

**Comment by devinroth** [comment]
Thanks. I’ll take a closer look when I get a chance.

In the meantime, since you are on Ventura. I’m working on an app that will solve this problem called Dipper. Swing over to Discord and take it for a spin.

https://discord.com/channels/775472045865173023/1071561373269626950

It’s an early release and is still in development so please keep that in mind if you’re going to try. And let me know if you come across any bugs.

**Comment by JesterMan** [comment]
I'm not much of a discord user, when I follow that link I get a "No Text Channels" screen. Is there a download page somewhere?

**Comment by devinroth** [comment]
No download page. Haven’t even got that far yet. Here try this. Since it’s still in development this is an alpha build. The build will expire after 30 days. Have fun.

https://www.dropbox.com/s/1d6fz4g29lvcbzf/Dipper.0.1.100-alpha.pkg?dl=0

**Comment by JesterMan** [comment]
Sweet, ty!
The Dipper UI is fairly intuitive, because I was able to get it working and set up with no docs!

Same problem! I guess I should start looking into Chrome audio settings? Pretty out of my depth here.

**Comment by devinroth** [comment]
I’m using BlackHole behind the scenes so this is good to know. I’ll poke around sometime later this week and let you know if I find anything out.

That being said, I’ve used BlackHole with Chrome / Meets numerous times and have integrated that setup with a number of apps before without any issue.

Also note that Ventura suffers from a number of audio issues. Have you tested with a different browser? Try recording into Audacity at the same time as using Meets. Does Audacity still sound fine?

And thanks for saying Dipper is fairly intuitive. That has been a big goal of the projects. Trying to make it as simple as possible to use.

**Comment by JesterMan** [comment]
Tested some things

- Audacity performs fine with Meet running. Meet does not improve with Audacity running.
- I can't get Safari to work with Blackhole
- Firefox has the same issue
- Zoom works fine. Meet does not improve with Zoom running.

**Comment by devinroth** [comment]
That’s really odd. The audio that Audacity gets is the exact same audio that Chrome / Firefox gets. Do you have a trillion tabs open? Take a took at Activity monitor and see if theirs is anything strange going on with Chrome. High CPU / Hight memory.

Devin

**Comment by JesterMan** [comment]
>Do you have a trillion tabs open?

I feel attacked! :P

Ok, tested with one, lonely, single tab. Still happens. After Zoom and Audacity did it without problem, my jedi senses say that Meet is processing the sound to "help" with something. Have you heard of anything like that?

**Comment by devinroth** [comment]
I just tested Ventura, Chrome. Apple Music -> BlackHole2ch -> Meet. Works fine. Of course the audio quality sounds like crap because of the stuff that Meet is doing, compression etc. Could you upload a sample of what you hear and I can hear if it’s meets that is doing it.

Devin
