### ISSUE TITLE
Broken image in wiki

### ISSUE THREAD

**Issue by stefansundin** [ExistentialAudio/BlackHole#709]
### Please Confirm

- [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
- [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
- [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)

### macOS Version

macOS 13 Ventura

### BlackHole Build(s) Affected

- [ ] 2 channel
- [ ] 16 channel
- [ ] 64 channel
- [ ] other/custom build

### Describe the bug

https://github.com/ExistentialAudio/BlackHole/wiki/Multi-Output-Device

There's supposed to be an image in step 1 but the markdown is broken.

```markdown
![Spotlight Search for Audio Midi Setup]Images/Multi-Output/1.png)
```

It is missing a `(`.

### Reproduction Steps

1. Visit https://github.com/ExistentialAudio/BlackHole/wiki/Multi-Output-Device
2. See broken markdown code instead of an image.

### Expected Behavior

See this image instead of broken markdown. https://raw.githubusercontent.com/wiki/ExistentialAudio/BlackHole/Images/Multi-Output/1.png

### Screenshots

![Screenshot 2023-02-27 at 17 28 03](https://user-images.githubusercontent.com/1991151/221728971-a416bdec-53d7-4db3-9d42-106b01afe3eb.png)

**Comment by orchetect** [comment]
Thanks for the heads-up. Fixed now.
