### ISSUE TITLE
How to set up with Syrinscape and Discord?

### ISSUE THREAD

**Issue by ksignorini** [ExistentialAudio/BlackHole#71]
Syrinscape is a sound playing app that outputs to the default sound output device only.

Discord is a voice chat app that lets users chat with each other. It allows choosing of input device and output device.

How do I set up Blackhole such that the input device in Discord includes both my headphone microphone as well as the sound coming out of Syrinscape (default Mac output device)?

(I've tried creating an aggregate device with my headphone mic and Blackhole then setting Blackhole as the default computer output device. In Discord I chose my aggregate device as the input device and my headset speakers as my output device. When I do this, I get no sound going in to Discord at all--no mic or Syrinscape sounds.)

**Comment by devinroth** [comment]
You'll need a DAW or some other app to route the Mic to BlackHole and then to Discord. I use Logic. But in theory any DAW should work.

**Comment by ksignorini** [comment]
> You'll need a DAW or some other app to route the Mic to BlackHole and then to Discord. I use Logic. But in theory any DAW should work.

Free options? Would Garage Band work? How would I set that up?

**Comment by devinroth** [comment]
Garage band should work. Audacity is free but has issues on Catalina.
