### ISSUE TITLE
BlackHole.c - A function declaration without a prototype is deprecated in all versions of C

### ISSUE THREAD

**Issue by LaKing** [ExistentialAudio/BlackHole#719]
### Please Confirm

- [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
- [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
- [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)

### macOS Version

macOS 13 Ventura

### BlackHole Build(s) Affected

- [ ] 2 channel
- [ ] 16 channel
- [ ] 64 channel
- [X] other/custom build

### Describe the bug

When compiling BlackHole, the compiler gives warnings that look like this

File: BlackHole.c
Line: 436

```
static CFStringRef get_box_uid()          { RETURN_FORMATTED_STRING(kBox_UID) }
static CFStringRef get_device_uid()       { RETURN_FORMATTED_STRING(kDevice_UID) }
static CFStringRef get_device_name()      { RETURN_FORMATTED_STRING(kDevice_Name) }
static CFStringRef get_device2_uid()       { RETURN_FORMATTED_STRING(kDevice2_UID) }
static CFStringRef get_device2_name()      { RETURN_FORMATTED_STRING(kDevice2_Name) }
static CFStringRef get_device_model_uid() { RETURN_FORMATTED_STRING(kDevice_ModelUID) }
```

A function declaration without a prototype is deprecated in all versions of C

### Reproduction Steps

Clone the repo, and compile.

### Expected Behavior

The building should succeed without errors and warnings.

### Screenshots

![image](https://user-images.githubusercontent.com/2204838/230679064-4bb59a54-07b9-4101-87bc-3460f710ad4d.png)

**Comment by devinroth** [comment]
That doesn't cause it not to build. It's just a warning.

**Comment by Ivanaxel1314** [comment]
> ### Please Confirm
> 
> - [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
> - [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
> - [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)
> 
> ### macOS Version
> 
> macOS 13 Ventura
> 
> ### BlackHole Build(s) Affected
> 
> - [ ] 2 channel
> - [ ] 16 channel
> - [ ] 64 channel
> - [X] other/custom build
> 
> ### Describe the bug
> 
> When compiling BlackHole, the compiler gives warnings that look like this
> 
> 
> 
> File: BlackHole.c
> 
> Line: 436
> 
> 
> 
> ```
> 
> static CFStringRef get_box_uid()          { RETURN_FORMATTED_STRING(kBox_UID) }
> 
> static CFStringRef get_device_uid()       { RETURN_FORMATTED_STRING(kDevice_UID) }
> 
> static CFStringRef get_device_name()      { RETURN_FORMATTED_STRING(kDevice_Name) }
> 
> static CFStringRef get_device2_uid()       { RETURN_FORMATTED_STRING(kDevice2_UID) }
> 
> static CFStringRef get_device2_name()      { RETURN_FORMATTED_STRING(kDevice2_Name) }
> 
> static CFStringRef get_device_model_uid() { RETURN_FORMATTED_STRING(kDevice_ModelUID) }
> 
> ```
> 
> 
> 
> A function declaration without a prototype is deprecated in all versions of C
> 
> ### Reproduction Steps
> 
> Clone the repo, and compile.
> 
> 
> 
> ### Expected Behavior
> 
> The building should succeed without errors and warnings.
> 
> ### Screenshots
> 
> ![image](https://user-images.githubusercontent.com/2204838/230679064-4bb59a54-07b9-4101-87bc-3460f710ad4d.png)

**Comment by devinroth** [comment]
Done.
