### ISSUE TITLE
Add routing from Blackhole to other audio devices (wiretap)

### ISSUE THREAD

**Issue by tombburnell** [ExistentialAudio/BlackHole#72]
It's great to be able to route audio say from Traktor to OBS for streaming. But it would be good to be able to also route that same audio to an audio interface to monitor. So a simple matrix selector would be very handy (BH 1-16 -> other devices)  (other devices -> BH 1-16) would be very handy!

Loopback has something similar.

**Comment by devinroth** [comment]
It's not something that can be done from the driver directly. You could use another app like a DAW to do the routing for you. I have plans on creating a UI to do that at some point but it will be pretty time consuming.

**Comment by tombburnell** [comment]
yeah I'm currently using Ableton but a friend who doesn't have Ableton and
could do with the routing options. Wonder what the lightest Daw is for such
a task.

**Comment by devinroth** [comment]
Audacity is free but is full of bugs.
