### ISSUE TITLE
blackhole 2ch doesn't work in mac mini, it doesn't capture any audio

### ISSUE THREAD

**Issue by guocity** [ExistentialAudio/BlackHole#725]
### Please Confirm

- [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
- [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
- [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)

### macOS Version

macOS 13 Ventura

### BlackHole Build(s) Affected

- [X] 2 channel
- [ ] 16 channel
- [ ] 64 channel
- [ ] other/custom build

### Describe the bug

blackhole 2ch doesn't work in mac mini m1 ventura, it doesn't capture any audio, it's working in macbook air m1 ventura

### Reproduction Steps

1. install latest 0.5.0 build from email received
2. go to Sound setting, input choose blackhole 2ch/ no audio spike
3. play audio, and any setting doesn't work
etc...

### Expected Behavior

input channel should have audio captured

**Comment by devinroth** [comment]
Please give more specifics about how to reproduce the bug. What applications are you using with BlackHole? How exactly do you have it setup? And how about screenshots to show how you have it setup.

**Comment by guocity** [comment]
thanks for responding,
I only want to aggregate internal audio with audio from airpod microphone, regardless the audio quality
my bad, not the mac mini issue, it's more like airpod microphone input cause the audio can not combined, 
Macbook air microphone has format 48.000z, and there is no issue, but the airpod microphone has input format only 24,000Hz

![audio2](https://user-images.githubusercontent.com/1127820/236711029-042433ee-460d-489d-8007-8a0c880919f3.jpg)

**Comment by devinroth** [comment]
An aggregate does not combine the audio. You need to use something else to mix them together. A daw will do the trick.

Devin

**Comment by guocity** [comment]
Thanks
