### ISSUE TITLE
Installation option for when `existential.audio` is unreachable

### ISSUE THREAD

**Issue by QuintinWillison** [ExistentialAudio/BlackHole#729]
### Please Confirm

- [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
- [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
- [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)

### macOS Version

macOS 12 Monterey

### BlackHole Build(s) Affected

- [X] 2 channel
- [ ] 16 channel
- [ ] 64 channel
- [ ] other/custom build

### Describe the bug

I tried installing via the link from your root readme in this GitHub repository and I get:

<img width="655" alt="Screenshot 2023-05-17 at 09 11 44" src="https://github.com/ExistentialAudio/BlackHole/assets/8318344/5879b7a9-efa9-4a22-ab1e-b33237807a76">

So I thought I would try via `brew` instead, but got similar:

```
% brew install blackhole-2ch
==> Downloading https://formulae.brew.sh/api/formula.jws.json
########################################################################################################################################################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
########################################################################################################################################################################################################### 100.0%
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/e3ee525cad238ab471f5afc16dc59748eb29e3c8/Casks/blackhole-2ch.rb
########################################################################################################################################################################################################### 100.0%
Error: Download failed on Cask 'blackhole-2ch' with message: Failure while executing; `/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.18\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://existential.audio/downloads/BlackHole2ch.v0.5.0.pkg` exited with 7. Here's the output:
curl: (7) Failed to connect to existential.audio port 443 after 4022 ms: Network is unreachable

quintin@Quintins-MacBook-Pro Temporary % ping existential.audio
PING existential.audio (162.241.218.190): 56 data bytes
36 bytes from box5584.bluehost.com (162.241.218.190): Destination Net Unreachable
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 5400 d03d   0 0000  3e  01 210e 10.21.3.153  162.241.218.190
```

### Reproduction Steps

1. Install via web link
2. Install via `brew`

### Expected Behavior

Being able to install this amazing software without infrastructure getting in the way.

Clearly GitHub is much more highly available than your `existential.audio` domain's underlying infrastructure, so perhaps consider just allowing the binary installer to be downloaded from GitHub's servers? You could attach it to the release, surely?

**Comment by devinroth** [comment]
First time this has ever happened. Server must have been down. I’m working on switching servers. Don’t use BlueHost, they are terrible.

I just tested right now and everything seems to be working. Is it back up for you?

**Comment by QuintinWillison** [comment]
Nice, thanks for the quick response @devinroth - just tried the `brew` route (`-2ch`) and it got much further this time, to the point of asking for password (elevated privileges). I've stopped there and not installed yet as I'm going to hold off until after I've upgraded macOS, but looks like all good now for what was failing before. 😁
