### ISSUE TITLE
Question, not an issue. 

### ISSUE THREAD

**Issue by CivZero** [ExistentialAudio/BlackHole#73]
Hi, 
I'm trying to see if there is a way to script out the setup for Audio Midi Setup and Blackhole. Does anyone have a way to script out creating a Multi-Output Device? The company I work for is trying to use software like Teams to do live presentations and BlackHole is exactly what I'm looking for but I can't find a way to script the setup so that I don't have to touch each install and setup. 

Thanks!

**Comment by devinroth** [comment]
Yes it’s possible but it’s a little complex. Email me at devinroth@existential.audio. I do freelance audio programming work and would be happy to help you out 

Devin
