### ISSUE TITLE
No bluetooth audio anymore after removal

### ISSUE THREAD

**Issue by dannybloe** [ExistentialAudio/BlackHole#74]
I tried BlackHole to see if it would solve my problem but I couldn't get it to work. Then I removed the drivers according to the documentation and after that I no longer can play any audio to any connected bluetooth device. Tried everything, reset bluetooth system, different users, pram resets, but no luck. Bluetooth device will connect but I cannot switch to the audio output for that device. The speaker icon in the menubar animates for a while and then switches back to built-in audio.  Maybe this is not related but I'm at a loss here.

Cheers, 
Danny.

**Comment by devinroth** [comment]
I have no idea why that would happen. Restarting your computer doesn’t solve the problem? Uninstalling BlackHole only affects BlackHole.

**Comment by alexshelkov** [comment]
I got the same issue, I installed BH16ch, then removed it and installed BH2ch, now I can't connect to bluetooth audio.

**Comment by devinroth** [comment]
What errors do you get in Console when you search for CoreAudio?

Devin

**Comment by devinroth** [comment]
I assume you’ve already restarted?

Devin

**Comment by alexshelkov** [comment]
Thanks for reply. But I was able to fix the problem by:

1) Uninstall Blackhole (all versions)
2) Reset Bluetooth settings (turn off Bluetooth and run `sudo rm -R /Library/Preferences/com.apple.Bluetooth.plist` in console)
3) Restart again
4) Install BH2ch

Now I can connect to Bluetooth again and it works with Blackhole.

**Comment by devinroth** [comment]
Strange. Glad it’s working.

Devin

**Comment by sysfu** [comment]
> Thanks for reply. But I was able to fix the problem by:
> 
> 1. Uninstall Blackhole (all versions)
> 2. Reset Bluetooth settings (turn off Bluetooth and run `sudo rm -R /Library/Preferences/com.apple.Bluetooth.plist` in console)
> 3. Restart again
> 4. Install BH2ch
> 
> Now I can connect to Bluetooth again and it works with Blackhole.

thanks for posting this, was able to restore Bluetooth audio after Blackhole 2ch borked it.
