### ISSUE TITLE
Uninstallation in Mojave

### ISSUE THREAD

**Issue by motorcykey** [ExistentialAudio/BlackHole#75]
I was unable to uninstall the audio device in Mojave using the instructions or locate the driver at all. Please advise on how to uninstall for Mojave OSX 10.14.

Thank you!

**Comment by devinroth** [comment]
My guess is you went to the wrong folder. HAL is under /Library/Audio/Plug-Ins/HAL/. People sometimes mistake ~/Library with /Library.

**Comment by motorcykey** [comment]
Thanks! That was exactly the issue.
