### ISSUE TITLE
Existential.audio domain SSL Certificate error prevents brew install

### ISSUE THREAD

**Issue by mistcat** [ExistentialAudio/BlackHole#754]
### Please Confirm

- [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
- [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
- [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)

### macOS Version

macOS 13 Ventura

### BlackHole Build(s) Affected

- [X] 2 channel
- [ ] 16 channel
- [ ] 64 channel
- [ ] other/custom build

### Describe the bug

when attempting to install blackhole-ch2 via brew, the install fails due to not being able to download the file from the existential.audio domain.  Visiting this domain via a browser results in this error: Error code: SSL_ERROR_RX_RECORD_TOO_LONG in Firefox.

The brew cli look like this:

`❯ brew install blackhole-2ch
==> Downloading https://formulae.brew.sh/api/formula.jws.json
############################################################################################################# 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
############################################################################################################# 100.0%
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/b71138fe5a0f4443c79f6bc407ac1d9ca9034bb7/Ca
############################################################################################################# 100.0%
==> Downloading https://existential.audio/downloads/BlackHole2ch.v0.5.0.pkg
curl: (35) LibreSSL/3.3.6: error:1404B42E:SSL routines:ST_CONNECT:tlsv1 alert protocol version

Error: Download failed on Cask 'blackhole-2ch' with message: Download failed: https://existential.audio/downloads/BlackHole2ch.v0.5.0.pkg
`

### Reproduction Steps

1. attempt to install with "brew install blackhole-2ch"
2. be sad.
3.
etc...

### Expected Behavior

file to be successfully downloaded and installed via brew

**Comment by devinroth** [comment]
I've been trying to figure this out for the past week. 

It is not a SSL Certificate error. 
https://www.sslshopper.com/ssl-checker.html#hostname=https://existential.audio/downloads/BlackHole2ch.v0.5.0.pkg

What I've been able to figure out is certain ISP are blocking the website for reasons unknown. One user seems to have narrowed it down to dns0.eu. Possible a false positive. They have been unresponsive to me enquires. 

If I could wager a guess, I think it has to do with using a shared hosting plan. In the meantime, here's a dropbox link. 

https://www.dropbox.com/s/yoneso9r22njd24/BlackHole2ch.v0.5.0.pkg?dl=0

**Comment by mistcat** [comment]
Thanks for the update Devin!  That sounds like a tricky one!  A few random other data points:  I ran the domain through CloudFlare Radar and they pointed out that there aren't content security policy headers currently set, maybe adding those could help cut down on false positives by any automated threat scanners?  I also happened to notice that if I ran the domain through https://www.virustotal.com/ it listed the following systems as flagging that domain:

`Avira - Phishing
Certego - Phishing
Cluster25 - Phishing
CRDF - Malicious
CyRadar - Malicious
Lionic - Phishing
Phishing Database - Phishing
VIPRE - Phishing
Webroot - Malicious`

So I imagine there is something that's tripping them up or causing a false positive?

**Comment by devinroth** [comment]
I’m going through the painstaking process of contacting companies to get removed from their list as a false positive. 3 removed so far.

And I’ll work on adding the security headers.

And get a dedicated IP.

Devin

**Comment by oliveraemmer** [comment]
According to the initial issue only 2ch is affected but I get the same error with _brew install blackhole-16ch_ and _brew install blackhole-64ch_.

```
brew install blackhole-2ch 
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json

==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/3d7982a
Already downloaded: /Users/temp/Library/Caches/Homebrew/downloads/87e764f72912b29a1953468f6f1967d08332d589cef6b7f454176a32aeaeac14--blackhole-2ch.rb
==> Downloading https://existential.audio/downloads/BlackHole2ch.v0.5.0.pkg
curl: (35) LibreSSL SSL_connect: SSL_ERROR_ZERO_RETURN in connection to existential.audio:443 

Error: Download failed on Cask 'blackhole-2ch' with message: Download failed: https://existential.audio/downloads/BlackHole2ch.v0.5.0.pkg
```

```
brew install blackhole-16ch
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/3d7982a
Already downloaded: /Users/temp/Library/Caches/Homebrew/downloads/fddebf12acdfc329f1dbb0c589be1797073b158646203ceda3e9711f1a3a720f--blackhole-16ch.rb
==> Downloading https://existential.audio/downloads/BlackHole16ch.v0.5.0.pkg
curl: (35) LibreSSL SSL_connect: SSL_ERROR_ZERO_RETURN in connection to existential.audio:443 

Error: Download failed on Cask 'blackhole-16ch' with message: Download failed: https://existential.audio/downloads/BlackHole16ch.v0.5.0.pkg
```

```
brew install blackhole-64ch
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/3d7982a
Already downloaded: /Users/temp/Library/Caches/Homebrew/downloads/2710ab106a3dc90f8590bc8a13357325e7a2b3bcb66e757d0ee7671028305309--blackhole-64ch.rb
==> Downloading https://existential.audio/downloads/BlackHole64ch.v0.5.0.pkg
curl: (35) LibreSSL SSL_connect: SSL_ERROR_ZERO_RETURN in connection to existential.audio:443 

Error: Download failed on Cask 'blackhole-64ch' with message: Download failed: https://existential.audio/downloads/BlackHole64ch.v0.5.0.pkg
```

**Comment by devinroth** [comment]
As explain above, it’s not a SSL error.

Devin

**Comment by devinroth** [comment]
Do you happen to be on VirginMedia?

**Comment by kasperkamperman** [comment]
<img width="703" alt="Screenshot 2023-12-05 at 22 16 43" src="https://github.com/ExistentialAudio/BlackHole/assets/1760616/841466a9-9a78-497f-961f-f16eca839278">

ISP: Odido Netherlands B.V.

**Comment by devinroth** [comment]
How about now? Fixed yet?

Devin

**Comment by kasperkamperman** [comment]
I tried on my university network and on a mobile connection and it works fine. 
However on my homenetwork it doesn't. Desktop gives an SSL error, on mobile the Asus firewall seems to kick in. 
Somehow the ip/host is flagged as suspicious. That why I suggested routing through cloudflare, since it masks the ip of your shared hosting (that might have some bad actors on it too). It won't cost you anything.

**Comment by devinroth** [comment]
This should be fixed. Reopen if you're still having issues.

**Comment by kasperkamperman** [comment]
It works now. How could you solve it? I have someone else whose website also has this issue. Curious what causes this. 

Thanks for fixing it and your tool obviously.

**Comment by devinroth** [comment]
The website was falsely flagged by a number of list from virtustotal.com. I went through the painstaking process and contacted each of those companies. Took a while. I’m still listed on one since they haven’t responded yet.

Devin

**Comment by mistcat** [comment]
Hi Devin,

I really appreciate you doing that, and working though this pretty esoteric
issue!  You are awesome!  Here on ye old Xfinity network in the US I seem
to be back in business.

Thank you so much!!!
nate

**Comment by devinroth** [comment]
Good to know!


Devin
