### ISSUE TITLE
Blackhole installation and setup for Quicktime recording

### ISSUE THREAD

**Issue by souvenirpictures** [ExistentialAudio/BlackHole#76]
Please, can someone help me set up Blackhole to record audio with Quicktime?  I am using Catalina, and I need to record high-quality audio with video for an on-going documentary project that must now be based within computer communication software, like Zoom or FaceTime. 

In other words, I will be interviewing my subjects via Zoom or FaceTime and need to record the audio (and video) in computer, avoiding the computer speakers.  

I have downloaded the latest version and am not seeing it in my applications.

**Comment by souvenirpictures** [comment]
Ok, I understand that I won't see Blackhole.  And it does pop up as an audio option in Quicktime.  However, my tests are not recording any audio at all.  Just video, when I select Blackhole for the audio option.

**Comment by devinroth** [comment]
Have you setup a multi-output and set that as your default output?

**Comment by souvenirpictures** [comment]
> Have you setup a multi-output and set that as your default output?

I do not see how to do that in Quicktime.

**Comment by devinroth** [comment]
It’s in Audio Midi setup. There is info in the wiki.

**Comment by souvenirpictures** [comment]
Thank you! So helpful

**Comment by idmah** [comment]
When I select BlackHole as audio in Quicktime. it gives me a yellow Not authorized for this device.
and then can't do anything else.

**Comment by devinroth** [comment]
Please upload a screenshot.
