### ISSUE TITLE
Crackling Audio

### ISSUE THREAD

**Issue by hekuli** [ExistentialAudio/BlackHole#761]
### Please Confirm

- [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
- [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
- [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)

### macOS Version

macOS 13 Ventura

### BlackHole Build(s) Affected

- [ ] 2 channel
- [X] 16 channel
- [ ] 64 channel
- [ ] other/custom build

### Describe the bug

I keep getting period crackling sounds whenever I use the latest version (0.5.0) with my Mac. I didn't have this issue before. Seems to be new with Sonoma or a recent update before that. It happens every 5-10 minutes or so. Sounds like digital clipping type of distortion.

I'm using Sonoma 14.2.1 (23C71) Apple M1 Max.

### Reproduction Steps

1. Set main system audio out to Blackhole 2 ch
2. Route the audio through a track in Ableton
3. Configure Ableton to route it's main out to my physical soundcard.
4. Listen to music from Spotify for a while.

### Expected Behavior

I expect clear audio with no crackling or distortion.

**Comment by devinroth** [comment]
This is an issue with Ableton. I have no idea what they are doing wrong.

Please try to reproduce in any other DAW and let me know.

**Comment by hekuli** [comment]
Hi thanks for responding so quickly.

I just tried and was able to quickly reproduce the same problem with a very simple Touchdesigner patch that does nothing but re-route the audio from Blackhole. 

<img width="1069" alt="Screenshot 2023-12-22 at 22 36 19" src="https://github.com/ExistentialAudio/BlackHole/assets/133100798/526c32bb-eac6-44d7-abb8-d47e74b690ac">

I don't have any other issues with Ableton, my system audio, or my sound interface. This problem only occurs for me when Blackhole is in the picture.

**Comment by devinroth** [comment]
Try another test.

With Ableton record the audio. Do you get crackles with recorded audio or any when monitoring?

**Comment by devinroth** [comment]
Also any errors in Console when you’re reproducing the issue?

**Comment by devinroth** [comment]
Also test with Logic / GarageBand.

**Comment by hekuli** [comment]
Here is a recording of it from Ableton.

https://drive.google.com/file/d/1Bn7cyIJ5oyqfxUBv1nw-hj5EPfigyBwm/view?usp=sharing

Nothing in the Console.

Sorry but I don't have/want Logic or Garageband.

**Comment by devinroth** [comment]
How about Audacity? Could you try recording in Audacity for me?

**Comment by aadityakr7** [comment]
I confirm this.

**Steps to reproduce:**
1. Open Ableton, go to settings, select Blackhole under both the audio input & output device.
2. Load any song onto the audio track.
3. Insert a new audio track & set the arm to record.
4. Hit the record button from the main control.
5. Listen SOLO to the newly recorded track & there will be crackling noise in between.

**My analysis:**
From what I could see, the crackling sound can be heard whenever there's clipping of the recorded waveform.

**How to resolve:**
Avoid using Blackhole as a direct audio I/O device & make a configuration for audio input & output. 
1. Open Audio MIDI setup.
2. Click + icon to add a new multi output device, check blackhole along with MacBook speaker (can also select other devices), check _Drift Correction_ for blackhole.
3. Click + icon to add a new aggregate device, check blackhole along with MacBook microphone (can also select other devices), check _Drift Correction_ for blackhole.
4. Now under Ableton settings, use these newly created configurations.

[Reference image for the recorded audio]
<img width="935" alt="image" src="https://github.com/ExistentialAudio/BlackHole/assets/36760501/87b0ac70-e8ba-4195-95b1-c3380cf0c411">

**Comment by aadityakr7** [comment]
I confirm this.

**Steps to reproduce:**
1. Open Ableton, go to settings, select Blackhole under both the audio input & output device.
2. Load any song onto the audio track.
3. Insert a new audio track & set the arm to record.
4. Hit the record button from the main control.
5. Listen SOLO to the newly recorded track & there will be crackling noise in between.

**My analysis:**
From what I could see, the crackling sound can be heard whenever there's clipping of the recorded waveform.

**How to resolve:**
Avoid using Blackhole as a direct audio I/O device & make a configuration for audio input & output. 
1. Open Audio MIDI setup.
2. Click + icon to add a new multi output device, check blackhole along with MacBook speaker (can also select other devices), check _Drift Correction_ for blackhole.
3. Click + icon to add a new aggregate device, check blackhole along with MacBook microphone (can also select other devices), check _Drift Correction_ for blackhole.
4. Now under Ableton settings, use these newly created configurations.

[Reference image for the recorded audio]
![image](https://github.com/ExistentialAudio/BlackHole/assets/36760501/e3a2c20f-94a3-4922-9184-cb484126d38b)

**Comment by devinroth** [comment]
Thanks. I’m still waiting for the audacity test.

Devin

**Comment by dylanharty** [comment]
Not sure if this helps, but using on Mac Sonoma in FL Studio 21. No crackling audio. Just thought I would add some context from a different DAW software.

**Comment by PianoMan7** [comment]
I got this same crackling audio issue with Logic yesterday during a livestreamed recital. I had to resort to using my iPhone mic as a workaround. I set the buffer size in Logic to be 512 or 1024 (way larger than what I think I need — I have an MBP with an M3 Max), and Logic, Black Hole, and my Steinberg interface were all at 48kHz.

**Comment by PianoMan7** [comment]
I would like to say that I didn't do as the documentation said by having Macbook Pro Speakers enabled and listed as the top device in the Multi-Output device. Is this the potential cause?

I would love more detail about why it needs to be done this way. What do you mean by "issues with MacOS"? Which MacOS? I'm on Sonoma 14.5.

**Comment by devinroth** [comment]
Without screenshot I can’t know for sure. That being said multi-outputs and aggregates are pretty buggy. If you can reproduce the issue without a multi-output then I can probably find a way to fix.

Devin

**Comment by Magganpice** [comment]
Can confirm that the issue is not only in Ableton Live. It get worse with time. So, basically if I livestream (basically only OBS, Minecraft and TouchPortal running) for some time, the crackling get's worse and worse. I then just have to switch the sound output to something else and then back again an then it's fine again (but again, get worse with time).

Using a multi-output virtual device to be able to capture the computer sound in OBS.

**Comment by Magganpice** [comment]
<img width="972" alt="Screenshot 2024-06-21 at 19 19 02" src="https://github.com/ExistentialAudio/BlackHole/assets/67961146/baada065-a8c4-475b-9383-8e698e63ddef">

OK, thanks! Is this the problem? Which one should I choose for Drift correction?

**Comment by devinroth** [comment]
All devices that are not the primary/clock device.

Devin

**Comment by devinroth** [comment]
The latest ffmpeg has issues. Roll back to a previous version or use sox instead.

Devin

**Comment by Pranay-Garg** [comment]
So I tried to recording blackhole output with both ffmpeg@5 , ffmpeg@6 , running this command `ffmpeg -f avfoundation -i :0 -ac 2 -ar 44100 output.wav` still facing the crackling sounds. I saw audacity uses ffmpeg version 5.
https://drive.google.com/file/d/1r3q4pS7q-RKtHDw-yWIU37FMZ5XcIfmK/view?usp=share_link

**Comment by devinroth** [comment]
Interesting. Yeah no cracking when recording with Audacity for me.

Devin
