### ISSUE TITLE
MultiSoundChanger - Add to Readme

### ISSUE THREAD

**Issue by tfbecker** [ExistentialAudio/BlackHole#763]
### Please Confirm

- [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
- [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
- [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)

### macOS Version

macOS 13 Ventura

### BlackHole Build(s) Affected

- [ ] 2 channel
- [X] 16 channel
- [ ] 64 channel
- [ ] other/custom build

### Describe the bug

Sorry for being lazy. Could you add https://github.com/rlxone/MultiSoundChanger to the readme/ FAQ ? :
This helped me with the problem of using an agg. device + still wanting to adjust the volume.
This is the part:
_"How can I change the volume of a Multi-Output device?
Unfortunately macOS does not support changing the volume of a Multi-Output device but you can set the volume of individual devices in Audio MIDI Setup."_

### Reproduction Steps

1. Open GH Link

### Expected Behavior

Seeing this in the Readme.md

**Comment by devinroth** [comment]
Thanks for the tip. I think I’ll add a “related projects” section and link to this.

Devin

**Comment by devinroth** [comment]
Done.
