### ISSUE TITLE
Download failed: https://existential.audio/downloads/BlackHole64ch.v0.5.0.pkg

### ISSUE THREAD

**Issue by somnabulimia** [ExistentialAudio/BlackHole#764]
### Please Confirm

- [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
- [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
- [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)

### macOS Version

macOS 13 Ventura

### BlackHole Build(s) Affected

- [X] 2 channel
- [X] 16 channel
- [X] 64 channel
- [ ] other/custom build

### Describe the bug

Existential.audio seems to be DOA.

### Reproduction Steps

1. Tried downloading the Installer from https://existential.audio/blackhole/?pk_campaign=github&pk_kwd=readme
2. Tried installing via homebrew.... ==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/75f7289490677fb0dee1346774013c57309493f1/Casks/b/blackhole-64ch.rb
################################################################################################################################################################# 100.0%
==> Downloading https://existential.audio/downloads/BlackHole64ch.v0.5.0.pkg
curl: (7) Failed to connect to existential.audio port 443 after 9 ms: Couldn't connect to server

Error: Download failed on Cask 'blackhole-64ch' with message: Download failed: https://existential.audio/downloads/BlackHole64ch.v0.5.0.pkg
3. No Profit

### Expected Behavior

Expected either to download the installer or install via homebrew.

### Screenshots

<img width="1165" alt="Screenshot 2024-01-07 at 4 50 42 PM" src="https://github.com/ExistentialAudio/BlackHole/assets/23368925/c0efbba9-ea44-434c-acd5-8c40a1c3aa98">

**Comment by devinroth** [comment]
I bet it’s a result of some firewall you have enabled directly or indirectly.

Devin

**Comment by somnabulimia** [comment]
Fascinating... my Eero system did not like exististential.audio. Switched over to another internet source and it installed.

Thanks. Enjoy a brew on me.

**Comment by devinroth** [comment]
If you could, please contact your provider and ask them to remove the website from their blacklist.

I wonder if it’s related to the name “BlackHole” since I believe there is a virus out there with the same name.

Devin

**Comment by somnabulimia** [comment]
I'm wondering if it is an Eero security issue. 

My other source is the same ISP, different LAN, not going through Eero and it worked. 

Also tried from a completely different ISP and it worked as well.

Would that request go to the ISP or to Eero?

**Comment by devinroth** [comment]
I’m guessing Eero.

Devin
