### ISSUE TITLE
Route Mic directly to headphones

### ISSUE THREAD

**Issue by Fuechsl** [ExistentialAudio/BlackHole#77]
Hi there,

Sorry to "hijack" the issue panel, but I didn't find any forum or support contact.

I tried really hard to use blackhole to route my mic input DRIECTLY to my Headphones, so that I can hear my own voice while doing videocalls (not recordings), but I didn't manage to do it. Is this possible? How?

Thanks, Martin (fuechsl@gmx.ch)

**Comment by devinroth** [comment]
You should be using a digital audio workstation for that. Output to BH is routed to the input. You need something to route the input to the output.

**Comment by devinroth** [comment]
I use a DAW like logic to do the trick.

**Comment by bsima** [comment]
For future reference, you can use "AU Lab" (a free program from Apple dev) to do this as well. Instructions: https://superuser.com/a/1358371
