### ISSUE TITLE
Using aggregate device on Mac Mini is limited to 48kHz audio over HDMI

### ISSUE THREAD

**Issue by Paveldeg** [ExistentialAudio/BlackHole#772]
### Please Confirm

- [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
- [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
- [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)

### macOS Version

macOS 13 Ventura

### BlackHole Build(s) Affected

- [ ] 2 channel
- [X] 16 channel
- [ ] 64 channel
- [ ] other/custom build

### Describe the bug

Using aggregate device on Mac Mini is limited to 48kHz audio over HDMI

### Reproduction Steps

1. Connect external audio device to Mac HDMI, such as AVR
2. Create aggregate device using BlackHole device and the AVR, set sample rate to 192kHz.
3. Play 192kHz audio content on Mac pointing at the aggregate device - observe sample rate in the AVR is 48kHz. 

### Expected Behavior

Hi-res content played back through an aggregate device should be played at sample rate set in the aggregate device, not fixed to 48kHz.

**Comment by devinroth** [comment]
This sounds like a macOS bug. I think BlackHole handles different sample rates fine alone without an aggregate.

Devin

**Comment by Paveldeg** [comment]
> This sounds like a macOS bug. I think BlackHole handles different sample rates fine alone without an aggregate. Devin
> […](#)
Using BlackHole alone produces no audio at all.

**Comment by Paveldeg** [comment]
Upgraded to Sonoma OS and issue got fixed.
