### ISSUE TITLE
Installation fails on macOS Sonoma 14.4

### ISSUE THREAD

**Issue by AtiX** [ExistentialAudio/BlackHole#774]
### Please Confirm

- [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
- [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
- [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)

### macOS Version

macOS 13 Ventura

### BlackHole Build(s) Affected

- [X] 2 channel
- [ ] 16 channel
- [ ] 64 channel
- [ ] other/custom build

### Describe the bug

When trying to install the 2ch version, the installation script fails with an unspecified error.

I tried the FAQ advice ("move the package file to another folder, e.g. your desktop").

I have a Macbook Pro with an M3 Apple Silicon chip.

### Reproduction Steps

1. Download intstaller (I tried with website and homebew) `BlackHole2ch.v0.5.0.pkg`
2. Run installer / run homebrew
3. Get an unspecified installation error

E.g. for homebrew the error is `installer: The install failed. (Die Installation ist aufgrund eines Fehlers fehlgeschlagen. Wende dich an den Hersteller der Software. Beim Ausführen der Skripts aus dem Paket „BlackHole2ch.v0.5.0.pkg“ ist ein Fehler aufgetreten.)` which basically means "Installation failed due to an error that occurred while running the the insallation script from the package"

### Expected Behavior

Installation should work

**Comment by devinroth** [comment]
There’s an issue with 14.4. The post install script fails. Please restart your computer and then check if BlackHole is in Audio MIDI Setup. If so it is installed correctly.

My plan is to change the installer to require a system reboot as recommended by Apple.

Devin

**Comment by AtiX** [comment]
Thanks for your reply. I can confirm that the package was actually installed and is working as intended after a restart.

**Comment by chris-miner** [comment]
BTW, this affects the homebrew install in a similar fashion.   The install fails, but on restart you see BlackHole is in the Audio MIDI Setup.  Unfortunately, since the install failed brew assumes the install failed.  You can't uninstall via home-brew.  You have to use the uninstaller.

**Comment by devinroth** [comment]
I have a new installer. I guess we need to update home-brew with the new details.

Devin
