### ISSUE TITLE
Problem with download of the package

### ISSUE THREAD

**Issue by vpernica** [ExistentialAudio/BlackHole#775]
### Please Confirm

- [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
- [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
- [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)

### macOS Version

macOS 13 Ventura

### BlackHole Build(s) Affected

- [X] 2 channel
- [ ] 16 channel
- [ ] 64 channel
- [ ] other/custom build

### Describe the bug

Currently it's not possible to install the blackhole audio in any way, because the certificate of the download server is reported as not valid.

### Reproduction Steps

brew install blackhole-2ch 

fails with error:
==> Downloading https://existential.audio/downloads/BlackHole2ch.v0.5.0.pkg
curl: (60) SSL certificate problem: self signed certificate                                                            
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

Error: Download failed on Cask 'blackhole-2ch' with message: Download failed: https://existential.audio/downloads/BlackHole2ch.v0.5.0.pkg

Similarly manually clicking on download installer lead to error message, that connection is not trusted.

### Expected Behavior

Package will be installed

### Screenshots

<img width="858" alt="image" src="https://github.com/ExistentialAudio/BlackHole/assets/48832159/48ab6f7a-c9f0-452f-9ca4-c0dcc6998dff">

<img width="684" alt="image" src="https://github.com/ExistentialAudio/BlackHole/assets/48832159/bd25a027-5d9d-4053-83c0-bee916ce7272">

**Comment by devinroth** [comment]
Could you please attach the certificate? I see no issues on my end.

Devin

**Comment by vpernica** [comment]
Hi Devin, the problem is caused by the security solution of my internet provider, which is blocking the download side. 
When testing it with Firefox there are more details:

<img width="630" alt="image" src="https://github.com/ExistentialAudio/BlackHole/assets/48832159/f35b60de-a687-4df6-a3ec-7d58459265e9">


I was able to download the install package from my virtual desktop without problem. 
Thus I guess, this can be closed. There is not problem on your side.

**Comment by vpernica** [comment]
Just a small update. I sent an email to the ISP. But checking it via virustotal.com, the page is being unfortunately marked as phishing by many sec. solutions:

<img width="863" alt="image" src="https://github.com/ExistentialAudio/BlackHole/assets/48832159/ce77cae9-182c-47cf-afa4-72ccb2445f46">


Vaclav

**Comment by devinroth** [comment]
What domain did you search? I get zero results for existential.audio on virustotal.

Devin

**Comment by vpernica** [comment]
The link from option 1:

<img width="394" alt="image" src="https://github.com/ExistentialAudio/BlackHole/assets/48832159/c075487c-8b91-4e7c-87c1-06643705170a">


https://existential.audio/blackhole/?pk_campaign=github&pk_kwd=readme

It's still reported as phish on VirusTotal.

**Comment by devinroth** [comment]
Very very odd. Https://existential.audio/blackhole isn’t listed and it’s the exact same website.

I’ll just update the link.


Devin

**Comment by vpernica** [comment]
Thanks for checking and update. I guess, we can close this.
Btw. also my internet provider has added that site on safe list after I wrote him.
