### ISSUE TITLE
Uninstaller "fails" on MacOS 14.4 and newer

### ISSUE THREAD

**Issue by BitGrub** [ExistentialAudio/BlackHole#777]
### Please Confirm

- [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
- [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
- [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)

### macOS Version

macOS 14.4

### BlackHole Build(s) Affected

- [X] 2 channel
- [X] 16 channel
- [X] 64 channel
- [ ] other/custom build

### Describe the bug

I assume this has to do with [launchctl's inability to restart coreaudiod](https://developer.apple.com/documentation/macos-release-notes/macos-14_4-release-notes#Core-Audio).

`sudo killall coreaudiod` is now more advisable, according to Apple

### Reproduction Steps

1. Install Blackhole (any number of channels)
2. Uninstall it via uninstaller, or manually

### Expected Behavior

No errors

**Comment by devinroth** [comment]
Thanks for the reminder. I forgot to update the uninstaller.

Devin

**Comment by lswee** [comment]
This works as a temporary solution:
https://github.com/ExistentialAudio/BlackHole/issues/779#issuecomment-2058581435

**Comment by devinroth** [comment]
Fixed with 0.6.0.
