### ISSUE TITLE
Can't update

### ISSUE THREAD

**Issue by mbierman** [ExistentialAudio/BlackHole#779]
### Please Confirm

- [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
- [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
- [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)

### macOS Version

macOS 13 Ventura

### BlackHole Build(s) Affected

- [x] 2 channel
- [ ] 16 channel
- [ ] 64 channel
- [ ] other/custom build

### Describe the bug

macOS 14.4.1 (23E224)
Updating with homebrew is failing

### Reproduction Steps

brew update
brew outdated
brew upgrade --greedy
brew cleanup

### Expected Behavior

Update using homebrew should work

### Screenshots

```
==> Upgrading blackhole-2ch
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/ef939c438c5519c1dc533f8384691106bc2262d9/Casks/b/blackhole-2ch.rb
Already downloaded: /Users/michael/Library/Caches/Homebrew/downloads/abaf20d208584f623d2627beaa5ae3045b883ebc804c27d35b9bc886a3c6dedd--blackhole-2ch.rb
==> Downloading https://existential.audio/downloads/BlackHole2ch-0.6.0.pkg
Already downloaded: /Users/michael/Library/Caches/Homebrew/downloads/094ac75837aa76e51e9defa1f6623144c5a3b223a1b426cf5ddb42c224e70c4a--BlackHole2ch-0.6.0.pkg
==> Uninstalling packages with sudo; the password may be necessary:
Could not kickstart service "com.apple.audio.coreaudiod": 1: Operation not permitted
==> Purging files for version 0.6.0 of Cask blackhole-2ch
Error: blackhole-2ch: Failure while executing; `/usr/bin/sudo -E -- /bin/launchctl kickstart -kp system/com.apple.audio.coreaudiod` exited with 1. Here's the output:
Could not kickstart service "com.apple.audio.coreaudiod": 1: Operation not permitted

```

**Comment by BetterB0y** [comment]
Uninstall is not working too.

**Comment by devinroth** [comment]
Kickstart no longer works. We updated this. I suggest opening an issue with home-brew since I think it’s related to older versions using that command.

Devin

**Comment by BetterB0y** [comment]
Okey, I will try contact brew. Still you've got readme to update. There are still kickstart commands.

**Comment by devinroth** [comment]
Thanks for the reminder. Feel free to @ me on the homebrew issue.

Devin

**Comment by mbierman** [comment]
@devinroth @BetterB0y Sorry you lost me a bit.  I don't see anything in the readme about updating. Do I have to uninstall and reinstall? it would be great if homebrew was fixed. I really prefer using that to handle this stuff when possible.

**Comment by BetterB0y** [comment]
@mbierman Command is still in readme. It's not resolving anything about this issue.

**Comment by BetterB0y** [comment]
@devinroth Is it possible that there is an error because I've got installed 0.5.0 version already. When did you updated that you are not using kickstart?

**Comment by gnattu** [comment]
I found a way to workaround this:

You go to the Caskroom for the cask, on Apple Silicon macs, it is here:

```
/opt/homebrew/Caskroom/blackhole-2ch/.metadata/0.5.0/
```

And you will see a date, cd into it, you will see the `blackhole-2ch.rb`

Edit it that file, change 
```ruby
system_command "/bin/launchctl",
                   args:         [
                     "kickstart",
                     "-kp",
                     "system/com.apple.audio.coreaudiod",
                   ],
                   sudo:         true,
                   must_succeed: true
```

to 
```ruby
system_command "/usr/bin/killall",
                   args:         ["coreaudiod"],
                   sudo:         true,
                   must_succeed: true
```

Then save the file, and then uninstall should success.

**Comment by BetterB0y** [comment]
@gnattu it worked for blackhole-2ch. What about blackhole-16ch? Is it okey to just delete blackhole-16ch dir from Caskroom?

**Comment by gnattu** [comment]
> @gnattu it worked for blackhole-2ch. What about blackhole-16ch? Is it okey to just delete blackhole-16ch dir from Caskroom?

No, you do the same for the `blackhole-16ch.rb` to replace the `system_command`

**Comment by gnattu** [comment]
The `.metadata` folder is a hidden and you cannot navigate into it using finder directly. You replace the path and cd into it directly.

**Comment by BetterB0y** [comment]
Thanks. It worked. I used cd but something weird happened and i wasn't in .metadata dir.

**Comment by rubincc** [comment]
Thanks @devinroth and @gnattu.
After `brew remove` (following your suggestion) I did a `brew install` and now everything works.

**Comment by WolfLink** [comment]
To be it clear, you can run "brew upgrade" after [editing blackhole-2ch.rb](https://github.com/ExistentialAudio/BlackHole/issues/779#issuecomment-2058581435) to successfully upgrade to the latest version (which should then upgrade fine in the future).

**Comment by bevanjkay** [comment]
A potentially easier solution, that makes it less likely to leave the cask file in an unreadable state is to remove the file from the Caskroom and then reinstall it.

This will cause Brew to use the most up-to-date uninstall stanza, instead of the one that was present when the installed version was installed.

Silicon Mac
`rm -rfi /opt/homebrew/Caskroom/blackhole-2ch/`

Intel Mac
`rm -rfi /usr/local/Caskroom/blackhole-2ch/`

Then reinstall
`brew reinstall blackhole-2ch`

**Comment by booi** [comment]
> A potentially easier solution, that makes it less likely to leave the cask file in an unreadable state is to remove the file from the Caskroom and then reinstall it.
> 
> This will cause Brew to use the most up-to-date uninstall stanza, instead of the one that was present when the installed version was installed.
> 
> Silicon Mac `rm -rfi /opt/homebrew/Caskroom/blackhole-2ch/`
> 
> Intel Mac `rm -rfi /usr/local/Caskroom/blackhole-2ch/`
> 
> Then reinstall `brew reinstall blackhole-2ch`

This oddly didn't work for me as it just downloaded 0.5.0 to run uninstall first which failed. The previous fix of patching the `.rb` file did work though.

**Comment by booi** [comment]
> If remove the `-k` parameter works fine.

I don't think that's right. What we need is for `coreaudiod` to restart which we were doing with `launchctl kickstart -k`.  Merely removing the `-k` will mean it won't restart `coreaudiod`. 

I think the correct solution is here: https://github.com/ExistentialAudio/BlackHole/issues/779#issuecomment-2058581435 . Since `coreaudiod` is considered a core service, it will restart if killed.

**Comment by HaigNalbandian** [comment]
This is not just a homebrew issue, the 2ch uninstaller .pkg in the README fails, and so do the commands provided in that same README

I had originally installed via the 2ch installer .pkg provided through the existential.audio site

**Comment by devinroth** [comment]
It’s a combination. It depends on which command you use.

To manually uninstall remove BlackHole from Hal and then restart. If that doesn’t work make sure you uninstall Rogue Amoeba’s apps since they mess with CoreAudio.

Devin

**Comment by MykolaVaskevych** [comment]
had the same issue today.
```
OS:
macOS Sequoia 15.2 arm64
```
```
❯ brew --version
Homebrew 4.4.20
```
file was located at:
```
❯ pwd && ls -al
/opt/homebrew/Caskroom/blackhole-16ch/.metadata/0.5.0/20230602190544.858/Casks
total 8
drwxr-xr-x@ 3 stnikolas  admin   96  2 Jun  2023 .
drwxr-xr-x@ 3 stnikolas  admin   96  2 Jun  2023 ..
-rw-r--r--@ 1 stnikolas  admin  910  2 Jun  2023 blackhole-16ch.rb
```

file contained:
```
o
  version "0.5.0"
  sha256 "573240f711010fd527698e1c63291487eee53ac1fd9e2f8ade0bf337abafcc83"

  url "https://existential.audio/downloads/BlackHole16ch.v#{version}.pkg"
  name "BlackHole 16ch"
  desc "Virtual Audio Driver"
  homepage "https://existential.audio/blackhole/"

  livecheck do
    url "https://github.com/ExistentialAudio/BlackHole"
    strategy :github_latest
  end

  pkg "BlackHole16ch.v#{version}.pkg"

  uninstall_postflight do
    system_command "/bin/launchctl",
                   args:         [
                     "kickstart",
                     "-kp",
                     "system/com.apple.audio.coreaudiod",
                   ],
                   sudo:         true,
                   must_succeed: true
  end

  uninstall quit:    "com.apple.audio.AudioMIDISetup",
            pkgutil: "audio.existential.BlackHole16ch"

  # No zap stanza required
end
```

after changing it to:
```
o
  version "0.5.0"
  sha256 "573240f711010fd527698e1c63291487eee53ac1fd9e2f8ade0bf337abafcc83"

  url "https://existential.audio/downloads/BlackHole16ch.v#{version}.pkg"
  name "BlackHole 16ch"
  desc "Virtual Audio Driver"
  homepage "https://existential.audio/blackhole/"

  livecheck do
    url "https://github.com/ExistentialAudio/BlackHole"
    strategy :github_latest
  end

  pkg "BlackHole16ch.v#{version}.pkg"

  uninstall_postflight do
    system_command "/usr/bin/killall",
                   args:         ["coreaudiod"],
                   sudo:         true,
                   must_succeed: true
  end

  uninstall quit:    "com.apple.audio.AudioMIDISetup",
            pkgutil: "audio.existential.BlackHole16ch"

  # No zap stanza required
end
```

issue was resolved.

**Comment by devinroth** [comment]
I just released a new version of BlackHole. I will need to update brew.

Devin
