### ISSUE TITLE
Multi-audio output.. doesn't.

### ISSUE THREAD

**Issue by BillKeenan** [ExistentialAudio/BlackHole#78]
Basic multi-audio output, just doesn't produce any sound, the aggregate device seems to work well, and if I use a system output device I can hear the aggregate, but multi-output seemingly does nothing...

Mojave-10.14.6 (18G3020)

<img width="668" alt="Screen Shot 2020-03-25 at 10 45 30 AM" src="https://user-images.githubusercontent.com/1319630/77549221-f5194080-6e85-11ea-9a31-6c09df219354.png">

**Comment by BillKeenan** [comment]
not sure if it's related to this

https://github.com/ExistentialAudio/BlackHole/issues/55

I'm getting also the video in , for a example a youtube or vlc window, freezing issue if I change anything etc...

**Comment by devinroth** [comment]
@BillKeenan  is probably right. Multi output devices are really buggy. Try to see if it works with just the MacBook Pro speakers first. If it does try adding one device at a time.

**Comment by BillKeenan** [comment]
will do, thanks for this, glad to see it actively developed.
