### ISSUE TITLE
The volume of balckhole always change back to 1.00

### ISSUE THREAD

**Issue by dawei101** [ExistentialAudio/BlackHole#786]
### Please Confirm

- [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
- [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
- [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)

### macOS Version

macOS 13 Ventura

### BlackHole Build(s) Affected

- [X] 2 channel
- [ ] 16 channel
- [ ] 64 channel
- [ ] other/custom build

### Describe the bug

I use blackhole as a loopback solution to fix the echo problem with jitsi meet desktop.
When I set the volume like  0.5(50%) , and the volume will rise up slowly until to max level. And the The Touch bar's volume is still 0.5, the volume in `system settings` is still 0.5 

If there is no music playing, this issue won't happen.

### Reproduction Steps

1. Set blackhole as default output
2. Read the blackhole input and flush it to buildin speaker
3. Play a music
4. Set the volume
5. Get the volume 1 time/second

### Expected Behavior

The volume should not change.

### Screenshots

Below is with macos-audio-devices debuging it.

```
> audioDevices.setOutputDeviceVolume.sync(55, 0.4)
undefined
> audioDevices.getOutputDeviceVolume.sync(55)
'0.40'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.40'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.40'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.43'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.43'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.55'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.63'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.63'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.63'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.76'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.76'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.78'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.78'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.87'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.87'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.87'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.87'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.92'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.92'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.92'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.92'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.92'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.92'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.92'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.92'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.92'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.92'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.92'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.92'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.92'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.92'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.92'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.98'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.98'
> audioDevices.getOutputDeviceVolume.sync(55)
'0.98'
> audioDevices.getOutputDeviceVolume.sync(55)
'1.00'
> audioDevices.getOutputDeviceVolume.sync(55)
'1.00'

```

**Comment by dawei101** [comment]
With the command line `osascript -e 'output volume of (get volume settings)' `, the result is same with macos-audio-devices

**Comment by devinroth** [comment]
That’s really funny. Trust me, there is nothing internally that changes the volume.

Things to test. Different audio apps to play music. Maybe the microphone is set as default and some app is changing the volume.

Devin

**Comment by dawei101** [comment]
I have found why it happen
```
                            return navigator.mediaDevices.getUserMedia({
                                audio: {
                                    deviceId: {
                                        exact: device.deviceId
                                    },
                                    sampleRate: 48000,
                                    echoCancellation: true,
                                    noiseSuppression: true,
                                    autoGainControl: false
                                }
                            });
```

the `autoGainControl: true` would make the volume change. So tricky...
Hope someone else with the same issue could see this.
