### ISSUE TITLE
AudioQueue output to hardcoded BlackHole device doesn't work as expected, no output

### ISSUE THREAD

**Issue by kmorrissey-mersive** [ExistentialAudio/BlackHole#79]
I'm trying to model a situation we'd like to implement, and I can't get it to work. I'm using Catalina 10.15.3, Xcode 11.4. There is a Simple A->B->C chain where

A is a small program (source at https://gist.github.com/kmorrissey-mersive/9dda07ef6096ff5dfe3cef33a7792626) that streams a generated  sine wave to an output AudioQueue with an output device set by deliberately hardcoded UID ("BlackHole_UID"). I didn't write the program, just made minimal changes to set the output device. What's important is that it opens a fixed output device.

B is BlackHole built with Xcode and manually installed.

C is Apple's CAPlayThrough example made to build and run on Catalina and just streams from Blackhole to built-in audio out.

My problem is that I don't hear anything when I run A. If I conditionally compile out setting the output device in A and let it just go to the system output device, I hear the generated sine wave. Also, if I play something to BlackHole with GarageBand, I hear the output. So, I know B and C are working and A mostly works. 

What am I doing wrong?

**Comment by devinroth** [comment]
Could be a number of issues but by quickly looking at the code the audio format of program A needs to match BlackHole. 

At line 49. 
```
  fmt.mSampleRate = 44100;
  fmt.mFormatID = kAudioFormatLinearPCM;
  fmt.mFormatFlags = kAudioFormatFlagIsSignedInteger | kAudioFormatFlagIsPacked;
  fmt.mFramesPerPacket = 1;
  fmt.mChannelsPerFrame = 1; // 2 for stereo
  fmt.mBytesPerPacket = fmt.mBytesPerFrame = 2; // x2 for stereo
  fmt.mBitsPerChannel = 16;
```
BlackHole uses Float32, 16 channels. If you fix that it should work. As a general comment you should query CoreAudio to get the correct format of the audio device instead of hard coding. It will take additional work but will be less prone to errors.

**Comment by kmorrissey-mersive** [comment]
Thanks, I will try that and report back. I'm new to macOS audio programming, so you spotted exactly the kind of detail I didn't have the eye for yet. I just ordered a book on Core Audio programming. I'm aware that Catalina has obsoleted parts of it, but I figure most of the book's content is still relevant.

**Comment by devinroth** [comment]
CoreAudio programming is a real pain. Hope you can figure it out.

**Comment by kmorrissey-mersive** [comment]
By changing the AudioQueue audio format to be 16 channels of floats and changing buffer data likewise, I started getting output. (You will need to refer to the code sample above to understand this.)

Changing to float data but sticking with the original 1 channel was insufficient. I didn't get data until I provided 16 channels of data.

**Comment by devinroth** [comment]
Awesome. I'm glad you were able to figure it out!
