### ISSUE TITLE
SHA256 mismatch

### ISSUE THREAD

**Issue by roi-f** [ExistentialAudio/BlackHole#795]
### Please Confirm

- [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
- [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
- [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)

### macOS Version

macOS 13 Ventura

### BlackHole Build(s) Affected

- [X] 2 channel
- [X] 16 channel
- [ ] 64 channel
- [ ] other/custom build

### Describe the bug

Mac M1, macOS Sonoma ver. 14.5, 
Tried brew install both 2 and 16 ch versions, both fail on sha256 mismatch.
Found only an [older issue](https://github.com/ExistentialAudio/BlackHole/issues/277) on this 
E.g. -

```rew install blackhole-2ch
==> Downloading https://formulae.brew.sh/api/formula.jws.json
################################################################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
################################################################################################################### 100.0%
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/21337fa1dd8a21eaaa733d2d26ca915d9f02af8f/Casks/b/
################################################################################################################### 100.0%
==> Downloading https://existential.audio/downloads/BlackHole2ch-0.6.0.pkg
################################################################################################################### 100.0%
Error: SHA256 mismatch
Expected: 8d2223cc1aa976b70d14ff7c469cc62a64c3192177c8c0eb38df0483db790c7b
  Actual: 06709430aec19e684a2e55012440d58c3152d76bb9a0c8e6a218d87e30f055d2

### Reproduction Steps

From Mac m1 with OS Sonoma 14.5, 
Open terminal, and type
```brew install blackhole-2ch

### Expected Behavior

install :)

### Screenshots

_No response_

**Comment by devinroth** [comment]
Just tested and have no issues. The downloaded package is 8d2223cc1aa976b70d14ff7c469cc62a64c3192177c8c0eb38df0483db790c7b.

Maybe try cleaning your cache.

Devin

**Comment by roi-f** [comment]
Thank you @devinroth .
I cleared all crew cache (and deleted downloads) a few times, without success. Any other ideas?

**Comment by devinroth** [comment]
No idea.

The file on the server is 8d2223cc1aa976b70d14ff7c469cc62a64c3192177c8c0eb38df0483db790c7b.

It’s the same after I download.

If you’re not getting that after you download then something is clearly getting corrupted in the process.

Try downloading the file yourself and running “shasum -a 256” on it.

Maybe some scary stuff is happening on your computer or internet traffic.

Try matching some shas of other downloads?

Devin
