### ISSUE TITLE
Introduces extreme audio latency

### ISSUE THREAD

**Issue by nbilyk** [ExistentialAudio/BlackHole#797]
### Please Confirm

- [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
- [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
- [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)

### macOS Version

macOS 13 Ventura

### BlackHole Build(s) Affected

- [x] 2 channel
- [ ] 16 channel
- [ ] 64 channel
- [ ] other/custom build

### Describe the bug

On macOS Sonoma, I am getting 4-5s of audio latency when BlackHole is installed, even if it's not selected for device output.

### Reproduction Steps

1.
2.
3.
etc...

### Expected Behavior

I would expect when BlackHole is not selected as device output it should not have an affect.

**Comment by devinroth** [comment]
This is impossible. BlackHole is a user space driver and is sandboxed. It has zero influence on other drivers. If so it’s a bigger core audio bug which I highly doubt. I suspect something else is the culprit. Do you have Rogue Amoeba’s stuff installed?

Plus you never included any steps to reproduce.

Devin

**Comment by nbilyk** [comment]
It happened on two different Macbooks for two different people and different headsets. 
The issue started after installing the driver and went away after uninstalling. 

Repro steps are to install 2ch macOS version (intel, Sonoma)
Set output device to Bluetooth headphones
Play audio 
Observe several seconds of latency

**Comment by nbilyk** [comment]
And no, I've never heard of Rogue Amoeba

**Comment by devinroth** [comment]
Play audio from where? And how are you measuring latency?

Devin

**Comment by nbilyk** [comment]
From any source, there is a several second delay between play and when audio can be heard. Sometimes as high as 5-6 seconds

**Comment by devinroth** [comment]
Even after a computer restart?

Devin

**Comment by nbilyk** [comment]
I uninstalled before I tried a restart

**Comment by devinroth** [comment]
Just Bluetooth or all audio?

Devin

**Comment by nbilyk** [comment]
Sorry, unsure, didn't spend a lot of time trying to isolate further than related to the black hole driver.

**Comment by devinroth** [comment]
I don’t think it’s related but I’ll test.

Devin

**Comment by devinroth** [comment]
Tested and I'm having absolutely no issues with my AirPods. Try again but this time restart your computer after installing. AirPods are known to be buggy and I can't guarantee what other apps do. It's entirely possible that the installation process which reboots CoreAudio causes issues with AirPods. Let me know the results.
