### ISSUE TITLE
Can't uninstall using uninstaller, I can see the blackhole 2ch in MIDI

### ISSUE THREAD

**Issue by orsaada** [ExistentialAudio/BlackHole#798]
### Please Confirm

- [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
- [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
- [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)

### macOS Version

macOS 13 Ventura

### BlackHole Build(s) Affected

- [X] 2 channel
- [ ] 16 channel
- [ ] 64 channel
- [ ] other/custom build

### Describe the bug

can't uninstall using the uninstaller - it says it can't be uninstalled due to an issue in the program and contact the developer. macbook pro m1
There isn't a folder in order to uninstall manually, while I see the software in MIDI

### Reproduction Steps

1. install ch2 via the link received on the email
2. uninstall using the uninstaller in the github

### Expected Behavior

the software is uninstalled

**Comment by devinroth** [comment]
I sure hope you tried restarting before coming here.

Devin

**Comment by GrapeJelly** [comment]
I'm having the same problem. Blackhole shows up in Audio Midi Setup, but the uninstaller fails to install and when I follow the manual instructions there is no Blackhole file in the folder. Yes, I rebooted. 
<img width="732" alt="Screenshot 2024-09-06 at 2 09 59 PM" src="https://github.com/user-attachments/assets/ee65bf2f-8bb1-4daf-a976-c56ae9514559">
<img width="993" alt="Screenshot 2024-09-06 at 2 12 16 PM" src="https://github.com/user-attachments/assets/9f5b5033-049c-4511-a3bf-31c71ee543f6">
<img width="682" alt="Screenshot 2024-09-06 at 2 12 30 PM" src="https://github.com/user-attachments/assets/0b344bbc-98bc-43e6-99fc-6c80d01b6748">

**Comment by devinroth** [comment]
ACE is the problem. It messes up CoreAudio. I’ve seen this before. Uninstall all the Rogue Amoeba stuff.

Devin

**Comment by GrapeJelly** [comment]
I deleted my earlier response but will note for future users that even though the uninstaller says it failed, it actually didn't, and you have to reboot. Blackhole will show up in your audio devices until you restart your computer.
