### ISSUE TITLE
Record directly to file

### ISSUE THREAD

**Issue by LwsBtlr** [ExistentialAudio/BlackHole#8]
Any chance we will be able to direct blackhole to simply dump the audio directly into a file instead of using another program to “record” the audio stream and then saving it when it’s done?

**Comment by devinroth** [comment]
I don't think it would be that hard to implement. It's not the highest thing on my priority list. I think there are other apps out there that can do it. But I'll add it to the features request.

**Comment by masonkoh** [comment]
That would be a quite powerful feature that makes this program even more perfect. I strongly suggest you implement that.

**Comment by iurikothe** [comment]
This would be lovely.

I'd use to record just audio from meetings (via Skype or Browsers)

**Comment by adarshp** [comment]
This would be a very useful feature for us.

**Comment by simcc** [comment]
A nice upgrade to that would be a timemachine...so say the last _x_ minutes is constantly written to a file...a "print button" saves the file with date/time as name.
