### ISSUE TITLE
Can not uninstall the Directory does not show any HAL folder

### ISSUE THREAD

**Issue by DushyantSaraswat** [ExistentialAudio/BlackHole#80]
R /Library/Audio/Plug-Ins/HAL/BlackHole.driver
rm: /Library/Audio/Plug-Ins/HAL/BlackHole.driver: No such file or directory

**Comment by TroyEdmison402** [comment]
The directory is in `/System/Library/...` instead of `user/Library/...`. Tripped me up at first as well.

**Comment by Robindo** [comment]
Thanks.. that helped me to start with. Finally I was able to uninstall BlackHole completely.

For those who still have trouble uninstalling, I've written a short 'how-to' which worked for me:

1. Close all your audio devices, including ‘Audio MIDI setup’ and ’Sound’ in your ‘System Settings’
2. Open your iTerm terminal

3. Go to the directory where the driver is located
`cd /Library/Audio/Plug-Ins/HAL`


4. Check if the driver is there. You should see the directory ‘BlackHole.driver’
`ls`


5. remove the directory ‘BlackHole.driver’
`sudo rm -rf BlackHole.driver`

6. restart the core audio driver
`sudo launchctl kickstart -kp system/com.apple.audio.coreaudiod`

7. Check your system preferences and / or audio midi setup.  You should not see the BlackHole driver anymore

**Comment by devinroth** [comment]
Thanks @Robindo i’ll add these clear instructions to the wiki.

**Comment by DushyantSaraswat** [comment]
Thank you Troy!
