### ISSUE TITLE
MacOS Sonoma 14.6.1 -  dB lock at "0.0" won't accept 6.0 (or any number)

### ISSUE THREAD

**Issue by ChristopherDaviau** [ExistentialAudio/BlackHole#807]
### Please Confirm

- [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
- [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
- [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)

### macOS Version

macOS 13 Ventura

### BlackHole Build(s) Affected

- [ ] 2 channel
- [X] 16 channel
- [ ] 64 channel
- [ ] other/custom build

### Describe the bug

In Audio Midi Setup, probably an Apple thing to disable Blackhole, but decibels "dB" is locked at "0.0", the user can select dB, and try to enter another value (6.0 recommended) but Mac won't let you submit, return, tab, or otherwise advance out of that field. If the value is anything other than "0.0" if forces that field to remain in focus. Only when it is set to "0.0" will it let you submit, return, tab, or otherwise advance past the dB field. See images.

### Reproduction Steps

1. open Audio Midi Setup
2. select Blackhole 16ch
3. Value of dB is default to 0.0
4. The field can be selected, and the number altered, but it forces that field to be focus, and cannot be submit, return, tabbed out of or otherwise advance beyond / become unfocused, unless it is set back to 0.0
etc...

### Expected Behavior

It should set to 6.0 or whatever value the user wishes, but with decibels forced to zero, it does matter if BlackHole can listen, the volume is locked at 0.0

### Screenshots

This is from BlackHole's help wiki, for setup directions:
![Screenshot 2024-09-25 at 4 15 09 PM](https://github.com/user-attachments/assets/1585333a-7cde-440c-965f-112b8377afdd)

This is when the user attempt to input any value other than 0.0 (in this case, 6), that value field is forced to focus, and can not submit, tab, return, or otherwise advance beyond…
![Screenshot 2024-09-25 at 4 13 21 PM](https://github.com/user-attachments/assets/10561624-54c5-46b1-a52f-76ce4f01a572)

…unless you set the value back to 0.0, where it then enable tab or return, here show advanced to the highlighted checkbox:
![Screenshot 2024-09-25 at 4 13 32 PM](https://github.com/user-attachments/assets/ea3bc3f9-9141-415f-a8c9-5e1bc341f69a)

**Comment by devinroth** [comment]
Of course it won’t accept 6.0 dB. The max is 0.0 dB. The accepted range is -64dB to 0dB.

**Comment by orchetect** [comment]
This value is using the dbFS scale which is used in digital audio. Zero is the maximum possible value.

So basically zero means in this case that no volume adjustment is being done by BlackHole and audio transmitted through it will be the same volume at the output as it is at the input.

The slider value is trim only, and will only accept negative values below zero. Which means you can only lower the volume at this stage.
