### ISSUE TITLE
Two Amazon Echos and stereo channels

### ISSUE THREAD

**Issue by giovannirco** [ExistentialAudio/BlackHole#81]
I am trying to setup two Echos in stereo as the output of my mac, Amazon offer this inside Alexa but I cannot bluetooth pair the stereo on the computer, only individual devices. My problem is that each individual device have 2 output channels and when trying to use as Black Hole I am not sure how to set it up, Using Multi-Output Device I end up with Mono sound playing on both outputs with a good quality, then tried using aggregated devices to separate the channels and used one channel per echo in each side and it worked but I feel like the sound quality isnt as good as it should. Tried Quadraphonic setup and used left channels for one device and right channels for the other device but I didnt feel any difference. Also I cannot change the output volume which I can overcome changing on the device itself but would be awesome to have it controlled on my keyboard. Another thing that annoyed me is that after changing the volume of each channel I cannot use the default values (0,5 - 70,5dB) anymore. so I feel like one of the echos is slightly louder than the other, any advices on that?

**Comment by devinroth** [comment]
Send me screenshots of how you have everything setup and I’ll see what i can do to help.

**Comment by giovannirco** [comment]
These are the two Amazon Echo's connected via bluetooth, each of them have two channels
![image](https://user-images.githubusercontent.com/34581682/78709882-cb7f0100-78ea-11ea-9f0b-3de0d8605cd6.png) ![image](https://user-images.githubusercontent.com/34581682/78709928-dd60a400-78ea-11ea-803a-49ec2e3ce079.png)

Then I created an aggregated audio device called `Echo Stereo` 
![image](https://user-images.githubusercontent.com/34581682/78710172-41836800-78eb-11ea-922e-7679ccfe3145.png)

Clicking on `Configure speakers` I have this:
![image](https://user-images.githubusercontent.com/34581682/78710270-7099d980-78eb-11ea-80d8-35fc76e52782.png)

After putting each individual Echo with max volume I achieved a good sound quality, not sure why but after that it helped a bit, but I still feel a better quality when I use them in mono.

Is this what I should be doing?

**Comment by devinroth** [comment]
It looks like you're doing everything right. Since I don't have two Echos to test it's hard for me to say why there's a difference in audio quality. Hopefully someone else can chime in.

**Comment by giovannirco** [comment]
thanks for the help! I am using mono when I just want to output the computer sound as it gets a bit better and I dont care for stereo for just playing media or youtube videos, I am using alexa to play music. I am good now. Sorry for not closing the issue before

**Comment by climbingcranes** [comment]
I'm having this issue where one of the other echo dots is louder than the other, how did u fix this and how can I tell if I'm getting mono or stereo sound?
