### ISSUE TITLE
Blackhole does not work after Sonoma 14.5 update

### ISSUE THREAD

**Issue by jbrewlet** [ExistentialAudio/BlackHole#814]
### Please Confirm

- [X] I have read the **[FAQ](https://github.com/ExistentialAudio/BlackHole#faq) and [Wiki](https://github.com/ExistentialAudio/BlackHole/wiki)** where most common issues can be resolved
- [X] I have searched **[Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)** to see if the same question has already been asked
- [X] This is a **bug** and not a question about audio routing or configuration, which should be posted in [Discussions](https://github.com/ExistentialAudio/BlackHole/discussions)

### macOS Version

macOS 13 Ventura

### BlackHole Build(s) Affected

- [X] 2 channel
- [ ] 16 channel
- [ ] 64 channel
- [ ] other/custom build

### Describe the bug

I've been using Blackhole to stream audio from multiple sources to a cohost. It seems to have stopped working after installing macOS Sonoma 14.5 for both my cohost and myself.

### Reproduction Steps

1. Installed Sonoma 14.5
2. Not working.

### Expected Behavior

Using Audio Hijack to stream multiple sources into the Blackhole 2ch. That no longer works, no sound comes out of that source/output now.

### Screenshots

![image](https://github.com/user-attachments/assets/ff9ba5a2-0865-47ad-bb2c-26018eb23905)

**Comment by devinroth** [comment]
BlackHole works fine on Sonoma 14.5 and newer. If you’re having issues with Audio Hijack, I suggest contacting them.

Devin

**Comment by vinayakhub** [comment]
Same issue here. it stopped working after the upgrade. currently on Sonoma 14.7.1

**Comment by devinroth** [comment]
Are you using Audio Hijack too?

Devin

**Comment by vin-appdirect** [comment]
I'm not. It's just blackhole with native mac audio setup. Using Quicktime to record screen.

**Comment by devinroth** [comment]
Try audacity. Make it simple for testing. No aggregates or multi output. BlackHole as default output and BlackHole as input into Audacity.

Devin

**Comment by vinpersonal** [comment]
Sure.  I will give that a try and report back.

**Comment by devinroth** [comment]
FYI. This is a different issue. Not related to the one you commented on.

Create a discussion instead.

Devin
