### ISSUE TITLE
No driver in HAL folder

### ISSUE THREAD

**Issue by rorysmyth** [ExistentialAudio/BlackHole#85]
I'm trying to uninstall the program, but there's no `BlackHole.driver` in my `/System/Library⁩/Audio⁩/Plug-Ins⁩/HAL` folder.

BlackHole is still showing up in audio settings. Where is the file?

**Comment by devinroth** [comment]
Try restarting your computer.

**Comment by rorysmyth** [comment]
Tried that. No luck

**Comment by devinroth** [comment]
Then you are not in the right folder. Follow this. 

https://github.com/ExistentialAudio/BlackHole/issues/80
