### ISSUE TITLE
Only able to output right channel of audio from VLC to Discord

### ISSUE THREAD

**Issue by williamwilkinson** [ExistentialAudio/BlackHole#91]
I am using Blackhole to route audio from VLC playing a movie to Discord live steam (to watch movie with all my friends stuck at home quarantine). I have it working successfully but I can only get Blackhole to export to one channel, audio is only playing out right side speakers. Is there a way for me to get both speakers working?

**Comment by devinroth** [comment]
Send me screenshot of how you have it setup and I’ll see what i can do to help.

**Comment by williamwilkinson** [comment]
I documented in this tweet – haven't messed with the default Audio Midi Setup settings! https://twitter.com/willw/status/1243252402913857536

**Comment by devinroth** [comment]
Stereo audio is coming out of VSL normally. Must be something with Discord. Looks like this might be your problem. 

https://support.discordapp.com/hc/en-us/community/posts/360029240151-Stereo-Audio-for-audio-sharing-adding-audio-sharing-to-Your-Entire-Screen-option-

**Comment by williamwilkinson** [comment]
Ah you are right! Thanks for the enlightenment and this amazing free app :-)

**Comment by devinroth** [comment]
You're welcome.
