### ISSUE TITLE
Built-in input and output(s) disappeared

### ISSUE THREAD

**Issue by intlly** [ExistentialAudio/BlackHole#92]
I recently dowloaded Blackhole and it works really well routing audio from my audio interface into OBS, 

After installing it, my built-in input and outputs disappeared, and now, I cannot listen through my laptop speakers, or record through my laptop microphone.
I am using a 2019 16" macbook pro with catalina 10.15.2.

How can I fix this?

**Comment by devinroth** [comment]
Just to check. Have you restarted your computer?

**Comment by intlly** [comment]
hey, devin,

my initial response was to restart it, which did not work.
however, it worked after the second restart i did a few minutes ago.

thanks!

keep making great things.



devin
bu.re_
instagram <https://www.instagram.com/bu.re_/> — spotify
<https://open.spotify.com/artist/6CJUEvrgdk2Qy2M8M8ucy0?si=eoM5sDYATSu3GufftGt9yg>
 — soundcloud <https://soundcloud.com/bu_re>

**Comment by devinroth** [comment]
Glad it's working again. Let me know if it happens again. I highly doubt it's related to BlackHole. But if it happens again get the console error messages for coreaudio. We'll take a look through them.

**Comment by intlly** [comment]
will do.

thank you very much.



devin

**Comment by devinroth** [comment]
#147 I wonder if this is related.
