### ISSUE TITLE
Discord -> Audacity

### ISSUE THREAD

**Issue by billherb** [ExistentialAudio/BlackHole#95]
I will be totally honest, I have no idea what I am doing. I would like to record discord audio, using Audacity. I have discord's output setting to Blackhole, and Audacity's input as Blackhole, but during recording it does not pick up any audio from discord. Why is this? It would also be very helpful if you could tell me the functions of Aggregate and Multi-Output devices, as I cant wrap my head around them.

**Comment by devinroth** [comment]
Aggregate - Groups multiple audio devices into one large audio device. Each channel in an aggregate is a specific channel on one of the audio devices.

Multi-output - Vertically groups multiple audio devices. Channel 1-2 output audio to channel 1-2 for ALL of the audio devices in the list.

**Comment by devinroth** [comment]
What OS are you on? Audacity has issues on Catalina. 

Please read through https://github.com/ExistentialAudio/BlackHole/wiki/Audacity. See if it helps.

**Comment by billherb** [comment]
Wow! Thanks for responding so quickly. I am currently on Catalina 10.15.4

**Comment by billherb** [comment]
Hmm... Should I use a different audio software?

**Comment by devinroth** [comment]
Audacity is the problem. Short answer is it won’t work. Long answer is some people have figured it out. You’ll need to google around. Search closed issues too since we’ve looked into it before. Hopefully you figure it out.

**Comment by billherb** [comment]
Audacity is also not listed for microphone access, even after moving and opening in downloads folder.

**Comment by billherb** [comment]
Ok, and thanks for your help

**Comment by billherb** [comment]
I've installed Garageband now, and I copied the exact settings over to Garageband, and I still have no audio.

**Comment by devinroth** [comment]
Check the audio setting. And there’s a garage band thread. See if that can help you.

**Comment by billherb** [comment]
Woops! my bad, forgot to save settings

**Comment by billherb** [comment]
Well, it works but I cannot hear my friend on discord...

**Comment by billherb** [comment]
Do I create an Aggregate device to incorporate my default speakers/microphone? Or a Multi-Output Device to hear my friend

**Comment by devinroth** [comment]
Try setting up a multi-output as output device from Discord. Please follow the instructions in the wiki.

**Comment by billherb** [comment]
Do I use the Multi Output Device as Input or Output for discord?

**Comment by billherb** [comment]
If I setup a Multi-Output device, then do I put all outputs into the device? Or only specific outputs?

**Comment by billherb** [comment]
After some tweaking, I figured it out! But it would be really convenient if I could record both discord and mic audio simultaneously.

**Comment by devinroth** [comment]
Okay. Create an aggregate with your mic and BlackHole. Use that as your input to GB and now you can record both.

**Comment by billherb** [comment]
The master device is blackhole?

**Comment by billherb** [comment]
The aggregate device seems to only be picking up mic audio, and not discord audio. Is there any way the Multi-Output device could have affected the aggregate device?

**Comment by devinroth** [comment]
It doesn’t matter which one is the master. 

Make sure you are selecting the correct channels from the aggregate. You’ll need two audio tracks in GB. One for BH and the other for your mic.

**Comment by billherb** [comment]
Which channel do I select?

**Comment by billherb** [comment]
Also, how do I create 2 different audio tracks? It creates the same audio track with I cant change without changing the other audio track

**Comment by billherb** [comment]
Sorry if I'm a hassle to deal with 😅

**Comment by billherb** [comment]
I took a look at the garageband thread and double checked all my settings, and I'm still having the same problem, "how do I create 2 different audio tracks? It creates the same audio track which I cant change without changing the other audio track"

**Comment by billherb** [comment]
I figured it out

**Comment by devinroth** [comment]
Awesome. 

Devin

**Comment by billherb** [comment]
Thanks for your help
