### ISSUE TITLE
Metallic and distorted sound with internal routing.

### ISSUE THREAD

**Issue by Rockmoneon** [ExistentialAudio/BlackHole#97]
Hi, 

so, on my Macs occurs a strange problem. BlackHole worked fine for weeks, last week I streamed to twitch. During the stream the problem occurs first time. The internal signal (iRealPro) signal was very "metallic" and distorted. So, when I change the channel from 1 and 2 to 2 and 2 , the signal is clean again. 
Yesterday, with Logic, same problem. I tried everything I know, but the prob still persists. 
Maybe you can help in any way...

Best regards

**Comment by devinroth** [comment]
Does restarting your computer make a difference?
Do you have drift compensation enabled?
What how to you have logic setup?

Screenshots help. 

Devin

**Comment by devinroth** [comment]
You need to enable drift correction.
