### ISSUE TITLE
routing Garageband to Jamulus

### ISSUE THREAD

**Issue by dgomezotero** [ExistentialAudio/BlackHole#99]
Hi,

I am struggling to route my MIDI keyboard  into Jamulus using Blackhole using Garageband, for instance.

I have an Audio Interface (Presonus 24c) and I have my keyboard into the MIDI input, I installed Blackhole and followed the instructions and some of the posts here, but I never manage to see signal in my jamulus.

I have tried different configurations, but right now, I have an aggregated device with the system output, Blackhole and my audio card (studio 24).  I set GB to use the agg. device and then in Jamulus I have both tried th agg. device or the blackhole direct.  

the keyboard and midi works, because I can hear it on Garageband, no problem, but  I don´t see any signal into Jamulus.

I don´t unsderstand there is the problem.  Any ideas?

BTW, how can I individually select the channel routing in blackhole?  Can´t see anywhere... could it be that the channel nr. is wrong?

Thanks!

David

ps.-  screenshots in spanish, sorry!
![Jamulus setup](https://user-images.githubusercontent.com/4664264/79066506-4ca21380-7cb0-11ea-8360-30861388e508.png)
![System Audio IN](https://user-images.githubusercontent.com/4664264/79066508-50359a80-7cb0-11ea-8202-c49b2084d3f0.png)
![SystemAudio OUT](https://user-images.githubusercontent.com/4664264/79066509-50359a80-7cb0-11ea-8f4e-df48fdb6cc59.png)
![GarageBand](https://user-images.githubusercontent.com/4664264/79066510-50ce3100-7cb0-11ea-8b8f-1b0819f98e93.png)
![MIDI Setup](https://user-images.githubusercontent.com/4664264/79066511-50ce3100-7cb0-11ea-95e2-33e316905d7e.png)

**Comment by alry07** [comment]
Any luck with this?  I am having the same issue but with guitar
